### ISSUE TITLE
Feature Request:  infer recommended relations for writeable views

### ISSUE THREAD

**Issue by dventimiglia** [hasura/graphql-engine#973] opened 2018-11-02 22:25 UTC
Hi! I've a feature request. I understand that in an upcoming release you're adding support for mutations on writable views in PostgreSQL, which is awesome. Would it be possible also to infer suggested relations for views, just as you do for tables? It's thoroughly plausible that this wouldn't be trivial, because while the database catalogs of course record foreign key constraints between tables, for views I think you'd have to parse the SQL DDL of the view definition, identify the tables, and then collect the recommendations for them. Still, it'd be super cool! Anyway, it's something for you to think about in your abundant spare time.

**Comment by manasag** [comment] 2023-12-27 11:11
This issue has not attracted significant attention for a long period of time, hence closing this.
Please feel free to reopen if the issue is still relevant for you.

**Closed by manasag** 2023-12-27 11:11 UTC
Labels: c/server, k/ideas, e/hard
