### ISSUE TITLE
[BUG] Delete record button stops working in 1.1.0

### ISSUE THREAD

**Issue by Albert-Gao** [hasura/graphql-engine#3908] opened 2020-02-19 11:11 UTC
In Hasura console.

![image](https://user-images.githubusercontent.com/18282328/74829236-75bfbb00-5375-11ea-974d-ad55223c43f7.png)

Nothing happens after clicking the trash bin button, not even sending a request

**Comment by rikinsk** [comment] 2020-02-19 12:38
@Albert-Gao I just tried this out on v1.1.0 and it seems to be working for me. Can you please confirm if this is happening for you consistently and across all tables?

**Comment by Albert-Gao** [comment] 2020-02-19 20:37
Yes, I can, only have 2 tables though

If it is hard for you to reproduce, 
Could you plz provide your email?

I can send the dev environment Hasura with the admin secret to you.

**Comment by rikinsk** [comment] 2020-02-20 08:09
@Albert-Gao Thanks for your help in debugging this. You can email me at rikin@hasura.io

**Comment by Albert-Gao** [comment] 2020-02-20 22:36
Sent, thanks

**Comment by Albert-Gao** [comment] 2020-02-20 22:38
Interesting, it starts working now....

It brought the alert() window correctly.

What is the logic prior to this bringing up `alert()` window? maybe that is the problem

**Comment by rikinsk** [comment] 2020-02-24 11:09
This was weird indeed. I dont believe that piece of logic had changed.

As there is no way to reproduce this currently, closing the issue for now.

**Closed by rikinsk** 2020-02-24 11:09 UTC
Labels: c/console 🖥️, support/needs-more-info
