### ISSUE TITLE
Non-nullable column should not expect nullable argument when inserting

### ISSUE THREAD

**Issue by ranjan-purbey** [hasura/graphql-engine#9809] opened 2023-08-02 07:39 UTC
### Version Information

Server Version: v2.30.1-cloud.1

### Environment

Cloud

### What is the current behaviour?

For a non-nullable database (pg) column:
![image](https://github.com/hasura/graphql-engine/assets/6953187/9defcaef-d8da-4eb9-a349-06b37abc0f68)

the generated schema does not have a non-nullable corresponding argument for insert mutation:
![image](https://github.com/hasura/graphql-engine/assets/6953187/6b3c0f75-9bbe-467d-8096-df259e723a07)

### What is the expected behaviour?
For non-nullable columns without a default value, the corresponding arg in insert mutation should also be non-nullable. Note that for update mutations, the current behaviour is as expected.

### How to reproduce the issue?

1. Create a table with a non-nullable field without a default value
2. Goto api explorer -> Docs -> insert mutation for the table
3. You will see that the corresponding arg is nullable

**Comment by SamirTalwar** [comment] 2023-08-02 10:05
This looks like a duplicate of #1433.

**Comment by ranjan-purbey** [comment] 2023-08-02 10:14
A 4 year old bug!! Thanks for your comment @SamirTalwar .

**Closed** 2023-08-02 10:15 UTC
Labels: k/bug
