### ISSUE TITLE
Add support for common fields like emails and URLs

### ISSUE THREAD

**Issue by jasonmccallister** [hasura/graphql-engine#1862] opened 2019-03-25 16:31 UTC
These items are not represented in Postgres, but are useful for the reducing the business logic from applications. I think it would be great if we could define columns, while using the console, as email or URL.  

For example:
- When adding an email column, the GraphQL engine should be able to verify the input provided is a valid email address (possibly using regex?)
- When using a URL column, the GraphQL engine should be able to verify the input is a valid URL

This would be useful for removing business logic (e.g. validating an email or URL) before persisting to the database.

**Comment by csreid** [comment] 2019-03-25 19:14
I think it would be nice to support [domains](https://www.postgresql.org/docs/current/sql-createdomain.html) and user-defined types generally.

**Comment by coco98** [comment] 2019-03-25 20:26
@tirumaraiselvan Do we have an issue for the adding console support for enabling data validation / constraint checks via the console?

**Comment by bionicles** [comment] 2020-01-27 21:44
+ phone numbers
+ emails 
would be useful and common

**Comment by beerose** [comment] 2020-01-28 11:47
Isn't it related to https://github.com/hasura/graphql-engine/issues/192?

**Comment by rikinsk** [comment] 2020-01-28 14:48
@beerose This is actually about adding validations for data via check constraints before insert/update.

**Comment by weyert** [comment] 2020-04-30 17:34
If you are going to regex for the email common field, please make sure the + is accept e.g. `username+github@gmail.com` should work, a lot of sites says the use of + is invalid.

**Comment by ShahAnuj2610** [comment] 2020-05-02 07:41
@rikinsk @beerose  I can work on this. Just to be on the same page, we need to add `fields` like `email`, `URL` in the `column_type` shown below, at the time of updating/inserting columns and check at the time of submission whether they're valid or not.

![](https://i.imgur.com/5mCxPnt.png)

**Comment by rikinsk** [comment] 2020-05-05 07:41
@ShahAnuj2610 The final UX for this still needs to be finalised. As these are not native types supported by PG they will have to be achieved by using a type like text along with a check constraint. How this information will be presented to the user still needs some figuring out and will need some designs.

We'll try to update this issue with the final expected behaviour soon

**Comment by RoniFinTech** [comment] 2021-03-14 15:44
Hi,
What's the status of this?
Something maybe more generic is to add regex constraints instead of having some specific contraints for emails/phone etc. (or maybe in addition)...

**Comment by codingkarthik** [comment] 2023-01-04 09:18
Closing this issue because this can now be done using Postgres's [check constraint](https://www.postgresql.org/docs/current/ddl-constraints.html#:~:text=A%20check%20constraint%20is%20the,CHECK%20(price%20%3E%200)%20)%3B).

**Closed by codingkarthik** 2023-01-04 09:18 UTC
Labels: c/console, design-rfc, e/intermediate
