### ISSUE TITLE
check SIGINT handling logic in server

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#1425] opened 2019-01-21 06:59 UTC
https://stackoverflow.com/questions/45839972/how-do-i-cause-a-warp-server-to-terminate#
http://neilmitchell.blogspot.com/2015/05/handling-control-c-in-haskell.html
https://stackoverflow.com/questions/2349233/catching-control-c-exception-in-ghc-haskell/2352915#2352915
https://stackoverflow.com/questions/13441676/how-to-write-ctrl-c-handler-in-haskell

**Comment by manasag** [comment] 2023-12-28 05:38
This issue has not attracted significant attention for a long period of time, hence closing this.
Please feel free to reopen if the issue is still relevant for you.

**Closed by manasag** 2023-12-28 05:38 UTC
Labels: c/server
