### ISSUE TITLE
Permission clone combo boxes not keyboard navigable

### ISSUE THREAD

**Issue by ndarilek** [hasura/graphql-engine#2425] opened 2019-06-25 15:34 UTC
As a screen reader user attempting to use the Hasura web interface, I can't seem to clone permissions. Clicking the Clone button pops up several combo boxes for selection that I cannot tab to. Additionally, none of the tricks I've attempted open the combo boxes for keyboard selection.

Thanks.

**Comment by Dhruvi16** [comment] 2020-10-08 07:44
I would like to take this up.

**Comment by ringfungi** [comment] 2020-10-08 13:03
I haven't been able to reproduce this issue, I can tab into the combo boxes (using Google Chrome
Version 85.0.4183.121, Windows 10 x64). Can you give us more details?

**Comment by ndarilek** [comment] 2020-10-08 13:20
Probably not, sorry. We stopped using Hasura a long time ago in part 
because we needed accessibility, and I'd have to set up an environment 
again.


Might no longer be relevant. I'd also test with a screen reader like 
NVDA, Orca or Voiceover, since this issue was opened in the context of 
multiple blind/low-vision users unable to use the product.

**Comment by NoriSte** [comment] 2022-10-04 07:18
> I haven't been able to reproduce this issue, I can tab into the combo boxes (using Google Chrome Version 85.0.4183.121, Windows 10 x64). Can you give us more details?

Closing this issue because of this @ringfungi 's comment, feel free to re-open it in the future

**Closed by NoriSte** 2022-10-04 07:18 UTC
Labels: k/enhancement, c/console, p/longterm, e/easy, hacktoberfest
