### ISSUE TITLE
Unable to track relationship for materialized views in new Relationships UI 

### ISSUE THREAD

**Issue by hitokiri82** [hasura/graphql-engine#9783] opened 2023-07-18 11:05 UTC
I'm running into the exact same bug described in issue [9499](https://github.com/hasura/graphql-engine/issues/9499) in version `v-2.29.1-cloud1`. 
My backend is Postgres, not MS SQL.

**Comment by vijayprasanna13** [comment] 2023-07-18 13:56
Thanks for reporting the issue @hitokiri82 ! We'll take a look at it

**Comment by vijayprasanna13** [comment] 2023-07-18 14:14
@hitokiri82 I tried this with a postgres view like you mentioned and I'm not able to replicate the issue on my side. Could you help me out here with a minimal SQL schema that can reproduce the error you see on your end?
https://github.com/hasura/graphql-engine/assets/11921040/9dad085a-1a9b-45bb-8710-f6be73b1aafd

**Comment by hitokiri82** [comment] 2023-07-18 16:43
I dont know if it will happen with a new schema. The symptom I'm running into is the same described in the linked bug, the dropdown to select the column on the view side of the relationship remains disabled.
It works if I go back to the old UI with no problems.
Would the fact that this is a cloud based hasura make any difference?

**Comment by hitokiri82** [comment] 2023-07-19 08:46
This is the specific version of Postgres I'm using as a backend: `PostgreSQL 14.5 on aarch64-unknown-linux-gnu, compiled by aarch64-unknown-linux-gnu-gcc (GCC) 7.4.0, 64-bit.`
It's running on AWS RDS.
I dont know if it's relevant but it might share some light on the issue.

**Comment by vijayprasanna13** [comment] 2023-07-21 06:45
@hitokiri82 I don't think this issue is related to cloud or a local version of Hasura but I suspect it might have something do with your schema. When you are in the relationships page and open the modal, do you see a `query` network call from the developer console? If you could post the request-response, it could help us debug the issue! This is what you are looking for -
![request](https://github.com/hasura/graphql-engine/assets/11921040/f5cbd67f-2204-4d08-8677-c34a6de245a8)
![response](https://github.com/hasura/graphql-engine/assets/11921040/5306d426-c447-40ff-941e-4509396e4fcd)

**Comment by hitokiri82** [comment] 2023-07-21 10:26
You are on the right track. 
The request for the columns list is:
`{
  "type": "run_sql",
  "args": {
    "sql": "\n   SELECT \n   column_name, data_type, is_nullable\n  FROM \n    information_schema.columns \n  WHERE \n    table_schema = 'public' AND \n    table_name  = 'rec_str_historic_conditions';",
    "source": "xxxxxx",
    "read_only": true
  }
}`

and the answer is indeed an empty list:

`{
  "result_type": "TuplesOk",
  "result": [
    [
      "column_name",
      "data_type",
      "is_nullable"
    ]
  ]
}`

If I run the same query directly on the DB server I also get an empty list. 

Apparently the way to get columns and attributes from a View is different than for a regular table?

**Comment by vijayprasanna13** [comment] 2023-07-24 09:30
@hitokiri82 that's interesting. It looks like SQL that we fire from the console is not able to find the entry for your _view_  `rec_str_historic_conditions` in your information_schema table. When you run the SQL manually, do you have the required permission for the table on which the view is based on?

**Comment by hitokiri82** [comment] 2023-07-24 14:39
Hello @vijayprasanna1. By checking what tables did and didnt come up in `information_schema` I realized that this issue is happening because `rec_str_historic_conditions` is a **materialized** view, not a regular view. I dug around a little bit and it seems that postgresql does not add materialized views to `information_schema`. 
I ran this queries as a superuser so I'm sure this is not an auth issue.

**Comment by vijayprasanna13** [comment] 2023-07-25 14:08
@hitokiri82 Thanks for info! I think we've hit an edge case with the new relationships UI and I'm able to replicate this on my side as well. You're right about `information_schema` not containing column info about materialised views. That leaves us with the alternative of getting this info from `pg_attribute`. 
We've already picked this up bug and we should have a fix in the next release! I'll update this thread once it's fixed

**Comment by vijayprasanna13** [comment] 2023-07-26 14:45
@hitokiri82 the fix has been merged to `main` https://github.com/hasura/graphql-engine/commit/929773d5b471fb50f565c92baa99c72ce15f6f3a and it should be out in the next release.

**Closed** 2023-08-31 08:42 UTC
Labels: k/bug, c/console, estimate/S
