### ISSUE TITLE
customize the frequency of action log fetches

### ISSUE THREAD

**Issue by johnparn** [hasura/graphql-engine#6460] opened 2021-01-18 20:01 UTC
Hi and thanks for a fantastic product!

After turning on `log_statement = 'all'` on in the postgresql.conf on my local installation of PostgreSQL I noticed there are updates running every second to the `hdb_catalog`. I wonder if it that is expected? 

This is what the log looks like:

```
2021-01-18 20:04:10.409 CET [61445] LOG:  execute 0: 
	      UPDATE hdb_catalog.event_log
	      SET locked = 't'
	      WHERE id IN ( SELECT l.id
	                    FROM hdb_catalog.event_log l
	                    WHERE l.delivered = 'f' and l.error = 'f' and l.locked = 'f'
	                          and (l.next_retry_at is NULL or l.next_retry_at <= now())
	                          and l.archived = 'f'
	                    ORDER BY created_at
	                    LIMIT $1
	                    FOR UPDATE SKIP LOCKED )
	      RETURNING id, schema_name, table_name, trigger_name, payload::json, tries, created_at
	      
2021-01-18 20:04:10.409 CET [61445] DETAIL:  parameters: $1 = '100'
2021-01-18 20:04:10.409 CET [61446] LOG:  execute <unnamed>: 
	        update hdb_catalog.hdb_action_log set status = 'processing'
	        where
	          id in (
	            select id from hdb_catalog.hdb_action_log
	            where status = 'created'
	            for update skip locked limit 10
	          )
	        returning
	          id, action_name, request_headers::json, session_variables::json, input_payload::json
	      
2021-01-18 20:04:11.418 CET [61446] LOG:  execute 0: 
	      UPDATE hdb_catalog.event_log
	      SET locked = 't'
	      WHERE id IN ( SELECT l.id
	                    FROM hdb_catalog.event_log l
	                    WHERE l.delivered = 'f' and l.error = 'f' and l.locked = 'f'
	                          and (l.next_retry_at is NULL or l.next_retry_at <= now())
	                          and l.archived = 'f'
	                    ORDER BY created_at
	                    LIMIT $1
	                    FOR UPDATE SKIP LOCKED )
	      RETURNING id, schema_name, table_name, trigger_name, payload::json, tries, created_at
	      
2021-01-18 20:04:11.418 CET [61446] DETAIL:  parameters: $1 = '100'
2021-01-18 20:04:11.419 CET [61445] LOG:  execute <unnamed>: 
	        update hdb_catalog.hdb_action_log set status = 'processing'
	        where
	          id in (
	            select id from hdb_catalog.hdb_action_log
	            where status = 'created'
	            for update skip locked limit 10
	          )
	        returning
	          id, action_name, request_headers::json, session_variables::json, input_payload::json

```

`hdb_catalog.event_log` and `hdb_catalog.hdb_action_log` are both empty.

I started out with version 1.1.0 about a year ago and have since upgraded to 1.3.3. I went straight from version 1.1.0 to 1.3.2 by just switching the version in the docker start command. And the same way I upgraded to from 1.3.2 to 1.3.3:

```sh
docker run -p 8080:8080 \
  -e HASURA_GRAPHQL_DATABASE_URL=postgres://username:password.docker.internal:5432/vb \
  -e HASURA_GRAPHQL_ENABLE_CONSOLE=true \
  hasura/graphql-engine:v1.3.3
```

My production version of Hasura in Kubernetes is still 1.1.0.

Thanks!

**Comment by marbemac** [comment] 2021-01-26 20:38
We've also noticed this, and it has become a pretty big problem. This `hdb_action_log set status` query is by far the most frequent query in our DB, and is crushing the CPU.

Spinning it up locally it does seem that even idle Hasura is making multiple queries a second to postgres. Is this expected?

We're on `v1.3.2`.

![Screen Shot 2021-01-26 at 2 34 40 PM](https://user-images.githubusercontent.com/847542/105902202-ee96b080-5fe3-11eb-8d9e-faba64f500d3.png)

**Comment by tirumaraiselvan** [comment] 2021-01-27 06:57
Changing this to a feature request:

We should introduce an env variable `HASURA_GRAPHQL_ASYNC_ACTIONS_FETCH_INTERVAL` for customising the fetch interval for async actions.

Also `HASURA_GRAPHQL_ASYNC_ACTIONS_FETCH_INTERVAL=0` should disable the fetching.

**Comment by marbemac** [comment] 2021-01-27 20:39
@tirumaraiselvan thanks for the follow up! Any chance you or somebody else could briefly outline what the purpose of these queries are? E.g. even with the `HASURA_GRAPHQL_ASYNC_ACTIONS_FETCH_INTERVAL` feature, what functionality would stop working or not work as well when `HASURA_GRAPHQL_ASYNC_ACTIONS_FETCH_INTERVAL=0`?

**Comment by tirumaraiselvan** [comment] 2021-01-28 04:23
`HASURA_GRAPHQL_ASYNC_ACTIONS_FETCH_INTERVAL=0` would mean async actions are disabled i.e. there won't be any thread picking up async action requests and delivering it to the configured webhook.

**Comment by marbemac** [comment] 2021-01-28 21:19
Ah perfect, that would work for us as we're not using async actions. Thanks for the explanation.

One more question related to understanding this behavior if you don't mind - what triggers the `update hdb_catalog.hdb_action_log set status` calls? Is it a static ~1 per second per hasura instance connected to the db? Or might other things contribute to the number of those queries? Asking because we're running ~4 hasura instances in our cluster but the PG insights is indicating ~40/second of those queries, which seems high (we're using sync actions, but no async actions). Thanks in advance.

**Comment by johnparn** [comment] 2021-02-03 12:21
Great! I'm not using the async actions either and being able to turn the queries off using an env variable is welcome. Thanks!

**Comment by ionTea** [comment] 2021-03-07 18:05
I'm also having this issue where the following query is having a huge load impact on the DB:
```
UPDATE
  hdb_catalog.hdb_action_log
SET
  status = $1
WHERE
  id IN (
  SELECT
    id
  FROM
    hdb_catalog.hdb_action_log
  WHERE
    status = $2 FOR
  UPDATE
    skip locked
  LIMIT
    $3 ) returning id,
  action_name,
  request_headers::json,
  session_variables::json,
  input_payload::json
```

![Screenshot 2021-03-07 at 18 03 37](https://user-images.githubusercontent.com/7414903/110249775-aa49e900-7f6f-11eb-8ece-eeb55bd8ba37.png)

Running PostgreSQL 12 in Google Cloud

**Comment by mihasya** [comment] 2021-03-08 19:20
We suddenly started seeing these queries dominate SQL usage in one of our clusters in the last 24 hours. The cluster has no events or actions configured whatsoever. Both tables have 0 rows in them.

At the same time, performance of queries going through hasura has become unpredictable, and the console fails to load frequently. It's a bit hard to say for sure since this is in a low-traffic dev cluster, but the database itself appears fine, though it is showing more load than before this started but we're definitely concerned that we're going to start seeing the same behavior in production.

We are on version 1.3.1.

Unsure what else to do to debug, any guidance would be appreciated. Here's a chart illustrating the before/after:

![image](https://user-images.githubusercontent.com/22596/110370227-46233580-8000-11eb-8237-ad3a885c5430.png)

**Comment by marbemac** [comment] 2021-03-09 00:07
> first of all, LOL at my zoom self view making it into the screenshot.

😂 

> We realized that this is a very small database and wondered if the underlying behavior didn't change, but rather how the db handled it. We failed over the DB and the issue disappeared.

@mihasya hmm that's interesting. Any other clues re why the failover might have solved the issue for you, or why it occurred in the first place? This is unfortunately still crushing our DB (we're in GCP, not AWS, but looks like the issue is not provider specific).

**Comment by xiaoyu-tamu** [comment] 2021-03-11 19:38
I'm also facing this problem on 1.4.0 beta.4
```
2021-03-11T19:33:10.000000+00:00 app[postgres.2024501]: [DATABASE] [227337-1]  sql_error_code = 00000 LOG:  execute 5:
2021-03-11T19:33:10.000000+00:00 app[postgres.2024501]: [DATABASE] [227337-2] 	      UPDATE hdb_catalog.event_log
2021-03-11T19:33:10.000000+00:00 app[postgres.2024501]: [DATABASE] [227337-3] 	      SET locked = NOW()
2021-03-11T19:33:10.000000+00:00 app[postgres.2024501]: [DATABASE] [227337-4] 	      WHERE id IN ( SELECT l.id
2021-03-11T19:33:10.000000+00:00 app[postgres.2024501]: [DATABASE] [227337-5] 	                    FROM hdb_catalog.event_log l
2021-03-11T19:33:10.000000+00:00 app[postgres.2024501]: [DATABASE] [227337-6] 	                    WHERE l.delivered = 'f' and l.error = 'f'
2021-03-11T19:33:10.000000+00:00 app[postgres.2024501]: [DATABASE] [227337-7] 	                          and (l.locked IS NULL or l.locked < (NOW() - interval '30 minute'))
2021-03-11T19:33:10.000000+00:00 app[postgres.2024501]: [DATABASE] [227337-8] 	                          and (l.next_retry_at is NULL or l.next_retry_at <= now())
2021-03-11T19:33:10.000000+00:00 app[postgres.2024501]: [DATABASE] [227337-9] 	                          and l.archived = 'f'
2021-03-11T19:33:10.000000+00:00 app[postgres.2024501]: [DATABASE] [227337-10] 	                    ORDER BY created_at
2021-03-11T19:33:10.000000+00:00 app[postgres.2024501]: [DATABASE] [227337-11] 	                    LIMIT $1
2021-03-11T19:33:10.000000+00:00 app[postgres.2024501]: [DATABASE] [227337-12] 	                    FOR UPDATE SKIP LOCKED )
2021-03-11T19:33:10.000000+00:00 app[postgres.2024501]: [DATABASE] [227337-13] 	      RETURNING id, schema_name, table_name, trigger_name, payload::json, tries, created_at
```

This repeat sql is crushing the server CPU. Is there any workaround for now? @tirumaraiselvan

**Comment by mihasya** [comment] 2021-03-11 22:13
@marbemac this was a staging database, a `t2.micro` which is on burstable compute etc. We don't have good data at the moment for the frequency of the query, so all we could see is that it suddenly started dominating the "Load by waits" chart. This issue made us realize that most likely this query had been getting executed a bunch of times even in the past, and also that the queries were just taking way too long for an update generated from a select that returned 0 rows. So that made us think "something's weird here," and so we just failed over to see if maybe our primary had gotten onto a wayward hypervisor, got a new noisy neighbor etc. We had previously restarted Hasura itself, etc. The failover cleared it right up.

We migrated the DB to an `m5.large` under the assumption that that'll keep us from wasting too much additional time in the future on something like this. Our equivalent production database, which also has very little data and also has 0 events or triggers configured, never had this issue, but we bumped it to a "real" instance class as well just to avoid the future headache. The `m5.large`s are still pretty cheap.

**Comment by xiaoyu-tamu** [comment] 2021-04-07 02:00
After upgrading v2.alpha7, I can disable fetching async actions. 

But the event refetch is still run every second,  @rakeshkky  can you also make this configurable? or refetch only when there's at-least one event handler present


```
2021-04-07T01:53:57.000000+00:00 app[postgres.2281013]: [DATABASE] [227455-2] 	      UPDATE hdb_catalog.event_log
2021-04-07T01:53:57.000000+00:00 app[postgres.2281013]: [DATABASE] [227455-3] 	      SET locked = NOW()
2021-04-07T01:53:57.000000+00:00 app[postgres.2281013]: [DATABASE] [227455-4] 	      WHERE id IN ( SELECT l.id
2021-04-07T01:53:57.000000+00:00 app[postgres.2281013]: [DATABASE] [227455-5] 	                    FROM hdb_catalog.event_log l
2021-04-07T01:53:57.000000+00:00 app[postgres.2281013]: [DATABASE] [227455-6] 	                    WHERE l.delivered = 'f' and l.error = 'f'
2021-04-07T01:53:57.000000+00:00 app[postgres.2281013]: [DATABASE] [227455-7] 	                          and (l.locked IS NULL or l.locked < (NOW() - interval '30 minute'))
2021-04-07T01:53:57.000000+00:00 app[postgres.2281013]: [DATABASE] [227455-8] 	                          and (l.next_retry_at is NULL or l.next_retry_at <= now())
2021-04-07T01:53:57.000000+00:00 app[postgres.2281013]: [DATABASE] [227455-9] 	                          and l.archived = 'f'
2021-04-07T01:53:57.000000+00:00 app[postgres.2281013]: [DATABASE] [227455-10] 	                    ORDER BY created_at
2021-04-07T01:53:57.000000+00:00 app[postgres.2281013]: [DATABASE] [227455-11] 	                    LIMIT $1
2021-04-07T01:53:57.000000+00:00 app[postgres.2281013]: [DATABASE] [227455-12] 	                    FOR UPDATE SKIP LOCKED )
2021-04-07T01:53:57.000000+00:00 app[postgres.2281013]: [DATABASE] [227455-13] 	      RETURNING id, schema_name, table_name, trigger_name, payload::json, tries, created_at
```

**Comment by tirumaraiselvan** [comment] 2021-04-07 02:38
> But the event refetch is still run every second.

@xiaoyu-tamu This is WIP as well.

**Comment by tirumaraiselvan** [comment] 2021-04-07 02:39
Released in v2.0.0-alpha.7 with the env var HASURA_GRAPHQL_ASYNC_ACTIONS_FETCH_INTERVAL (milliseconds)

**Closed by tirumaraiselvan** 2021-04-07 02:39 UTC
Labels: c/server

**Comment by Bessonov** [comment] 2021-05-21 19:51
@tirumaraiselvan I'm experiencing the same behavior as https://github.com/hasura/graphql-engine/issues/6460#issuecomment-814546030 :

```yaml
  hasura:
    image: hasura/graphql-engine:v2.0.0-alpha.10
[...]
    environment:
      HASURA_GRAPHQL_ASYNC_ACTIONS_FETCH_INTERVAL: "0"
```

Tried also `0` and `"10000000"` - queries still happen:
```sql
postgres_1               | 2021-05-21 19:50:03.269 UTC [123] LOG:  execute 0: BEGIN ISOLATION LEVEL SERIALIZABLE READ WRITE
postgres_1               | 2021-05-21 19:50:03.270 UTC [123] LOG:  execute 5: 
postgres_1               | 	      UPDATE hdb_catalog.event_log
postgres_1               | 	      SET locked = NOW()
postgres_1               | 	      WHERE id IN ( SELECT l.id
postgres_1               | 	                    FROM hdb_catalog.event_log l
postgres_1               | 	                    WHERE l.delivered = 'f' and l.error = 'f'
postgres_1               | 	                          and (l.locked IS NULL or l.locked < (NOW() - interval '30 minute'))
postgres_1               | 	                          and (l.next_retry_at is NULL or l.next_retry_at <= now())
postgres_1               | 	                          and l.archived = 'f'
postgres_1               | 	                    ORDER BY created_at
postgres_1               | 	                    LIMIT $1
postgres_1               | 	                    FOR UPDATE SKIP LOCKED )
postgres_1               | 	      RETURNING id, schema_name, table_name, trigger_name, payload::json, tries, created_at
postgres_1               | 	      
postgres_1               | 2021-05-21 19:50:03.270 UTC [123] DETAIL:  parameters: $1 = '100'
postgres_1               | 2021-05-21 19:50:03.270 UTC [123] LOG:  execute 4: COMMIT

```

**Comment by xiaoyu-tamu** [comment] 2021-08-09 16:46
> > But the event refetch is still run every second.
> 
> @xiaoyu-tamu This is WIP as well.

Hi, @tirumaraiselvan  any updates on this?

**Comment by tirumaraiselvan** [comment] 2021-08-10 12:58
@xiaoyu-tamu You can use `HASURA_GRAPHQL_EVENTS_FETCH_INTERVAL` for event trigger fetching configurability.
