### ISSUE TITLE
Allow-list does not work?

### ISSUE THREAD

**Issue by comerc** [hasura/graphql-engine#3608] opened 2019-12-31 12:56 UTC
Hasura v1.0.0 on Heroku.

- Set HASURA_GRAPHQL_ENABLE_ALLOWLIST .env variable as "true".
- Set X-Hasura-Role header as "user". 
- Add table with one field id (uuid).
- Insert rows to table.
- Add all select permissions for role "user".
- Add query to "Allowed Queries" interface with name "get_try":
```
query get_try {
  try {
    id
  }
}
```
- Reload metadata.

"NO SCHEMA AVAILABLE" in GraphiQL Explorer.

**Comment by comerc** [comment] 2019-12-31 19:56
But the query works:

![Снимок экрана от 2019-12-31 22-53-41](https://user-images.githubusercontent.com/1025241/71632627-8038c080-2c20-11ea-8b4d-f784cd576a07.png)

**Comment by rikinsk** [comment] 2020-01-02 05:35
@comerc This is expected behaviour. Only exact queries added to the allow list will be allowed to be run. 

Is there any reason you expect the behaviour to be different?

**Comment by rikinsk** [comment] 2020-01-02 05:37
If you are wondering why `No schema available` is shown, that is because the introspection query required to fetch the schema has not been added to the allow-list

**Comment by 0x777** [comment] 2020-01-09 11:44
As @rikinsk pointed you, you can't introspect the server after enabling allow-list unless the introspection query itself is added to the allow-list. This is the introspection query that is used typically by graphiql like interfaces:
```graphql
query IntrospectionQuery {
  __schema {
    queryType { name }
    mutationType { name }
    subscriptionType { name }
    types {
      ...FullType
    }
    directives {
      name
      description
      locations
      args {
        ...InputValue
      }
    }
  }
}
fragment FullType on __Type {
  kind
  name
  description
  fields(includeDeprecated: true) {
    name
    description
    args {
      ...InputValue
    }
    type {
      ...TypeRef
    }
    isDeprecated
    deprecationReason
  }
  inputFields {
    ...InputValue
  }
  interfaces {
    ...TypeRef
  }
  enumValues(includeDeprecated: true) {
    name
    description
    isDeprecated
    deprecationReason
  }
  possibleTypes {
    ...TypeRef
  }
}
fragment InputValue on __InputValue {
  name
  description
  type { ...TypeRef }
  defaultValue
}
fragment TypeRef on __Type {
  kind
  name
  ofType {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
              }
            }
          }
        }
      }
    }
  }
}
```

I'm closing this issue, feel free to re-open this if you this doesn't fix your issue.

**Closed by 0x777** 2020-01-09 11:44 UTC
Labels: k/question❓

**Comment by THPubs** [comment] 2020-03-31 10:23
For me it's still happening. I can't even use `gq` to download the introspect to a file.

**Comment by rikinsk** [comment] 2020-03-31 10:33
@THPubs Can you clarify what exactly you are attempting to do and what's not working?
