### ISSUE TITLE
actions: ability to send `extensions` to error responses 

### ISSUE THREAD

**Issue by lnikell** [hasura/graphql-engine#4001] opened 2020-03-02 21:25 UTC
I use the latest "hasura/graphql-engine:v1.2.0-beta.1", after testing actions I found that it responds in different formats for 5xx and 4xx errors.
For 5xx errors I could get from the response any custom objects with data from the server
```
{
  "errors": [
    {
      "extensions": {
        "internal": {
          "webhook_response": {
            "errors": [
              {
                "status": 500,
                "code": "Error",
                "detail": "hello world"
              }
            ]
          }
        },
        "path": "$",
        "code": "unexpected"
      },
      "message": "internal error"
    }
  ]
}
```
When for 4xx it only accepts `{"message": "error message"}` any custom options will not be displayed at "extensions" - "internal" like for 5xx error.

I would like to have 4xx support any custom formats with the ability to path more information rather than just a "message" field.

**Comment by matomesc** [comment] 2020-03-02 23:53
Currently facing the same problem and my workaround is to encode the custom error object as json, for example:

```json
{
  "errors": [
    {
      "extensions": {
        "path": "$",
        "code": "unexpected"
      },
      "message": "{\"message\":\"Failed to save user\",\"fields\":{\"firstName\":\"First name is required\"}}"
    }
  ]
}
```

Not ideal but it works.

**Comment by lnikell** [comment] 2020-03-03 11:40
@matomesc yep,  I thought about this option too, not ideal definitely. I mostly don't like the idea of having 2 different error handlers, so the one for processing 4xx errors and another one for 5xx.

**Comment by matomesc** [comment] 2020-03-05 23:26
@lnikell Just wondering, what did you return from your handler in order to get the array of errors for a 5xx response? All my errors look like this:

```json
{
  "errors": [
    {
      "extensions": {
        "path": "$",
        "code": "unexpected"
      },
      "message": "internal error"
    }
  ]
}
```

**Comment by matomesc** [comment] 2020-03-15 16:12
@lnikell I wrote the following apollo link to extract the serialized handler error and mutate the graphql error so I can just use one error handler:

```ts
// Prefix the json string in `message` so we can identify action handler errors
const PREFIX = 'hasuraActionError';

/**
 * Extract the serialized hasura action handler error and add the error's fields
 * to the existing graphql error.
 */
const hasuraActionHandlerErrorLink = onError(({ graphQLErrors }) => {
  if (!graphQLErrors) {
    return;
  }

  graphQLErrors.forEach(error => {
    if (!error.message.startsWith(PREFIX)) {
      return;
    }

    const writableError = error as Writable<typeof error>;
    const actionHandlerError = JSON.parse(error.message.slice(PREFIX.length));

    if (isValidActionHandlerError(actionHandlerError)) {
      // Add action handler error fields to the graphql error
      writableError.extensions = actionHandlerError.extensions;
      writableError.message = actionHandlerError.message;
    } else {
      console.error('Invalid action handler error', actionHandlerError);
      writableError.message = 'Something bad happened';
    }
  });
});
```

**Comment by tirumaraiselvan** [comment] 2020-04-03 12:34
Currently for 4xx requests we expect a response like: 

```
{
  "message": "<mandatory error message>",
  "code": "<optional error code>"
}
```
we can extend this to also expect an `extensions` key like:


```
{
  "message": "<mandatory error message>",
  "code": "<optional error code>",
  "extensions": "<any json>"
}
```

I am changing the title to reflect this feature request.

**Comment by ecthiender** [comment] 2021-09-20 08:06
Fixed via 8bfcd9a55cf42032ca6de0afecd2051c89d937b9 . cc @tirumaraiselvan for link to docs

**Closed by ecthiender** 2021-09-20 08:06 UTC
Labels: c/server, p/high, c/actions

**Comment by hubiwan** [comment] 2021-11-21 15:36
@tirumaraiselvan  Not trying to necro this one but looks like the extensions key/object returned by the action handler is still ignored.

**Comment by DandyDev** [comment] 2021-12-03 15:57
This still doesn't work indeed

**Comment by robx** [comment] 2021-12-06 16:42
As best as I can tell, the change linked above does address this issue, and made it into release v2.0.10. @tamas-soos @hubiwan @DandyDev which version are you seeing this with?

**Comment by robx** [comment] 2021-12-07 08:54
The versioning story is too complicated for me to figure out, @tirumaraiselvan could you please let us know which versions actually have that change?

**Comment by tirumaraiselvan** [comment] 2021-12-08 12:14
The git commit which introduced this change (mentioned in https://github.com/hasura/graphql-engine/issues/4001#issuecomment-922710659) has the tags v2.1.0-beta.1 and above. Pls try this with the latest release: v2.1.0-beta.2

**Comment by cj** [comment] 2022-01-13 21:16
@tirumaraiselvan I am trying it with the latest version 2.1.1 and having the same issue as https://github.com/hasura/graphql-engine/issues/4001#issuecomment-954686315

**Comment by cj** [comment] 2022-01-13 21:20
```
{
  body: {
    message: 'ActionError: EMAIL_NOT_ALLOWED',
    extensions: { foo: 'bar', code: 'EMAIL_NOT_ALLOWED' }
  }
}
```

gives: 

```
{
    "path": "$",
    "error": "ActionError: EMAIL_NOT_ALLOWED",
    "code": "unexpected"
}
```

**Comment by BenoitRanque** [comment] 2022-01-21 17:51
> ```
> {
>     message: 'ActionError: EMAIL_NOT_ALLOWED',
>     extensions: { foo: 'bar', code: 'EMAIL_NOT_ALLOWED' }
> }
> ```
> 
> gives:
> 
> ```
> {
>     "path": "$",
>     "error": "ActionError: EMAIL_NOT_ALLOWED",
>     "code": "unexpected"
> }
> ```

I've just attempted to replicate this behavior with no success.
This is my action handler's code:
```js
    res.status(400).json({
      message: 'ActionError: EMAIL_NOT_ALLOWED',
      extensions: { foo: 'bar', code: 'EMAIL_NOT_ALLOWED' },
    });
```
And this is the payload from calling my action through hasura:
```json
{
  "errors": [
    {
      "extensions": {
        "foo": "bar",
        "code": "EMAIL_NOT_ALLOWED"
      },
      "message": "ActionError: EMAIL_NOT_ALLOWED"
    }
  ]
}
```
This is the behavior we are expecing. 
Can you share more details on your setup, and if possible minimal reproduction steps?
We tested this on 2.1.1.

**Comment by srflorea1** [comment] 2022-05-09 07:58
> ```
> {
>     message: 'ActionError: EMAIL_NOT_ALLOWED',
>     extensions: { foo: 'bar', code: 'EMAIL_NOT_ALLOWED' }
> }
> ```
> 
> gives:
> 
> ```
> {
>     "path": "$",
>     "error": "ActionError: EMAIL_NOT_ALLOWED",
>     "code": "unexpected"
> }
> ```

I am having the exact same problem with Hasura 2.2.0. There are not much steps that can described. The issue is pretty straight forward and clear: the "extensions" field does not get passed over Hasura. The "code" field gets passed through only if I send it at the same first level with the "message" field.

**Comment by chewthemonkey** [comment] 2023-04-13 09:57
Looks like this is still broken.

**Comment by BradStell** [comment] 2023-06-08 17:15
Hi, I have a working solution.
If I return this from my action
```
{
  statusCode: 400,,
  body: JSON.stringify({ message: 'Some error message', code: '400' }),
}
```
then in Hasura I get this response
```
{
  "errors": [
    {
      "extensions": {
        "code": "400",
        "path": "$"
      },
      "message": "Some error message"
    }
  ]
}
```

**Comment by Tejesh-Duvvuru** [comment] 2023-08-01 07:27
I tried every thing but it not working for can any help.

res.status(400).json({
      message: 'ActionError: EMAIL_NOT_ALLOWED',
      extensions: { foo: 'bar', code: 'EMAIL_NOT_ALLOWED' },
    });

reponse getting  graphQLErrors: [{"extensions": {"code": "unexpected", "path": "$"}, "message": "Invalid response from authorization hook"}]
