### ISSUE TITLE
Remote relationships

### ISSUE THREAD

**Issue by revskill10** [hasura/graphql-engine#1846] opened 2019-03-23 15:32 UTC
Since Hasura already supports schema stitching, are we able to specify relationship to remote tables ?

Suggestion:
When specifying manual relationship, options for remote table should also include remote tables from remote schemas.

**Comment by tirumaraiselvan** [comment] 2019-06-04 10:07
This is an exciting new feature we are working on. A preview is also available here: https://github.com/hasura/graphql-engine/pull/1990

Happy to get feedback and use-cases for this feature.

**Comment by tirumaraiselvan** [comment] 2019-06-15 04:03
Duplicate of #1225

**Closed by tirumaraiselvan** 2019-06-15 04:03 UTC
Labels: c/console, c/server, k/enhancement, p/high
