### ISSUE TITLE
Insert with Generated Columns

### ISSUE THREAD

**Issue by go4cas** [hasura/graphql-engine#3572] opened 2019-12-19 15:14 UTC
Using [generated columns](https://www.postgresql.org/docs/12/ddl-generated-columns.html), introduced with Postgresql 12, work fine when doing queries or mutations through GraphQL. When trying to insert a row, using the console Insert Row tab, tries to set the column value to NULL, which results in a "unexpected : cannot insert into column" error.

**Comment by paf31** [comment] 2019-12-19 19:11
This seems like it's probably caused by the same issue as in #2508.

**Comment by 0x777** [comment] 2020-01-09 11:27
@paf31 Will this be fixed with #3598?

**Comment by paf31** [comment] 2020-01-09 17:24
I expect so, yes.

**Comment by nolandg** [comment] 2020-01-10 20:47
I'm confused how @go4cas got this to work even over Graphql. I have a table with generated column but when I try to insert an object over Graphql API (and not pass anything for that generated column), I get a Postgres error. Looking at the error message, you can see that Hasura has taken the liberty of adding all columns to the attempted INSERT command, filling in defaults where I didn't pass values. This break the generated column of course.

How are you making this work? This is a show stopping bug for us right now. Any workaround suggestions would be appreciated.

**Comment by nolandg** [comment] 2020-01-10 22:41
I made more investigation of this and made a new issue: https://github.com/hasura/graphql-engine/issues/3681

**Comment by tirumaraiselvan** [comment] 2020-04-03 15:44
This is fixed in https://github.com/hasura/graphql-engine/pull/3598

**Closed by tirumaraiselvan** 2020-04-03 15:44 UTC
Labels: c/server, k/bug, s/wip
