### ISSUE TITLE
Unexpected behaviour with REST API with route params and body

### ISSUE THREAD

**Issue by Tchoupinax** [hasura/graphql-engine#8316] opened 2022-03-13 18:46 UTC
Hello,

I met an unexpected behaviour with the REST API.

I want to update a table, given an idea and a property value. I provide all needed information and I get an error:

```
{"path":"$","error":"expecting a value for non-nullable variable: \"priority\"","code":"validation-failed"}
```

The network tab in inspector does not show the payload.

However, if i remove the `:id` param from the url and provide same value the query succeeds, and in the inspector the payload is correctly sent with id and priority.

In others words, I have the impression that when a variable is taken from route variable, variable in the body is not sent.

![image](https://user-images.githubusercontent.com/9136206/158074251-15f16e0e-cd3e-4a67-b008-49ca1110380e.png)

Thank you for all your work :)
Have a nice day!

**Comment by sordina** [comment] 2022-03-14 23:59
Hi @Tchoupinax thanks for the bug report! I'd like to reproduce this, but for clarity would you be able to copy the request from the network inspector using "copy as curl"? (feel free to redact any confidential information).

**Comment by sordina** [comment] 2022-03-16 21:33
Hi @Tchoupinax I've replicated the issue here and it looks like the console is not sending the request body.

Here's the request being sent:

```
curl 'http://localhost:8080/api/rest/ideas/135cbc97-b436-443f-a84b-1ef2184d6b63' \
-X 'PUT' -H 'Content-Type: application/json'
```

but here is what should be being sent:

```
curl 'http://localhost:8080/api/rest/ideas/135cbc97-b436-443f-a84b-1ef2184d6b63' \
-X 'PUT' -H 'Content-Type: application/json' \
-d '{"priority":99}'
```

The good news is that you should be able to use the REST endpoint as defined with your client of choice, however the Preview Request UI will need to be fixed. I'll let the @hasura/hge-console-owners know about this issue.

**Comment by Tchoupinax** [comment] 2022-03-19 15:36
Hello @sordina,

First of all, thank you a lot for your investigation and your time. I could not seeing this this week and I wanted to test again to confirm you the issue.

- Indeed, the payload is missing from the request sent by the console. When I copy the request and add the payload, it works well with curl.
- When I read your message I was suprised because I discover this bug when trying to make the request from my code (Node.js/axios), not from the console. I tried again and indeed, it works well. I can so continue to use the REST endpoint.

Hope this issue will be useful and a fix can come soon!

Thank you again
Have a nice day!

**Comment by abhi40308** [comment] 2022-03-26 06:50
This should be fixed now ref https://github.com/hasura/graphql-engine/commit/9ba1e3993e8d821b6a240ad80b3ae2b0aa4266df

**Closed by abhi40308** 2022-03-26 06:50 UTC
Labels: k/bug, a/api/rest
