### ISSUE TITLE
Error on voyager view

### ISSUE THREAD

**Issue by edsonbonfim** [hasura/graphql-engine#3023] opened 2019-10-05 01:37 UTC
I got this message when I trying to open voyager view in my hasura app with heroku.

```
Error: abort(7). Build with -s ASSERTIONS=1 for more info.
    at Array.n.listeners.<computed> (https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v1.0/vendor.js.gz:1:3828515)
    at Worker.<anonymous> (https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v1.0/vendor.js.gz:1:3828346)
```

**Comment by EdsonOnildoJR** [comment] 2019-12-02 00:47
![image](https://user-images.githubusercontent.com/8020047/69923463-c95fee00-1483-11ea-9ef9-be5b070c7100.png)

This message is all that I have. I've deploy my app with heroku.

**Comment by stefan1968** [comment] 2019-12-11 00:20
I get the same issue.

**Comment by mnlbox** [comment] 2019-12-11 07:41
I have the same issue in big projects with many tables. For small projects every thing is working fine.

**Comment by PeterDraex** [comment] 2020-01-18 17:39
I have a similar issue. Also occurs on voyager view, but different row numbers.

```
Error: abort(7). Build with -s ASSERTIONS=1 for more info.
    at Array.n.listeners.<computed> (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.0/vendor.js.gz:1:3832520)
    at Worker.<anonymous> (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.0/vendor.js.gz:1:3832351)
```

I'm running Hasura in Docker, which is connected to PostreSQL outside of docker, which is connected to MySQL (via Foreign Data Wrappers). GraphQL queries are working fine.

**Comment by DevSnap** [comment] 2020-02-03 16:06
Same error on a project with 40+ tables.

```
Error: abort(7). Build with -s ASSERTIONS=1 for more info. 
at Array.n.listeners.<computed> (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.0/vendor.js.gz:1:3832520) 
at Worker.<anonymous> (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.0/vendor.js.gz:1:3832351)
```

I tried to upload the introspection query result on [https://apis.guru/graphql-voyager](https://apis.guru/graphql-voyager) and it works (it takes 10 seconds to render).

**Comment by tpurschke** [comment] 2020-02-16 22:11
same issue here with hasura running in docker and 60 tables with very little data. 
Error:
```
e/</n.listeners[a]@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.0/vendor.js.gz:1:3832109
e/<@https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.0/vendor.js.gz:1:3831940
```

**Comment by 24601** [comment] 2020-04-09 16:38
I have a similar issue, but different error, but I think we are all experiencing the same thing (or some of us) and a proposed workaround/solution:

```Error: Maximum call stack size exceeded
    at Array.n.listeners.<computed> (https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v1.2/vendor.js.gz:1:5523135)
    at Worker.<anonymous> (https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v1.2/vendor.js.gz:1:5522964)```

The issue is likely related to resource usage in Voyager and there is guidance in this issue around raising limits (https://github.com/APIs-guru/graphql-voyager/issues/129). 

Is there a way we could expose the two config items for the embedded Voyager as a Hasura configuration variable (even if someone can give me some guidance has to how to do that or even just where to start in the codebase I'd be happy to submit a PR, just reduce that barrier to entry for me so I can prioritize it :) - I am not a Hasura expert on internals and I don't know Rust, either, but I do know JS pretty well...)? 

I know the schema works well and isn't too big as pasting in the introspection query SDL directly into Voyager works just fine, so it's possible with the right limits.

**Comment by beerose** [comment] 2020-04-13 11:36
Hi @24601,
The solution suggested in https://github.com/APIs-guru/graphql-voyager/issues/129 is strictly related to the voyager code. Stack and heap sizes are hardcoded in the voyager [code](https://github.com/APIs-guru/graphql-voyager/blob/ce68069ec8f10d745293256c20dd0cb76e447985/src/utils/index.ts#L29-L30).

**Comment by 24601** [comment] 2020-04-13 15:03
> Hi @24601,
> The solution suggested in [APIs-guru/graphql-voyager#129](https://github.com/APIs-guru/graphql-voyager/issues/129) is strictly related to the voyager code. Stack and heap sizes are hardcoded in the voyager [code](https://github.com/APIs-guru/graphql-voyager/blob/ce68069ec8f10d745293256c20dd0cb76e447985/src/utils/index.ts#L29-L30).

Yes, so I have thought of just doing a custom build, patching, and calling it good, which I may do, but I am curious if there is any interest in having this process exposed through standard Hasura variables/config methods, I could think of a few ways this could be done, I was erring on the side of externalizing their hard-coded variables (hopefully they'd accept a PR for something fixing something as obtuse as hard coded config w/o an override) and then having the Hasura changes in GraphiQL that render the button pass values of config vars (LIke HASURA_CONSOLE_VOYAGER_XXXX). 

But if this kind of PR would never be accepted I don't want to waste our time if we're going to be stuck running custom builds. 

Any thoughts on if this is something worth looking at?

**Comment by soneymathew** [comment] 2020-04-14 13:09
Got this error today in voyager view

```
Error: syntax error in line 151285 scanning a HTML string (missing '>'? bad nesting? longer than 16384?)
String starting:<<TABLE ALIGN="LEFT" BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5">
 

    at Array.n.listeners.<computed> (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/vendor.js.gz:1:3890992)
    at Worker.<anonymous> (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.1/vendor.js.gz:1:3890821)
```

**Comment by bobberkarl** [comment] 2020-05-05 07:47
Same today with 1.2.0. 
![image](https://user-images.githubusercontent.com/13062328/81044913-29b7e900-8e83-11ea-8d4b-fe9d26677966.png)

**Comment by Ckbhatia** [comment] 2020-05-21 16:50
@beerose @edsonbonfim Hey, Can anyone please share a codesandbox link or similar link? So, I can reproduce the error and fix it.

**Comment by beerose** [comment] 2020-05-22 12:11
@Ckbhatia the best way to reproduce this would be to start Hasura Console and create multiple test tables. As I know this issue occurs when there are more than ~40 tables. 

[Here](https://github.com/hasura/graphql-engine/blob/master/console/README.md) are the instructions on how to run Console locally.

**Comment by airstep** [comment] 2020-10-12 12:45
Got: Error: syntax error in line 4654

    at Array.r.listeners.<computed> (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.3/vendor.js.gz:1:6855882)
    at Worker.<anonymous> (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.3/vendor.js.gz:1:6855711)

**Comment by zorro-lp** [comment] 2020-11-23 08:52
I met same error when running Hasura in Azure docker container.
`Error: abort(7). Build with -s ASSERTIONS=1 for more info.
    at Array.r.listeners.<computed> (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.3/vendor.js.gz:1:6932448)
    at Worker.<anonymous> (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.3/vendor.js.gz:1:6932277)`

**Comment by TejasQ** [comment] 2020-12-02 15:48
please

**Comment by KristjanVall** [comment] 2021-01-13 11:11
+1

**Comment by mattsears18** [comment] 2021-02-24 13:58
Same error running Hasura Pro. Is there a fix for this yet?

Error: abort(7). Build with -s ASSERTIONS=1 for more info.
    at Array.n.listeners.<computed> (https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v1.3.3-cloud.3/vendor.js.gz:1:10089536)
    at Worker.<anonymous> (https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v1.3.3-cloud.3/vendor.js.gz:1:10089365)

**Comment by kaotika** [comment] 2021-06-09 08:08
Any updates on this? Got the same exception with 2.0 beta 1

**Comment by huss-jay** [comment] 2021-07-01 12:45
any updates on this?

**Comment by JordyMiggelbrinkBridge** [comment] 2021-07-01 20:06
Same for our environments, no voyager available:
```
Error: abort(7). Build with -s ASSERTIONS=1 for more info.
    at Array.r.listeners.<computed> (https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v2.0/vendor.js.gz:1:6886012)
    at Worker.<anonymous> (https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v2.0/vendor.js.gz:1:6885841)
```

**Comment by rikinsk** [comment] 2023-06-02 10:58
Closing this as voyager is not exposed on the Hasura console anymore.

**Closed by rikinsk** 2023-06-02 10:58 UTC
Labels: k/bug, c/console, external-dependency, a/collab-ci-cd, t/product-platform
