### ISSUE TITLE
Enum Not Added To Schema

### ISSUE THREAD

**Issue by jcmoore0** [hasura/graphql-engine#3759] opened 2020-01-22 21:00 UTC
**Problem:**  Enums are not updating v1.1.0-beta.2

**Details/ Steps to Reproduce:**

**New Enum**
1. Change table to enum
   Go to Docs -> no enum found for table

**Change Enum**
1. Add row to existing enum table.
2. Press 'reload enum values'
   Go to Docs -> no additional enum found for table

**Comment by lexi-lambda** [comment] 2020-01-24 16:48
Thanks for the report! I think I know what’s causing this—we added some additional caching to the metadata reloading process, and it’s being a little too aggressive for enum tables (the enum values aren’t technically part of the metadata, so it thinks the table “didn’t change” and skips reprocessing it). The fix should be easy.

**Comment by jcmoore0** [comment] 2020-02-08 01:31
Hi @lexi-lambda -  I am still having issues with the new v1.1.0-beta.3 release.  

   'reload enum values'  -  intermittently works  ~20% time
   'make table an enum' - doesn't work after many tries

Thanks for the help.
Best regards,

**Comment by lexi-lambda** [comment] 2020-02-10 15:21
@jcmoore0 Could you say more about what you’re seeing? Are you getting any errors, or is there just no effect whatsoever?

**Comment by jcmoore0** [comment] 2020-02-10 21:31
@lexi-lambda -  I don't get any errors.  It's just not changing the schema.
Thanks,
John

**Comment by jcmoore0** [comment] 2020-02-15 23:56
Hi @lexi-lambda - I just realized the schema will not include enum until a relationship is created to an enum table.

Update:
'reload enum values' - intermittently works ~20% time  -> restart server as a work around
'make table an enum' - works -> need to create a relationship to the enum table first

Thanks for the help.
Best regards,

**Comment by mirzap** [comment] 2020-03-13 18:08
Still a problem in `v1.2.0-beta.2`
After adding a new value to the enum table, I reloaded enum values multiple times but still metadata wasn't updated. I get following err:

```
graphql-engine_1  | Spock Error while handling ["v1","query"]: expected one of the values "en", "de" for type "settings_locales", given "fr"
```
`fr` is a new value in enum table.

Restarting hasura server helped.

**Comment by fbrbovic** [comment] 2020-03-20 15:36
I am experiencing the same problem, no matter how many times I reload it, new values don't show up.
Will try restarting the server.

**Comment by lexi-lambda** [comment] 2020-03-24 01:45
It would be very helpful if you should share a schema that reproduces the issue! Otherwise it’s hard to know what’s going on.

**Comment by jcmoore0** [comment] 2020-03-24 04:49
Hi @lexi-lambda -  'Reload enum values'  doesn't update schema.   It's not super urgent since there is a workaround by restarting the server.

I just ran a simple test and included migrations here:
https://github.com/jcmoore0/hasura_enum

Let me know if you need something else.

Best regards,

**Comment by lexi-lambda** [comment] 2020-03-24 21:13
Thanks, that’s extremely helpful! I can’t promise that we’ll look into it immediately, but I’ll definitely make sure it gets looked at in the near future.

**Comment by mirzap** [comment] 2020-04-06 17:27
This seems to be fixed with latest release (v1.2.0-beta.3)
After clicking "reload enum values" metadata is updated correctly and there's no need to restart hasura server anymore.

Thanks! 🙏

**Comment by jcmoore0** [comment] 2020-04-07 21:25
Confirmed fix.   Thanks, great job.

**Comment by Vishwas-93** [comment] 2020-04-28 20:57
Hi @lexi-lambd,

**Issue**
Adding a brand new Enum Table doesn't show up in the schema. Even after we restarted the server.

**Version - 1.2.0 - beta.5**

Thanks
Vish

**Comment by kurt-o-sys** [comment] 2020-05-17 22:17
It's still not updated here, I'm running hasura 1.2.1.
After adding new values, I can't use the new values in insert operations. 
If I query the enum field using the graphiql/api-explorer, the new values are there.

**Comment by BlueSeph28** [comment] 2020-06-24 18:19
The same happens here! Hasura 1.1.1,
I insert some values, click to "reload values" and doens't work

I do the "switching off and 'Set table as enum'" workaround and it works!

**Comment by pronevich** [comment] 2020-07-11 10:06
v1.2.2 the same issue. @marionschleifer it's more than half year for pretty serious bug )

**Comment by nomocas** [comment] 2020-07-27 23:25
Hi All, Same issue on Hasura 1.3.

**Comment by andycmaj** [comment] 2020-08-17 19:46
i believe that might be what's causing this as well:

![enum bug](https://user-images.githubusercontent.com/97470/90437382-20940600-e087-11ea-9bf9-3b53e81d8328.gif)

running same query multiple times (with an `enum_userOnboardingStatus_enum_comparison_exp`) returns failure about 50% of the time. 

this was after a migration that added a new enum value. 

i force-restarted all of my hasura instances, and this problem went away completely. so yes. seems like caching is the issue.

this is on 1.3.0 running 2 dynos on heroku.

**Comment by Nomad-Go** [comment] 2020-09-17 19:38
Still having this problem on version 1.3.2 had to "force new deployment" on my AWS ECS Service. I tried both reloading the enum table and reloading all metadata.

**Comment by MarkNBroadhead** [comment] 2020-09-29 21:13
Having issue on Hasura 1.3.2. Brand new docker container & database, schema not updating when new enums are added to database table.

**Comment by bgold0** [comment] 2020-10-12 13:46
This is happening to me on Hasura Cloud. I literally can't update my application because of this bug.

**Comment by lexi-lambda** [comment] 2020-10-12 22:59
I finally got to looking into this, and I’m afraid to say I still cannot reproduce this on my machine. :slightly_frowning_face: I tried following the steps in https://github.com/hasura/graphql-engine/issues/3759#issuecomment-603013180 a few times against graphql-engine v1.3.2, but every time I pressed “Reload Enum Values,” I saw the schema immediately update.

This is frustrating, because obviously the issue is happening for several people. I am definitely not denying that! But I have no idea what could possibly be going wrong, and without being able to reproduce the problem, I am not sure how to proceed.

Here are the full details of my environment:

  * HGE: `hasura/graphql-engine:v1.3.2`
  * Postgres: 12.4
  * OS: Ubuntu 18.04 Bionic
  * Docker: 19.03.13

If anyone can provide an environment that consistently reproduces this issue, I’d be much obliged. In the meantime, I’m afraid I’m at something of a loss.

**Comment by pronevich** [comment] 2020-10-15 13:23
Hi, @lexi-lambda here is the reproduction:

1. I created new project in Hasura Cloud.
2.   Created in console SQL:
```sql
CREATE TABLE test_enum (
  val text PRIMARY KEY,
  description text
);

INSERT INTO test_enum (val, description) VALUES
  ('FIRST', 'First test enum val'),
  ('SECOND', 'Second test enum val');
```
3. Created in console SQL. type - ref to test_enum
```sql
CREATE TABLE use_enum (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type text NOT NULL REFERENCES test_enum
);

INSERT INTO use_enum (type) VALUES
  ('FIRST'),
  ('SECOND');
```
4. Set table as enum
5. Update enum value FIRST to FIRST_UPD
6. Reload enum values
![image](https://user-images.githubusercontent.com/680439/96131942-7a3b7400-0f02-11eb-8f8e-bbbecc0a24e7.png)
7. Test if enum value was changed in schema - NO
![image](https://user-images.githubusercontent.com/680439/96132164-ba9af200-0f02-11eb-9290-3c101d76a8fb.png)

**Comment by lexi-lambda** [comment] 2020-10-15 21:50
Good news: with the help of both the comments in this issue and a couple other folks on the team, I finally managed to consistently reproduce the issue on my machine. PR #6027 has the fix, which should hopefully finally resolve this problem for good once merged. Thank you all for your patience!

**Closed** 2020-10-27 19:52 UTC
Labels: c/server, e/easy, k/bug, p/high

**Comment by janosroden** [comment] 2021-01-27 12:01
For hasura newbies like me: add Foreign key below columns, not Relation.

**Comment by willyxiao** [comment] 2021-04-02 02:54
Hi @lexi-lambda is there a workaround for this for hasura v1.3.2?

**Comment by osdiab** [comment] 2021-12-29 04:01
Just registering that this is still happening to my project on version `2.1.0-beta.3` CLI / `v2.1.0` gql engine. If there doesn't exist a foreign key to an enum table, then the enum won't be generated in GQL (and therefore `graphql-codegen` also won't create the enum in my TypeScript project). This is easily worked around by just making a dummy table that never gets used that just contains a reference to the enum table, but that's ugly so would prefer if the enum just got created reliably!

**Comment by ofilipowicz** [comment] 2022-06-22 14:26
Hey @lexi-lambda, it's not working on `v2.2.1`. I tried reloading enums, disabling and enabling enum on a table. Whatever I do, it just isn't added as enum to scheme.

**Comment by OlivierBS** [comment] 2023-03-07 11:45
This is still an issue in v2.16.1, the only fix seems to be to create a seperate dummy table with a foreign key to trick hasura into generating the enum type.

**Comment by ingridkindem** [comment] 2023-05-23 07:17
Tried reloading metadata, but just got errors. Restarting the server did the trick for me

**Comment by hpsmatheus** [comment] 2023-08-02 20:22
Still getting this error on v2.25.1 @lexi-lambda

**Comment by ts-hems** [comment] 2024-08-23 04:22
Hi there,

I'm experiencing the same issue in version 2.42.0. It was working with the previous added enum, but when we added a new enum in a different schema, it's not being picked up and is causing an error in the fetch query.

Is there any solution? @hpsmatheus, has this been resolved yet?

Thank you
Hems Patel
Tracksuit
