### ISSUE TITLE
Hasura 2.0: cannot insert NULL on nullable column (specifically for nested inserts)

### ISSUE THREAD

**Issue by tokestermw** [hasura/graphql-engine#7484] opened 2021-08-31 18:34 UTC
Hi, say we have a table A

```
id: number, primary key, unique, default: nextval
related_id: integer, nullable
```

and table B

```
id: number, primary key, unique, default: nextval
related_text: string
```

w/ foreign keys

```
related_id -> B.id
```

and add a relationship called `relationship`

Now since `related_id` is nullable, we should be able to insert

```
mutation MyMutation {
  insert_A(objects: {relationship: null}) {
    returning {
      relationship {
        id
        related_text
      }
    }
  }
}
```

I am getting the following error

```
"expected an object for type \"B_obj_rel_insert_input\", but found null"
```

This error does not happen on Hasura 1.3.3.

I wonder if it's related nested inserts (https://hasura.io/docs/latest/graphql/core/databases/postgres/mutations/insert.html#nested-inserts). I also didn't find anything in the release notes for Hasura 2.0.

Thanks

**Comment by tirumaraiselvan** [comment] 2021-09-01 07:54
In 2.0, we introduced not allowing `null` values to column operators. This is based on the discussion here: https://github.com/hasura/graphql-engine/issues/704

We also introduced a flag: `HASURA_GRAPHQL_V1_BOOLEAN_NULL_COLLAPSE: true` for preserving the older behaviour but it doesn't work over columns/relationships. For more details, refer to this comment: https://github.com/hasura/graphql-engine/issues/704#issuecomment-864727792

Unfortunately, the only solution is to rewrite the query as so:

```
mutation MyMutation {
  insert_tableA(objects: {relationship: {data: {}}}) {
    returning {
      relationship {
        id
        rel_text
      }
    }
  }
```

**Comment by tokestermw** [comment] 2021-09-01 16:10
Hi @tirumaraiselvan thanks for you response. Good to know the `null` changes affects inserts too.

Your suggested query did not work either as in this case, `related_text` is not nullable.

```
"Not-NULL violation. null value in column \"related_text\" violates not-null constraint"
```

One thing that works is removing `relationship` altogether from the query.

```
mutation MyMutation {
  insert_A(objects: {}) {
    returning {
      relationship {
        id
        related_text
      }
    }
  }
}
```

But then in the code, we are forced to maintain two separate queries.

**Comment by tirumaraiselvan** [comment] 2021-09-06 13:24
Ah, sorry. I thought you wanted to insert a relationship row as well. So, basically you want one query which inserts a parent row and optionally children rows. 

@nicuveo Any thoughts here?

**Comment by nicuveo** [comment] 2021-09-14 13:33
Sorry for the delay! Nope, this is not directly related to the boolean collapse: that was simply an oversight during the work towards 2.0 (see below for an detailed explanation). I have a fix, internally; it will be merged soon, and will hopefully be part of the next release, I'll let you know ASAP.

---

Ok, now, for the behind-the-scenes details.

The GraphQL spec distinguishes between [_implicit_ and _explicit_ null values](http://spec.graphql.org/June2018/#sec-Null-Value): it's not the same thing, semantically, to omit the value, or to explicitly give it `null`. We use this to our advantage, in the engine, to distinguish between _required_ and _optional_ arguments: an optional argument can be omitted (implicit null), but could also be internally non-nullable and reject explicit null values: this is indeed what we now do for boolean values. Such a field would, however, still appear nullable in the schema.

When we rewrote the schema generation code and its corresponding input parsers, we made the field for nested inserts _optional_: the field is nullable in the schema, the relationship can be omitted; but we forgot to make it internally nullable, meaning we erroneously reject explicit null values.

The difference can be seen in the following snippet: https://github.com/hasura/graphql-engine/blob/e919c4132ffb81a2e54b2b1c6f7e6afbd908fde4/server/src-lib/Hasura/GraphQL/Schema/Mutation.hs#L138-L146

in the case of array relationships, the parser is constructed with `P.fieldOptional` and `P.nullable`, but in the case of object relationship, the `P.nullable` is missing.

**Closed** 2021-09-15 13:11 UTC

**Comment by nicuveo** [comment] 2021-09-15 13:20
This was automatically closed when the fix was submitted: it will be part of the next release!

**Comment by tokestermw** [comment] 2021-09-30 21:08
Hi @nicuveo This seems to happen to queries too (not just inserts).

So let's say `name` is Nullable. We want to query `name` inside a relationship called `template`. If `name` is `NULL`, this query fails

```unexpected null value for type \"citext\"```

```graphql
 query ai_agent_query_app_hints(
    $id: Int
    $name: citext
  ) {
    app_users(
      where: {
        id: { _eq: $id }
        template: {
          name: { _eq: $name }
        }
      }
      order_by: { created_at: asc_nulls_last }
    ) {
      id
      created_at
      template {
        name
      }
    }
  }
```

Where query variables

```
{
  "id": 1,
  "name": null
}
```

**Comment by 1018715564** [comment] 2021-11-29 13:56
> 嗨@nicuveo这似乎也发生在查询上（不仅仅是插入）。
> 
> 所以让我们说`name`是 Nullable。我们想`name`在一个名为 的关系中进行查询`template`。如果`name`是`NULL`，则此查询失败
> 
> `unexpected null value for type \"citext\"`
> 
> ```graphql
>  查询 ai_agent_query_app_hints (
>      $id : Int 
>     $name : citext
>   ){
>     app_users（
>       其中：{
>          id：{_ eq：$id }
>         模板：{
>            name：{_ eq：$name }
>         }
>       }
>       order_by : { created_at : asc_nulls_last }
>     ){
>       id 
>       created_at
>       模板{
>         名称
>       }
>     }
>   }
> ```
> 
> where 查询变量
> 
> ```
> {
>   "id": 1,
>   "name": null
> }
> ```

bro, Did you solve this problem, I also encountered the same problem

**Comment by BenoitRanque** [comment] 2022-01-26 04:58
@tokestermw @1018715564 both of you encountered the boolean collapse behavior mentioned earlier in this issue.
This is not a bug. The issue for it is found at #704
