### ISSUE TITLE
cli exits with "Killed: 9" (MacOS 11)

### ISSUE THREAD

**Issue by bconnorwhite** [hasura/graphql-engine#5462] opened 2020-07-25 01:46 UTC
I'm assuming this issue is specific to the MacOS 11 beta- running the hasura cli downloaded from GitHub immediately exits with "Killed: 9".

If instead I clone the repo and build myself, the cli runs as normal.

**Comment by qpre** [comment] 2020-07-30 13:46
Got the same issue using the latest beta of OXS Big Sur.

@bconnorwhite did you manage to get around this ?
<img width="709" alt="Screenshot 2020-07-30 at 15 45 50" src="https://user-images.githubusercontent.com/2156263/88930452-cec44100-d27b-11ea-8fb1-0790d370ab4c.png">

**Comment by bconnorwhite** [comment] 2020-07-30 15:20
There is either an issue in how the cli is built or in MacOS such that the cli only runs on MacOS 11 if it is built on MacOS 11. I'm not familiar with Go, so I was too lazy to debug the real issue myself.

This seems to work as a temporary solution though:
```
git clone https://github.com/hasura/graphql-engine
cd graphql-engine/cli
make deps
make build
```

Then use `graphql-engine/cli/_output/master-xxxxxxxx-dirty/cli-hasura-darwin-amd64` to run.

**Comment by qpre** [comment] 2020-10-01 08:33
Do you know when the Big Sur compatible prebuilt binaries will be available ?
Its release is pending and all Mac users upgrading will encounter this issue.

**Comment by coloradocolby** [comment] 2020-10-25 07:55
Would really benefit from this being fixed as well!

**Comment by gusfune** [comment] 2020-11-05 09:32
Same here using Big Sur 11.0.1 Beta (20B5012d), compiling from Go sources worked. Guess it's a matter of updating the binaries for this release.

**Comment by scriptonist** [comment] 2020-11-05 16:36
Thanks for bringing this to notice folks, I think this was a problem with a tool we use to compress the binary. #6140 should probably have fix for this. It'll great if someone can help us verify the following build works fine. 
https://200424-137724480-gh.circle-artifacts.com/0/cli/binaries/cli-hasura-darwin-amd64

**Comment by gusfune** [comment] 2020-11-05 17:01
> Thanks for bringing this to notice folks, I think this was a problem with a tool we use to compress the binary. #6140 should probably have fix for this. It'll great if someone can help us verify the following build works fine.
> https://200424-137724480-gh.circle-artifacts.com/0/cli/binaries/cli-hasura-darwin-amd64

Yes, it worked nicely here.
OS: **Big Sur 11.0.1 Beta (20B5012d)**

**Comment by qpre** [comment] 2020-11-05 17:50
> Thanks for bringing this to notice folks, I think this was a problem with a tool we use to compress the binary. #6140 should probably have fix for this. It'll great if someone can help us verify the following build works fine.
> https://200424-137724480-gh.circle-artifacts.com/0/cli/binaries/cli-hasura-darwin-amd64

Works for me too !

**Closed** 2020-11-06 06:54 UTC
Labels: c/cli, p/high

**Comment by bubba** [comment] 2020-11-13 14:46
> > Thanks for bringing this to notice folks, I think this was a problem with a tool we use to compress the binary. #6140 should probably have fix for this. It'll great if someone can help us verify the following build works fine.
> > https://200424-137724480-gh.circle-artifacts.com/0/cli/binaries/cli-hasura-darwin-amd64
> 
> Works for me too !
> 
> (also on 11.0.1 Beta (20B5012d))

Binary worked great for me too, thanks! Just had to `chmod u+x` and remove the quarantine flag before running:

```
$ xattr -d com.apple.quarantine /usr/local/bin/hasura
```

**Comment by Ciboulette** [comment] 2020-11-13 15:24
Works great also 🦾

**Comment by alioguzhan** [comment] 2020-11-14 10:32
> Thanks for bringing this to notice folks, I think this was a problem with a tool we use to compress the binary. #6140 should probably have fix for this. It'll be great if someone can help us verify that the following build works fine.
> https://200424-137724480-gh.circle-artifacts.com/0/cli/binaries/cli-hasura-darwin-amd64

I can confirm. that it works on `11.0.1 (20B29)`

**Comment by wmhilton** [comment] 2020-11-14 15:58
I upgraded to Big Sur last night 🙈. When will the fixed CLI be published on `npm`? I'm currently on `"hasura-cli": "1.3.1"`.

**Comment by olegakbarov** [comment] 2020-11-15 11:29
Doesn't work for me when I install cli from url:

```
--> Download complete!
--> Moving cli from /tmp/cli-hasura-darwin-amd64 to /usr/local/bin
-->
--> hasura cli installed to /usr/local/bin
-->
bash: line 137: 99729 Killed: 9               hasura version
```

What are exact steps to install pre-build cli?

**Comment by wmhilton** [comment] 2020-11-16 17:34
For now I'm using @olegakbarov's instructions, modified to copy the file to `node_modules/hasura-cli/hasura`.

**Comment by olegakbarov** [comment] 2020-11-17 04:02
I don't think issue should be closed, since there're only workarounds but not solution

**Comment by tirumaraiselvan** [comment] 2020-11-17 07:35
@olegakbarov Github automatically closes issues when the corresponding PR is merged. This is also good for internal tracking. This has the unfortunate consequence that it feels like the fix is also released. I have added the milestone label for this so that it's clear about which version it will be released in.

**Comment by ryami333** [comment] 2020-11-17 09:25
Hi there, upgraded to Big Sur and now I can't run a console for our Hasura application(s). Can we expect 1.3.3 to be released today?

**Comment by cakemountain** [comment] 2020-11-17 20:55
Broken for me as well, upgraded to Big Sur last night. Similar error: `[1]    23092 killed     hasura`

**Comment by cakemountain** [comment] 2020-11-17 21:11
@olegakbarov do you happen to have a solution for yarn dependency management? Your solution above works great for running Hasura manually but fails on yarn commands with the same error, I'm assuming because yarn doesn't pull from the `/usr/local/bin` version your solution manually patches.

**Comment by toddheslin** [comment] 2020-11-17 23:07
@cakemountain there was a new version released, which should fix the problem.

[Uninstall the current version](https://hasura.io/docs/1.0/graphql/core/hasura-cli/uninstall-hasura-cli.html)

[Install again](https://hasura.io/docs/1.0/graphql/core/hasura-cli/install-hasura-cli.html#install-hasura-cli)

I temporarily used the workaround last night but the newly released version `1.3.3` works fine.

**Comment by qpre** [comment] 2020-11-18 17:24
works fine for me using Big Sur on Intel MBP 15" late 2018

**Comment by wmhilton** [comment] 2020-11-19 15:08
Nice. The `hasura-cli` npm package has been updated to 1.3.3 too. So it all works now!

**Comment by LeulAria** [comment] 2022-11-20 07:23
```sh
chmod 777 /usr/local/bin/hasura
```

NB: user permission of your for user or group
