### ISSUE TITLE
Inheritance and foreign key

### ISSUE THREAD

**Issue by HyperionART** [hasura/graphql-engine#4166] opened 2020-03-23 12:00 UTC
_Originally posted by @marionschleifer in https://github.com/hasura/graphql-engine/issues/3453#issuecomment-561082649_

I'm currently setting up a schema on Hasura (I'm not the one who installed it) and I have this issue with inheritance : 

I have these tables : 

- node
- node_type
- node_content
- game (inherits node_content)

Node contain 2 foreign keys : 
- one to node_type.id
- one to node_content.id

But as soon as I try to insert data, got a violation of FK constraint... 
tried everything and looks like we can't add data as soon as one of the has inheriting child...

Edit : If I remove game of the equation : works fine...

**Comment by tirumaraiselvan** [comment] 2020-03-25 06:05
I tried to repro this with the following schema:

```
CREATE TABLE cities (
    name            text,
    population      int,
    altitude        int,   
    state           text
);

CREATE TABLE capitals (
    airport_id  char(2)
) INHERITS (cities);

CREATE TABLE states (
    name text
);

ALTER TABLE cities
ADD FOREIGN KEY (state) REFERENCES states(name);
```

I could perform all the insert mutations: insert_cities, insert_capitals, insert_states

Can you provide a sample schema and the exact mutation that you are trying to perform which throws this error?

**Comment by HyperionART** [comment] 2020-03-25 13:08
here is what I'm trying to do : 
![Capture d’écran 2020-03-25 à 14 05 47](https://user-images.githubusercontent.com/37306161/77539528-d032c680-6ea1-11ea-9d5f-07a89f5e72d1.png)

The issues is that as soon as I want to make an insert in node via Hasura interface (Data > add row), it throw an fk constraint error (node_content_fk). 
If I remove the inheritance, it works... 

Maybe i did something wrong...

**Comment by tirumaraiselvan** [comment] 2020-03-25 13:38
@HyperionART Are you sure you have all the valid child references present in the child tables i.e. `node_content` and `node_type`  before inserting a row into table `node` with those references?

**Comment by HyperionART** [comment] 2020-03-25 13:42
> @HyperionART Are you sure you have all the valid child references present in the child tables i.e. `node_content` and `node_type` before inserting a row into table `node` with those references?

Yep. 
I added a type, a node_content and then try to add a node by copy/paste the UUID of each (type and content)

**Comment by tirumaraiselvan** [comment] 2020-03-25 13:43
@HyperionART I am not able to reproduce this at my end. Can you share a sample schema and input values?

**Comment by tirumaraiselvan** [comment] 2020-03-25 13:54
Also, your original post shows that `game` inherits `node`. But your diagram shows `game` inherits `node_content`. Could you clarify?

**Comment by HyperionART** [comment] 2020-03-25 13:56
> Also, your original post shows that `game` inherits `node`. But your diagram shows `game` inherits `node_content`. Could you clarify?

oh it's a mistake from me... game inherits from node_content

**Comment by HyperionART** [comment] 2020-03-25 14:03
https://dane2.herokuapp.com/console/data/schema/public/tables/node/insert 
Feel free to check and tell me if I did a mistake (which is possible...)

**Comment by tirumaraiselvan** [comment] 2020-03-25 16:00
@HyperionART Thanks for the repro !

I repro'ed the problem and this is because you inserted into `game` table to get your `node_content`. If you directly insert into `node_content` then this doesn't happen.

This behaviour is because of caveats of inherited tables: https://www.postgresql.org/docs/10/ddl-inherit.html 
From the above postgres docs:

> A serious limitation of the inheritance feature is that indexes (including unique constraints) and foreign key constraints only apply to single tables, not to their inheritance children. This is true on both the referencing and referenced sides of a foreign key constraint.

This means that when you inserted into `game` table,  the referenced table `node_content` did not recognize that row as part of being in the "foreign key" constraint. Now, when you insert into `node` with that node_content value, it obviously fails reference check and throws the error.

I am not sure how you can solve this problem really.

**Comment by tirumaraiselvan** [comment] 2020-03-28 06:20
@HyperionART There is infact a workaround.

You can drop the actual foreign key constraint on `node`:

`
alter table node drop constraint node_node_content_fkey
`

And then you can create a manual relationship instead as `node.node_content -> node_content.id`. See https://hasura.io/docs/1.0/graphql/manual/schema/relationships/create.html#create-manual-relationships

This allows you to insert into either `node_content` and `game` while still being able to preserve the relationship. See https://dane2.herokuapp.com/console/data/schema/public/tables/node/insert to try this out.

**Comment by HyperionART** [comment] 2020-03-31 12:05
> @HyperionART There is infact a workaround.
> 
> You can drop the actual foreign key constraint on `node`:
> 
> `alter table node drop constraint node_node_content_fkey`
> 
> And then you can create a manual relationship instead as `node.node_content -> node_content.id`. See https://hasura.io/docs/1.0/graphql/manual/schema/relationships/create.html#create-manual-relationships
> 
> This allows you to insert into either `node_content` or `game` while still being able to preserve the relationship. See https://dane2.herokuapp.com/console/data/schema/public/tables/node/insert to try this out.

Hello ! 

I took a bit of time to make my test and THANK YOU ! You saved me a lot of issues for my project ! 
This is exactly what I was looking to

**Comment by tirumaraiselvan** [comment] 2020-03-31 13:40
No problem. I am closing this issue then :)

**Closed by tirumaraiselvan** 2020-03-31 13:40 UTC
Labels: k/question❓
