### ISSUE TITLE
Configure trigger to add related data in payload

### ISSUE THREAD

**Issue by tombroens** [hasura/graphql-engine#3298] opened 2019-11-02 09:31 UTC
Related to #3247, to make the payload of a firing trigger a bit more elaborate.

Add to trigger configuration (in the console) the ability to select the relation to be added in the payload. E.g. set trigger on table Article (which has a relationship with table User), select User(firstname, lastname) to be added in the payload when the trigger on Article fires.

Possible challenge is to support n:m relationships as they probably include 2 levels of releationships. But 1:n would already be very helpfull.

**Comment by fbrbovic** [comment] 2020-03-11 19:21
This would help greatly in reducing the number of calls back to Hasura server in my use case so got my vote for this :)

**Comment by sobrinho** [comment] 2020-04-13 19:11
That's important here as well!

We can easily trigger hundreds of events here that needs to go back to Hasura to pull a specific field of our table (a computed one, of course).

**Comment by tirumaraiselvan** [comment] 2020-12-24 14:33
Going to close this as dupe of: https://github.com/hasura/graphql-engine/issues/3298

Pls comment/reopen if you feel otherwise!

**Closed by tirumaraiselvan** 2020-12-24 14:33 UTC
Labels: c/server, k/enhancement, p/medium, triage/2-needs-rfc

**Comment by sobrinho** [comment] 2020-12-24 17:15
That's the #3298 😂
