### ISSUE TITLE
close gaps between metadata apis and console

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#1683] opened 2019-03-01 05:24 UTC
There are still some things like creating composite foreign keys etc. that are possible via the API, but through the console. These gaps should be addressed immediately.

**Comment by rikinsk** [comment] 2019-05-24 11:02
Step 1: make a list of all gaps
Step 2: fork off individual issues for each gap

**Comment by rikinsk** [comment] 2019-07-24 09:30
Raw SQL
- [ ] `check_metadata_consistency` flag in `run_sql`

Table modify
- [ ] `cascade` flag in `untrack_table` _(console should give option to drop dependants after showing list)_

Relationships
- [ ] comments for relationships
- [ ] `cascade` flag in `drop_relationship` _(console should give option to drop dependants after  after showing list)_

Permissions
- [ ] comments for permissions
- [ ] '*' in permission columns

**Comment by manasag** [comment] 2023-12-28 16:57
This issue has not attracted significant attention for a long period of time, hence closing this.
Please feel free to reopen if the issue is still relevant for you.

**Closed by manasag** 2023-12-28 16:57 UTC
Labels: c/console, design-rfc, p/high, e/intermediate
