### ISSUE TITLE
Voyager Crash with error

### ISSUE THREAD

**Issue by ioloc** [hasura/graphql-engine#6208] opened 2020-11-17 14:52 UTC
Error: abort("Assertion failed: font->name, at: textspan.c,206,textspan_size"). Build with -s ASSERTIONS=1 for more info.
    at Array.r.listeners.<computed> (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.3/vendor.js.gz:1:6932448)
    at Worker.<anonymous> (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.3/vendor.js.gz:1:6932277)

**Comment by ioloc** [comment] 2020-11-17 14:52
The same error message occurs ever time I try use voyager.

**Comment by beerose** [comment] 2020-11-17 15:02
Thanks for reporting. We have [a fix](https://github.com/hasura/graphql-engine/pull/4856) in place and hopefully, we'll release it soon.

In the meantime, I'm closing this issue as a duplicate of https://github.com/hasura/graphql-engine/issues/3023

**Closed by beerose** 2020-11-17 15:02 UTC
Labels: c/console, duplicate
