### ISSUE TITLE
Console: Randomly disconnects and throws a CORS error - sometimes resulting in totally catatonic/broken console instance

### ISSUE THREAD

**Issue by 24601** [hasura/graphql-engine#7430] opened 2021-08-20 17:33 UTC
v2.0.7 server & client

At the browse rows path in the "Data" route on one of our Tables: 

![Screen Shot 2021-08-20 at 11 31 08](https://user-images.githubusercontent.com/1157207/130271802-317417d3-3b76-45e1-b9fe-352a845d1d9a.png)

Retrying usually addresses the issue, but sometimes the console remains in a broken state and the `hasura console` process needs to be restarted. When it fails, any subsequent operations to the console result in the following error, although the admin key is correct, is provided on the CLI (e.g. the instance was started and working, so the key is obviously correct). 

![Screen Shot 2021-08-20 at 11 35 59](https://user-images.githubusercontent.com/1157207/130272237-4837fbc1-a2f3-4a1e-ad0e-d06ba5cbff14.png)

These issues (along with a couple others) have our dev team 100% blocked on feature dev (we are a Hasura Cloud customer for our production instances, so I hope we can find a way to escalate this using that support contract, as we are paying customers).

**Comment by lucarestagno** [comment] 2023-05-31 12:46
This issue refers to an old version of the Console, therefore this should have been addressed in recent versions.
If the issue is still present, @24601 please reopen it — thanks.

**Closed by lucarestagno** 2023-05-31 12:46 UTC
Labels: k/bug, c/console, c/cli
