### ISSUE TITLE
Mutations fail when selecting computed columns if target tables have untracked columns

### ISSUE THREAD

**Issue by chardo** [hasura/graphql-engine#10553] opened 2024-09-30 17:35 UTC
### Version Information

Server Version: 2.43.0
CLI Version (for CLI related issue):

### Environment

OSS, Docker
DB is Postgres version 12

### What is the current behaviour?

Our DB schema includes a couple of procedures which are exposed as as [custom fields](https://hasura.io/docs/2.0/schema/postgres/computed-fields/) on two of our tables. Whenever we add a column to any of our tables, any mutation against the modified table that selects a computed field in its results fails. The errors we get from the graphql API look like this (real example from our schema):
```
{
  "errors": [
    {
      "message": "database query error",
      "extensions": {
        "path": "$",
        "code": "unexpected",
        "internal": {
          "arguments": [],
          "error": {
            "description": "Input has too few columns.",
            "exec_status": "FatalError",
            "hint": null,
            "message": "cannot cast type record to ecommerce_accounts",
            "status_code": "42846"
          },
          "prepared": false,
          "statement": "WITH \"_mra__ecommerce_accounts\" AS (UPDATE \"public\".\"ecommerce_accounts\" SET \"created_at\" = ('now()')::timestamptz  WHERE ((\"public\".\"ecommerce_accounts\".\"ecommerce_platform\") = (('shopify')::\"ecommerce_platform\")) RETURNING * , ('true')::boolean AS \"check__constraint\"), \"_aca__ecommerce_accounts\" AS (SELECT  \"id\" , \"account_configuration\" , \"brand_id\" , \"ecommerce_platform\" , \"created_at\" , \"updated_at\" , \"deleted_at\" , \"foo\"  FROM \"_mra__ecommerce_accounts\"      ) SELECT  json_build_object('returning', (SELECT  coalesce(json_agg(\"root\" ), '[]' ) AS \"root\" FROM  (SELECT  row_to_json((SELECT  \"_e\"  FROM  (SELECT  \"_root.base\".\"id\" AS \"id\", \"public\".\"ecomm_subsciptions_enabled\"(\"_root.base\")  AS \"has_subscriptions\"       ) AS \"_e\"      ) ) AS \"root\" FROM  (SELECT  *  FROM \"_aca__ecommerce_accounts\" WHERE ('true')     ) AS \"_root.base\"      ) AS \"_root\"      ) ) , (SELECT  coalesce(bool_and(\"check__constraint\" ), 'true' )  FROM \"_mra__ecommerce_accounts\"      )        "
        }
      }
    }
  ]
}
```

This does resolve when we reload the metadata in our graphql-engine server, either by issuing a `hasura metadata reload` command, or by (in prod) rolling all the pods of our deployment so that the new pods refresh their metadata automatically on startup. However, this still causes issues in our production applications because people are making changes to our DB schema that appear to be backwards compatible - adding columns to tables without exposing those new columns to API users or using them in any of our applications. Because the computed fields I referenced earlier are on a couple of central tables in our schema, it's common for mutations in our applications to select them and run into these errors.

Even if we were to try and automatically reload metadata whenever we change our DB schema, this situation makes it impossible to guarantee zero-downtime schema modifications as there's no way to guarantee how quickly pods in our deployment can roll. 

### What is the expected behaviour?

In basically all other use cases that I've tested, adding columns to a table that the graphql-engine is tracking, without trying to use that column in applications, doesn't appear to be a breaking change. After adding a new column to a table but before reloading metadata in the graphql-engine server, I'm able to do both of the following via the graphql API without any errors:
 - query the table in question, directly or via joins
 - mutate rows in the table (as long as I don't select any computed fields from the results)

In other words, I'd expect adding columns (or adding tables) to our DB schema to be a non-breaking change regardless of whether the graphql-engine server has reloaded its metadata, and it appears to be in most cases. As suggested above, this is especially important in any real-world production environment, where there's basically no way to guarantee a synchronous, safe execution of a DB schema modification _and_ complete redeployment of graphql-engine.

If what I'm describing _is_ the expected behavior, it would be really helpful to have a clear description somewhere of the DB schema changes that are expected to break Hasura in production and recommendations/best practices for mitigating or minimizing downtime or degraded capabilities in our applications. For various reasons, it's not really an option for our team to use Hasura to manage our DB schema, so at minimum we would love to have some clarity and consistency around how to operationalize schema changes as safely as possible. 

### How to reproduce the issue?

1. Run `graphql-engine:2.43.0` and `postgres:12` in a docker compose stack.
2. Create some initial tables and data in your DB like so:
```sql
create table t1 (
    id serial primary key,
    name text
);
create table t2 (
    t1_id int not null references t1,
    name text
);
create function t1_is_foo(t t1) returns boolean stable language plpgsql as
$$
begin
    return t.name === 'foo';
end;
$$;
insert into t1 (name)
values ('foo'), ('bar');
insert into t2 (t1_id, name)
values (1, 'foo_join'), (2, 'bar_join');
```
3. Track `t1` and `t2`, expose `t1_is_foo` as a computed field on `t1` (call it `is_foo`), and create a relationship between the two tables. Confirm that works by submitting the following query to the graphql endpoint:
```graphql
query select_computed {
  t2 {
    t1 {
      name
      is_foo
    }
  }
}
```
Which should return:
```
{
  "data": {
    "t2": [
      {
        "t1": {
          "name": "foo",
          "is_foo": true
        }
      },
      {
        "t1": {
          "name": "bar",
          "is_foo": false
        }
      }
    ]
  }
}
```
4. Add a column to t1: `alter table t1 add column new_col int;`
5. Confirm that the `select_computed` query above still works, but then try running the following series of mutations and observe which ones succeed/fail:
```graphql
# This modifies an unchanged table and doesn't select a computed field. It succeeds.
mutation modify_t2 {
  update_t2(
    where: {t1_id: {_eq: 1}},
    _set: {name: "updated"}
  ) {
    returning {
      name
    }
  }
}

# This modifies an unchanged table and selects a computed field from a relationship. It succeeds.
mutation modify_t2_select_computed {
  update_t2(
    where: {t1_id: {_eq: 1}},
    _set: {name: "updated again"}
  ) {
    returning {
      name
      t1 {
        is_foo
      }
    }
  }
}

# This modifies a changed table but does NOT select a computed field. It succeeds.
mutation modify_t1 {
  update_t1_by_pk(
    pk_columns: {id: 1},
    _set: {name: "updated"}
  ) {
    name
  }
}

# This modifies a changed table AND selects a computed field. It fails!
mutation modify_t1_select_computed {
  update_t1_by_pk(
    pk_columns: {id: 1},
    _set: {name: "updated again"}
  ) {
    name
    is_foo
  }
}
```
The error should look like this:
```
{
  "errors": [
    {
      "message": "database query error",
      "extensions": {
        "path": "$",
        "code": "unexpected",
        "internal": {
          "arguments": [],
          "error": {
            "description": "Input has too few columns.",
            "exec_status": "FatalError",
            "hint": null,
            "message": "cannot cast type record to t1",
            "status_code": "42846"
          },
          "prepared": false,
          "statement": "WITH \"_mra__t1\" AS (UPDATE \"public\".\"t1\" SET \"name\" = ('updated again')::text  WHERE ((\"public\".\"t1\".\"id\") = (('1')::integer)) RETURNING * , ('true')::boolean AS \"check__constraint\"), \"_aca__t1\" AS (SELECT  \"id\" , \"name\"  FROM \"_mra__t1\"      ) SELECT  (SELECT  coalesce((json_agg(\"root\" )->0), 'null' ) AS \"root\" FROM  (SELECT  row_to_json((SELECT  \"_e\"  FROM  (SELECT  \"_root.base\".\"name\" AS \"name\", \"public\".\"t1_is_foo\"(\"_root.base\")  AS \"is_foo\"       ) AS \"_e\"      ) ) AS \"root\" FROM  (SELECT  *  FROM \"_aca__t1\" WHERE ('true')     ) AS \"_root.base\"      ) AS \"_root\"      ) , (SELECT  coalesce(bool_and(\"check__constraint\" ), 'true' )  FROM \"_mra__t1\"      )        "
        }
      }
    }
  ]
}
```
6. Now add a column to t2: `alter table t2 add column new_col int;`
7. Re-run the mutations above, and observe that `modify_t2` and `modify_t1` still succeed, but `modify_t2_select_computed` now fails with the following error:
```
{
  "errors": [
    {
      "message": "database query error",
      "extensions": {
        "path": "$",
        "code": "unexpected",
        "internal": {
          "arguments": [],
          "error": {
            "description": "Input has too few columns.",
            "exec_status": "FatalError",
            "hint": null,
            "message": "cannot cast type record to t1",
            "status_code": "42846"
          },
          "prepared": false,
          "statement": "WITH \"_mra__t1\" AS (UPDATE \"public\".\"t1\" SET \"name\" = ('updated again')::text  WHERE ((\"public\".\"t1\".\"id\") = (('1')::integer)) RETURNING * , ('true')::boolean AS \"check__constraint\"), \"_aca__t1\" AS (SELECT  \"id\" , \"name\"  FROM \"_mra__t1\"      ) SELECT  (SELECT  coalesce((json_agg(\"root\" )->0), 'null' ) AS \"root\" FROM  (SELECT  row_to_json((SELECT  \"_e\"  FROM  (SELECT  \"_root.base\".\"name\" AS \"name\", \"public\".\"t1_is_foo\"(\"_root.base\")  AS \"is_foo\"       ) AS \"_e\"      ) ) AS \"root\" FROM  (SELECT  *  FROM \"_aca__t1\" WHERE ('true')     ) AS \"_root.base\"      ) AS \"_root\"      ) , (SELECT  coalesce(bool_and(\"check__constraint\" ), 'true' )  FROM \"_mra__t1\"      )        "
        }
      }
    }
  ]
}
```
8. Reload the metadata in the graphql-engine server (make sure to check "Reload all databases" if doing this in the console) and now observe that all 4 mutations succeed.

### Screenshots or Screencast

I think the above steps should make it pretty easy to recreate, but please let me know if any specific screenshots or recordings would be helpful!

### Please provide any traces or logs that could help here.

See all the error responses above. In addition, here are the logs I see in my locally running server when I submit one of the failed mutations:
```
2024-09-30 10:25:19 {"detail":{"generated_sql":null,"kind":"database","query":{"operationName":"modify_t1_select_computed","query":"# This modifies an unchanged table and doesn't select a computed field. It succeeds.\nmutation modify_t2 {\n  update_t2(\n    where: {t1_id: {_eq: 1}},\n    _set: {name: \"updated\"}\n  ) {\n    returning {\n      name\n    }\n  }\n}\n\n# This modifies an unchanged table and selects a computed field from a relationship. It succeeds.\nmutation modify_t2_select_computed {\n  update_t2(\n    where: {t1_id: {_eq: 1}},\n    _set: {name: \"updated again\"}\n  ) {\n    returning {\n      name\n      t1 {\n        is_foo\n      }\n    }\n  }\n}\n\n# This modifies a changed table but does NOT select a computed field. It succeeds.\nmutation modify_t1 {\n  update_t1_by_pk(\n    pk_columns: {id: 1},\n    _set: {name: \"updated\"}\n  ) {\n    name\n  }\n}\n\n# This modifies a changed table AND selects a computed field. It fails!\nmutation modify_t1_select_computed {\n  update_t1_by_pk(\n    pk_columns: {id: 1},\n    _set: {name: \"updated again\"}\n  ) {\n    name\n    is_foo\n  }\n}"},"request_id":"1239529d-05e0-4e61-be59-019e5764b450"},"level":"info","span_id":"1d3ab352d43cc11f","timestamp":"2024-09-30T17:25:19.278+0000","trace_id":"3d5ddca1d16e1576f999612968610f54","type":"query-log"}
2024-09-30 10:25:20 {"detail":{"http_info":{"content_encoding":null,"http_version":"HTTP/1.1","ip":"192.168.65.1","method":"POST","status":200,"url":"/v1/graphql"},"operation":{"error":{"code":"unexpected","error":"database query error","internal":{"arguments":[],"error":{"description":"Input has too few columns.","exec_status":"FatalError","hint":null,"message":"cannot cast type record to t1","status_code":"42846"},"prepared":false,"statement":"WITH \"_mra__t1\" AS (UPDATE \"public\".\"t1\" SET \"name\" = ('updated again')::text  WHERE ((\"public\".\"t1\".\"id\") = (('1')::integer)) RETURNING * , ('true')::boolean AS \"check__constraint\"), \"_aca__t1\" AS (SELECT  \"id\" , \"name\"  FROM \"_mra__t1\"      ) SELECT  (SELECT  coalesce((json_agg(\"root\" )->0), 'null' ) AS \"root\" FROM  (SELECT  row_to_json((SELECT  \"_e\"  FROM  (SELECT  \"_root.base\".\"name\" AS \"name\", \"public\".\"t1_is_foo\"(\"_root.base\")  AS \"is_foo\"       ) AS \"_e\"      ) ) AS \"root\" FROM  (SELECT  *  FROM \"_aca__t1\" WHERE ('true')     ) AS \"_root.base\"      ) AS \"_root\"      ) , (SELECT  coalesce(bool_and(\"check__constraint\" ), 'true' )  FROM \"_mra__t1\"      )        "},"path":"$"},"query":{"operationName":"modify_t1_select_computed","query":"# This modifies an unchanged table and doesn't select a computed field. It succeeds.\nmutation modify_t2 {\n  update_t2(\n    where: {t1_id: {_eq: 1}},\n    _set: {name: \"updated\"}\n  ) {\n    returning {\n      name\n    }\n  }\n}\n\n# This modifies an unchanged table and selects a computed field from a relationship. It succeeds.\nmutation modify_t2_select_computed {\n  update_t2(\n    where: {t1_id: {_eq: 1}},\n    _set: {name: \"updated again\"}\n  ) {\n    returning {\n      name\n      t1 {\n        is_foo\n      }\n    }\n  }\n}\n\n# This modifies a changed table but does NOT select a computed field. It succeeds.\nmutation modify_t1 {\n  update_t1_by_pk(\n    pk_columns: {id: 1},\n    _set: {name: \"updated\"}\n  ) {\n    name\n  }\n}\n\n# This modifies a changed table AND selects a computed field. It fails!\nmutation modify_t1_select_computed {\n  update_t1_by_pk(\n    pk_columns: {id: 1},\n    _set: {name: \"updated again\"}\n  ) {\n    name\n    is_foo\n  }\n}","variables":null},"query_execution_time":0.325768042,"request_id":"1239529d-05e0-4e61-be59-019e5764b450","request_mode":"error","request_read_time":1.2541e-5,"response_size":1010,"uncompressed_response_size":1010,"user_vars":{"x-hasura-role":"admin"}},"request_id":"1239529d-05e0-4e61-be59-019e5764b450"},"level":"error","span_id":"1d3ab352d43cc11f","timestamp":"2024-09-30T17:25:19.278+0000","trace_id":"3d5ddca1d16e1576f999612968610f54","type":"http-log"}
```

### Any possible solutions/workarounds you're aware of?

Basically the only path forward I see is to have our DB tooling hook into our production Hasura instance, either via the API or indirectly via Kubernetes operations, to ensure that our metadata gets reloaded whenever our DB schema changes. However, at best I view this as a reduction of downtime and not really a way of avoiding it altogether (there will always be some lag between the DB operations completing and all Hasura instances having fresh metadata). Practically I think I'm going to do this anyways, but I'd love to know if you all have any recommendations for managing these sorts of changes with no downtime.

Or I suppose we could use Hasura to manage our DB schema, but as I mentioned above that's not really a viable path forward for us (would prefer to avoid getting locked in or forcing our entire team to learn how to use Hasura, plus it seems like v3 of Hasura doesn't even support DB schema management).

### Keywords

input has too few columns, mutation on modified table, computed fields, stale metadata, breaking vs non-breaking schema change, managing schema outside of hasura without downtime

**Comment by rakeshkky** [comment] 2024-10-03 08:55
Hi @chardo, thank you for raising the issue with detailed description.

By design, Hasura v2 relies on Postgres' table catalog metadata to effectively generate SQL for mutations. It stores a cache of the database schema, for tracked items, and this cache can only be refreshed when changes are made through Hasura (console or run_sql API). You don't want to use Hasura to manage your database schema. It is totally understandable.

I second the approach you mentioned in the workarounds section. Using the [API](https://hasura.io/docs/2.0/migrations-metadata-seeds/resolving-metadata-inconsistencies/) to refresh the schema is better than restarting the pods. Furthermore, configure the API to make it efficient, i.e, avoid reloading remote schemas, recreating event triggers and reload only a specific data source (when multiple sources exist).

Removing the `k/bug` label, as it is not a bug but a design choice. Closing this issue for now; feel free to re-open it if you have any further queries.

**Closed by rakeshkky** 2024-10-03 08:55 UTC
Labels: k/bug, v2-server, c/v2-engine

**Comment by chardo** [comment] 2024-10-03 16:36
@rakeshkky cool, really appreciate the response! It's helpful to at least know that this is expected behavior, and an operational limitation that we'll need to work around. A few questions / points of feedback, just in case it's helpful:
 - This point is interesting to me: "Using the API to refresh the schema is better than restarting the pods" - can you provide a little more detail about this? Better in what way(s), and why? How does that square with [your docs](https://hasura.io/docs/2.0/deployment/production-checklist/#disable-apis) that specifically recommend not to expose the metadata API in prod?
 - While I totally understand the constraints of these systems, and I appreciate that this is not an easy problem to solve, I do think it should be made more clear somewhere in your documentation that 0-downtime schema migrations aren't actually possible. In any real production scenario, people are going to be running more than one instance of the graphql-engine, and I'd be surprised if we were the only team using Hasura for the GraphQL API without using it to manage our schema (plus it looks like V3 doesn't even support schema management?). To be clear, I'm a huge fan of Hasura and I'm really glad we're using it! But also, evolving a DB schema under a live API is a really common workflow, and knowing upfront that this common operation would likely always incur downtime probably would have changed my thought process about adopting it in the first place.

**Comment by rakeshkky** [comment] 2024-10-03 17:35
@chardo, thank you for the feedback. 

The `reload_metadata` API refreshes the cache while keeping the GraphQL API live. Hasura uses an internal locking mechanism during the reload process to ensure that all subsequent requests are served with the most up-to-date metadata.

However, in a production environment, we generally recommend disabling the console and metadata API. This is based on the assumption that Hasura metadata and database schema changes aren't made dynamically in production.

I have a suggestion that might be worth considering. You could spin up a separate instance of graphql-engine (same version) dedicated exclusively to handle metadata API requests, without exposing it publicly. Hasura has a built-in schema-sync mechanism, so any metadata changes made through this instance will eventually be propagated to the other production instances, without any downtime.

Let me know your thoughts.

Ref: https://hasura.io/docs/2.0/deployment/graphql-engine-flags/reference/#schema-sync-poll-interval

**Comment by chardo** [comment] 2024-10-03 18:55
oh, that's interesting. so basically the suggestion is to spin up a short-lived, ideally local, instance of the server that connects to our prod DB and reloads the metadata. then the graphql-engine pods in production would detect that metadata update and automatically refresh their own caches.

just so you're aware (might be helpful to know how hasura's used in practice?), I think for now we're going to stick with an automated `kubectl rollout restart deployment` command just because that's the simplest thing for us to automate in our environment. but if (or, more likely, when) the tradeoffs of that approach bother us, I'll definitely consider this approach. still won't mean a true 0-downtime update, but will be less thrashing of production resources.

thanks again for the help, truly helpful to get some input on this.

**Comment by rakeshkky** [comment] 2024-10-04 09:10
If possible, you can always keep the metadata-only instance running beside your production instances. Please make sure the production traffic is not routed to this instance, and its API is only available to internal services. Hope this is helpful. Thank you.
