### ISSUE TITLE
Pgdump mismatch with Postgres server /docker-compose

### ISSUE THREAD

**Issue by sethsnel** [hasura/graphql-engine#6161] opened 2020-11-10 09:12 UTC
I have the same issue as #2749, however just a little diffirent:
`time="2020-11-10T09:48:39+01:00" level=fatal msg="cannot fetch schema dump: [unexpected] error while executing pg_dump: pg_dump: error: server version: 13.0 (Debian 13.0-1.pgdg100+1); pg_dump version: 12.2 (Debian 12.2-2.pgdg90+1)\npg_dump: error: aborting because of server version mismatch\n ($)"`

I'm using this image:
`hasura:
    image: hasura/graphql-engine:latest`

Are there plans to update to pg_dump 13?
And is there maybe a way to have the pg version defined externally?

**Comment by kolharsam** [comment] 2020-11-10 10:10
Hey @sethsnel 👋 
We are working on it. See #6070. We should have it out soon :)
There is a preview image [available](https://200042-137724480-gh.circle-artifacts.com/0/server/image.tar). Let us know if there are any unexpected behaviors.

**Comment by kolharsam** [comment] 2020-11-10 10:14
Closing this as a dupe of #5836

**Closed by kolharsam** 2020-11-10 10:14 UTC

**Comment by sethsnel** [comment] 2020-11-10 11:09
@kolharsam , great thanks!
