### ISSUE TITLE
Hasura Console errors behind proxy after 2.0 upgrade

### ISSUE THREAD

**Issue by JeffSpies** [hasura/graphql-engine#7457] opened 2021-08-24 20:22 UTC
Hi, folks,

I upgraded to Hasura v2.0.7 (via Docker) and the Data page no longer loads (chrome console messages below--fails on all browsers tried though). The API Explorer works fine.

Everything works as expected by going to localhost:8002 (the exposed Hasura port).

If anyone has ideas or the 2.0 console running behind a proxy and wouldn't mind sharing their configuration, I'd appreciate it.

Thanks!

**Browser errors against a minified main.js**
```
Uncaught (in promise) TypeError: e.map is not a function
    at graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.0/main.js.gz:1
main.js.gz:1 Uncaught (in promise) TypeError: Cannot read property '1' of undefined
    at graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.0/main.js.gz:1
main.js.gz:1 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.0/main.js.gz:1
```

**Ports**
```
NGINX_PORT=8000
HASURA_PORT=8002
```

**Relevant nginx conf (w some gomplate templating)**
```
upstream hasura {
  server {{ .Env.DOCKER_HOST_IP}}:{{ .Env.HASURA_PORT }};
  keepalive 64;
}

server {
  listen {{ .Env.NGINX_PORT}};

  location ~ /console { 
    proxy_pass http://hasura;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location ~ /(v1alpha1|v1|v1beta1|v2|apis|healthz) {
    proxy_pass http://hasura;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
...
}
```

**Comment by coco98** [comment] 2021-08-25 01:25
@JeffSpies Does this happen only after the upgrade or on a brand new 2.0.7 project as well?

**Comment by lucarestagno** [comment] 2023-05-31 12:46
This issue refers to an old version of the Console, therefore this should have been addressed in recent versions.
If the issue is still present, @JeffSpies please reopen it — thanks.

**Closed by lucarestagno** 2023-05-31 12:46 UTC
Labels: k/bug, c/console
