### ISSUE TITLE
Feature Request:Send schema name and table name to authentication webhook

### ISSUE THREAD

**Issue by rinfimate** [hasura/graphql-engine#1159] opened 2018-12-03 11:33 UTC

**Comment by 0x777** [comment] 2018-12-03 12:03
@rinfimate Can you describe your use case where this information is needed? It is not as simple a single graphql query could potentially access any number of tables.

**Comment by manasag** [comment] 2023-12-27 13:58
This issue has not attracted significant attention for a long period of time, and since alternatives are available, we are closing this.
Please feel free to reopen if the issue is still relevant for you.

**Closed** 2023-12-27 14:10 UTC
Labels: k/ideas
