### ISSUE TITLE
SQL query from Analyze has extra spaces

### ISSUE THREAD

**Issue by dnlo** [hasura/graphql-engine#6498] opened 2021-01-28 13:09 UTC
GraphQL query runs fine, tags is JSONB :
```
query MyQuery {
  vehicles(where: {tags: {_contains: "Offer Delivery"}}) {
    id
    tags
  }
}
```

Analyzed query returns `operator does not exist: jsonb @` when I run it from hasura console
```
SELECT
  coalesce(json_agg("root"), '[]') AS "root"
FROM
  (
    SELECT
      row_to_json(
        (
          SELECT
            "_1_e"
          FROM
            (
              SELECT
                "_0_root.base"."id" AS "id",
                "_0_root.base"."tags" AS "tags"
            ) AS "_1_e"
        )
      ) AS "root"
    FROM
      (
        SELECT
          *
        FROM
          "public"."vehicles"
        WHERE
          (
            ("public"."vehicles"."tags") @ > (('"Offer Delivery"') :: jsonb)
          )
      ) AS "_0_root.base"
  ) AS "_2_root"
```

PostgreSQL 12.4 on x86_64-pc-linux-gnu, compiled by Debian clang version 10.0.1 , 64-bit
Hasura Current server version: v1.3.1

**Comment by tirumaraiselvan** [comment] 2021-02-05 08:45
I think the issue is that there is an extra space added in `@ >`.

**Comment by dnlo** [comment] 2021-02-05 14:58
@tirumaraiselvan You are right, without the space it works fine

**Comment by beerose** [comment] 2021-02-24 20:56
Closing in favor of https://github.com/hasura/graphql-engine/issues/4893

**Closed by beerose** 2021-02-24 20:56 UTC
Labels: c/console, k/bug
