### ISSUE TITLE
OpenAPI import create action error

### ISSUE THREAD

**Issue by ashleygeorgeclarke** [hasura/graphql-engine#10261] opened 2024-05-24 10:06 UTC
### Version Information

Server Version: v2.39.1

### Environment

EE

### What is the current behaviour?

When trying to create an action from an imported OpenAPI spec, some of the actions return an error as below.

```
[
    {
        "error_code": "Parse Error",
        "message": "Unexpected token '?'.",
        "source_position": {
            "end_column": 34,
            "end_line": 92,
            "start_column": 32,
            "start_line": 92
        }
    }
]
```

### How to reproduce the issue?

Have attached the openapi spec. 
[oapi.json](https://github.com/hasura/graphql-engine/files/15431770/oapi.json)
Have also included the request body sent upon 'create' attempt [requestbody.json](https://github.com/hasura/graphql-engine/files/15431763/requestbody.json)
The spec file passes validation.

### Screenshots or Screencast

<img width="1203" alt="image" src="https://github.com/hasura/graphql-engine/assets/4650777/cc433119-1659-41a3-b902-cfc95dfb8380">

### Please provide any traces or logs that could help here.

I could not find any relevant logs.

### Keywords

OAS3 import openapi action

**Comment by Varun-Choudhary** [comment] 2024-07-15 04:58
Hey @ashleygeorgeclarke, the issue is fixed in the latest version `v2.41`. Please upgrade and check if you can create actions from the imported open API spec.

**Closed** 2024-07-18 08:53 UTC
Labels: k/bug
