### ISSUE TITLE
Custom webhook is triggered for every API call even after passing cache-control/expires header

### ISSUE THREAD

**Issue by aniketkambli** [hasura/graphql-engine#9204] opened 2022-11-12 05:42 UTC
### Version Information

Server Version:
CLI Version (for CLI related issue):

### Environment

Cloud

### What is the current behaviour?
Currently the webhook that i have implemented for custom authentication it is getting triggered again and again even when i am passing the cache-control header like Cache Control : Max age 62000

 I have implemented the custom auth webhook but the problem I am facing is that even after sending the cache-control header with value set to 600 , Hasura is again triggering the custom webhook (within 600 seconds) for subsequent request with the same token. What I want is Hasura calls my auth webhook once and I return a 24 hours cache control and it again validates the token only after 24 hours. Is there any way to achieve this ?
### What is the expected behaviour?

Hasura should cache the response form my webhook and not call the webhook again and again
### How to reproduce the issue?

1. Create the custom webhook for authentication
2. Pass the authorization header form the console/api console
3. Check logs of the webhook for checking the invocation time and payload.

### Screenshots or Screencast

<img width="738" alt="image" src="https://user-images.githubusercontent.com/38850180/201459231-e82f675b-f575-4f99-9c5e-aca7ec56a733.png">

### Any possible solutions/workarounds you're aware of?
No

### Keywords

Custom auth webhook, custom authentication

**Comment by kevinmichaelchen** [comment] 2023-01-05 18:16
This would be an awesome feature! Just tested with `cache-control: max-age=604800` and had the same observation: Hasura is not caching the response.

<img src="https://user-images.githubusercontent.com/5129994/210851352-a4cd196b-8d24-45ba-8992-ea8a9ca094cd.png" width="200" />

**Comment by tirumaraiselvan** [comment] 2023-01-06 06:47
The behaviour of Cache-Control/Expires header is for reauthenticating websocket connections because they are long-running (this is documented here: https://hasura.io/docs/latest/auth/authentication/webhook/#refreshing-websocket-connections). 

Caching of auth responses is a feature request here: https://github.com/hasura/graphql-engine/issues/5743 and it is on the roadmap.

I will close this issue as a dupe of #5743

**Closed by tirumaraiselvan** 2023-01-06 06:47 UTC
Labels: k/bug, t/gql-services
