### ISSUE TITLE
creating Scheduled trigger failed, null value in column id violates not null constraint

### ISSUE THREAD

**Issue by ahmedmagdyy** [hasura/graphql-engine#5508] opened 2020-08-02 06:50 UTC
I've upgraded Hasura from v1.2.2 to the latest version 1.3.0, Now I am trying to create cron job but the operation fails every time,
giving this error "null value in column \"id\" violates not-null constraint"
![Screenshot_20200802_083755](https://user-images.githubusercontent.com/26116580/89117233-92236000-d49c-11ea-9035-3fd5f4242365.png)
I found in graphql-engine initialise.sql file that id column in hdb_cron_events set to DEAFULT gen_random_uuid()
I don't know what's wrong since it should give a uuid for the record.

**Comment by ahmedmagdyy** [comment] 2020-08-09 19:19
I've found a workaround for this,
The issue happens only if you update from a version older than 1.3 when I created new repo using Hasura v1.3 didn't face this problem.
The workaround was that I have deleted table hdb_cron_events and hdb_cron_event_invocation_logs and recreated them using SQL queries in graphql-engine initialize.sql file.

**Comment by praveenweb** [comment] 2020-08-10 03:23
Seems like an issue with `get_random_uuid()`. This mostly occurs when the pgcrypto extension is not available. Can be fixed using `CREATE EXTENSION pgcrypto`.

@tirumaraiselvan - The server takes care of this automatically right?

**Comment by tirumaraiselvan** [comment] 2020-08-26 07:29
Can you check if the table actually has a default in postgres:

```
SELECT column_name, column_default
FROM information_schema.columns
WHERE (table_schema, table_name) = ('hdb_catalog', 'hdb_cron_event_invocation_logs')
ORDER BY ordinal_position;
```

Did you happen to drop the `public` schema at some point (maybe in migrations?). See this related comment: https://github.com/hasura/graphql-engine/issues/4009#issuecomment-604976587

**Comment by ahmedmagdyy** [comment] 2020-09-06 14:29
![Screenshot_20200906_161539](https://user-images.githubusercontent.com/26116580/92327744-35e3cb00-f05c-11ea-9bbf-d292faf66ca1.png)
Table already has a default, I think this makes sense because the workaround I mentioned fixed the problem and didn't face it again but before it didn't have a default value and yes I have dropped public schema using these queries
TRUNCATE hdb_catalog.schema_migrations;
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

**Comment by tirumaraiselvan** [comment] 2020-10-24 06:46
> yes I have dropped public schema using these queries

In that case, closing this as dupe of #4009

**Closed by tirumaraiselvan** 2020-10-24 06:46 UTC
