### ISSUE TITLE
parse-field error when applying metadata on remote schemas permissions yaml file

### ISSUE THREAD

**Issue by jgoux** [hasura/graphql-engine#7034] opened 2021-06-10 12:47 UTC
Hello,

We manually manage our remote_schemas.yaml in order to keep the permissions written as SDL for a better git merge experience (related to https://github.com/hasura/graphql-engine/issues/7033).

I tried to use the console UI to change some permissions, Hasura did its work, and added them to our remote_schemas.yaml, formatting all our existing definitions from SDL to a minified json. At this step there is no error, and we can keep modifying the file through the console UI.

Now the next time we boot Hasura's container, it doesn't work and emit this error : 

```bash
time="2021-06-10T12:33:55Z" level=fatal msg="error applying metadata \n{\n  \"path\": \"$.metadata.remote_schemas[0].permissions[0].definition.schema\",\n  \"error\": \"parsing the schema document: \\\"endOfInput\\\"\",\n  \"code\": \"parse-failed\"\n}"
``` 

So it seems like when going from console UI -> remote_schemas.yaml file, Hasura isn't formatting the file correctly.

I made a [gist](https://gist.github.com/jgoux/a7a841e89b55a29a09e32115e316e30e) with : 
- `remote_schemas_before.yaml` : Our original file in SDL, which is parsed just fine when Hasura is applying metadata
- `remote_schemas_after.yaml` : The exact same formatted by Hasura (I just hit the "save" button in the console UI), which is working as long as we don't apply the metadata again. Once the metadata are applied again, Hasura is failing to parse the file.

**Comment by abhi40308** [comment] 2021-06-16 09:38
Hi @jgoux, could you mention the hasura version you are using, and also the exact steps to replicate the error. I am having difficulty replicating the issue. Specifically, in the gist you mentioned, `remote_schemas_after.yaml` file, SDL is having a quoted string, which never occurs for me. I think that is causing the parsing error. We still have to look into the possibility to save a well formatted SDL. 

For me, the `remote_schemas.yaml` contents are as shown in [this](https://gist.github.com/abhi40308/4ec0781859909e150cf2683728fc1a5c) gist.

**Comment by jgoux** [comment] 2021-06-16 12:20
Hello @abhi40308,

We're using the image `hasura/graphql-engine:v2.0.0-beta.1.cli-migrations-v3`.

The steps are as follow : 
- docker-compose up with our original file not formatted by Hasura
- launch `hasura console` UI
- edit anything that trigger a modification of the metadata
- the remote_schemas.yaml file is then updated and formatted by `hasura console` automatically
- at this point there is no error because I assume the metadata changes are reflected in-memory and not reloaded from the updated .yaml files.
- docker-compose down (end of PR / development session)
- docker-compose up with the now hasura's formatted `remote_schemas.yaml` file
- error, the container won't properly start because of the formatting issue

If you want to go deeper I'll be happy to do a screen sharing session, you can ping me on Discord on `0ur0b0r0s#3052`

**Comment by abhi40308** [comment] 2021-06-24 16:40
Hi @jgoux, I tried the following steps:

```
➜  hasura version
INFO hasura cli                                    version=v2.0.0-beta.2
INFO hasura graphql engine                         endpoint="http://localhost:8080/" version=v2.0.0-beta.1
```

1. `docker-compose up` with image `hasura/graphql-engine:v2.0.0-beta.1.cli-migrations-v3`.
2. `hasura init` to create a new project. `hasura console` to start cli. Then I added a remote schema using console UI `https://1fyli.sse.codesandbox.io/` which shows up in my `remote_schemas.yaml` and it looks like [this](https://gist.github.com/abhi40308/ecc7937551b8b6432cef9b1039264e3b).
3. Went on to add a new role using console UI.  `remote_schemas.yaml` [contents](https://gist.github.com/abhi40308/624424b40fe3fb509cfdcf945ac0cbfa). All well and good for now and if I do `docker-compose down` and remove the volumes etc, and then start docker again and try to apply `hasura metadata apply`, it works fine, and I can see the permissions in console UI.
3. Now I formatted my `remote_schemas.yaml` file like in [this](https://gist.github.com/abhi40308/0a7668e7e36868f47653cc37821163ff) gist. 
4. I can't apply metadata using `hasura metadata apply` [[docs](https://hasura.io/docs/latest/graphql/core/hasura-cli/hasura_metadata_apply.html)] now, it will give error as the `remote_schemas.yaml` has permission formatted in a way not expected by cli. The error in this case would be 
```{
  "path": "$.metadata.remote_schemas[0].permissions[0].definition.schema",
  "error": "parsing the schema document: \"endOfInput\"",
  "code": "parse-failed"
}
```
5. If I try to create another role after step 4, hasura cli will reformat the `remote_schemas.yaml` in [this](https://github.com/abhi40308/hasura-cli-rsp-repro/blob/master/hasura/metadata/remote_schemas.yaml) format. Now I can easily do `docker-compose down` again, prune the volumes etc, start docker again and run `hasura metadata apply` and it works fine for me, and i can see the remote schema and its permissions in UI.

Please let me know if I missed something. I have created a repro [here](https://github.com/abhi40308/hasura-cli-rsp-repro). I I could not arrive at the `remote_schemas_after.yaml` file, which seems to contain quoted string for permission.

**Comment by jgoux** [comment] 2021-06-24 17:46
I just upgraded to `v2.0.1` (both the docker image and the hasura-cli), this is still happening.

I removed all my remote permissions and used 100% the UI. If I allow only simple queries it's ok, but as soon as I include a mutation, the formatting breaks.

I think I'm starting to pinpoint the issue, it seems that some GraphQL structures aren't well formatted by the UI when written to the remote_schemas.yaml file, like my `remote_schemas_after.yaml` gist, you can notice that there are numerous `\n` characters, but they should be written as newline in the yaml with the `|-` operator, and that's not the case.
Because of this, there are arbitrary line breaks in the schema so maybe on one particular line there is a sequence of characters that isn't valid.

Could you try adding those following structures in your schema : 
- mutation
- union
- custom scalar
- input type

Again, if you want to debug this quickly I'll be happy to do a screen sharing session anytime.

**Comment by goodmase** [comment] 2021-06-25 18:19
Same issue. Using `hasura/graphql-engine:v2.0.0-alpha.9.cli-migrations-v2` my remote schemas worked. `hasura/graphql-engine:v2.0.1.cli-migrations-v3` or `hasura/graphql-engine:v2.0.1.cli-migrations-v2` the remote schemas failed. Using non minified with `|-` resolved my issue but prevents me from making updates in the UI.

**Comment by abhi40308** [comment] 2021-06-29 12:14
@jgoux I can reproduce this, thanks! Will look into it.

**Comment by abhi40308** [comment] 2021-06-30 09:43
Looks like the trailing space at the end of the permissions string is causing an issue with `JSON` to `YAML` conversion. @codingkarthik

**Comment by abhi40308** [comment] 2021-07-02 12:49
Looks like its occuring due to trailing whitespaces but there’s a catch. Any whitespace before newline will cause issue with JSON to YAML conversion, which in turn will cause this error. So for example:
```union launchRocket  = Launch | Rocket\nscalar jsonb\n``` this works.
```union launchRocket  = Launch | Rocket\nscalar jsonb (whitespace at end)``` this wont work
```scalar jsonb \nunion launchRocket  = Launch | Rocket\n``` this won’t work either due to `scalar jsonb` having whitespace.
We have to make sure any field doesn’t get a whitespace at end.

**Comment by codingkarthik** [comment] 2021-07-26 08:35
fixed via 6d95271d5746709ab10c1020f0147a6404ceef7c

**Closed by codingkarthik** 2021-07-26 08:35 UTC
Labels: c/remote-schemas, c/server

**Comment by ericxiao251** [comment] 2021-07-30 17:53
Hi, where can I find the PR and files changed that fixed this issue? I can't seem to find it in the linked release.

**Comment by jgoux** [comment] 2021-08-09 15:06
@abhi40308 thanks for fixing it, I just tested on v2.0.5 and it works!

There is a last remaining issue. The formatting within `remote_schemas.yaml` isn't predictable.

If I go on Hasura Console and just click on the "save" remote permissions for my role "user", it puts the "user" role first in the remote_schemas.yaml.
Now if I go on my "public" role and save its permissions as well, it now put the "public" role first in the file.

This is pretty annoying for git diffing and easily spotting the changes.

I think the array of roles in this file should always be the same (sorted by name?).
