### ISSUE TITLE
console: Cannot read property 'foldable' of undefined

### ISSUE THREAD

**Issue by blinkn** [hasura/graphql-engine#4907] opened 2020-05-28 01:32 UTC
Hi, I got the following error:

Error Screenshot
https://imgur.com/3thgMw7

```
TypeError: Cannot read property 'foldable' of undefined
    at https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/main.js.gz:1:3916472
    at Array.map (<anonymous>)
    at RTFoldableTable.applyFoldableForColumns (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/main.js.gz:1:3916400)
    at RTFoldableTable.n (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/main.js.gz:1:3917655)
    at Wa (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/vendor.js.gz:1:4352001)
    at Ua (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/vendor.js.gz:1:4351794)
    at Ya (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/vendor.js.gz:1:4355233)
    at fs (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/vendor.js.gz:1:4377676)
    at ds (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/vendor.js.gz:1:4378066)
    at Js (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/vendor.js.gz:1:4385244)
```

Have no idea why it happened, I'll try to explain what i did to get this:
Everything was done in Hasura Console:

1. Deleted all references and data from a particular table.
2. Deleted the table.
3. Recreated table with same name, different column names.
4. Added foreign columns reference before confirming.
5. Confirm table create.

After this, I tried to click in the left side list of tables on the new created table and I got this error, now I am unable to modify, see or do anything with this table using Hasura Console.

I'll try to delete this table using SQL and then try to create again.
Cheers

**Comment by blinkn** [comment] 2020-05-28 01:33
I just created the same table again, same references and columns, no problems. So, I have no idea what happened, lucky me it was on development stage of the project.

**Comment by antoinemaz** [comment] 2020-05-28 10:13
i have this problem too.

Steps :

- Create a view in a schema
- Track this views, and add permissions
- Delete this view in SQL
- Reload metadatas and drop all inconsistents objects
- Create a new view (with the same name) for adding three new columns
- Track this new view
- And this error page appears : "TypeError: Cannot read property 'foldable' of undefined"

**Comment by antoinemaz** [comment] 2020-05-28 12:34
Found !

i have created my view with postgres, whereas i use this view with another SQL user !

so it was a permission issue

so add grand usage on the schema 

```
  grant usage on schema <MY_SCHEMA> to <MY_HASURA_USER>;
grant
select
  on all tables in schema <MY_SCHEMA> to <MY_HASURA_USER>;
````

**Comment by beerose** [comment] 2020-05-28 12:54
Thanks @blinkn and @antoinemaz for reporting and providing reproduction steps.

@antoinemaz thanks for the update. We'll take care of handling this case so it doesn't trigger a runtime error.

**Comment by Vbubblery** [comment] 2020-05-30 20:47
For me, it's more wired. It works well on MacOS, but on my windows, I get the same error:
```
TypeError: Cannot read property 'foldable' of undefined
    at https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/main.js.gz:1:3941899
    at Array.map (<anonymous>)
    at RTFoldableTable.applyFoldableForColumns (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/main.js.gz:1:3941827)
    at RTFoldableTable.n (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/main.js.gz:1:3943082)
    at Wa (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/vendor.js.gz:1:4352010)
    at Ua (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/vendor.js.gz:1:4351803)
    at Ya (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/vendor.js.gz:1:4355242)
    at fs (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/vendor.js.gz:1:4377685)
    at ds (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/vendor.js.gz:1:4378075)
    at Js (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/vendor.js.gz:1:4385253)
```

**Comment by farzd** [comment] 2020-06-07 11:57
im still getting this issue, it happens when i try access one table. Tried dropping all rows and removing relationships with it but no avail
```
TypeError: Cannot read property 'foldable' of undefined
    at https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/main.js.gz:1:3941899
    at Array.map (<anonymous>)
    at RTFoldableTable.applyFoldableForColumns (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/main.js.gz:1:3941827)
    at RTFoldableTable.n (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/main.js.gz:1:3943082)
    at Wa (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/vendor.js.gz:1:4352010)
    at Ua (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/vendor.js.gz:1:4351803)
    at Ya (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/vendor.js.gz:1:4355242)
    at fs (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/vendor.js.gz:1:4377685)
    at ds (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/vendor.js.gz:1:4378075)
    at Js (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/vendor.js.gz:1:4385253)
```

**Comment by Vbubblery** [comment] 2020-06-08 13:33
> im still getting this issue, it happens when i try access one table. Tried dropping all rows and removing relationships with it but no avail
> 
> ```
> TypeError: Cannot read property 'foldable' of undefined
>     at https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/main.js.gz:1:3941899
>     at Array.map (<anonymous>)
>     at RTFoldableTable.applyFoldableForColumns (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/main.js.gz:1:3941827)
>     at RTFoldableTable.n (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/main.js.gz:1:3943082)
>     at Wa (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/vendor.js.gz:1:4352010)
>     at Ua (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/vendor.js.gz:1:4351803)
>     at Ya (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/vendor.js.gz:1:4355242)
>     at fs (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/vendor.js.gz:1:4377685)
>     at ds (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/vendor.js.gz:1:4378075)
>     at Js (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.2/vendor.js.gz:1:4385253)
> ```

I think just because the PR has not been merged. 🙁

**Closed** 2020-06-08 14:40 UTC
Labels: c/console, k/bug, support/needs-more-info
