### ISSUE TITLE
event trigger is invoked during server startup and logs an awkward msg

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#1873] opened 2019-03-26 12:11 UTC
![image](https://user-images.githubusercontent.com/8663570/54996090-5fd33a00-4fee-11e9-949c-c38dac02b68a.png)

**Comment by manasag** [comment] 2023-12-28 17:31
This issue has not attracted significant attention for a long period of time, hence closing this.
Please feel free to reopen if the issue is still relevant for you.

**Closed by manasag** 2023-12-28 17:31 UTC
Labels: c/server, a/eventing/data-triggers
