### ISSUE TITLE
Hasura Console Login Failure - MySQL Preview

### ISSUE THREAD

**Issue by ReghuShanker** [hasura/graphql-engine#5828] opened 2020-09-23 11:53 UTC
I am trying to login to the Hasura MySQL preview console. When I enter the admin password, it logins and I see the console for a second. The console then returns back to the login screen. I checked my docker-compose file and verified I am using the correct admin password. The server is in the Digital Ocean.

The following is the screencast of the issue: https://nimb.ws/8aOfkK

My docker-compose is the following :
[docker-compose.txt](https://github.com/hasura/graphql-engine/files/5267909/docker-compose.txt)

When I check the network requests I at first login requests return success but later another request is denied permission.
Screenshots of the failed requests:

Request URL: http://<ipaddress>/v1/query
Request Method: POST
Status Code: 400 Bad Request
Remote Address: <ipaddress>:80
Referrer Policy: strict-origin-when-cross-origin
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
Access-Control-Allow-Origin: http://ipaddress
Content-Length: 81
Content-Type: application/json; charset=utf-8
Date: Wed, 23 Sep 2020 11:30:10 GMT
Server: Caddy
Server: Warp/3.3.10
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9,ml;q=0.8
Connection: keep-alive
Content-Length: 87
Content-Type: text/plain;charset=UTF-8
Cookie: pma_lang=en; pmaUser-1=%7B%22iv%22%3A%22TpaLPvi6tc9paKbBZc7IAw%3D%3D%22%2C%22mac%22%3A%2260d80d4c1f5f78b45f0df115cbb9c63c48160334%22%2C%22payload%22%3A%22h3%5C%2FnYHmw0yF5mZGQbZm4Bw%3D%3D%22%7D; phpMyAdmin=9686c6a5f6211f4ab59d17a88a6335fb
DNT: 1
Host:ipaddress
Origin: http://ipaddress
Referer: http://ipaddress/console
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
{type: "run_sql", args: {sql: "SELECT version();", cascade: false, read_only: false}}
args: {sql: "SELECT version();", cascade: false, read_only: false}
type: "run_sql"

The Hasura log from docker container for the above request is the following:

graphql-engine_1 | {"type":"http-log","timestamp":"2020-09-23T11:27:54.577+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"anonymous"},"error":{"path":"$.args","error":"restricted access : admin only","code":"access-denied"},"request_id":"aa58017e-b26e-4b64-af5c-39db9610f0d4","response_size":81,"query":{"args":{"cascade":false,"check_metadata_consistency":null,"sql":"SELECT version();","read_only":false},"version":1,"type":"run_sql"}},"http_info":{"status":400,"http_version":"HTTP/1.1","url":"/v1/query","ip":"103.134.135.89","method":"POST","content_encoding":null}}}

The following is the log for successful requests:

graphql-engine_1 | {"type":"http-log","timestamp":"2020-09-23T11:27:54.577+0000","level":"info","detail":{"operation":{"query_execution_time":0.183807047,"user_vars":{"x-hasura-role":"admin"},"request_id":"eb3b6a6b-c262-4f99-aa58-f5825d0186a9","response_size":1918,"request_read_time":2.531373e-3},"http_info":{"status":200,"http_version":"HTTP/1.1","url":"/v1/query","ip":"103.134.135.89","method":"POST","content_encoding":"gzip"}}}

Seems like x-hasura-role has changed from admin to anonymous not sure if this the reason or not.

If anyone can take a look at it, then it would be really helpful.

**Comment by GavinRay97** [comment] 2020-09-25 17:48
Please create a repository that can be cloned and run with `docker-compose up` for reproduction :pray: 

I am not able to recreate this -- using the gist instructions here does it still fail for you?
https://gist.github.com/GavinRay97/28c94f9f23d318542fb310bbffff8d04

**Comment by ReghuShanker** [comment] 2020-10-06 20:35
@GavinRay97 Sorry for the delayed reply. 

1. I am able to access console when I disable the password. The issue occurs only when there is a password.
2. If you take a look at the docker compose file I have attached in the original post, I am only using only publicaly available docker images of hasura, mysql,pgsql and doesnt have any docker images of  any of my projects in the compose file. So you should be able to just docker-compose up and run it for reproduction. 
3. My console is working fine, the issue is only I set password for the console, it prevents me from accessing the console even when the password is correct.

**Comment by beerose** [comment] 2020-10-12 15:35
Hi @ReghuShanker!

The issue occurs because we're not handling MySQL databases in the console yet. The current version of the console (and the one in the preview) works only with a single Postgres database. The MySQL preview has only server changes. 

You can access the console (`Graphiql` tab specifically) without a password because this page is kind of independent of the rest of the application. We're not doing any database queries, nor perform any database related logic from this page.

However, if there's a password set, we're making an API call to fetch data from the metadata table as a part of login verification. This query fails and as a result, there's a login failure.

**Comment by toomanyjoes** [comment] 2020-10-21 06:07
+1 
The [docs](https://hasura.io/docs/1.0/graphql/core/guides/mysql-preview.html#step-4-try-out-the-graphql-api) say that a schema can still be managed externally. But that's all it says. Are there any resource for how to manage schema/permissions outside of the console?

**Comment by rsd1122** [comment] 2023-03-07 20:19
Closing this one out as we recently launched our new MySQL alpha integration 
https://hasura.io/docs/latest/databases/mysql/index/

It has support for queries, table relationships and permissions. Support for mutations is coming soon.

Please reach out to me if you would like to be a part of the early-access slack channel where we post the latest builds and updates.

**Closed by rsd1122** 2023-03-07 20:19 UTC
