### ISSUE TITLE
VSCode Apollo GraphQL extension and 404 Error

### ISSUE THREAD

**Issue by ozum** [hasura/graphql-engine#3771] opened 2020-01-24 11:03 UTC
Hi,

I'm trying to use VSCode Apollo GraphQL (1.13.0) extension following this guide: https://docs.hasura.io/1.0/graphql/manual/guides/code-editor-integrations/visual-studio-code.html

I'm getting 404 error:

My config:
```
module.exports = {
  client: {
    service: {
      name: "project",
      url: "http://localhost:8080/v1/graphql",
      headers: {
        "x-hasura-admin-secret": "password"
      }
    }
  }
};
```

Response in Docker log:
```
{"type":"http-log","timestamp":"2020-01-24T10:55:34.280+0000","level":"error","detail":{"operation":{"error":{"path":"$","error":"resource does not exist","code":"not-found"},"request_id":"125a08ca-601b-4909-b0a4-d470917ad34e","response_size":65,"raw_query":"{\"operationName\":\"IntrospectionQuery\",\"variables\":{},\"query\":\"query IntrospectionQuery {\\n  __schema {\\n    queryType {\\n      name\\n    }\\n    mutationType {\\n      name\\n    }\\n    subscriptionType {\\n      name\\n    }\\n    types {\\n      ...FullType\\n    }\\n    directives {\\n      name\\n      description\\n      locations\\n      args {\\n        ...InputValue\\n      }\\n    }\\n  }\\n}\\n\\nfragment FullType on __Type {\\n  kind\\n  name\\n  description\\n  fields(includeDeprecated: true) {\\n    name\\n    description\\n    args {\\n      ...InputValue\\n    }\\n    type {\\n      ...TypeRef\\n    }\\n    isDeprecated\\n    deprecationReason\\n  }\\n  inputFields {\\n    ...InputValue\\n  }\\n  interfaces {\\n    ...TypeRef\\n  }\\n  enumValues(includeDeprecated: true) {\\n    name\\n    description\\n    isDeprecated\\n    deprecationReason\\n  }\\n  possibleTypes {\\n    ...TypeRef\\n  }\\n}\\n\\nfragment InputValue on __InputValue {\\n  name\\n  description\\n  type {\\n    ...TypeRef\\n  }\\n  defaultValue\\n}\\n\\nfragment TypeRef on __Type {\\n  kind\\n  name\\n  ofType {\\n    kind\\n    name\\n    ofType {\\n      kind\\n      name\\n      ofType {\\n        kind\\n        name\\n        ofType {\\n          kind\\n          name\\n          ofType {\\n            kind\\n            name\\n            ofType {\\n              kind\\n              name\\n              ofType {\\n                kind\\n                name\\n              }\\n            }\\n          }\\n        }\\n      }\\n    }\\n  }\\n}\\n\"}"},"http_info":{"status":404,"http_version":"HTTP/1.1","url":"/v1/v1/graphql","ip":"172.17.0.1","method":"POST","content_encoding":null}}}
```

**Comment by ecthiender** [comment] 2020-01-27 08:07
@ozum from the above pasted Docker logs, I can see `"url":"/v1/v1/graphql"`. So seems like that is the issue? Not sure how though (because your config looks alright to me).

**Comment by ozum** [comment] 2020-01-27 09:20
@ecthiender, I saw `"url":"/v1/v1/graphql"` somewhere during investigation too, even tried with `url: "http://localhost:8080/graphql"`, `url: "http://localhost:8080"`. I'm pretty sure config is correct, because other tools work as expected.

BTW, I followed this [guide from Hasura](https://docs.hasura.io/1.0/graphql/manual/guides/code-editor-integrations/visual-studio-code.html).

**Comment by ecthiender** [comment] 2020-01-27 11:10
@praveenweb any idea about this?

**Comment by beerose** [comment] 2020-01-28 12:00
Not sure if this will help, but I was able to reproduce tis bug doing the following:

1. I provided proper config. VSCode Apollo extension was working fine.
2. I change url to invalid one. Server returned the same error as in the issue.
3. I changed url back to valid one, but extension was still broken, server kept returning an error.

Then I reloaded VSCode and it was working fine again.

**Comment by praveenweb** [comment] 2020-07-15 11:57
Tested on v1.16.0 too. This seems to occur when the initial apollo.config.js has a wrong URL configured and the VSCode extension seems to be broken. It only recovers and starts working after restarting VSCode. 
This is more of an issue on the extension side and hence closing this one.

**Closed by praveenweb** 2020-07-15 11:57 UTC
Labels: c/community, k/question
