### ISSUE TITLE
[Feature request] Check Table Constraint management

### ISSUE THREAD

**Issue by revskill10** [hasura/graphql-engine#2076] opened 2019-04-26 04:21 UTC
This feature will allow user to add boolean check constraint to table when inserting, updating, using postgresql check constraint [here](https://www.postgresql.org/docs/9.4/ddl-constraints.html)

## Example and use case

You can follow this [page](https://www.w3resource.com/PostgreSQL/check.php) for usage about syntax.

## Console change

There should be a `Validation` tab for user to add many constraints to the table.
Information needed:

- Constraint name
- Constraint rule
- Error message

## Alternative solution:

You can use the `SQL` tab to add constraints. But they couldn't be managed at console.

**Comment by tirumaraiselvan** [comment] 2019-04-26 04:52
Possible dupe of https://github.com/hasura/graphql-engine/issues/1700

**Comment by revskill10** [comment] 2019-04-26 16:51
@tirumaraiselvan I'm not sure about dupe. #1700 is about field-level validation. This one is at table level. But i don't know what's the difference between the two.

**Comment by tirumaraiselvan** [comment] 2019-05-09 13:15
Let's track this both at #1700

**Closed by tirumaraiselvan** 2019-05-09 13:15 UTC
Labels: c/console, k/enhancement
