### ISSUE TITLE
Error when clicking on track table

### ISSUE THREAD

**Issue by psrcek** [hasura/graphql-engine#6425] opened 2021-01-06 08:23 UTC
![image](https://user-images.githubusercontent.com/13370323/103746092-d218e100-5000-11eb-8b3d-a2b8f3e604a2.png)

```
TypeError: Cannot read property 'index' of undefined
    at https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.3/main.js.gz:1:974375
    at Array.map (<anonymous>)
    at https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.3/main.js.gz:1:974266
    at Array.map (<anonymous>)
    at n (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.3/main.js.gz:1:973960)
    at n (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.3/main.js.gz:1:4139339)
    at fo (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.3/vendor.js.gz:1:4845959)
    at Xl (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.3/vendor.js.gz:1:4892698)
    at jl (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.3/vendor.js.gz:1:4885355)
    at zl (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v1.3/vendor.js.gz:1:4885280)
```

It shows an error page, but the table gets tracked anyway.

**Comment by beerose** [comment] 2021-01-11 14:52
Hi @psrcek! We were not able to reproduce this error. Is this a recurring problem? Could you provide more info — e.g. definition of the table you wanted to track?

**Comment by psrcek** [comment] 2021-01-18 16:46
I cannot reproduce it myself either, even with the same table definition. I just know that it did happen, therefore I reported it. There's an unhandled exception there that should:

a: Be displayed as an error e.g. "hasura was unable to track that table due to ___", or
b: Be caught and ignored if it's not one.

**Comment by beerose** [comment] 2021-01-22 11:16
I'm closing the issue as we can't reproduce it and haven't had this error reported before.

Please reopen if you find a repro or if it happens again.

**Closed by beerose** 2021-01-22 11:16 UTC
Labels: c/console, k/bug
