### ISSUE TITLE
A metadata error during migrate apply can cause inconsistent migration state

### ISSUE THREAD

**Issue by kevboh** [hasura/graphql-engine#2890] opened 2019-09-16 19:41 UTC
For sql+yaml migrations, if the sql step succeeds but the yaml step fails, hasura seems to think your migration has been applied even though your metadata was not.

Specifically, I was able to reliably get into this state by

1. running `hasura migrate create some-migration`
2. adding a valid sql file to that migration
3. putting valid-but-erroring yaml in that migration. In my case this was a create_array_relationship on a table that didn't exist:

```
- type: create_array_relationship
  args:
    comment: Demo of issue
    name: problematic
    table:
      schema: idontexist
      name: idontexist
    using:
# more here
```

It's not clear to me if the issue is that my table descriptor is bad, or if any missing data in create_array_relationship will cause the issue.

After running `hasura migrate apply`, you'll get a fatal error:

```
FATA[0000] apply failed: [not-exists] table "idontexist.idontexist" does not exist ($.args[2].args)
```

but your migration will appear applied:

```
> hasura migrate apply
Applying migrations...◐ INFO nothing to apply
INFO migrations applied
```

**Comment by BenoitRanque** [comment] 2019-09-16 19:53
Just to add to what @kevboh said: I've found failure in a yaml migration file with multiple steps wil usually result in an inconsistent state.

The following is moslty guesswork from my experience: It seems that during migrations, if there is an error in a yaml migration file, there is no automatic rollback. This means that if my migration file fails on step 2, and I fix the error, it will try to execute step 1 again and will now fail there.

**Comment by shahidhk** [comment] 2019-09-17 04:33
@kevboh I am unable to reproduce this issue. Will you be able to share a migrations directory and the Hasura version with which I can repro the issue?

**Comment by kevboh** [comment] 2019-09-17 13:28
@shahidhk here you go: https://github.com/kevboh/hasura-repro-2890

**Comment by shahidhk** [comment] 2019-09-19 06:54
Thanks @kevboh, will check it out and get back.

**Comment by shahidhk** [comment] 2019-09-19 10:13
@kevboh It looks like the SQL contains `begin` and `commit`. All migrations are already run in a transaction and adding begin and commit again in a migration file aborts the transaction. This is what is getting you into this inconsistent state. 

Let me know if removing begin and commit fixes your issue.

**Comment by BenoitRanque** [comment] 2019-09-20 14:06
> 
> 
> @kevboh It looks like the SQL contains `begin` and `commit`. All migrations are already run in a transaction and adding begin and commit again in a migration file aborts the transaction. This is what is getting you into this inconsistent state.
> 
> Let me know if removing begin and commit fixes your issue.

That must be it. All my SQL migrations contain begin and commit. Will try to experiment with this today

**Comment by marionschleifer** [comment] 2019-10-01 08:38
@kevboh @BenoitRanque I'm closing this issue. If you have any more question, feel free to re-open 🙂

**Closed by marionschleifer** 2019-10-01 08:38 UTC
Labels: c/cli, k/question
