### ISSUE TITLE
Case insensitive search on console

### ISSUE THREAD

**Issue by Luifr** [hasura/graphql-engine#6581] opened 2021-02-22 13:04 UTC
Current search on hasura console (web page) works as a %{search}%, it would be so much better if it was case insensitive (when searching for tables or actions)

**Comment by beerose** [comment] 2021-02-22 13:08
Closing as a duplicate of https://github.com/hasura/graphql-engine/issues/4321.
We have a PR in place that needs to be reviewed and merged.

**Closed by beerose** 2021-02-22 13:08 UTC
Labels: c/console, duplicate
