### ISSUE TITLE
when permissions are missing for column: return null values instead of dropping the column

### ISSUE THREAD

**Issue by barbalex** [hasura/graphql-engine#6541] opened 2021-02-11 18:48 UTC
In our app there are different roles. For the first time now I am encountering the situation that one role needs to not access the data of a few columns in a table.

So I removed the permission for the column `lokalname` in the console to test this.

But then every query that tries to access the column returns this error:
```
{
  "errors": [
    {
      "extensions": {
        "path": "$.selectionSet.herkunft.selectionSet.lokalname",
        "code": "validation-failed"
      },
      "message": "field \"lokalname\" not found in type: 'herkunft'"
    }
  ]
}
```

This is hard to solve. We use subscriptions. And store the data locally, as this app is offline capable. 
The thing that breaks first are the subscriptions. But it is also pretty hard to solve the case of data structure changing in the local store, depending on the role the user has.

This is why the behavior we would like to see is: The api returns the exact same data structure, no matter what columns the user is allowed to access. But columns that the user is not allowed to access contain only null values.

Is this achievable?

**Comment by barbalex** [comment] 2021-02-11 19:51
I now saw this issue https://github.com/hasura/graphql-engine/issues/6279 where it is proposed to use skip to not query the columns that a user may not access. Though this only works beginning in 1.3.4 which is still in beta.

This would force us to query the user dataset in order to know the user's role _before_ initializing the subscriptions. And implementing a lot of client side logic that mirrors the permission set on the database. Though this may be possible (and I am afraid we will have to do this) it would be so much cleaner and simpler if the api returned null values instead.

If it were Christmas soon and I was allowed to make a wish I would wish for an option that makes hasura pass null values on columns a user is not allowed to access, instead of dropping the column.

**Comment by xiaoyu-tamu** [comment] 2021-02-11 23:48
+1 want this feature, it could save a lot of boilerplate code

**Comment by tirumaraiselvan** [comment] 2021-03-01 11:00
This will be possible with our inherited roles feature. You can simply create a dummy role which gives access to all columns but no rows (by setting an always false condition). Then you can add this dummy role to your actual role to create a new inherited role (say, `role_with_all_cols`).

Preview here: https://github.com/hasura/graphql-engine/pull/6396

**Comment by xiaoyu-tamu** [comment] 2021-03-01 14:34
@tirumaraiselvan  will inherit role release in v2

**Comment by tirumaraiselvan** [comment] 2021-03-10 14:02
Inherited roles is now released in `v2.0.0-alpha.4`  and you can now solve this problem via the solution as described in the above comment: https://github.com/hasura/graphql-engine/issues/6541#issuecomment-787859378

**Closed by tirumaraiselvan** 2021-03-10 14:02 UTC

**Comment by switz** [comment] 2022-01-08 23:41
Would also like to see an example.

I have an unauthorized user that I would like to return null for fields it doesn't have access to, rather than failing the query entirely.

**Comment by mediocrename** [comment] 2022-04-21 10:41
@tirumaraiselvan Your proposed solution doesn't work, I'm afraid. 

We set up a "dummy" role with a row level check that always returns false (`{ id: { _eq: null } }`) and access to all columns: `id, name, email`

Then we set up a user role with access to all rows but only to a subset of columns: `id, name`

Now after setting up the user role to inherit permissions from the dummy role, validation fails when querying the `email` field with the user role in x-hasura-role.

Running v2.5.0 here.

**Comment by tirumaraiselvan** [comment] 2022-04-21 12:07
@mediocrename Can you pls share the metadata of the table, if possible?

**Comment by mediocrename** [comment] 2022-04-21 16:58
@tirumaraiselvan thanks for looking into this!

here's the relevant part of the `tables.yaml`:

```yaml
- table:
    schema: public
    name: users
  object_relationships:
  # ...
  computed_fields:
  - name: is_present
    definition:
      function:
        schema: public
        name: get_status_for_user
    comment: ""
  insert_permissions:
  - role: dummy
    permission:
      check:
        id:
          _is_null: true
      columns: '*'
  select_permissions:
  - role: dummy
    permission:
      columns:
      - email
      - first_name
      - last_name
      - created_at
      - updated_at
      - id
      computed_fields:
      - is_present
      filter:
        id:
          _is_null: true
      allow_aggregations: true
  - role: user
    permission:
      columns:
      - first_name
      - last_name
      - id
      filter: {}
  # ...
```

**Comment by tirumaraiselvan** [comment] 2022-05-02 06:24
@mediocrename 

I think the issue is that you need to use the inherited role in `x-hasura-role`. As per your previous comment, you were using the `user` role:

> Then we set up a user role with access to all rows but only to a subset of columns: id, name
>
> Now after setting up the user role to inherit permissions from the dummy role, validation fails when querying the email field with the user role in x-hasura-role.

I could accomplish your use-case. As an example,  I set up a table `user` with columns (`id`, `name`, `email`).

I setup a role `user` with permission to all rows but columns `id` and `name` only.
I setup a role `public` with permission to no rows but all columns.
I setup an inherited role `inheritedrole` which combines roles `user` and `public`. I can query with this role and get `null` for email.

Here is the snippet of metadata:


```
        "tables": [
          {
            "table": {
              "schema": "public",
              "name": "user"
            },
            "select_permissions": [
              {
                "role": "public",
                "permission": {
                  "columns": [
                    "email",
                    "id",
                    "name"
                  ],
                  "filter": {
                    "id": {
                      "_eq": 0
                    }
                  }
                }
              },
              {
                "role": "user",
                "permission": {
                  "columns": [
                    "id",
                    "name"
                  ],
                  "filter": {}
                }
              }
            ]
          }
        ],
        .
        .
        .
    "inherited_roles": [
      {
        "role_name": "inheritedrole",
        "role_set": [
          "user",
          "public"
        ]
      }
    ]
```

**Comment by Tomas1337** [comment] 2022-07-05 21:32
@tirumaraiselvan in your example above
How would one setup the configuration if I wanted `user` to access all the fields (`id`, `name`, `email`)
but have `guest` only access the columns `name` and `id` while returning NULL for `email`?

**Comment by barbalex** [comment] 2023-02-09 16:46
@tirumaraiselvan 
I could theoretically solve my issue by creating a new role that combines the role a user has now with a new one that gives access to all columns.

But I can't give all the users this new role. They have a fixed one.
It should work with the role they are given today.

(How) Can this be solved?

**Comment by barbalex** [comment] 2023-05-10 17:50
@tirumaraiselvan

I would be very thankfull if you could tell me if my above question from February this is possible or not:

> I need to be able to add inherited roles to an existing role

**Comment by barbalex** [comment] 2023-05-11 15:34
This is actually trivial to add any time in something like postgraphile as it uses postgresql's own policies: https://www.graphile.org/postgraphile/security/#how-it-works. 

@tirumaraiselvan: Is it possible to use policies with hasura? 
(I'm sure it wasn't a while ago but haven't followed the development closely)

**Comment by mrbarletta** [comment] 2023-05-19 20:15
Been using this for more than a year. 

It does work BUT, IS  **VERY SLOW**

As the DB fills, permission queries are now the #1 reason for slow performance, and the permission for this null columns is the cause.

> > You can simply create a dummy role which gives access to all columns **but no rows (by setting an always false condition)**
> 
> How would I have to set a false condition? Would I have to set something like `id = 'blah'`?

Yes you can.
