### ISSUE TITLE
Cannot properly set HASURA_GRAPHQL_ADMIN_SECRET variable

### ISSUE THREAD

**Issue by gitxav** [hasura/graphql-engine#2715] opened 2019-08-11 20:35 UTC
Hi all:

Something seems to get broken in my Hasura setup after trying to add HASURA_GRAPHQL_ADMIN_SECRET variable to project. This was not happening before.
The env variable not only isn't properly reflected in the headers section of the Graphiql API console but also the graphql scheme itself simply vanished.  Everything else seems to work fine.

![Screenshot from 2019-08-11 14-48-36](https://user-images.githubusercontent.com/11687381/62839230-d5157380-bc4c-11e9-833b-6f1e71d63dae.png)

![Screenshot from 2019-08-11 14-39-31](https://user-images.githubusercontent.com/11687381/62839232-e8c0da00-bc4c-11e9-9de8-44cc737c1ca5.png)

In Logs I have:

2019-08-11T19:38:52.667999+00:00 app[web.1]: {"timestamp":"2019-08-11T19:38:51.815+0000","level":"info","type":"http-log","detail":{"status":200,"query_hash":"01640c6dd131826cff44308111ed40d7fbd1cbed","http_version":"HTTP/1.1","query_execution_time":null,"request_id":"221e28fc-0ad8-4ad5-9dfe-7f5754f4d9c1","url":"/v1/graphql","ip":"201.141.37.66","response_size":111,"user":null,"method":"POST","detail":{"error":{"path":"$","error":"x-hasura-admin-secret/x-hasura-access-key required, but not found","code":"access-denied"},"request":"{\"query\":\"\\n    query IntrospectionQuery {\\n      __schema {\\n        queryType { name }\\n        mutationType { name }\\n        subscriptionType { name }\\n        types {\\n          ...FullType\\n        }\\n        directives {\\n          name\\n          description\\n          locations\\n          args {\\n            ...InputValue\\n          }\\n        }\\n      }\\n    }\\n\\n    fragment FullType on __Type {\\n      kind\\n      name\\n      description\\n      fields(includeDeprecated: true) {\\n        name\\n        description\\n        args {\\n          ...InputValue\\n        }\\n        type {\\n          ...TypeRef\\n        }\\n        isDeprecated\\n        deprecationReason\\n      }\\n      inputFields {\\n        ...InputValue\\n      }\\n      interfaces {\\n        ...TypeRef\\n      }\\n      enumValues(includeDeprecated: true) {\\n        name\\n        description\\n        isDeprecated\\n        deprecationReason\\n      }\\n      possibleTypes {\\n        ...TypeRef\\n      }\\n    }\\n\\n    fragment InputValue on __InputValue {\\n      name\\n      description\\n      type { ...TypeRef }\\n      defaultValue\\n    }\\n\\n    fragment TypeRef on __Type {\\n      kind\\n      name\\n      ofType {\\n        kind\\n        name\\n        ofType {\\n          kind\\n          name\\n          ofType {\\n            kind\\n            name\\n            ofType {\\n              kind\\n              name\\n              ofType {\\n                kind\\n                name\\n                ofType {\\n                  kind\\n                  name\\n                  ofType {\\n                    kind\\n                    name\\n                  }\\n                }\\n              }\\n            }\\n          }\\n        }\\n      }\\n    }\\n  \"}"}}}

Please help me to understand what's happening.
Thanks in advance.

**Comment by marionschleifer** [comment] 2019-08-12 06:00
@gitxav the schema disappears because the admin secret was not found. Try adding the admin secret to the request headers on the console. Then it should work. 

Also, have you tried reloading the console? There should be a prompt to enter the admin secret and then it should be added to the request headers automatically.

Let me know if you can resolve it or if you need further assistance 🙂

**Comment by gitxav** [comment] 2019-08-13 16:51
Sorry Marion for delayed response. You are right: entering the admin secret in console restores the schema.

Cheers!

**Comment by marionschleifer** [comment] 2019-08-14 06:11
@gitxav glad the problem is resolved 🙂 closing this issue.

**Closed by marionschleifer** 2019-08-14 06:11 UTC
Labels: k/question
