### ISSUE TITLE
delete table with dependencies console behavior confusing

### ISSUE THREAD

**Issue by AnnieAtHasura** [hasura/graphql-engine#1602] opened 2019-02-14 11:05 UTC
1. make a table a with a primary id
2. make a table that has a foreign key relationship to table a
3. attempt to delete table a
EXPECTED: grayed out button telling me I can't delete (and, ideally, why)
OBSERVED: Delete key simply missing. For new user, no clue that this is it's usual location.

**Comment by rikinsk** [comment] 2019-05-13 15:52
@AnnieAtHasura Couldnt reproduce this. Can you share a screenshot?

**Comment by marionschleifer** [comment] 2019-07-10 07:36
I'm closing this issue 🙂 @AnnieAtHasura please feel free to re-open if you would like to add something :)

**Closed by marionschleifer** 2019-07-10 07:36 UTC
Labels: c/console, needs-more-info
