### ISSUE TITLE
Console opens a new websocket connection for every subscription, all remain open

### ISSUE THREAD

**Issue by jberryman** [hasura/graphql-engine#3879] opened 2020-02-13 17:19 UTC
I think subscriptions should either re-use an existing connection we hold open, or close the connection when "stop" is pressed.

To repro: start subscription, stop subscription (a few times), observe "stop" logs. Close window, observe several "close" logs for each subscription you stopped and started. This is a space leak, but I'm not sure if it's a production concern for folks (probably not related to #3388)

**Comment by beerose** [comment] 2020-05-30 20:32
Closing as a duplicate of https://github.com/hasura/graphql-engine/issues/3918

**Closed by beerose** 2020-05-30 20:32 UTC
Labels: c/console, e/easy, p/medium
