### ISSUE TITLE
Creating custom relationship: TypeError: Cannot read property 'column_mapping' of undefined

### ISSUE THREAD

**Issue by tmaxmax** [hasura/graphql-engine#6674] opened 2021-03-17 19:27 UTC
Whenever I create a custom relationship in Hasura Console, after it's created this error is thrown:

```
TypeError: Cannot read property 'column_mapping' of undefined
    at e (https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.0.0-alpha.2.cloud.2/vendor.js.gz:1:1950918)
    at https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.0.0-alpha.2.cloud.2/vendor.js.gz:1:3029841
    at Array.map (<anonymous>)
    at e (https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.0.0-alpha.2.cloud.2/vendor.js.gz:1:3029503)
    at pi (https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.0.0-alpha.2.cloud.2/vendor.js.gz:1:11090728)
    at Vi (https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.0.0-alpha.2.cloud.2/vendor.js.gz:1:11097684)
    at Xi (https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.0.0-alpha.2.cloud.2/vendor.js.gz:1:11104034)
    at ds (https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.0.0-alpha.2.cloud.2/vendor.js.gz:1:11126561)
    at fs (https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.0.0-alpha.2.cloud.2/vendor.js.gz:1:11126951)
    at Zs (https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.0.0-alpha.2.cloud.2/vendor.js.gz:1:11134129)
```

Not much else to say about it, I'm using a Heroku database.

**Comment by jacobaraujo7** [comment] 2021-04-02 02:40
Same problem here too!

**Comment by khan297** [comment] 2021-04-02 02:40
Maps

**Comment by Seeker14491** [comment] 2021-04-04 06:58
I got basically the same error manually adding an object relationship:

```
TypeError: Cannot read property 'column_mapping' of undefined
    at n (https://graphql-engine-cdn.hasura.io/console/assets/channel/alpha/v2.0/main.js.gz:1:2997092)
    at https://graphql-engine-cdn.hasura.io/console/assets/channel/alpha/v2.0/main.js.gz:1:3991856
    at Array.map (<anonymous>)
    at n (https://graphql-engine-cdn.hasura.io/console/assets/channel/alpha/v2.0/main.js.gz:1:3991492)
    at fo (https://graphql-engine-cdn.hasura.io/console/assets/channel/alpha/v2.0/vendor.js.gz:1:4835803)
    at es (https://graphql-engine-cdn.hasura.io/console/assets/channel/alpha/v2.0/vendor.js.gz:1:4844763)
    at Xl (https://graphql-engine-cdn.hasura.io/console/assets/channel/alpha/v2.0/vendor.js.gz:1:4883466)
    at jl (https://graphql-engine-cdn.hasura.io/console/assets/channel/alpha/v2.0/vendor.js.gz:1:4875199)
    at zl (https://graphql-engine-cdn.hasura.io/console/assets/channel/alpha/v2.0/vendor.js.gz:1:4875124)
    at Ol (https://graphql-engine-cdn.hasura.io/console/assets/channel/alpha/v2.0/vendor.js.gz:1:4871974)
```

The relationship seems to have been made successfully though, despite the error. I'm using Hasura v2.0.0-alpha.6.

**Comment by tmaxmax** [comment] 2021-04-04 07:55
Same behaviour for me. The relationship is created, but after the process there is a very long loading screen and then it fails with that given error.

**Comment by beerose** [comment] 2021-04-28 08:16
Closing as a duplicate of https://github.com/hasura/graphql-engine/issues/6639

**Closed by beerose** 2021-04-28 08:16 UTC
