### ISSUE TITLE
Expose a stored procedure as a mutation

### ISSUE THREAD

**Issue by RodolfoSilva** [hasura/graphql-engine#2805] opened 2019-08-30 13:09 UTC
Given this table:
```sql
CREATE TABLE accounts (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    balance DEC(15,2) NOT NULL,
    PRIMARY KEY(id)
);
```
With somethings
```sql
INSERT INTO accounts(name, balance) VALUES ('Bob', 10000);
INSERT INTO accounts(name, balance) VALUES ('Alice', 10000);
```

I've created a stored procedure:
```sql
CREATE OR REPLACE PROCEDURE transfer(INT, INT, DEC)
LANGUAGE plpgsql
AS $$
BEGIN
    -- subtracting the amount from the sender's account
    UPDATE accounts
    SET balance = balance - $3
    WHERE id = $1;

     -- adding the amount to the receiver's account
    UPDATE accounts
    SET balance = balance + $3
    WHERE id = $2;
COMMIT;
END;
$$;
```
I want expose this procedure as a graphql mutation.

I know is possible made with functions, but I thinks if the SQL view is exposed by Graphql query why not expose procedures as mutation?

Maybe create a pattern to turn possible create and expose a stored procedure.

**Comment by macs91** [comment] 2019-09-20 07:05
Yes please there's ton of use cases where simple CRUD is not enough

**Comment by marionschleifer** [comment] 2020-03-04 10:57
Closing this as a duplicate of https://github.com/hasura/graphql-engine/issues/1514.

**Closed by marionschleifer** 2020-03-04 10:57 UTC
Labels: c/server, k/ideas 💡
