### ISSUE TITLE
FatalError: function hdb_views.<random string>() does not exist

### ISSUE THREAD

**Issue by MarcelloTheArcane** [hasura/graphql-engine#3703] opened 2020-01-14 15:32 UTC
I am trying to delete permissions for the `manager` role, but I get this error. I have tried creating a function with that name, in the hopes that it would delete that, but it still doesn't work.

![image](https://user-images.githubusercontent.com/21159570/72357350-b8d99f00-36e2-11ea-90f7-920521b104da.png)

```json
{
    "statement": "DROP FUNCTION \"hdb_views\".\"30862b57153c01eff2067aa8a479073734c8cb9a13f20f3ca84de2bf\"()",
    "prepared": false,
    "error": {
        "exec_status": "FatalError",
        "hint": null,
        "message": "function hdb_views.30862b57153c01eff2067aa8a479073734c8cb9a13f20f3ca84de2bf() does not exist",
        "status_code": "42883",
        "description": null
    },
    "arguments": []
}
```

*Hasura Version:* v1.1.0-beta.1

**Comment by lexi-lambda** [comment] 2020-01-15 08:12
Duplicate of #3710

**Closed** 2020-01-15 08:13 UTC
Labels: c/server
