### ISSUE TITLE
Console Add Table Failed - 500 Internal Server Error

### ISSUE THREAD

**Issue by jcmoore0** [hasura/graphql-engine#3325] opened 2019-11-09 01:44 UTC
When adding a table, I get 'Creating Failed, Try Again'

v.1.0.0-beta-9

I have tried it with several simple tables like:
name: test
column: id  (auto increment) integer
primary_key: id

Errors: 
```
**Browser:**
Request URL: http://localhost:9693/apis/migrate
Request Method: POST
Status Code: 500 Internal Server Error

Response:
{"code":"internal_error","message":"json: cannot unmarshal array into Go struct field HasuraError.internal of type hasuradb.SQLInternalError"}

**Hasura Server**
No logs with errors
```

Other migrations are working properly (permission, add/remove column)
Restarted local console server and console several times and still troubleshooting.

I would appreciate any insight to resolve.
Best regards,
John

**Comment by rikinsk** [comment] 2019-11-11 12:51
@jcmoore0 this is unexpected. I could not reproduce this behaviour based on the given information. 

Could you please share the some more information to help us debug quicker:
- What's the Postgres version you are using
- Were you able to ever create tables via the console?
- Are you setting up a fresh db instance or are you building on top of an existing db?
- Are you able to create tables directly via SQL using the RawSQL tab in the console (e.g. `CREATE TABLE test (id serial PRIMARY KEY)`). 

cc: @shahidhk @arvi3411301

**Comment by jcmoore0** [comment] 2019-11-11 19:08
@rikinsk  -  Thanks for the quick reply.  
After changing the node on GKE, it is now working.
I changed the server env var to test anonymous access control.
I did not test table creation before applying the change so I don't know when exactly the problem went away.

I recommend closing this as I don't have additional information to troubleshoot further.

1. What Postgres version?:  11
2. Can you create tables via the console?:  Yes, every day.
3. This was an existing Db
4. I did not use raw sql but I would expect this would work.

Additional Info:
1.  Two consoles on different machines had the same issue on Friday when trying to add a table via the console.
2.  The problem is no longer repeatable.

Best regards,
John

**Comment by rikinsk** [comment] 2019-11-12 06:25
Thanks for the extra info. Closing this for now.

**Closed by rikinsk** 2019-11-12 06:25 UTC
Labels: needs-more-info
