### ISSUE TITLE
type info not found for: 'table_obj_rel_insert_input'

### ISSUE THREAD

**Issue by SkinyMonkey** [hasura/graphql-engine#6035] opened 2020-10-18 03:43 UTC
When i activate the backend only option on the insert permission of one of my table, i get a cryptic message on the Graphiql view.

```
Schema introspection query failed
type info not found for: '${name_of_my_table}_obj_rel_insert_input'
```

Can i fix this myself or is it a bug?

Thank you!

**Comment by SkinyMonkey** [comment] 2020-10-18 03:46
The repo i'm working on is public if you want to need more informations :

https://github.com/SkinyMonkey/hasura-fs/tree/develop

**Comment by tirumaraiselvan** [comment] 2020-10-23 08:13
Seems like a dupe of https://github.com/hasura/graphql-engine/issues/5059

This has been fixed in master

**Closed** 2020-10-23 08:13 UTC
