### ISSUE TITLE
Upgrade to v1.0.0-beta.7 causes problems on tables set as enum

### ISSUE THREAD

**Issue by brainplug** [hasura/graphql-engine#3083] opened 2019-10-10 07:56 UTC
Enum tables that comply with the criteria and work perfectly fine in beta.6 cause the beta.7 to fail when starting up. An example message from the logs (schema and table name obfuscated):

{"definition":{"schema":"xxx","name":"yyy"},"reason":"the table \"xxx.yyy\" cannot be used as an enum for the following reasons:\n  • the table’s primary key must not span multiple columns (id, id)\n  • the table must have exactly one primary key and optionally one comment column, not 4 columns (id, id, value, value)\n","type":"table"}

As you can see the server seems to think there are 2 id and 2 value fields but in reality there is only 1 id field and only 1 value field.

This inconsistency in the metadata (we have multiple of these messages) prevents the startup process from continuing. We currently reverted back to beta.6 where everything works just fine.

**Comment by lexi-lambda** [comment] 2019-10-10 08:11
Could you share your schema, or at least a portion of it that’s enough to reproduce the issue? I tried to reproduce what you’re seeing but I haven’t managed to yet.

I tried creating a table like this using `v1.0.0-beta.6`:

```sql
CREATE TABLE colors (
  value text NOT NULL,
  comment text NOT NULL
);
```

I added some values to it and marked it as an enum. I then started version `v1.0.0-beta.7`, and it seemed to migrate alright.

**Comment by brainplug** [comment] 2019-10-10 08:30
The tables are actually equally simple as yours. One example:

CREATE TABLE transport_type (
    "id" text PRIMARY KEY UNIQUE, 
    "value" text NOT NULL UNIQUE
);

Some additional info:

- our Hasura setup runs within Kubernetes (AWS EKS). I simply changed the version number in my deployment and used kubectl to replace the existing deployment (as per your docs)
- our database is an AWS Aurora database in the PostgreSQL-compatible mode
- our Hasura setup is secured with an admin secret and JWT security (integrated with AWS Cognito)

**Comment by lexi-lambda** [comment] 2019-10-10 08:43
Could I ask you to execute the following SQL query against your beta.6 instance and tell me what the output is?

```sql
SELECT table_schema, table_name, columns, primary_key_columns
FROM hdb_catalog.hdb_table_info_agg
WHERE table_schema = 'public' AND table_name = 'transport_type';
```

For example, when I run it against my sample `colors` table, I get this:

```
 table_schema | table_name |                                                                             columns                                                                              | primary_key_columns
--------------+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------
 public       | colors     | [{"name" : "value", "type" : "text", "is_nullable" : false, "references" : []}, {"name" : "comment", "type" : "text", "is_nullable" : false, "references" : []}] | ["value"]
(1 row)
```

**Comment by brainplug** [comment] 2019-10-10 09:04
I modified table_schema to the actual schema we use and then get this:

`table_schema | table_name         |                                                                             columns                                                                              | primary_key_columns
-------------+--------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------
 xxxxx       | transport_type     | [{"name" : "id", "type" : "text", "is_nullable" : false, "references" : []}, {"name" : "value", "type" : "text", "is_nullable" : false, "references" : []}]      | ["id"]
(1 row)`

**Comment by lexi-lambda** [comment] 2019-10-10 09:19
Ah, I’ve found the bug. Due to a change in 99174cca9b99ebb4b7d55d02fa1dcda150a3d57c, the internal `hdb_catalog.hdb_column` was extended with some additional `JOIN`s, and they unfortunately produce duplicate rows if there are two tables in different schemas with the same name.

The good news is that it’s an easy fix, and we should be able to patch it in the next release, which should be pretty soon after this most recent one. The bad news is that I don’t think our test suite is currently super well-equipped to catch these kinds of SQL mistakes, which is how this one slipped through the cracks. We’ll have to think about a better solution to that… maybe we can auto-generate extra tables in other schemas during testing or something like that.

**Comment by brainplug** [comment] 2019-10-10 09:29
Ah yes: we do also have the same table in the public schema as this is a development environment and one of our developers first started in the public schema before realizing it would be better to put his tables in their own schema. ;-)

We'll continue working on beta.6 for the time being, skip beta.7 and then upgrade when beta.8 comes out. Thanks!

**Closed** 2019-10-10 15:11 UTC
Labels: c/server, k/bug
