### ISSUE TITLE
support rotating access keys without downtime

### ISSUE THREAD

**Issue by samuela** [hasura/graphql-engine#1471] opened 2019-01-25 07:46 UTC
At present, hasura can only be configured with a single access key as far as I understand. This has the distinct disadvantage that one cannot rotate access keys safely without downtime. Instead it would be best to support at most 2 access keys. Then a transition of keys could occur without any downtime between clients and hasura.

**Comment by mdp** [comment] 2019-08-15 21:13
Is this just better handled with JWKs? It seems like rotation is built into JWK, vs trying to fit rotation into an environment variable.

**Comment by manasag** [comment] 2023-12-28 15:17
This issue has not attracted significant attention for a long period of time, and since alternatives are available (using JWKs), we are closing this.
Please feel free to reopen if the issue is still relevant for you.

**Closed by manasag** 2023-12-28 15:17 UTC
Labels: k/enhancement, c/server, p/longterm, a/cloud
