### ISSUE TITLE
Event based subscriptions

### ISSUE THREAD

**Issue by Maxpain177** [hasura/graphql-engine#5380] opened 2020-07-14 16:04 UTC
Hello. We have a website with a lot of active online users and subscriptions to a lot of tables.
During peak hours, we have huge CPU usage on Postgres.
Yes, subscription multiplication helps, but it only helps when it is not a user-based subscription. We have a lot of user-based subscriptions, like user counters (like messages and notifications count, money/balance), and a lot of primary-key based subscriptions (Every user can subscribe to 3-10 rows in a table by a primary key).
We also used Hasura for chats, but now we have to implement event-based subscriptions by ourself.

In these cases, we use separate Node.js microservice with ApolloServer and use `graphql-redis-subscriptions`, as a source for events we use `Hasura Event Triggers`. Why not implement event-based subscriptions for `INSERT`, `UPDATE`, and `DELETE` events by specific primary key right in Hasura GraphQL Engine?

**Comment by revskill10** [comment] 2020-07-14 21:05
@Maxpain177 Actually Hasura is generic enough that you can built it by yourself. 
In this case, i'll create new `events` table and subscribe from that table.
Hope this helps.

**Comment by Maxpain177** [comment] 2020-07-14 21:11
@revskill10 yes, I know, I noticed in my first message that I use hasura's trigger system to trigger my own handler and then send message to redis pub/sub to make apollo graphql subscriptions to work. Why not implement this right in Hasura?

**Comment by revskill10** [comment] 2020-07-14 22:25
@Maxpain177 Being generic is good, because we can choose our own implementation of our choice, for example, i would choose RabbitMQ to queue events.

**Comment by Maxpain177** [comment] 2020-07-15 09:14
@revskill10 I mean implement native postgres trigger based graphql subscriptions for browser websocket clients, not for backend

**Comment by tirumaraiselvan** [comment] 2020-07-28 06:33
Closing as dupe of https://github.com/hasura/graphql-engine/issues/2317

Let's continue the discussion in #2317 pls.

**Closed by tirumaraiselvan** 2020-07-28 06:34 UTC
