### ISSUE TITLE
Protect query/mutations against non authenticated users

### ISSUE THREAD

**Issue by alex-w0** [hasura/graphql-engine#4108] opened 2020-03-13 14:19 UTC
Hello, I'm trying to get started with hasura and can't figure out how I can do the following.
After I've connected hasura with my postgres instance, it'll generate automatically all standard queries for my tables (reservations, reservations_aggregate, reservations_by_pk...).
Additionaly I have two roles: admin and public
-> admin role: can use these queries
-> public role: should not be grant permission to execute these queries.

But both roles have access to the table reservations (update, insert, select..)

**Comment by wwwdepot** [comment] 2020-03-13 16:21
First thing, you need to set **HASURA_GRAPHQL_ADMIN_SECRET** (admin access key), 
then choose your authentication methods: webhooks or JWT. See https://hasura.io/docs/1.0/graphql/manual/auth/authentication/index.html

**Comment by alex-w0** [comment] 2020-03-13 16:35
@wwwdepot I've already set **HASURA_GRAPHQL_ADMIN_SECRET** , but how can I protect then the autogenerated queries with the authentication method ? Both, the public and the admin users can perform an insert action on the table, but only the admin user should have access to the auto generated queries?

**Comment by wwwdepot** [comment] 2020-03-13 18:40
@alex-w0 If you just want to test basic access control, you can set 

```
HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
```
now uncheck the `x-hasura-admin-secret` the Request Headers in the Hasura Console, queries will be protected from unauthenticated users. Make sure the `anonymous` role is added to the table's permission.

Finally **Allow-list** gives you more controls over what queries are available to users. https://hasura.io/docs/1.0/graphql/manual/deployment/allow-list.html

**Comment by alex-w0** [comment] 2020-03-13 19:32
@wwwdepot Maybe I don't get it. Lets assume that we have three roles:
-> admin
-> user
-> public

and the following queries:
-> reservations (is generated by default from hasura)
-> reservations_by_pk (is generated by default from hasura)
-> reservations_aggregate (is generated by default from hasura)
-> reservation_by_token (comes from a remote schema)

- the role admin can have access to all 4 queries
- the role user should only have access to reservations_by_pk and reservation_by_token 
- the role public should only have access to reservation_by_token

How can I define now within the allow-list which of the roles have access to which queries?

**Comment by wwwdepot** [comment] 2020-03-13 21:00
Someone did mentioned Role-base queries and allow-list feature in #2804.

Permissions for remote schemas is WIP, see #2461.

**Comment by alex-w0** [comment] 2020-03-13 21:23
@wwwdepot So that means that's not possible at the moment to make role based queries?

**Comment by wwwdepot** [comment] 2020-03-13 21:35
@alex-w0 yep, not possible at the moment.

**Comment by alex-w0** [comment] 2020-03-13 21:43
@wwwdepot Okay thanks. How do others solve this problem? i can well imagine that many people have these requirements

**Comment by tirumaraiselvan** [comment] 2020-03-16 08:17
> the role admin can have access to all 4 queries
the role user should only have access to reservations_by_pk and reservation_by_token
the role public should only have access to reservation_by_token

I think the issue is that you want to hide certain fields which are auto-generated when you have given `select` permissions on a table. The RFC here let's you hide top-level fields like `reservations` and/or `reservations_by_pk` inside of select permissions: https://github.com/hasura/graphql-engine/pull/4110

Let us know if this will solve your problem.

**Comment by alex-w0** [comment] 2020-03-16 12:06
Hi @tirumaraiselvan , I don't want to hide the fields, but instead they should be protected against non authenticated roles. For example the admin role and user role has both the select permission on the table, but only the admin role should be able to perform the query reservations. Hope you can understand me what I wanna do.

**Comment by tirumaraiselvan** [comment] 2020-03-22 06:38
@alex-w0 I am not sure I understand. If you don't want to allow "user" to perform queries on reservations, why give select permissions to "user" on this table in the first place?

Do you not want to allow query `reservations` but allow query `reservations_by_pk` ? In that case, the RFC I linked in my previous comment should be relevant.

**Comment by alex-w0** [comment] 2020-03-22 12:17
@tirumaraiselvan At the moment I have two problems that I'm facing:

1) "**user**" can perform queries on reservations, but I need a hook or something where I can define that only the reservations should be returned where the "user" is related to, because the user should not have access to reservations from other users. (on the other hand the query reservations should return all reservations from all users when the role is "admin")
2) The next problem is that there is also existing a role called "**public**". When I've for example a booking widget where each client can book directly an accomodation. The widget is divided into different booking steps
1. selecting the period
2. selecting the room
3. selecting additional services
4. show the previously selected data and finally book the accomodation.

On the first step of the widget the reservation **must be created** with the basic data and after each step it should be **updated**. At the last step the reservation (with all the data) **should be fetched** from the database.

In total the role public have the following permissions: select, insert, update
Even if it has access to these permissions, it should not be possible that this role can perform queries on reservations or reservations_by_pk

So I don't want only to restrict the queries but also apply different conditions based on the role that is making the request

**Comment by tirumaraiselvan** [comment] 2020-03-22 14:37
> "user" can perform queries on reservations, but I need a hook or something where I can define that only the reservations should be returned where the "user" is related to, because the user should not have access to reservations from other users. (on the other hand the query reservations should return all reservations from all users when the role is "admin")

The permission system allows you to do this. You can give select permissions for "user" with the boolean check `{ "user_id": {"_eq": "X-Hasura-User-Id"}`. See https://hasura.io/docs/1.0/graphql/manual/auth/authorization/common-roles-auth-examples.html#logged-in-users

> The next problem is that there is also existing a role called "public". When I've for example a booking widget where each client can book directly an accomodation. The widget is divided into different booking steps

I am guessing "public" is an unauthorized role. This is also solvable using the permissions system. You can have an insert permission on "booking" table which is open to "public" (aka unauthorized role) and this should return a booking id. But for select and update, you have a rule which needs `X-Hasura-Booking-Id` to be present in the headers. For unauthorized roles, you can send x-hasura-* headers from the client as per: https://github.com/hasura/graphql-engine/issues/1686

**Comment by alex-w0** [comment] 2020-03-24 00:08
> The permission system allows you to do this. You can give select permissions for "user" with the boolean check `{ "user_id": {"_eq": "X-Hasura-User-Id"}`. See https://hasura.io/docs/1.0/graphql/manual/auth/authorization/common-roles-auth-examples.html#logged-in-users

And when the role is an **admin** and doesn't match with the user_id from the reservation? Because the reservation is always referenced to a specific **user**.

> I am guessing "public" is an unauthorized role. This is also solvable using the permissions system. You can have an insert permission on "booking" table which is open to "public" (aka unauthorized role) and this should return a booking id. But for select and update, you have a rule which needs `X-Hasura-Booking-Id` to be present in the headers. For unauthorized roles, you can send x-hasura-* headers from the client as per: #1686

Yes, public is an unauthorized role. In my case there doesn't exist a booking table, only the table "reservations" exists, which should be accessible in different ways for these roles. So can I define that the unauthorized role can select the reservations by the booking id, the user can select only by { "user_id": {"_eq": "X-Hasura-User-Id"} and the admin can select all reservations without any restrictions?

**Comment by tirumaraiselvan** [comment] 2020-03-24 03:04
@alex-w0 

> And when the role is an admin and doesn't match with the user_id from the reservation? Because the reservation is always referenced to a specific user.

The role "admin" is a special role and has full access to everything.

> So can I define that the unauthorized role can select the reservations by the booking id, the user can select only by { "user_id": {"_eq": "X-Hasura-User-Id"} and the admin can select all reservations without any restrictions?

Yes.

I would also recommend going through few access control examples in the docs: https://hasura.io/docs/1.0/graphql/manual/auth/authorization/common-roles-auth-examples.html

You can also use the community chat for discussing such questions: https://discordapp.com/invite/hasura

**Comment by alex-w0** [comment] 2020-03-25 18:11
@tirumaraiselvan 

> The role "admin" is a special role and has full access to everything.

And if I have another role that is a little bit lower than the admin, which is also not related to a specific user_id from the reservation?

> Yes.
I would also recommend going through few access control examples in the docs: https://hasura.io/docs/1.0/graphql/manual/auth/authorization/common-roles-auth-examples.html

Alright thanks, so I'll give it a try.

**Comment by tirumaraiselvan** [comment] 2020-05-11 10:34
Closing the issue. Feel free to open it if you have any further questions.

**Closed by tirumaraiselvan** 2020-05-11 10:34 UTC
Labels: k/question
