### ISSUE TITLE
Give better response on graphql engine 404 urls

### ISSUE THREAD

**Issue by rikinsk-zz** [hasura/graphql-engine#1207] opened 2018-12-13 12:17 UTC
In case HGE is launched with console disabled, there is no feedback to the user if HGE is running when user hits a server url. i.e.
![screenshot from 2018-12-13 17-39-28](https://user-images.githubusercontent.com/153602/49937853-1dce2e80-fefe-11e8-99b3-470305cbae09.png)

Instead, on all 404 pages give a response saying, "Hasura GraphQL Engine is running! GraphQL endpoint is /v1alpha1/graphql"  or some other similar message.

**Comment by manasag** [comment] 2023-12-27 14:27
This issue has not attracted significant attention for a long period of time, hence closing this.
Please feel free to reopen if the issue is still relevant for you.

**Closed by manasag** 2023-12-27 14:27 UTC
Labels: k/enhancement, c/server, a/api
