### ISSUE TITLE
Using computed fields in where clause 

### ISSUE THREAD

**Issue by tejashree-23** [hasura/graphql-engine#6582] opened 2021-02-22 13:57 UTC
Hi,

I have created some computed fields(both scalar and table) by following the hasura documentation at
https://hasura.io/docs/1.0/graphql/core/schema/computed-fields.html#

The computed fields display the data properly. However, when I try to use them in the where clause in the graphql explorer, it gives an error : 'Field is not defined by type bool-exp'.

Please guide on the usage of computed fields in the where clause.

![computed-fields-where1](https://user-images.githubusercontent.com/77322486/108717990-f181b400-7543-11eb-8f8b-9bba08f4e91c.png)
![computed-fields-display1](https://user-images.githubusercontent.com/77322486/108717997-f34b7780-7543-11eb-8725-d88f84e94148.png)

**Comment by tirumaraiselvan** [comment] 2021-03-01 07:20
Filtering on computed field is not implemented yet. Closing as dupe of https://github.com/hasura/graphql-engine/issues/3772

**Closed by tirumaraiselvan** 2021-03-01 07:20 UTC
