### ISSUE TITLE
Allow table comments to describe the schema type

### ISSUE THREAD

**Issue by jasonmccallister** [hasura/graphql-engine#2615] opened 2019-07-28 13:59 UTC
When adding a table, we have the option of adding a comment on the table, it would be useful if the comment was added to the description of the type in the GraphQL schema. 

Right now the generated description is `"columns and relationships of "<table-name>"`. Ideally this should be the comment on the table e.g. `stores preferences for the users profile`.

Looks like the line of code here defines the schema description, maybe just check if the table has a comment?

https://github.com/hasura/graphql-engine/blob/a76e34770a6a62d0c5cdfa45a90a46dde2990f81/server/src-lib/Hasura/GraphQL/Schema.hs#L258

**Comment by marionschleifer** [comment] 2019-07-29 05:10
Hi @jasonmccallister 👋 This issue is a duplicate of https://github.com/hasura/graphql-engine/issues/446 and will be added with this PR: https://github.com/hasura/graphql-engine/pull/2397. Closing this for now.

**Closed by marionschleifer** 2019-07-29 05:10 UTC
