### ISSUE TITLE
Hasura v2 breaks queries where it shouldn't ("unexpected variables in variableValues")

### ISSUE THREAD

**Issue by manuFL** [hasura/graphql-engine#7163] opened 2021-07-01 15:30 UTC
Hi,

I'm experiencing the following error: `unexpected variables in variableValues` since Hasura v2 upgrade.

This happens due to the fact that my queries include some variables which are necessary but used only inside a skip condition, not within the query body. 

Here is an example query which such behaviour, which was working OK with hasura v1:

```gql
   query notes(
      $customersIDs: [Int!]
      $overrideCustomersIDs: Boolean = false
   ) {
      globalFilterCustomers
         @client
         @export(as: "customersIDs")
         @skip(if: $overrideCustomersIDs)      
      notes(
         where: {
            customerID: { _in: $customersIDs }            
         }
      ) {
         customerID
         noteText
      }
   }
```

I would like to disable this validation, or any other solution to be able to get this kind of queries working again... thank you!

**Comment by maszhin** [comment] 2021-07-14 18:33
Similar issue here. When using Relay API -> appendEdge, we need to provide connections as query params (as specified in docs https://relay.dev/docs/next/guided-tour/list-data/updating-connections/#appendedge--prependedge). Those query params are not removed from relay variables, sent along with the request, and then Hasura is returning validation error.
```
{errors: [{extensions: {path: "$", code: "validation-failed"},…}]}
errors: [{extensions: {path: "$", code: "validation-failed"},…}]
0: {extensions: {path: "$", code: "validation-failed"},…}
extensions: {path: "$", code: "validation-failed"}
message: "unexpected variables in variableValues: connections"
```

**Comment by BenoitRanque** [comment] 2021-09-07 04:07
I have been trying to reproduce this issue for a while, with no success.
I am a bit confused by your query, specifically by the `globalFilterCustomer` field.
Assuming this field comes from a remote schema?

> queries include some variables which are necessary but used only inside a skip condition, not within the query body.

I tried to reproduce this using the following query, which is best described as "fetch a post, and that post's comments, their users, and the other comments of the users on the same post" (redundant I know but as an example)

```gql
query MyQuery ($id: Int! $otherId: Int $skipComments: Boolean = true) {
  post_by_pk(id: $id) {
    title
    body
    comments @skip(if: $skipComments) {
      body
      user {
        name
        comments (where: { post_id: { _eq: $otherId } }) {
          body
        }
      }
    }
  }
}
```
I was unable to reproduce the issue.
I would be grateful if you could provide more information.

**Comment by dvekeman** [comment] 2021-09-07 07:20
We are seeing a similar issue when testing the upgrade from v1.3.3 to 2.x (last one we tried was 2.0.7)

The following query works on v1.3.3 but not on 2.0.7. 

```
query MyBreakingChange(
  $name:String
  $something: Boolean = false
) {
  risolto_report_definition(
    where:{
      name: {_like: $name }
    }
  ) {
    name
    owner
  }
}
```

with variables

```
{ "name": "test%", "something": true }
```

In GraphiQL there is a warning but the query succeeds anyway

<img width="417" alt="image" src="https://user-images.githubusercontent.com/12081083/132301553-5aa7f818-05f8-49e7-bbcd-36bf14f42d1c.png">

**Comment by BenoitRanque** [comment] 2021-09-07 10:38
@dvekeman this behavior is compliant with the [grapqhl spec](https://spec.graphql.org/June2018/#sec-All-Variables-Used).
Defining a variable and never using it in the query is not permitted.
This isn't the same thing @manuFL described, which is defining a variable and using it within a part of the query that may be skipped using the `@skip` directive.

**Comment by manuFL** [comment] 2021-09-14 12:41
@BenoitRanque Hi, the `globalFilterCustomer` field comes from apollo `InMemoryCache`:

 ` ` `gql
import * as globalFiltersReactiveVars from 'apollo-store/reactiveVars/globalFiltersReactiveVars';
import { InMemoryCache } from '@apollo/client';

const cache = new InMemoryCache({
   typePolicies: {
      Query: {
         fields: {
            globalFilterCustomers: {
               read() {
                  const globalFilterCustomers = globalFiltersReactiveVars.globalFilterCustomers();
                  return globalFilterCustomers.length > 0
                     ? globalFilterCustomers.map((customer) => customer.idx)
                     : null;
               },
            },
            
         },
      },
   },
});

export default cache;
 ` ` ` 

We are using global input field filters, mapped to react vars and stored in the cache.

This piece of code:

```
globalFilterCustomers
         @client
         @export(as: "customersIDs")
         @skip(if: $overrideCustomersIDs)    
```

Means: take the `customerIDs` variable from `globalFilterCustomers` cached field, but only if the `skip` statement is false. If else, use the passed `customersIDs` variable instead of the global one.

**Comment by BenoitRanque** [comment] 2021-09-14 17:04
@manuFL after taking a look at the documentation for those directives, I believe I understand the issue now.
The part of the query anotated with `@client` is managed client side, and never makes it to hasura.
But it seems the `overrideCustomersIDs` variable does, which explains your problem.

This is an issue with apollo-graphql and the implementation of the `@client` directive. You can find a related issue [here](https://github.com/apollographql/apollo-client/issues/3475)

Due to this not being an issue with hasura, and because the current behavior is compliant with the [graphql specification](https://spec.graphql.org/June2018/#sec-All-Variables-Used) and thus unlikely to change, I am closing this issue

**Closed by BenoitRanque** 2021-09-14 17:04 UTC
