### ISSUE TITLE
Multi-tab UI for GraphiQL to keep queries

### ISSUE THREAD

**Issue by revskill10** [hasura/graphql-engine#336] opened 2018-08-30 19:59 UTC
Currently with `graphql-playground`, you can have multi-tab UI , so we don't have to delete/recreate queries we want to keep them there.
There're two options for this.
- Adopt graphql-playground or something similar for a better UX.
- Hacking on GraphiQL.

**Comment by shahidhk** [comment] 2018-09-05 16:53
@praveenweb @revskill10 Cant't the History button and the sidebar on GraphiQL itself serve this purpose?

**Comment by revskill10** [comment] 2018-09-06 05:40
@shahidhk I think in long term, multi-tab is unavoidable when you have large number of queries to test at the same time, so it would be easier to manage through tabs.

**Comment by elitan** [comment] 2019-01-22 07:05
I think GraphiQL in the Hasura console is enough. 

If you want to use the  GraphiQL Playground, which is a great tool, you can use it separately as a web app without adopt it into the Hasura console.

**Comment by imolorhe** [comment] 2019-02-04 20:36
I would suggest adopting [Altair](https://altair.sirmuel.design/) though.

**Comment by mnlbox** [comment] 2019-02-06 06:07
Wooooo @imolorhe it's very beautiful. Thanks

**Comment by FakhruddinAbdi** [comment] 2022-07-19 07:56
I believe it should be a short-term feature
It's really annoying when working on a real project and you can not manage all the queries in the console
I have to copy and paste from the code every time

Compared with apollo studio and Altair, GrqphiQl interface is outdated

And as the issue is open since 2018, its supposed to be fixed by now even with the long term label

**Comment by elitan** [comment] 2022-07-19 13:37
@FakhruddinAbdi Hasura is open source. If you want this fixed, you can do so and make a PR.

**Comment by FakhruddinAbdi** [comment] 2022-07-19 17:06
> @FakhruddinAbdi Hasura is open source. If you want this fixed, you can do so and make a PR.

 you are partially correct. but is not a minor bug fixing and the main project is not fully open source.
Please take my point lightly, I just wanted to help you with the task prioritzing.

**Comment by elitan** [comment] 2022-07-20 07:29
I think I'm 100% correct because:

- Whether a bug (it's not really a bug but a feature request) is minor or major is arbitrary.
- The part you want to be fixed is open source.

**Comment by revskill10** [comment] 2022-07-21 11:07
@elitan Your point is not wrong, but it's not helpful, because we're on github, and of course Hasura Core is open source. So the quote "Because it's open source, if you want to have a feature, please make a PR for it" seems unrelated, as it's 100% correct, regardless of any kind of github open source project. So what's the point of commenting such thing here ?

Feature request is to let the team know of real demand from users.

Hope Hasura team could hide your message because of not related purpose. Or you can just copy and paste your message to all feature request GH issues here.

**Comment by elitan** [comment] 2022-07-21 11:51
Adding useful comments to expand issues and show user demand is good.

What's not helpful, and what I was pointing out, is this type of comment:

> And as the issue is open since 2018, its supposed to be fixed by now

https://github.com/hasura/graphql-engine/issues/336#issuecomment-1188724170

**Comment by manasag** [comment] 2023-12-27 09:28
This request is already addressed in the new Hasura V3, hence closing this. The Hasura V3 console supports the latest GraphiQL which has the multiple tab support. Please follow the [guide](https://hasura.io/docs/3.0/getting-started/overview/) here for Alpha access to Hasura V3.

**Closed by manasag** 2023-12-27 09:28 UTC
Labels: k/enhancement, c/console, p/longterm, a/product-design
