### ISSUE TITLE
Feature request: dynamic change database at runtime

### ISSUE THREAD

**Issue by mingushead** [hasura/graphql-engine#1726] opened 2019-03-10 11:09 UTC
Propbably related to: https://github.com/hasura/graphql-engine/issues/821

- Need to be able to supply Postgres database (not postgres instance) per query
- Schemas guaranteed to be the same for every database

Example: I have a `hasura/graphql-engine` instance running and connected to _postgresUrl_.
The Postgres instance at _postgresUrl_ contains the databases _db1_, and _db2_.
I am sure that the schemas describing _db1_ and _db2_ are identical. I want to be able to query either (not necessarily both simultaneously) db at runtime.

**Comment by ecthiender** [comment] 2019-03-13 08:04
Closing this as duplicate of #821 . @mingushead you can upvote the other issue.

**Closed by ecthiender** 2019-03-13 08:04 UTC
