### ISSUE TITLE
Remote schema mutation permissions break when using cli metadata apply

### ISSUE THREAD

**Issue by AThilenius** [hasura/graphql-engine#8674] opened 2022-07-07 17:21 UTC
### Version Information

Server Version: v2.8.4-cloud.1 and v2.8.4
CLI Version (for CLI related issue): v2.8.4

### Environment
Server: cloud and self-hosted
CLI V2.8.4 (and the version I was on before) as well as the `hasura/graphql-engine:latest.cli-migrations-v3.ubuntu` Docker image.

### What is the current behaviour?

With remote schema permissions enabled, setting permissions for a non-admin user on a mutation works just fine while in the Console (UI). You can see and execute this mutation with `x-hasura-admin-secret` set, and with or without the custom `x-hasura-role` set. All good so far 👍

If you then `hasura metadata export...` and `hasura metadata apply` the project, the permissions still show as checked, but Hasura will give you `no mutations exist` when `x-hasura-role` is set to the custom role, but works otherwise.

### What is the expected behaviour?

Exportin and importing a project doesn't break mutation permissions for remote schemas.

### How to reproduce the issue?

- Create a Hasura project (cloud or self-hosted)
- Set `HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS=true`
- Add `https://graphqlzero.almansi.me/api` as a remote schema
- Go to Permissions, add a 'systemuser' and click filter. Check a query, and a mutation
- Go to API, and see the ability to execute both there
- Add `x-hasura-role`: `systemuser` to the headers and see that it doesn't effect the above
- In a shell somewhere
  - `hasura init`
  - `hasura metadata export --endpoint ... --admin-secret ...` (see that the permissions look correct in `remote_schema.yaml`
  - `hasura metadata apply --endpoint ... --admin-secret ...`
- Permission still look correct under the remote schema, but you can no longer access mutations when `x-hasura-role`: `systemuser` is set.

### Any possible solutions?

If you uncheck the permissions in the UI, save, and re-check them it will work again. Not a good solution when you're workflow depends on remote pushes of metadata like ours.

### Can you identify the location in the source code where the problem exists?

Nope. I would guess the CLI somewhere since it works in the console.

### If the bug is confirmed, would you be willing to submit a PR?

My GoLang foo is not strong.

### Keywords

CLI, Metadata, Remote Schema, Permissions, Mutation

**Comment by adAAM91** [comment] 2022-07-09 08:09
@AThilenius, we run into the same problem, I noticed theres a difference in json and yaml (exported metadata) permissions after you save it in the UI. I fixed it by adding this to the permission (remote_schemas.yaml):

```
schema  {
    query: Query 
    mutation: Mutation 
}
```

**Comment by AThilenius** [comment] 2022-07-19 21:05
@adAAM91 I can't get the CLI to be happy with that format, I always get the following error:
```
FATA[0001] error applying metadata
{
  "path": "$.args.metadata.remote_schemas[0].permissions[0].definition.schema",
  "error": "parsing the schema document: \"endOfInput\"",
  "code": "parse-failed"
}
```

**Comment by codingkarthik** [comment] 2022-07-20 09:03
Dupe of https://github.com/hasura/graphql-engine/issues/8455

**Closed by codingkarthik** 2022-07-20 09:03 UTC
Labels: k/bug
