### ISSUE TITLE
Question regarding "row select permissions"

### ISSUE THREAD

**Issue by mamasselin** [hasura/graphql-engine#6599] opened 2021-02-24 21:25 UTC
Hello!

First, thanks for this awesome product! I really enjoy using it!

I have a question regarding the "row select permissions" capabilities:

I'm trying to scope my data on a given claim value in my JWT token but not against a table field; I want to compare it against a simple string.

My use case is to prevent users without a specific claim value from retrieving data at all.

Example: if you don't have `order:view` in your token's `X-Hasura-Permissions` claim, you can't retrieve data from the "order" table at all:

`{ "order:view": { "_in": "X-Hasura-Permissions" } }`

But it does not allow me to do this. The left side of the comparison forces me to put a table field.

I read about the "roles" approach but I don't have a static list of roles. Each tenant in my app can create their own roles and select the permissions they want for each role.

Currently as a workaround, I have to join with my "accessRole" table (which contains the same permission claims as in my token) like so:

```json
{
  "_exists": {
    "_table": { "name": "accessRole", "schema": "public" },
    "_where": {
      "_and": [
        { "id": { "_eq": "X-Hasura-Access-Role-Id" } },
        { "permissions": { "_has_key": "order:view" } }
      ]
    }
  }
}
```

But I'm afraid this will affect the performance, and since I already have this information in my token, I would like to just read it from the token.

Is there a better way to achieve what I want?

**Comment by tirumaraiselvan** [comment] 2021-03-01 07:07
Closing as dupe of https://github.com/hasura/graphql-engine/issues/3685

Would be great if you could add any (additional) comments there!

**Closed by tirumaraiselvan** 2021-03-01 07:07 UTC
