### ISSUE TITLE
Unable to apply allow_list.yaml

### ISSUE THREAD

**Issue by petecorreia** [hasura/graphql-engine#4759] opened 2020-05-13 10:12 UTC
I'm in the process of enabling allowed queries in an automated way rather than manually via the console.

I'm running `metadata apply` with the following files:

**query_collections.yaml**
```json
[
  {
    "name": "allowed-queries",
    "definition":
      {
        "queries":
          [
            {
              "name": "Test",
              "query": "query Test {\n    users {\n        id\n    }\n}",
            },
          ],
      },
  },
]
```

**allow_list.yaml**
```json
[{ "collection": "allowed-queries" }]
```

The command runs successfully and I can see the query Test in the console but when I export the metadata it's clearly missing the `allowlist` key in the exported `json` file. 

The allowlist key is present when doing it via the console.

Via the console:
```json
  "query_collections": [
    {
      "name": "allowed-queries",
      "definition": {
        "queries": [
          {
            "name": "Test",
            "query": "query Test {\n    users {\n        id\n    }\n}"
          }
        ]
      }
    }
  ],
  "allowlist": [
    {
      "collection": "allowed-queries"
    }
  ],
```

Via CLI:
```json
  "query_collections": [
    {
      "name": "allowed-queries",
      "definition": {
        "queries": [
          {
            "name": "Test",
            "query": "query Test {\n    users {\n        id\n    }\n}"
          }
        ]
      }
    }
  ],
  // allowlist MIA
```

This leads to all queries getting invalidated as it's not referencing the collection. 

What am I doing wrong? Or is there an issue with CLI?

_Note: The test query works well when added via the console. It's not related to the actual query or anything like that._

**Comment by tirumaraiselvan** [comment] 2020-05-13 10:13
Probably dupe of: https://github.com/hasura/graphql-engine/issues/4687

**Comment by petecorreia** [comment] 2020-05-13 10:15
@tirumaraiselvan looks that way. I'll subscribe to the other issue in case you want to close this one.

**Comment by codingkarthik** [comment] 2020-05-13 14:12
@petecorreia @tirumaraiselvan I was able to reproduce this issue. 

> Note: The test query works well when added via the console.

When adding a query to the allow list and then exporting it immediately includes the `allowList` key when exporting the metadata.

If you clear the metadata and import the exported metadata from the above step the allow list gets imported in the graphql-engine but now when you export it, the `allowList` will be missing.

Most probably it's a server bug

**Comment by tirumaraiselvan** [comment] 2020-05-13 14:24
ok, let's track this in https://github.com/hasura/graphql-engine/issues/4687

**Closed by tirumaraiselvan** 2020-05-13 14:24 UTC
Labels: c/server, k/bug
