### ISSUE TITLE
How to clear one schema from the gql-engine metadata?

### ISSUE THREAD

**Issue by sulliwane** [hasura/graphql-engine#1250] opened 2018-12-20 12:22 UTC
Looking at the **hasura-cli** doc, or at the **web dashboard**, I can't find a way to remove either tables or a whole schema from the graphql-engine metadata.

I saw this in the code: `clear_metadata` but not sure How it's supposed to work.

My use case: every new user needs to get a new -duplicated- schema in postgres/hasura. And every user removal requires the removal of its schema from postgres/hasura. I'm currently scripting this in bash, and having management control on the schema level in the metadata would be super usefull I feel 

```bash
hasura metadata add --schema=test # not replacing whole metadata
hasura metadata clear --schema=test # not clearing whole metadata
```

Or should I implement the logic of exporting whole metadata, remove lines related to a schema using `sed`, and applying back the updated metadata? Does that make sense...?

Many Thanks!

**Comment by 0x777** [comment] 2018-12-21 06:54
Hi, currently we don't have any such operations (clearing/duplicating) at the schema level. We'll definitely add this feature to the cli.

> Or should I implement the logic ..

You can use the metadata APIs to generate the correct migration (say tracking/untracking all the tables in a schema). https://docs.hasura.io/1.0/graphql/manual/api-reference/schema-metadata-api/index.html

**Comment by manasag** [comment] 2023-12-28 04:29
The V3 architecture pays much attention to metadata authoring and management. It introduces a concept of subgraph which can be modelled to be managed separately by different teams from Ci/CD point of view. You can probably map the subgraph to be backed by tables of only 1 schema. Please do try the alpha version of [Hasura V3](https://hasura.io/docs/3.0/getting-started/overview/) to see if this solves your requirement. We would like to get an early feedback.

We are closing this issue as it has not attracted significant attention for a long period of time.
Please feel free to reopen if the issue is still relevant for you.

**Closed by manasag** 2023-12-28 04:29 UTC
Labels: k/enhancement, c/cli, p/medium, e/hard, c/migrations
