### ISSUE TITLE
failed to wait for port 8080 (on first postgres run)

### ISSUE THREAD

**Issue by sulliwane** [hasura/graphql-engine#1168] opened 2018-12-05 14:15 UTC
Hi,

When postgres/timescale docker is up for the first time, `hasura/graphql-engine:v1.0.0-alpha31.cli-migrations` will fail to start with this message:
```
starting graphql engine on port 8080...
waiting for 8080
.Postgres connection info:
    Host: timescale
    Port: 5432
    User: postgres
    Database: qu4nt
{"internal":"could not connect to server: Connection refused\n\tIs the server running on host \"timescale\" (172.18.0.4) and accepting\n\tTCP/IP connections on port 5432?\n","path":"$","error":"connection error","code":"postgres-error"}
```
If running `docker-compose down && docker-compose up` then graphql-engine works fine. I believe it due to the time used by postgres/timescale on a first init, but graphql-engine should still be resilient to this...

thanks for your feedback :)

docker-compose.yml excerpt:
```
services:
  timescale:
    image: timescale/timescaledb:latest-pg10
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha31.cli-migrations
    depends_on:
      - "timescale"
```

**Comment by shahidhk** [comment] 2018-12-06 06:44
@sulliwane You can add `restart: always` to the docker compose file for graphql-engine service. 

In the current configuration, GraphQL Engine expects Postgres to be ready and accepting connections.

**Comment by sulliwane** [comment] 2018-12-06 08:33
Thanks @shahidhk for your reply. It's actually already set to `restart: always`, still GraphQL Engine hangs on `waiting for 8080, failed to wait for port 8080`. I didn't figure out how this error is related to postgres port not available (I suppose graphQL engine won't listen for port 8080 before being connected to postgres...)

For integration tests, postgres may need to start "from scratch" (initialize DB files) which means that it may not be available right away. I'll further investigate a solution to this probably next week and I'll post here if I get any solution.

**Comment by shahidhk** [comment] 2018-12-06 08:39
@sulliwane When using `cli-migrations` image, the entrypoint script [waits for 30 seconds](https://github.com/hasura/graphql-engine/blob/master/scripts/cli-migrations/docker-entrypoint.sh#L12) for GraphQL Engine to be running so that it can apply migrations. The error message is definitely coming from there.

Yes, GraphQL Engine will not start listening on 8080 unless connection with Postgres is established. But, the idea is to let GraphQL Engine crash consecutively using `restart: always` till Postgres is available.

**Comment by KCErb** [comment] 2019-05-31 08:11
I'm having this same issue, but the migrations don't seem to ever make it in. It seems that it wants to wait 30s but dies and restarts and on the next restart I get no messaging about migrations as if some flag got set and the new instance thinks migrations are being handled by the old one.

**Comment by rikinsk** [comment] 2019-05-31 12:01
Reopened for KCErb's issue

**Comment by KCErb** [comment] 2019-06-03 05:28
Here is a minimal example that reproduces the issue for me: https://github.com/KCErb/hasura-example-test.

On my real example, I have a web framework ([lucky](https://luckyframework.org/)) managing the database for me. So I am only expecting the metadata.json to run. In this example, I also include a simple migration file for creating a test table. It seems that neither this migration file nor the metadata file are used because the migration system never runs.

To my knowledge, even with a faulty set of migration files the migration system should still report "migrations not applied" or "nothing to apply" or something to that effect. Instead I get the following output: [gist](https://gist.github.com/KCErb/f41855813fbc5bded34f2864e3afbc4a). Where you can't see that line 74 is the last output of the first graphql-engine (in yellow color in my terminal) and line 75 is the first output of the next graphql-engine (green in my terminal).

As you can see from the timestamps, the engine fires up before postgres and goes into a 30s wait, then postgres is ready about 1 second later, then 29 seconds later the engine dies and a new one springs up thinking the migrations are applied.

**Comment by KCErb** [comment] 2019-06-04 05:33
I was able to fix this issue by changing the entrypoint script to use `nc -z` instead of just `nc` when looking for port 8080 to be up. I'm not sure what plain `nc localhost 8080` does on your machine, but on my docker machine it just hangs. I get a nice clean 1 or 0 exit code with the `-z` flag.

Should I submit a PR or is their something more to this that I don't see from my perspective?

**Comment by KCErb** [comment] 2019-06-04 06:08
Also, while digging into this I noticed that the messaging is "we'll wait 30s before trying again" but in reality it tries silently 30 times and then gives up. So I think it'd be better to phrase it as X attempts not X wait time.

**Comment by KCErb** [comment] 2019-06-10 06:50
@shahidhk Should I open a PR on this? Adding that `-z` flag is critical from what I can tell and an easy fix.

**Comment by KCErb** [comment] 2019-07-10 10:46
Any thoughts on this?

**Comment by lexi-lambda** [comment] 2019-07-10 20:01
I can’t reproduce your problem with the repository you provided, but the missing `-z` flag to `nc` does seem wrong, and I agree that a PR to add the flag would be a good idea.

**Comment by KCErb** [comment] 2019-07-10 21:04
@lexi-lambda did you run it with the command in the gist `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up`? I just cloned down that repo and ran that command and got almost the same output.

But at first I was confused why I put up a repo to demonstrate the problem and never mentioned the command used to run it.

At any rate, this really does just boil down to the correct use of `nc` and `-z` flag seems unambiguous in this context. Thanks for giving this a run / look at :)

**Comment by lexi-lambda** [comment] 2019-07-10 21:09
I did do that—I saw the command you ran in the gist you linked. Honestly, I don’t know why it does something different on my machine, since with `tty: true`, I would expect `nc` to block on input and never return, but my guess is that some piece of Docker tooling is doing something with stdin I don’t totally understand. But yes, I think the missing `-z` is probably just a typo.

**Comment by shahidhk** [comment] 2019-07-31 05:20
Closed in https://github.com/hasura/graphql-engine/commit/dc52c0e5075b1171ec4ff76bf9b0f3eef174b730

**Closed by shahidhk** 2019-07-31 05:20 UTC
Labels: c/cli

**Comment by KCErb** [comment] 2019-08-12 10:31
Nice :+1:
