### ISSUE TITLE
Feature Request -- Unschedule One-Off Event

### ISSUE THREAD

**Issue by rahulmadduluri** [hasura/graphql-engine#6321] opened 2020-12-08 18:59 UTC
Can you add an "delete_scheduled_event" metadata API call?

https://hasura.io/docs/1.0/graphql/core/api-reference/schema-metadata-api/scheduled-triggers.html#delete-cron-trigger

I am scheduling events in my app, but sometimes I want to delete them before they are triggered. Right now, it's just resulting in an extraneous webhook, but I would like to prevent that if possible.

**Comment by tirumaraiselvan** [comment] 2020-12-17 14:20
Closing as dupe of https://github.com/hasura/graphql-engine/issues/5025

**Closed by tirumaraiselvan** 2020-12-17 14:20 UTC
