### ISSUE TITLE
BigQuery return types are always JSON strings

### ISSUE THREAD

**Issue by qnm** [hasura/graphql-engine#9840] opened 2023-08-22 02:08 UTC
### Version Information

Server Version: 2.31.0

### Environment

OSS / EE

### What is the current behaviour?

I have a native query for a table. I can query this table in Hasura, and my JSON result contains string and numeric types as expected.

![image](https://github.com/hasura/graphql-engine/assets/5343/26edd61a-d79e-4043-8aab-9ae885d2a4a0)

![image](https://github.com/hasura/graphql-engine/assets/5343/c40099d1-f86f-4d14-883c-242602c91612)

I've created a logical model for a result set for this same data, which contains string, int64, float64 and timestamp types.

![image](https://github.com/hasura/graphql-engine/assets/5343/1275de57-00c7-4535-96a9-f0161b8772d0)

Querying via the native query / logical model results in all non-null fields being returned as string types.

![image](https://github.com/hasura/graphql-engine/assets/5343/33accdbc-4bcb-4260-b296-38e82bc7c754)

I do not have the same issues with NQ/LM on my Postgres database.

### What is the expected behaviour?

I would expect to see the correct types returned by my logical model.

### How to reproduce the issue?

1. Create a BigQuery table with non-string values e.g. int64 float64
2. Build a logical model / query around the table
3. Query it, observe the int64 and float64 values as strings

### Screenshots or Screencast
As above.

### Please provide any traces or logs that could help here.

None. I can provide on request.

### Any possible solutions/workarounds you're aware of?

I have hacked my frontend code to cast the values. Not a solution.

### Keywords

bigquery, native model, types

Note: As this is a bug, I am republishing https://github.com/hasura/graphql-engine/discussions/9828

**Comment by manasag** [comment] 2023-08-22 08:16
Hi @qnm , we are trying to reproduce this internally. We'll update shortly.

**Comment by i-am-tom** [comment] 2023-08-23 13:51
Hi @qnm, thanks for your bug report.

First of all: can we confirm that the query you run on the table is also running on BigQuery? In which case, can you share the GraphQL schema for that table? For example, we've been testing with a table that looks like this:

<img width="230" alt="image" src="https://github.com/hasura/graphql-engine/assets/6302310/1e3dab31-f5c1-4302-a574-be6fdd98fef5">


We want to verify that the table is being interpreted as a BigQuery source - if it is, both the native query and the regular tracked table should output strings for numeric fields, rather than specific integer or float types. This is how they are presented to us from BigQuery (which supports 8-byte types), and we preserve this representation because the GraphQL spec only supports 4-byte types. In short, if we converted the strings to numeric types, we'd risk losing some information in the process.

**Comment by qnm** [comment] 2023-08-28 04:40
> Hi @qnm, thanks for your bug report.
> 
> First of all: can we confirm that the query you run on the table is also running on BigQuery? In which case, can you share the GraphQL schema for that table? For example, we've been testing with a table that looks like this:
> <img alt="image" width="230" src="https://user-images.githubusercontent.com/6302310/262689234-1e3dab31-f5c1-4302-a574-be6fdd98fef5.png">
> 
> We want to verify that the table is being interpreted as a BigQuery source - if it is, both the native query and the regular tracked table should output strings for numeric fields, rather than specific integer or float types. This is how they are presented to us from BigQuery (which supports 8-byte types), and we preserve this representation because the GraphQL spec only supports 4-byte types. In short, if we converted the strings to numeric types, we'd risk losing some information in the process.

Ah - I have to apologise. I had another table with the same name on a postgres database.

Confirming that the tracked table query also has strings:

![image](https://github.com/hasura/graphql-engine/assets/5343/846002a7-d3fe-459f-9ad8-b7e20082db22)

**Comment by KayakinKoder** [comment] 2023-09-06 20:22
We noticed this same behavior last year, and got this response from David V. at Hasura:

> It turns out this is not a Hasura bug and is expected, though it could be (and will be) better documented.  The Google BigQuery API returns numeric types as JSON Strings so that when consumed by Javascript there will be no loss of precision.  Note that this is not a limitation inherent in JSON (for which number types are arbitrary precision) but of Javascript which is probably the biggest consumer of JSON.  In deference to that, the Google API designers chose to represent BigQuery numeric values in results as strings.  Hasura chooses to preserve those values as Strings as that honors the semantics of the underlying API most cleanly.  So, there's no "fix" from Hasura on this, I'm afraid, other than to improve the documentation on the issue.

**Comment by i-am-tom** [comment] 2023-11-22 13:32
Closing this as I think @dventimihasura and I both said the same thing - this is the safest way to handle responses from BigQuery without risking information loss, so we play it safe and transport numbers as strings!

**Closed by i-am-tom** 2023-11-22 13:32 UTC
Labels: k/bug, t/native-dbs
