### ISSUE TITLE
Metadata export output success but no metadata exported

### ISSUE THREAD

**Issue by tapeo** [hasura/graphql-engine#6825] opened 2021-04-27 09:30 UTC
Hasura version: v2.0.0-alpha.7

It works exporting metadata manually from console.

Follows the command output.

> hasura metadata export --admin-secret "admin" --log-level DEBUG
DEBU global config file exisits, verifying contents 
DEBU global config is pre-set to &cli.GlobalConfig{UUID:"e871ba60-7561-44f3-9dc9-9770073ec101", EnableTelemetry:true, ShowUpdateNotification:true, CLIEnvironment:"default"} 
DEBU global config: uuid: e871ba60-7561-44f3-9dc9-9770073ec101 
DEBU global config: enableTelemetry: true         
DEBU global config: showUpdateNotification: true  
DEBU global config: cliEnvironment: default       
DEBU cannot get config information from server, this might be because config API is not enabled: json: cannot unmarshal object into Go struct field HasuraServerInternalConfig.jwt of type string 
DEBU graphql engine endpoint: http://localhost:1000 
DEBU graphql engine admin_secret: admin           
DEBU versions: cli: [v2.0.0-alpha.7] server: [v2.0.0-alpha.7] 
DEBU compatibility check: [true] older cli version might not be compatible with latest server apis, please update cli 
DEBU server: uuid: 99a877ed-84b6-4c64-937d-41fc670ea4f6 
DEBU output: {"success":true,"output_file_path":"/var/folders/pd/yskxvy0n3sbg271mhd82jr6h0000gn/T/082327605.json"}  command="sdl to"
DEBU reading functions node from metadatanode not found:
    github.com/goccy/go-yaml.init
        /go/pkg/mod/github.com/goccy/go-yaml@v1.8.8/error.go:12 
DEBU reading functions node from metadatanode not found:
    github.com/goccy/go-yaml.init
        /go/pkg/mod/github.com/goccy/go-yaml@v1.8.8/error.go:12 
INFO Metadata exported                            
DEBU telemetry: beamed                             fields.time=641.533042ms isError=false

**Comment by scriptonist** [comment] 2021-04-27 09:53
@tapeo you don't see any changes in your project directory after a `metadata export` ?

**Comment by tapeo** [comment] 2021-04-27 10:10
Ok new info available: now if I do a `metadata export` and a `metadata apply` to my production endpoint, it works.
I thought it didn't work because when I applied the metadata exported to a new created Hasura instance the first time, it did't applied them so I thought that `metadata export` didn't works. 
But maybe I can create a new issue for that. Thank you!

**Comment by scriptonist** [comment] 2021-04-27 10:22
@tapeo Thanks, can we close this issue if you feel the problem is resolved?

Feel free start a [Discussion](https://github.com/hasura/graphql-engine/discussions) or open an issue if you run into problems.

**Comment by tapeo** [comment] 2021-04-27 10:24
Yes! I will start a discussion or create a new issue if I will encountering the problem again!

**Closed** 2021-04-27 10:29 UTC
Labels: c/cli, k/question
