### ISSUE TITLE
Calculated field is not present in Boolean expression schema

### ISSUE THREAD

**Issue by alukos** [hasura/graphql-engine#4235] opened 2020-03-30 07:07 UTC
graphql-engine v.1.1.1
After adding a calculated field, the field appears in the query schema, but not in the filter type
![screenshot_20200330_095851](https://user-images.githubusercontent.com/1665776/77884647-228f3100-726e-11ea-98bf-4f3a92b5abaf.png)
![screenshot_20200330_095912](https://user-images.githubusercontent.com/1665776/77884661-28851200-726e-11ea-96c3-1e2be20254e2.png)

**Comment by karthikvt26** [comment] 2020-03-30 07:18
Closing this. Dupe of #3772

**Closed by karthikvt26** 2020-03-30 07:18 UTC
