### ISSUE TITLE
DB schema loading failed: postgres-error : more than one row returned by a subquery used as an expression

### ISSUE THREAD

**Issue by edmundmunday** [hasura/graphql-engine#3778] opened 2020-01-26 04:28 UTC
Was working in the Hasura UI building DB schema. Then randomly started getting this error.

```json
{
  "statement": "\nselect \n  COALESCE(\n    json_agg(\n      row_to_json(info)\n    ), \n    '[]' :: JSON\n  ) AS tables \nFROM \n  (\n    select \n      ist.table_schema, \n      ist.table_name,\n      ist.table_type,\n      obj_description(\n        (\n          quote_ident(ist.table_schema) || '.' || quote_ident(ist.table_name)\n        ):: regclass, \n        'pg_class'\n      ) AS comment, \n      COALESCE(json_agg(\n        DISTINCT row_to_json(is_columns) :: JSONB || jsonb_build_object(\n          'comment',\n          (\n            SELECT \n              pg_catalog.col_description(\n                c.oid, is_columns.ordinal_position :: int\n              ) \n            FROM \n              pg_catalog.pg_class c \n            WHERE \n              c.oid = (\n                SELECT \n                  (\n                    (\n                      quote_ident(ist.table_schema) || '.' || quote_ident(ist.table_name)\n                    ):: text\n                  ):: regclass :: oid\n              ) \n              AND c.relname = is_columns.table_name\n          )\n        )\n      ) FILTER (WHERE is_columns.column_name IS NOT NULL), '[]' :: JSON) AS columns,\n      COALESCE(json_agg(\n        DISTINCT row_to_json(is_triggers) :: JSONB || jsonb_build_object(\n          'comment',\n          (\n            SELECT description FROM pg_description JOIN pg_trigger ON pg_description.objoid = pg_trigger.oid \n            WHERE tgname = is_triggers.trigger_name\n          )\n        )\n      ) FILTER (WHERE is_triggers.trigger_name IS NOT NULL), '[]' :: JSON) AS triggers,\n      row_to_json(is_views) AS view_info\n    FROM \n      information_schema.tables AS ist \n      LEFT OUTER JOIN information_schema.columns AS is_columns ON \n        is_columns.table_schema = ist.table_schema \n        AND is_columns.table_name = ist.table_name \n      LEFT OUTER JOIN information_schema.views AS is_views ON is_views.table_schema = ist.table_schema\n        AND is_views.table_name = ist.table_name\n      LEFT OUTER JOIN information_schema.triggers AS is_triggers ON \n        is_triggers.event_object_schema = ist.table_schema AND \n        is_triggers.event_object_table = ist.table_name\n    where (ist.table_schema='public') \n    GROUP BY \n      ist.table_schema, \n      ist.table_name,\n      ist.table_type,\n      is_views.*\n  ) AS info\n",
  "prepared": false,
  "error": {
    "exec_status": "FatalError",
    "hint": null,
    "message": "more than one row returned by a subquery used as an expression",
    "status_code": "21000",
    "description": null
  },
  "arguments": []
}
```

Hasura UI could no longer see any of the Postgres tables, all the relationships still seemed functional in GraphiQL.

Attempted to modify meta-data manually to remove any recently created relationships that might be causing the error, even cleared all metadata to start fresh, did not resolve the issue.

Was going to try to roll back the most recent migration but could not figure out how to do this when running Hasura via Docker-compose.

**Comment by lexi-lambda** [comment] 2020-01-27 21:08
It isn’t immediately clear from the error message what the problem is, so could I ask you to provide a little more information? What version of graphql-engine are you running, and is it possible to reproduce the issue starting from a fresh database schema?

**Comment by 0x777** [comment] 2020-01-28 04:38
@rikinsk This looks like a query that the console issues?

**Comment by rikinsk** [comment] 2020-01-28 10:40
> This looks like a query that the console issues?

It is.

@edmundmunday As @lexi-lambda mentioned, we will need some way to reproduce this to be able to debug it. 

As the error suggests, one of the sub-queries in the query is returning multiple rows where 1 was expected but we can't tell which one exactly from the error message.

**Comment by edmundmunday** [comment] 2020-02-03 22:39
@rikinsk - Unfortunately I'm not able to recreate it, I was able to solve the issue by generating a new migration for the DB in its current state and then rebuilding the DB based on that migration.

Looking back on it, I suspect I might have created some kind of circular foreign key references with records referencing each other in a loop.

**Comment by lexi-lambda** [comment] 2020-02-04 01:41
Since you’re not able to reproduce it, I’m going to close this issue, but feel free to reopen it if the problem happens again!

**Closed by lexi-lambda** 2020-02-04 01:41 UTC
Labels: c/console 🖥️, support/needs-more-info

**Comment by siddhatiwari** [comment] 2020-12-15 05:09
I ran into this error after I tried applying migrations and metadata to a postgres db that was already seeded with tables and data.

The issue turned out to be these statements in the seed dump file -
```
COPY hdb_catalog.hdb_custom_types (custom_types) FROM stdin;
{"enums": [], "objects": [{"name": "SampleOutput", "fields": [{"name": "accessToken", "type": "String!", "arguments": null, "description": null}], "description": null, "relationships": null}], "scalars": [], "input_objects": [{"name": "SampleInput", "fields": [{"name": "username", "type": "timestamptz", "description": null}, {"name": "password", "type": "String!", "description": null}], "description": null}]}
{"enums": [], "objects": [{"name": "SampleOutput", "fields": [{"name": "accessToken", "type": "String!", "arguments": null, "description": null}], "description": null, "relationships": null}], "scalars": [], "input_objects": [{"name": "SampleInput", "fields": [{"name": "username", "type": "timestamptz", "description": null}, {"name": "password", "type": "String!", "description": null}], "description": null}]}
{"enums": [], "objects": [{"name": "SampleOutput", "fields": [{"name": "accessToken", "type": "String!", "arguments": null, "description": null}], "description": null, "relationships": null}], "scalars": [], "input_objects": [{"name": "SampleInput", "fields": [{"name": "username", "type": "timestamptz", "description": null}, {"name": "password", "type": "String!", "description": null}], "description": null}]}
\.
```

The 3 duplicate entries made `select custom_types from hdb_catalog.hdb_custom_types` return more than 1 row, causing `coalesce((select custom_types from hdb_catalog.hdb_custom_types), '{}')` to fail when hasura was running the migrations.

I removed 2 rows in the seed dump file so it looked like below, reset the db, dumped the seed data, ran hasura migrations, and then there were no errors.
```
COPY hdb_catalog.hdb_custom_types (custom_types) FROM stdin;
{"enums": [], "objects": [{"name": "SampleOutput", "fields": [{"name": "accessToken", "type": "String!", "arguments": null, "description": null}], "description": null, "relationships": null}], "scalars": [], "input_objects": [{"name": "SampleInput", "fields": [{"name": "username", "type": "timestamptz", "description": null}, {"name": "password", "type": "String!", "description": null}], "description": null}]}
\.
```

Not sure if this fix applies to all `more than one row returned by a subquery used as an expression` errors, but it worked for me in this case

**Comment by albertoal** [comment] 2021-12-10 17:18
Thanks for sharing @siddhatiwari ! I hit the exact same issue after also mistakenly restoring a DB dump into the wrong DB and removing the duplicate entries from `hdb_catalog.hdb_custom_types` did the trick for me. Thank you so much!
