### ISSUE TITLE
`hasura deploy` fails for trigger changes + migration: "event trigger ... does not exist"

### ISSUE THREAD

**Issue by RomainEndelin** [hasura/graphql-engine#9093] opened 2022-10-10 00:18 UTC
### Version Information

Server Version: 2.9.0
CLI Version (for CLI related issue): 2.9.0 - 2.12.0

### Environment

OSS

### What is the current behaviour?

`hasura deploy` fails when applying dependant changes on `metadata` and `migrations`: rename a DB column and modify triggers related to that column.
```
ERRO applying metadata failed
FATA[0004] operation failed: error applying metadata 
{
  "code": "not-exists",
  "error": "event trigger \"new_echo_name\" does not exist",
  "path": "$.args"
} 
```

### What is the expected behaviour?

`hasura deploy` should apply both `metadata` and `migration` without failure, and metadata should be consistent.

### How to reproduce the issue?

Setup:
1. Create a table `dummy_table`, with a column `original_name`
2. Add an event trigger `echo_name` listening to `dummy_table.original_name` on update
3. Make sure you're up-to-date: `hasura deploy`

Reproduce steps (_Steps 1 to 3 should only be file updates, not executed_):
1. Edit `metadata`: remove the `echo_name` trigger
2. Add a migration to remove the `dummy_table.original_name` to `dummy_table.new_name`
3. Edit `metadata`: re-introduce a `new_echo_name` trigger, listening to `dummy_table.new_name`
4. Run `hasura deploy`

### Screenshots or Screencast

N/A

### Please provide any traces or logs that could help here.

N/A

### Any possible solutions?

Workaround: replace `hasura deploy` by these commands:
```
hasura migrate apply
hasura metadata reload
hasura metadata ic drop
hasura metadata apply
```

### Can you identify the location in the source code where the problem exists?

No

### If the bug is confirmed, would you be willing to submit a PR?

No (I'm not familiar with the codebase)

### Keywords

Hasura Deploy
Event Trigger

**Comment by Luca8991** [comment] 2022-10-19 19:41
> Workaround: replace `hasura deploy` by these commands:
> 
> ```
> hasura migrate apply
> hasura metadata reload
> hasura metadata ic drop
> hasura metadata apply
> ```

It worked for me! Thanks @RomainEndelin and waiting for the bug fix!

**Comment by tirumaraiselvan** [comment] 2022-11-30 12:58
Dupe of https://github.com/hasura/graphql-engine/issues/8624, we are working on the fix.

**Closed by tirumaraiselvan** 2022-11-30 12:58 UTC
Labels: k/bug, t/product-platform
