### ISSUE TITLE
Type Generation of Views

### ISSUE THREAD

**Issue by adas98012** [hasura/graphql-engine#8868] opened 2022-08-25 17:48 UTC
### Discussed in https://github.com/hasura/graphql-engine/discussions/8854

<div type='discussions-op-text'>

<sup>Originally posted by **zephaniahong** August 25, 2022</sup>
Hi!
I am having an issue updating fields of a custom view using the Hasura Explorer vs on my own NextJs app which uses type generation to generate the types from Hasura.

I have a table `Event` with fields such as `id, userId, title, budget, description.` However, as I want to only give access of` budget, description` to the user which this event belongs to, I turned off the column select permission of `budget, description` on the `Event` table. I also created a View called `own_event` which has the fields `id, budget, description`. I then created an object relationship between `Event` and `own_event` by referencing the `userId` from the `Event` table to the `id` of the `own_event` view with the relationship name of `private_details`

The problem I'm facing is in 2 fold:
1. Using the Hasura Explorer, the `events_set_input` type does not contain the `private_details` field, but instead directly contains `description, budget`.
2. On my NextJs app, after generating the types, my `events_set_input` contains neither the `private_details` field nor the `description, budget` BUT the `events_insert_input` does indeed contain the private_details field.

I'm puzzled as to why the insert and set type are different even though I've double checked that the permissions I've set on my tables are all correct.

Thank you!
</div>

**Comment by zephaniahong** [comment] 2022-08-26 06:41
Technologies: Hasura Cloud, NextJs

Reproduction Steps:
1. Create `events` table with fields `id, userId, title, budget, description`
2. Create an `own_event` view by running: 
```CREATE OR REPLACE VIEW "public"."own_event" AS 
 SELECT events.userid,
    events.description,
    events.budget,
    events.id
   FROM events;
3. Configure an object relationship called private_details referencing the own_event view from id to id
4. Permissions for the event table
    - insert & update: 
        - row permissions:
            - {"userid:{"_eq":"X-Hasura-User-Id}}
        - column permissions
            - allow everything except budget and description
     - select
         - row permissions:
             - no checks
         - column permissions
             - allow everything except budget and description
5. Permissions for own_event view
    - insert & update & select
        - row permissions
            - {"userid:{"_eq":"X-Hasura-User-Id}}
        - column 
            - allow only budget and description
6. run `yarn run generate`
7. The problem is with the generated types (attached screenshots below). Both events_insert_input & events_set_input have differing types (missing `private_details`) even though both have the same permissions.

Thank you!

![events](https://user-images.githubusercontent.com/33389011/186838673-4ecdd91e-1c59-43e2-90ee-9ee113226ebe.png)
![events_insert_input](https://user-images.githubusercontent.com/33389011/186838675-9c42673d-9dda-468f-ab44-a0f1d2786ccc.png)
![events_set_input](https://user-images.githubusercontent.com/33389011/186838678-e02a4927-64d5-4512-9403-2ad7e892d2aa.png)

**Comment by plcplc** [comment] 2024-01-04 09:53
Because this issue has not attracted significant attention for several months I'm going to close it.

Feel free to reopen if the issue is still relevant for you.

**Closed by plcplc** 2024-01-04 09:53 UTC
