### ISSUE TITLE
[sql-server] Support event triggers on SQL Server

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#7075] opened 2021-06-17 11:02 UTC
Add support for [event triggers](https://hasura.io/docs/latest/graphql/core/event-triggers/index.html) on SQL Server.

**Comment by jmarbutt** [comment] 2021-08-25 15:53
What is the time frame for this?

**Comment by ampsarfraz** [comment] 2021-11-08 12:38
Hello any update on this features for SQL Server?

**Comment by jmarbutt** [comment] 2021-11-08 17:08
@tirumaraiselvan What is the latest on this, we are about a month past the 3-4 week estimate.

**Comment by ericwilhite** [comment] 2021-11-12 15:38
Would love to see some movement on this. We need to build out some notification infrastructure soon and event triggers would make that really easy to manage.

**Comment by m4ttheweric** [comment] 2022-02-08 17:41
@tirumaraiselvan You mentioned last August that this would be available in 3-4 weeks. What's the status?

**Comment by arjunyel** [comment] 2022-02-08 20:16
Hi friends, 7 days ago a PR for this feature opened up in our internal repo and is now under going testing, I am not sure when it will release but it is actively being worked on

**Comment by jmarbutt** [comment] 2022-03-15 23:43
Thanks @arjunyel for the update, can't wait for this feature!

**Comment by tirumaraiselvan** [comment] 2022-04-26 09:23
Dupe of https://github.com/hasura/graphql-engine/issues/7228

**Closed by tirumaraiselvan** 2022-04-26 09:23 UTC
Labels: a/eventing/data-triggers
