### ISSUE TITLE
Setting default sorting order for graphql responses

### ISSUE THREAD

**Issue by revskill10** [hasura/graphql-engine#2073] opened 2019-04-25 21:52 UTC
When create table or modifying table, we should allow specifying default sorting columns.

For example, all my tables have `created_at` columns, i'd love to set `created_at` as default order when querying.

Multiple columns default sorting should be allowed, too.

**Comment by rikinsk** [comment] 2019-07-09 13:46
@revskill10 I am not sure I quite understand the request. 

> i'd love to set created_at as default order when querying.

What do you mean by querying here exactly? Do you mean the default sort should happen in the console browse rows or the GraphQL API queries?

**Comment by revskill10** [comment] 2019-07-11 09:23
@rikinsk The problem is simple.

WIth current query

```
users {
id
first_name
last_name
created_at
}
```

What will be the order of results ?

In this case, i'd love to force the default order returning by query above to be set to `created_at: asc_nulls_last`, for example.

**Comment by rhyslbw** [comment] 2020-04-14 18:16
Is there a workaround for this? There are natural situations that really require sensible defaults

**Comment by rikinsk** [comment] 2020-04-15 09:14
@rhyslbw I can think of a couple of workarounds that you could use depending on your setup:
- If you are in control of the client of your API, you could add some middleware on your client to intercept and append the default `order_by` expression to your queries. 
- You could create a postgres view of your table with the sort order defined and query that instead. 
  For example: 
  ```sql
  CREATE VIEW "ordered_users" AS SELECT * FROM "users" ORDER BY "created_at" ASC
  ```

**Comment by rhyslbw** [comment] 2020-04-15 13:14
Thanks @rikinsk . I'm actually fronting Hasura with another GraphQL server to produce a refined public-facing model, that delegates the complete query for Hasura to resolve if accepted by validation rules. I did investigate the middleware solution for another requirement, but at the time seemed counterproductive and tedious to parse and manipulate the query when we can just demand more explicit fetching. Do you know of any tooling that might make this more appealing?

I'll see what I can achieve with the postgres schema option, as that would be the best solution here

**Comment by rikinsk** [comment] 2020-04-15 13:51
I cannot think of any specific tooling more helpul than the usual graphql libraries used to parse GraphQL queries. Maybe you could ask the Hasura community if they have any smarter solutions. You can join our discord server via https://discord.gg/vBPpJkS if you havent already :)

**Comment by manasag** [comment] 2023-12-29 05:16
This issue has not attracted significant attention for a long period of time, and since alternatives are available, we are closing this.
Please feel free to reopen if the issue is still relevant for you.

**Closed by manasag** 2023-12-29 05:16 UTC
Labels: c/server, k/ideas
