### ISSUE TITLE
Request feature user-management

### ISSUE THREAD

**Issue by Leakmonyta** [hasura/graphql-engine#996] opened 2018-11-08 03:43 UTC

**Comment by 0x777** [comment] 2018-11-08 06:38
@Leakmonyta Can you elaborate a bit? What are the features that you are looking for?

**Comment by richcorbs** [comment] 2018-12-07 03:18
For me, username/password or email/password authentication would be a great feature to add!

Also, file upload via mutation (to S3 or DO Spaces or local storage) would be absolutely AMAZING.

**Comment by zicklag** [comment] 2020-12-19 01:06
Best option I know of right now is https://github.com/nhost/hasura-backend-plus.

Also, kind of a duplicate ( though it doesn't discuss editing users in the console specifically ): https://github.com/hasura/graphql-engine/issues/5204.

**Comment by manasag** [comment] 2023-12-27 12:33
We are closing this issue, as it has not attracted significant attention for a long period of time, and also because user management in Console is not planned in the near roadmap. We will suggest Hasura Cloud as a better option for user management related requirements.
Please feel free to reopen if the issue is still relevant for you.

**Closed by manasag** 2023-12-27 12:33 UTC
Labels: k/ideas
