### ISSUE TITLE
ENHANCEMENT: Support for hierachical roles or multiple roles to a user

### ISSUE THREAD

**Issue by fomenta** [hasura/graphql-engine#3491] opened 2019-12-04 19:47 UTC
Our application defines lots of rules to apply to each users. Having a flat role model makes it very difficult to maintain. We are in need of having either:

* Multi-level roles (role inheritance).

Or:

* Assign multiple roles to a user.

Or both. I was checking the documentation about roles in Hasura and it states hierarchical roles are currently not supported:

https://docs.hasura.io/1.0/graphql/manual/auth/authorization/roles-variables.html
![image](https://user-images.githubusercontent.com/2394742/70175170-3356de00-16a4-11ea-92a9-d6c762e400af.png)

**Comment by lexi-lambda** [comment] 2019-12-17 17:42
I think this is a duplicate of #877. It’s something we definitely want to support and are currently looking into, but it isn’t something we have a concrete plan for just yet.

**Comment by pcmaffey** [comment] 2019-12-17 18:37
@lexi-lambda Do you have any recommended workarounds for the time being? 

eg. Adding roles as flags on the user object somewhere, and then looking up those permissions as custom checks on a single `user` role. So the custom check would look like:
```
{
  "org": {
    "org_users": {
      "_and": [
        { "user_id": { "_eq": "X-Hasura-User-Id" } },
        {
          "_or": [
            { "isRole1": { "_eq": "true" } },
            { "isRole2": { "_eq": "true" } }
          ]
        }
      ]
    }
  }
}
```

Would this work? Would this kind of lookup on every action cause a big performance hit?

**Comment by tirumaraiselvan** [comment] 2019-12-18 12:41
Dupe of #877

**Closed by tirumaraiselvan** 2019-12-18 12:41 UTC
Labels: c/server
