### ISSUE TITLE
[Bug] Subscriptions are idle after Postgres restarts

### ISSUE THREAD

**Issue by pwliwanow** [hasura/graphql-engine#5099] opened 2020-06-16 01:27 UTC
Hey, thanks for your work and for the product, it really does make life easier. 

I've observed a bug with subscriptions: when subscription is active and Postgres gets restarted, the subscription stays active, but it doesn't receive any new updates. 

**Steps to reproduce:**
1. Create table in Postgres: `create table users(id serial primary key, name text not null);`
2. Insert a record to the table: `insert into users(name) values ('Anne');`
3. Track the table in hasura
4. Start subscription from Hasura UI with: 
```
subscription {
  users {
    id
    name
  }
}
```
5. To verify that subscription indeed is acive, insert some more data: `insert into users(name) values ('Jack');`. Latest update from subscription should return two rows.
6. Restart Postgres (note that subscription is still active)
7. When Postgres is running again insert another record: `insert into users(name) values ('Mike');`

**Observed result:** 
Subscription doesn't push an update

**Expected result:** 
Hasura should recover and return newest update to the active subscription 
**or:** 
Hasura should close active subscription when Postgres gets unreachable

**Comment by michaelAtCoalesce** [comment] 2023-06-07 18:51
is anyone working on this? this seems like a pretty bad issue where subscriptions don't get new data.

**Comment by krushanbauva** [comment] 2023-06-22 07:15
Hi @pwliwanow, I am not able to reproduce this locally on the latest version.
I have my postgres instance running in a docker. I can see that subscriptions are able to fetch new updates on inserting after a `docker restart`. And I can be sure the postgres instance has restarted because I see `postgres connection failed` in the logs when I restart the container.

What version are you running?

**Comment by tirumaraiselvan** [comment] 2023-06-26 07:38
Closing this as this is not expected by the architecture and we cannot repro it. Please comment again and reopen if you are able to repro.

**Closed by tirumaraiselvan** 2023-06-26 07:38 UTC
Labels: support/needs-action, c/subscriptions ✋
