### ISSUE TITLE
support multiple JWT secrets

### ISSUE THREAD

**Issue by kkshyu** [hasura/graphql-engine#2208] opened 2019-05-16 23:20 UTC
for admin secret, we can set in the environment variable: `HASURA_GRAPHQL_ADMIN_SECRET` and pass `x-hasura-admin-secret` in header to authorize the permission.

in my scenario, i have two applications sharing the same Hasura API server. Theses two applications have their own JWT secret (specifically different jwk_url). I don't want to duplicate the Hasura server to handle these two applications. 

is it possible to set multiple JWT secrets into Hasura server?
or pass the jwt secret to Hasura in header like `x-hasura-jwt-secret`?
or specifically select the `jwk_url` in run-time?

**Comment by revskill10** [comment] 2019-05-17 00:10
I made a proposal on these problems here: https://github.com/hasura/graphql-engine/issues/1995

I think it relates to your issue here.

**Comment by kkshyu** [comment] 2019-05-17 00:29
@revskill10 i've seen your proposal, it is related but i'm not sure whether the secret key management includes JWT secret or not.
because the format of JWT secret is `{type, jwk_url, claims_format}` and it is different from the other secret (`admin-secret` and secret key from your proposal are `string`)

if these two kind of formats can be merged, it will be great~

**Comment by kkshyu** [comment] 2019-05-17 00:34
one more different part is that:
in your proposal, it focuses on grant access to clients to access Hasura console as admin
but my scenario is that I have multiple auth server to grant access to clients to access Hasura API as user

**Comment by MeixnerTobias** [comment] 2019-05-17 11:21
I am looking for the same solution.
We run a multi-tenant app with ideally one Hasura instance to serve all tenants.
Every tenant is using a different Cognito user pool as a result the current implementation of HASURA_GRAPHQL_JWT_SECRET does not cover this use-case.
Ideally, I can think of 2 solutions here
1. We can assign a different jwt-secret based on a parameter in the header i.e. x-hasura-org-id
which then routes the jwt-secret based on the x-hasura-org-id
HASURA_GRAPHQL_JWT_SECRET: {
tenant1: tenant1Url
tenant2: tenant2Url
}
whereas tenant1 = x-hasura-org-id
2. Decode the jwt and route to a standard iss provided by the token (Cognito always has the same URL format)

**Comment by kkshyu** [comment] 2019-05-18 16:11
> I am looking for the same solution.
> We run a multi-tenant app with ideally one Hasura instance to serve all tenants.
> Every tenant is using a different Cognito user pool as a result the current implementation of HASURA_GRAPHQL_JWT_SECRET does not cover this use-case.
> Ideally, I can think of 2 solutions here
> 
> 1. We can assign a different jwt-secret based on a parameter in the header i.e. x-hasura-org-id
>    which then routes the jwt-secret based on the x-hasura-org-id
>    HASURA_GRAPHQL_JWT_SECRET: {
>    tenant1: tenant1Url
>    tenant2: tenant2Url
>    }
>    whereas tenant1 = x-hasura-org-id
> 2. Decode the jwt and route to a standard iss provided by the token (Cognito always has the same URL format)

Thanks for @MeixnerTobias explanations. These two methods are great!
My scenario is exactly the same as you. We also use multiple Cognito User Pools for the multi-tenant implementation and would like to share the same Hasura API server.
Currently, we can only write some scripts to launch docker container for Hasura after a new tenant registered. We don't like this method and would like to configure once and use for all.

How about sending the jwt-secret on header for each request?
```
{
    'x-hasura-jwt-secret': '{"type": "SHA256", ...}'
}
```
if we send it from the browser, is it unsecured? 
i thought the jwk can be public

**Comment by MeixnerTobias** [comment] 2019-05-19 06:10
Yes, the format of of jwks urls follow always the same format under .well-known which we can consider public, so I setting it in the http header can work too.

**Comment by cthurston** [comment] 2019-08-06 15:46
My need case for this feature is for firebase. If you create a custom token through firebase it is signed with a different issuer (service account) and requires a different JWT_SECRET. Would be great if I could just add an array of acceptable secrets to try.

```
[
  {
    "type":"RS256",
    "jwk_url": "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com",
    "audience": "<firebase-project-id>",
    "issuer": "https://securetoken.google.com/<firebase-project-id>"
  },
  {
    "type": "RS256",
    "jwk_url": "https://www.googleapis.com/service_accounts/v1/jwk/firebase-adminsdk-xxxxx%40<firebase-project-id>.iam.gserviceaccount.com",
    "audience": "<firebase-project-id>",
    "issuer": "firebase-adminsdk-xxxxx@<firebase-project-id>.iam.gserviceaccount.com",
  }
]
```

**Comment by kesavkolla** [comment] 2020-01-05 11:11
My usecase also very similar.  I've single keycloak server where each tenant is one single realm.  I want to use single hasura server for all tenants.  For keycloak jwks url for each tenant/realm is different.  I want an ability to inject the x-hasura-org-id in jwks url.

**Comment by smunozp** [comment] 2020-03-30 16:32
Hello

There is any update in this? We have the same situation, we want to serve multitennant with the same server

**Comment by NorthJaw** [comment] 2020-06-07 13:08
This can be done using the webhook mode instead of the jwt mode for authentication in Hasura: https://hasura.io/docs/1.0/graphql/manual/auth/authentication/webhook.html

The jwt token along with other headers are passed by Hasura to this webhook which will handle the authentication part and sends back just the session variables to Hasura to use.

A sample auth webhook for Firebase has been provided in the same docs page: https://github.com/hasura/graphql-engine/blob/master/community/boilerplates/auth-webhooks/nodejs-firebase/firebase/firebaseHandler.js

**Comment by Nomad-Go** [comment] 2020-07-24 20:59
> This can be done using the webhook mode instead of the jwt mode for authentication in Hasura: https://hasura.io/docs/1.0/graphql/manual/auth/authentication/webhook.html
> 
> The jwt token along with other headers are passed by Hasura to this webhook which will handle the authentication part and sends back just the session variables to Hasura to use.
> 
> A sample auth webhook for Firebase has been provided in the same docs page: https://github.com/hasura/graphql-engine/blob/master/community/boilerplates/auth-webhooks/nodejs-firebase/firebase/firebaseHandler.js

I would call this a workaround. No one wan't that extra round trip. Every millisecond counts.

**Comment by osaxma** [comment] 2021-01-16 15:22
@cthurston did you find a way around this? I'm having the exact problem (i.e., multiple firebase apps + tokens generated from the admin sdk).

**Comment by cthurston** [comment] 2021-01-17 03:23
@osaxma  Found this:
 https://firebase.google.com/docs/auth/web/custom-auth
 
 Then wrote this:
 ```javascript
const axios = require('axios')

async function firebaseExchangeToken (token, apiKey) {
  return axios.request({
    url: `https://identitytoolkit.googleapis.com/v1/accounts:signInWithCustomToken?key=${apiKey}`,
    headers: {
      'Content-Type': 'application/json',
    },
    method: 'POST',
    data: {
      token,
      returnSecureToken: true,
    },
  })
}

module.exports = firebaseExchangeToken
```

Then I exchange my tokens to use the project id that I have registered with my hasura instance.

**Comment by robnewton** [comment] 2021-01-21 19:20
Being able to have more than one JWT pub cert at a time would prove helpful for migrating from one identify system to another without disruption. Is there any chance what @cthurston suggested will be taken up by the Hasura team and implemented? I'd like to be able to plan accordingly one way or another.

**Comment by m4rcelofs** [comment] 2021-01-22 13:59
> Being able to have more than one JWT pub cert at a time would prove helpful for migrating from one identify system to another without disruption. Is there any chance what @cthurston suggested will be taken up by the Hasura team and implemented? I'd like to be able to plan accordingly one way or another.

That's exactly our current situation - we need to support both Firebase and Auth0 for a while. Having `HASURA_GRAPHQL_JWT_SECRET` accept an array of configs would certainly make our life easier - the only way out currently seems to use webhook auth? That's not exactly great.

**Comment by brunobraga95** [comment] 2021-02-04 08:00
+1

**Comment by andrewbeckman** [comment] 2021-03-17 23:42
@rikinsk I noticed you tagged this a while ago. Any updates on this issue?

**Comment by keremgocen** [comment] 2021-04-01 21:09
we need this as well:) My team wants to re-use the same Hasura API layer for 2 separate user pools, I guess for now we can make do with using separate groups within the same pool. It sounds logical to be able to authenticate Hasura from different auth sources and not deploy one for each.

**Comment by andrewbeckman** [comment] 2021-04-01 21:48
@keremgocen in case it's helpful, I talked to Hasura support and confirmed that we have 2 options currently: 1) use [webhooks](https://hasura.io/docs/latest/graphql/core/auth/authentication/webhook.html) or 2) create a second Hasura project pointed at the same database. Importantly, the second option requires both projects to be on Hasura GraphQL Engine version 2.0 or greater. I ended up creating a second project to avoid the downsides of webhooks. Let me know if you have any questions!

**Comment by keremgocen** [comment] 2021-04-01 22:07
@andrewbeckman thanks that's helpful, I now just need to convince my team that it's not possible to create a single Cognito user pool as a proxy and link multiple pools to it from separate domains in order to use a single `jwt_url`.

I don't think webhooks will work for us. We don't have a lot of users yet and we will possibly never end up paying for the round-trip if we use Lambda for the webhook, but the fact that each request needs to make that round-trip does not feel right to me as an engineer, while we have a better, more convenient way.

**Comment by andrewbeckman** [comment] 2021-04-01 22:34
> @andrewbeckman thanks that's helpful, I now just need to convince my team that it's not possible to create a single Cognito user pool as a proxy and link multiple pools to it from separate domains in order to use a single `jwt_url`.
> 
> I don't think webhooks will work for us. We don't have a lot of users yet and we will possibly never end up paying for the round-trip if we use Lambda for the webhook, but the fact that each request needs to make that round-trip does not feel right to me as an engineer, while we have a better, more convenient way.

My thoughts exactly. Even though it creates a bit of a headache to manage keeping the two projects in sync, I'd rather have the headache than degrade the experience for users.

**Comment by josephnaber** [comment] 2021-05-19 19:41
We are also seeking a way to integrate with multiple AWS cognito user pools. we would like to see HASURA_GRAPHQL_JWT_SECRET with an array of objects, rather than a single object

**Comment by andrewbeckman** [comment] 2021-07-07 16:58
@vaishnavigvs @0x777 is there an ETA for this feature?

**Comment by tirumaraiselvan** [comment] 2021-09-09 10:50
Hey folks, is it okay to assume that the issuer will be different for each of the JWT secrets?

**Comment by solomon-b** [comment] 2021-12-03 03:42
> @vaishnavigvs @0x777 is there an ETA for this feature?

The feature has been merged into HGE's main branch! Next, Infra needs to make a small update for Cloud support.

**Comment by ota42y** [comment] 2021-12-28 05:28
Hello!
I find this feature very important and eagerly awaiting.

This feature merged master, but it has been reverted by[this commit](https://github.com/hasura/graphql-engine/commit/4121c1dd3daceda87ca6274f0e19ed7dbd4928fa), and it doesn't seem to be in v2.1.1. 
Did something go wrong?

**Comment by carterventures** [comment] 2022-01-01 22:30
We have the same issue regarding the use of Keycloak and multiple realms to handle multi-tenant auth. Would be great to assign a tenant to the audience field and use that for selecting the appropriate key (and get audience validation in the process).

**Comment by cassus** [comment] 2022-01-04 08:37
I found a possible workaround in blog post about how we could combine JWKS URLs with a lambda function, and supposedly hasura supports multiple keys from a JWKS URLs. I haven't tried it yet.

https://adhikary.net/en/2021/09/27/hasura-jwks-jwt-w-multiple-auth0-tenants/

**Comment by solomon-b** [comment] 2022-01-06 23:05
Just a heads up to everyone. The feature revert is temporary and we are prioritizing a fix now. I'll update this issue when we are ready to merge it back in.

**Comment by vasily-suslov** [comment] 2022-01-21 06:33
Hello! any update on approximate ETA? Thank

**Comment by cassus** [comment] 2022-01-22 10:09
As a workaround I'm successfully using multiple JWT secrets with a JWKS url.

Based on this article: https://adhikary.net/en/2021/09/27/hasura-jwks-jwt-w-multiple-auth0-tenants/

**Comment by Shalashtein** [comment] 2022-02-10 11:16
This is indeed a much needed feature, I've got different apps for the customer side of things and the admin side, they use different Cognito User Pools, and I'd like to have just one Hasura instance to manage everything

**Comment by marsouin** [comment] 2022-03-02 10:52
Hi! any news on this? I am also using multiple Cognito User Pools... ;) thanks!

**Comment by AThilenius** [comment] 2022-03-03 21:44
A note to anyone lurking in this issue like me: **the JWKs URL workaround isn't a performance bottleneck**; Hasura calls the JWK URL once on startup then caches the value. Which is kind of ironic, because that seems like the only reason you would want to use a URL in the first place, to dynamically update keys 🤷‍♂️

Unrelated... I'm immensely impressed with Hasura, so kudos and love to the devs! A few warts (this and that Remote Schema "ACLs" aren't particularly useful) but the core GQL functionality is fantastic ❤️

**Comment by Nomad-Go** [comment] 2022-03-03 21:52
I consider our company an initial Hasura user. I first ran the image on EC2 in early 2019. @coco98 personally helped me debug some scalability issues over a zoom call. I still need this feature as I have to go multi cloud soon and I need a different auth workflow for Hardware. Amazing product, would not be where we are today with out them.

**Comment by bkniffler** [comment] 2022-03-10 21:26
Just in case anyone missed it, this feature was mentioned in last months email

<img width="589" alt="Bildschirmfoto 2022-03-10 um 22 24 00" src="https://user-images.githubusercontent.com/4349324/157757305-7bfdded6-9745-4736-823f-44f7640382ef.png">

**Comment by franzwilhelm** [comment] 2022-04-04 13:29
@tirumaraiselvan @sordina  any progress on this, as it's mentioned in the community call (https://youtu.be/8LRx3uVBzJg?t=1744), and is already available to cloud users. We are now considering doing a lot of workarounds to implement this on our own. Would be a shame if this feature is kept as a "pro" feature. What I imagine will happen is that people will start forking this repo and implement their own multiple jwt solution, so why not just release what you have to the world?

**Comment by madmod** [comment] 2022-04-14 23:09
When is this going to be available in Hasura Cloud?

**Comment by tirumaraiselvan** [comment] 2022-04-27 07:38
Hey folks, this is available in Hasura Cloud (v2.3 onwards). The docs are available here: https://hasura.io/docs/latest/graphql/cloud/security/multiple-jwt-secrets/

If you are not on Cloud, there is a simple workaround:

1. Create a new endpoint that combines the result of all your JWK providers.
2. Use this endpoint as the `jwk_url` in a single JWT Secret configuration.

**Closed by tirumaraiselvan** 2022-04-27 07:38 UTC
Labels: k/ideas, p/medium, a/authn

**Comment by cleivson** [comment] 2022-06-24 17:50
Does that mean this feature is not going to be ported to the on premises version?

**Comment by dlebech** [comment] 2022-08-25 09:46
We managed to make Hasura accept two types of Firebase tokens using the `jwk_url` suggestion. We use both Firebase session tokens (for service-side rendering) and client tokens (for calling the API from the browser) for authenticating with Hasura.

In order to make this work, we created a "dumb" Cloud Function that simply combines the results of the different Firebase JWT keys and returns them from a single endpoint. Then we can point `jwk_url` to this cloud function like @tirumaraiselvan suggests, and it works ok.

I have shared more instructions in this repository, I hope it helps someone: https://github.com/exitplanner/firebase-jwts

(Sidenote: It would be nice if the open source Hasura just supported multiple JWTs, but it seems clear by now that this is not going to happen, so if you have the infrastructure for it, the above is an almost-effortless version)

**Comment by stevehenderson** [comment] 2022-09-15 04:37
When trying to handle JWT from both Auth0 and Firebase (or Cloud Identity), you may run into an error:  

`"Could not verify JWT: Multiple JWTs found"`

The issue is that the [Auth0 suggested JWT](https://hasura.io/docs/latest/auth/authentication/jwt/#popular-providers-and-known-issues) documentation is specified as a key, where [Firebase suggested JWT](https://hasura.io/docs/latest/auth/authentication/jwt/#popular-providers-and-known-issues) is a json with `jwt_url`, `audience`, and `issuer`

I ended up solving this by using a `key`, `type`, and `issuer` for both:

```
[
    {
        "key": "-----BEGIN PUBLIC KEY----AUTH0PUBKEY-----END PUBLIC KEY-----",
        "type": "RS256",
        "issuer": "https://auth0-issuer-url-from-your-tenant.com/"
    },
    {
        "key": "-----BEGIN CERTIFICATE-----GOOGLE_FIREBASE_CERT-----END CERTIFICATE-----\n",
        "type": "RS256",
        "issuer": "https://securetoken.google.com/<your-project-id>"
    }
]
```

The first entry is the PUBLIC KEY  [Auth0 suggested JWT](https://hasura.io/docs/latest/auth/authentication/jwt/#popular-providers-and-known-issues) entry and corresponds to the official documentation **PLUS** an added "issuer" key that is the iss of your Auth0 tenant...if you don't know this, post one of your Auth0 JWT to [jwt.io](https://jwt.io) and look at `iss`

The second entry is a PUBLIC KEY copied from [https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com](https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com).  There are multiple public keys, so you need the `kid`   You can see this by pasting a firebase JWT in  [jwt.io](https://jwt.io) and looking at the decoded header.   Then use that key from google.

It's important that both keys retain their placement of newline symbols `\n`

**Comment by RexGalicie** [comment] 2022-09-27 16:10
@stevehenderson  Hey mate 
Did you manage to sort 

> When trying to handle JWT from both Auth0 and Firebase (or Cloud Identity), you may run into an error:
> 
> `"Could not verify JWT: Multiple JWTs found"`
> 
> The issue is that the [Auth0 suggested JWT](https://hasura.io/docs/latest/auth/authentication/jwt/#popular-providers-and-known-issues) documentation is specified as a key, where [Firebase suggested JWT](https://hasura.io/docs/latest/auth/authentication/jwt/#popular-providers-and-known-issues) is a json with `jwt_url`, `audience`, and `issuer`
> 
> I ended up solving this by using a `key`, `type`, and `issuer` for both:
> 
> ```
> [
>     {
>         "key": "-----BEGIN PUBLIC KEY----AUTH0PUBKEY-----END PUBLIC KEY-----",
>         "type": "RS256",
>         "issuer": "https://auth0-issuer-url-from-your-tenant.com/"
>     },
>     {
>         "key": "-----BEGIN CERTIFICATE-----GOOGLE_FIREBASE_CERT-----END CERTIFICATE-----\n",
>         "type": "RS256",
>         "issuer": "https://securetoken.google.com/<your-project-id>"
>     }
> ]
> ```
> 
> The first entry is the PUBLIC KEY [Auth0 suggested JWT](https://hasura.io/docs/latest/auth/authentication/jwt/#popular-providers-and-known-issues) entry and corresponds to the official documentation **PLUS** an added "issuer" key that is the iss of your Auth0 tenant...if you don't know this, post one of your Auth0 JWT to [jwt.io](https://jwt.io) and look at `iss`
> 
> The second entry is a PUBLIC KEY copied from https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com. There are multiple public keys, so you need the `kid` You can see this by pasting a firebase JWT in [jwt.io](https://jwt.io) and looking at the decoded header. Then use that key from google.
> 
> It's important that both keys retain their placement of newline symbols `\n`

hey @stevehenderson  
Did you manage that issue.
I faced same when use multiple issuers

**Comment by nosovk** [comment] 2022-12-21 22:08
It would be nice to have that feature in community edition, it helps to test multiple environments. Extremely useful when you stick to Firebase auth.

**Comment by vymarkov** [comment] 2022-12-21 22:10
> It would be nice to have that feature in community edition, it helps to test multiple environments. Extremely useful when you stick to Firebase auth.

+1 extremely useful feature
