### ISSUE TITLE
GraphiQL in console does not correctly handle jsob variables

### ISSUE THREAD

**Issue by dminkovsky** [hasura/graphql-engine#5055] opened 2020-06-10 18:40 UTC
Following from #5054: 

I am using 1.2.2 and have a mutation action defined as 

```
type Mutation {
  createAccount (
    username: String!
    password: String!
    device: jsonb
  ): CreateAccountOutput
}
```

Suppose this mutation:

```
mutation ($username: String!, $password: String!, $device: jsonb) {
  createAccount(username: $username, password: $password, device: $device) {
    userId
  }
}
```

When I run this mutation, #5054 requires that `$device` be at least an empty object in input variables. However, GraphiQL incorrectly highlights this as an error:

<img width="433" alt="Screen Shot 2020-06-10 at 2 35 53 PM" src="https://user-images.githubusercontent.com/218725/84305231-b2cbdb00-ab27-11ea-8fe1-c8442d932c4b.png">

**Comment by tirumaraiselvan** [comment] 2020-06-16 06:11
This is a dupe of https://github.com/hasura/graphql-engine/issues/4787

I think the issue is graphiql has no idea about custom scalars like `jsonb` and it expects string literals for custom scalars.

**Closed** 2020-06-16 06:11 UTC
