### ISSUE TITLE
Hasura console login failure

### ISSUE THREAD

**Issue by JosRoseboom** [hasura/graphql-engine#6389] opened 2020-12-24 09:20 UTC
**Version**

hasura/graphql-engine:pull5655-633f084f

**How to reproduce:**

- get the docker compose => wget https://raw.githubusercontent.com/hasura/graphql-engine/master/install-manifests/docker-compose-mysql-preview/docker-compose.yaml
- configure mysql
- start and check if console (http://localhost:8080/console) is working
- add env var HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
- go to http://localhost:8080/console and login
- you see the console for a second and then you are back at the login screen

**Why is this failing?**

Looking at the traffic after hitting the "Enter" button to log in:

<img width="1235" alt="Schermafbeelding 2020-12-24 om 10 11 22" src="https://user-images.githubusercontent.com/1628433/103077656-7ac24c00-45d0-11eb-88a4-7305590eef37.png">

First 7 queries are no problem, then the 8th one returns 401. Looking into the requests, I see that the first 7 (that succeed), have the _x-hasura-admin-secret_ header set to _myadminsecretkey_ . The 8th request misses this header, so it makes sense that this returns 401. 

Using the ModHeader Chrome extension to add the _x-hasura-admin-secret_ with _myadminsecretkey_ to all requests, the console works without a problem.

**Proposed solution**

add the  _x-hasura-admin-secret_ header to the 8th query (the one with "SELECT version();")

**Comment by tirumaraiselvan** [comment] 2020-12-24 13:09
Apologies for the trouble! And thanks for the analysis. The console does not support mysql preview yet: https://github.com/hasura/graphql-engine/issues/5828#issuecomment-707193439 . You are recommended to use GraphiQL separately (via `graphqurl` maybe) to try MySQL.

I am closing this as dupe of #5828

**Closed by tirumaraiselvan** 2020-12-24 13:09 UTC

**Comment by JosRoseboom** [comment] 2020-12-24 13:15
Thanks for the quick reply. I found #5828 in my search for a solution. The result for the user is the same here, but I belief the cause is different. Here, the cause is 1 of the queries missing a header, thereby giving 401. In #5828 , the response was 400 bad request. Therefore I considered it not a dupe and opened this issue.

**Comment by tirumaraiselvan** [comment] 2020-12-24 13:16
Ah, understood! Either way, the console is not supported yet so it would be best to keep one thread opened for "Support MySQL in console"
