### ISSUE TITLE
docs: updates docs for `_eq`, `_ne` operators to include a caveat for null values

### ISSUE THREAD

**Issue by sabuydee** [hasura/graphql-engine#2167] opened 2019-05-12 17:48 UTC
![image](https://user-images.githubusercontent.com/10388591/57585853-c9b09000-7517-11e9-8f20-0c0f7d7ffabe.png)

is_delete = false is have output
is_delete = null is not have output (should have output)

(Operators _eq, _in and _nin should have null in list  ?)

**Comment by dsandip** [comment] 2019-05-13 10:42
@0x777 For the described permission rule, the generated SQL has 👇 as the where clause:

```SQL
WHERE
  (
    (
      ("public"."article"."is_delete") <> (('true') :: boolean)
    )
    OR (
      (("public"."article"."is_delete") IS NOT NULL)
      AND ((('true') :: boolean) IS NULL)
    )
  )
```
Is the `(("public"."article"."is_delete") IS NOT NULL)` part added by design?

**Comment by dsandip** [comment] 2019-05-13 12:46
This behaviour should be documented here:
1) https://docs.hasura.io/1.0/graphql/manual/queries/query-filters.html#equality-operators-eq-neq 
2) https://docs.hasura.io/1.0/graphql/manual/api-reference/graphql-api/query.html#operator

**Comment by rikinsk** [comment] 2021-08-19 12:33
Closed via https://github.com/hasura/graphql-engine/commit/313e4e1a52c8a15dc83efac172e2a37dd4e91d50

**Closed by rikinsk** 2021-08-19 12:33 UTC
Labels: c/docs
