### ISSUE TITLE
Misleading GraphiQL behavior on _or clause

### ISSUE THREAD

**Issue by Bessonov** [hasura/graphql-engine#7016] opened 2021-06-06 10:32 UTC
As documented in [Example: _or](https://hasura.io/docs/latest/graphql/core/databases/postgres/queries/query-filters.html#using-multiple-filters-in-the-same-query-and-or) and [orExp](https://hasura.io/docs/latest/graphql/core/api-reference/graphql-api/query.html#orexp) the `_or` clause must contains an array and not an object to work properly. Unfortunately, if GraphiQL is used, it creates an object. It would be nice if embedded GraphiQL would produce intended output.

**Comment by soorajshankar** [comment] 2021-06-07 06:30
This is probably an issue for the GraphiQL Explorer repo: https://github.com/OneGraph/graphiql-explorer

**Comment by Bessonov** [comment] 2021-06-07 16:32
@soorajshankar I was not sure, because I was thinking that syntax differences between `_or` and `_and` must be handled on integrator (=> hasura) side and not in a general tool. If I'm wrong, then feel free to close this issue and then I will create an issue for OneGraph.

**Comment by tirumaraiselvan** [comment] 2021-06-08 12:44
Closing as dupe of https://github.com/hasura/graphql-engine/issues/3322

**Closed by tirumaraiselvan** 2021-06-08 12:44 UTC
Labels: c/console, c/graphiql-online, external-dependency
