### ISSUE TITLE
Remote Schema Relationships expected type "String" but got "String"

### ISSUE THREAD

**Issue by denisyilmaz** [hasura/graphql-engine#6113] opened 2020-11-02 08:08 UTC
Hello, I'm trying to get Remote Schema Relationsships to work. I have a CraftCMS backend and have included it as a Remote Schema, which is working fine. Now when trying to add a Schema Relationship i get the folowing error: 
```
Creating remote relationship failed
in table "messages": in remote relationship"producer": cannot validate remote relationship because expected type "String" but got "String"
```
 I saw a issue regarding differing types (Int to BigInt) but why is this failing in my case?? #5174 
here is the detailed error message with Hasura Version 1.3.2: 
```
[
    {
        "definition": {
            "remote_field": {
                "category": {
                    "arguments": {
                        "uid": "$producer_uid"
                    }
                }
            },
            "name": "producer",
            "hasura_fields": [
                "producer_uid"
            ],
            "remote_schema": "CraftCMS",
            "table": {
                "schema": "public",
                "name": "messages"
            }
        },
        "reason": "in table \"messages\": in remote relationship\"producer\": cannot validate remote relationship because expected type \"String\" but got \"String\"",
        "type": "remote_relationship"
    }
]
```
I additionally found this issue which seems to be resolved: https://github.com/hasura/graphql-engine/issues/5133

**Comment by tirumaraiselvan** [comment] 2020-11-02 08:10
#5133 is fixed but not yet released unfortunately. The issue happens when you are trying to make a remote relationship with `[String]` type argument in your remote field.

**Comment by denisyilmaz** [comment] 2020-11-02 08:18
Ah i See, any idea when this update can be expected?

**Comment by tirumaraiselvan** [comment] 2020-11-02 08:22
We will try for v1.3.3 this week.

**Comment by tirumaraiselvan** [comment] 2020-11-06 06:26
Closing as dupe of https://github.com/hasura/graphql-engine/issues/5133

**Closed by tirumaraiselvan** 2020-11-06 06:26 UTC
