### ISSUE TITLE
Console Browse Rows view is slow, hangs and crashes with large data columns

### ISSUE THREAD

**Issue by franciscolourenco** [hasura/graphql-engine#5812] opened 2020-09-21 10:59 UTC
When viewing a table which contains a JSONB columns with large objects, the _Browse Rows_ views takes a lot of CPU resources to render and often crashes the tab.

![image](https://user-images.githubusercontent.com/208149/93759082-dcf26600-fc09-11ea-8ddb-a1fe0e11e1ad.png)

The Graphqli view in the same console instance is able to fetch the data and render it much quicker and without problems. There is some time delay due the network, but the actual rendering works fine.

**Comment by beerose** [comment] 2020-10-22 12:25
Closing as a duplicate of https://github.com/hasura/graphql-engine/issues/5136

**Closed by beerose** 2020-10-22 12:25 UTC
Labels: c/console, duplicate
