### ISSUE TITLE
Is it possible to make an outer join to a remote schema?

### ISSUE THREAD

**Issue by ccalvarez** [hasura/graphql-engine#7108] opened 2021-06-23 21:58 UTC
Hi.

I have a remote schema that returns 1000 records.

On the other side, in my Hasura Postgres, I have a table with 650 matching records.

I want to create a query to returns all the 1000 records from the remote schema, and their respective record in Postgres, but I want to get always the 1000 records, whether or not they have the corresponding record in Postgres.

I know how to make it the opposite way, adding a Remote Schema Relationship to my Postgres table, but that way I get only the 650 records, but I need to get the 1000 records from the remote schema.

Thank you.

**Comment by 0x777** [comment] 2021-06-24 11:59
Hey, @ccalvarez we are planning to add 'remote schema to database' relationships which is meant to solve use cases such as yours. We are wrapping up cross database relationships currently and as soon as that is done, we'll be taking up 'remote schema to database' relationships.

**Comment by 0x777** [comment] 2021-07-30 10:19
Closing this as a duplicate of https://github.com/hasura/graphql-engine/issues/5801.

**Closed by 0x777** 2021-07-30 10:19 UTC
