### ISSUE TITLE
Foreign Keys - graphql-default naming convention

### ISSUE THREAD

**Issue by trburger** [hasura/graphql-engine#8809] opened 2022-08-17 18:06 UTC
### Version Information
Server Version:
hasura/graphql-engine:v2.10.1

**Example Tables**
user (FK with user_type below)
user_type

### What is the current behaviour?
Foreign keys are not support and result in relationships to other tables using underscores with graphql-default set as naming convention. Basic field names are correctly being handled correctly.
user.user_type

### What is the expected behaviour?
user.userType

**Comment by ajohnson1200** [comment] 2022-08-18 23:11
Just to confirm, you've configured your Hasura instance to use the graphql-default naming convention as documented here (https://hasura.io/docs/latest/schema/postgres/naming-convention/#supported-naming-conventions) and you're seeing that the correct results...except NOT with foreign keys?

**Comment by trburger** [comment] 2022-08-19 05:45
As best I can tell, things are setup correctly. Below show the DB config and 2 tables to show the issue more clearly. Rather new to Hasura, so perhaps I'm missing or overlooked something.

**Database Config**

![image](https://user-images.githubusercontent.com/23127587/185549847-d1d8954a-6078-467d-ac41-a870e59acf58.png)

**Simple 2 tables with a foreign key relationship and fields in snake-case**

![image](https://user-images.githubusercontent.com/23127587/185550725-fe8f99c8-d989-4474-b1a9-09805bc0b0ee.png)

**API Explorer - Fields are correct, relationships are not accounted for**

![image](https://user-images.githubusercontent.com/23127587/185550636-af3ce12d-3fb1-4f14-954a-c93c6cadf780.png)

**Comment by trburger** [comment] 2022-08-19 05:48
As best I can tell, things are setup correctly. Below show the DB config and 2 tables to show the issue more clearly. Rather new to Hasura, so perhaps I'm missing or overlooked something.

**Database Config**

![image](https://user-images.githubusercontent.com/23127587/185549847-d1d8954a-6078-467d-ac41-a870e59acf58.png)

**Simple 2 tables with a foreign key relationship and fields in snake-case**

![image](https://user-images.githubusercontent.com/23127587/185550725-fe8f99c8-d989-4474-b1a9-09805bc0b0ee.png)

**API Explorer - Fields are correct, relationships are not accounted for**

![image](https://user-images.githubusercontent.com/23127587/185550636-af3ce12d-3fb1-4f14-954a-c93c6cadf780.png)

**Comment by trburger** [comment] 2022-08-19 05:51
As best I can tell, things are setup correctly. Below show the DB config and 2 tables to show the issue more clearly. Rather new to Hasura, so perhaps I'm missing or overlooked something.

**Database Config**

![image](https://user-images.githubusercontent.com/23127587/185549847-d1d8954a-6078-467d-ac41-a870e59acf58.png)

**Simple 2 tables with a foreign key relationship and fields in snake-case**

![image](https://user-images.githubusercontent.com/23127587/185550725-fe8f99c8-d989-4474-b1a9-09805bc0b0ee.png)

**API Explorer - Fields are correct, relationships are not accounted for**

![image](https://user-images.githubusercontent.com/23127587/185550636-af3ce12d-3fb1-4f14-954a-c93c6cadf780.png)

**Comment by trburger** [comment] 2022-08-19 05:59
As best I can tell, things are setup correctly. Below show the DB config and 2 tables to show the issue more clearly. Rather new to Hasura, so perhaps I'm missing or overlooked something.

**Database Config**

![image](https://user-images.githubusercontent.com/23127587/185549847-d1d8954a-6078-467d-ac41-a870e59acf58.png)

**Simple 2 tables with a foreign key relationship and fields in snake-case**

![image](https://user-images.githubusercontent.com/23127587/185550725-fe8f99c8-d989-4474-b1a9-09805bc0b0ee.png)

**API Explorer - Fields are correct, relationships are not accounted for**

![image](https://user-images.githubusercontent.com/23127587/185550636-af3ce12d-3fb1-4f14-954a-c93c6cadf780.png)

**Comment by paritosh-08** [comment] 2022-08-19 06:18
Duplicate of https://github.com/hasura/graphql-engine/issues/8573

**Comment by seanparkross** [comment] 2022-08-24 12:06
Closed in favor of #8573

**Closed by seanparkross** 2022-08-24 12:06 UTC
Labels: k/bug, c/console
