### ISSUE TITLE
Computed fields of functions which return a single row should return a single object

### ISSUE THREAD

**Issue by franciscolourenco** [hasura/graphql-engine#4678] opened 2020-05-05 20:07 UTC
### Actual:
Querying a computed field defined by a function which `RETURNS table_name`, results in an array of objects, same as if the function was defined with `RETURNS SETOF tablename`

```js
"computed_field": [
  {
    "id": 1
  }
]
```

### Expected:
A function which `RETURNS table_name` should result in a single object, because the function can only return a single row.

```js
"computed_field": {
    "id": 1
}

```

### Notes:
The [hasura docs](https://hasura.io/docs/1.0/graphql/manual/schema/computed-fields.html) say that only `RETURNS SETOF table_name` is supported, however hasura seems to treat `RETURNS table_name` as if it is had `SETOF`.

------------------
Related to https://github.com/hasura/graphql-engine/issues/4299

**Comment by tirumaraiselvan** [comment] 2021-01-27 06:00
Closing this in favour of https://github.com/hasura/graphql-engine/issues/4299

**Closed by tirumaraiselvan** 2021-01-27 06:00 UTC
Labels: c/computed-fields, c/server, k/bug

**Comment by larsblumberg** [comment] 2021-06-09 15:26
To my understanding this issue is a duplicate of #6562 (rather than #4299).

I am hoping for #6562 to get implemented as an object relationship for a computed field looks like a fundamental and yet missing feature for me. The array relationship yields an ugly workaround for relationships where there really can be just one object (or none).
