### ISSUE TITLE
Can't interact with Code Exporter

### ISSUE THREAD

**Issue by kalwabed** [hasura/graphql-engine#9214] opened 2022-11-16 01:43 UTC
### Version Information

Server Version:
CLI Version (for CLI related issue):

### Environment
Cloud

### What is the current behaviour?
When I want to copy code from Code Exporter, the snippet blocks me from interacting with the input there.

### What is the expected behaviour?
I can interact with it.

### How to reproduce the issue?

1. Inside GraphiQL.
2. Open Code Exporter.

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/49640654/202061695-9ab84dbb-6b17-462d-b5b9-e6cf07145d9d.png)

**Comment by manasag** [comment] 2022-11-16 02:15
Hi @kalwabed thanks for raising this issue. I am closing this as duplicate of #9169. We can continue the discussion there.

**Closed by manasag** 2022-11-16 02:15 UTC
Labels: k/bug
