### ISSUE TITLE
allow methods other than post to trigger webhooks

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#416] opened 2018-09-11 11:57 UTC

**Comment by corysimmons** [comment] 2018-09-11 12:17
Replicating from https://github.com/hasura/graphql-engine/issues/406

>Coming from a REST background, I'm inclined to do stuff like PUT on updates.

**Comment by manasag** [comment] 2023-12-27 10:37
This issue has not attracted significant attention for a long period of time, hence closing this.
Please feel free to reopen if the issue is still relevant for you.

**Closed by manasag** 2023-12-27 10:37 UTC
Labels: k/enhancement, c/server, k/ideas, v2
