### ISSUE TITLE
Casting Issue when using Native Queries with custom arguments within the FREETEXTABLE function

### ISSUE THREAD

**Issue by lucasnad27** [hasura/graphql-engine#9729] opened 2023-06-21 23:53 UTC
### Version Information

Server Version:
CLI Version (for CLI related issue): n/a

### Environment

Cloud - v2.28.0-cloud.1
SQL Server 2017

### What is the current behaviour?

I'm creating a Native Query through the console that takes a single parameter, "term" and returns a search results, ordered by most relevant. Unfortunately, when I take a working SQL statement with the search term `'foo'`, and replace it with `{{term}}`, I get a CAST error when calling the native query.

The errors array, reduced for easier reading:
```json
{
  "errors": [
    {
      "message": "database query error",
      "extensions": {
        "path": "$",
        "code": "unexpected",
        "internal": {
          "exception": {
            "message": "[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'CAST'.",
            "type": "unsuccessful_return_code"
          },
          "query": "WITH [search_result_with_rank0] AS ( SELECT TOP 10 FT_TBL.Label, KEY_TBL.RANK as Rank\nFROM SearchResult AS FT_TBL   \n     INNER JOIN  \n     FREETEXTTABLE(SearchResult, SearchTerm, (N'foo')) AS KEY_TBL \n     ON FT_TBL.Id = KEY_TBL.[KEY] \nWHERE KEY_TBL.RANK >= 10  \nORDER BY KEY_TBL.RANK DESC\n ... */"
        }
      }
    }
  ]
}
```

### What is the expected behaviour?

I should be able to take a working SQL statement that utilizes the [FREETEXTTABLE SQL Server function](https://learn.microsoft.com/en-us/sql/relational-databases/system-functions/freetexttable-transact-sql?view=sql-server-ver16)  and replace the search string with the handlebars-style template system and call the native query and receive results.

### How to reproduce the issue?

It's tricky given all the state packed into the SQL Server setup, but below are some high-level steps to get you started. Happy to give more detailed information if necessary, although I'm hoping the error message is informative enough.
1. Create a table called SearchResult with necessary columns (Id, Label, SearchTerm, etc.,)
2. Create a full text index on the SearchTerm column
3. Create a LogicalModel that surfaces the SearchResult fields, along with a Rank field
4. create a native query that returns the above logical model. it should have a single text parameter called "term" and SQL that looks something like this
```sql
SELECT TOP 10 FT_TBL.Label, KEY_TBL.RANK as Rank
FROM SearchResult AS FT_TBL   
     INNER JOIN  
     FREETEXTTABLE(SearchResult, SearchTerm, {{term}}) AS KEY_TBL 
     ON FT_TBL.Id = KEY_TBL.[KEY] 
WHERE KEY_TBL.RANK >= 10  
ORDER BY KEY_TBL.RANK DESC
```
5. call the new native query through a graqphql query...
```gql
query MyQuery {
  search_result_with_rank(args: {term: "foo"}) {
    Label
    Rank
  }
}
```

### Please provide any traces or logs that could help here.
n/a

### Any possible solutions/workarounds you're aware of?

Not at this time.

### Keywords

sqlserver, native queries

**Comment by soupi** [comment] 2023-06-26 06:33
Thanks for the bug report @lucasnad27! We believe we identified the problem causing this and we've added this ticket to our internal backlog.

**Comment by lucasnad27** [comment] 2023-06-26 21:37
Great to hear @soupi ! Happy to provide additional details or confirm fix in a future release, if that's helpful.

**Comment by lucasnad27** [comment] 2023-07-14 18:34
@soupi Any ETA on this bug getting squashed and released on Hasura cloud?

**Comment by soupi** [comment] 2023-07-19 06:03
Hi @lucasnad27, this is one of the top items in our backlog currently, but I can't say exactly when it will be fixed and available.

**Comment by SamirTalwar** [comment] 2023-07-20 19:03
@lucasnad27, I can't reproduce the exact error you're seeing:

```
Incorrect syntax near 'CAST'.
```

I imagine it's because you're on MS SQL Server 2017 and I don't have access to that version with full text search, so I am trying to reproduce it on version 2022. I get this error instead:

```
Incorrect syntax near '('.
```

Could you run your query with the hard-coded string surrounded in parentheses and let us know if that causes the same error?

```sql
SELECT TOP 10 FT_TBL.Label, KEY_TBL.RANK as Rank
FROM SearchResult AS FT_TBL   
     INNER JOIN  
     FREETEXTTABLE(SearchResult, SearchTerm, (N'foo')) AS KEY_TBL 
     ON FT_TBL.Id = KEY_TBL.[KEY] 
WHERE KEY_TBL.RANK >= 10  
ORDER BY KEY_TBL.RANK DESC
```

We believe that's the problem but before trying to fix it, we want to make sure it's the correct issue.

**Comment by lucasnad27** [comment] 2023-07-20 22:43
If I try to run that SQL query directly on the database via Azure Data Studio, I get a syntax error due to the parentheses surrounding `N'foo'`.

![image](https://github.com/hasura/graphql-engine/assets/2490636/692dcb0a-9193-4f0e-b731-a45ea75bab76)

If I try to run it anyways, I get the error `Incorrect syntax near '('.` If I remove the parentheses, it executes successfully. 

I hope this is helpful.

**Comment by SamirTalwar** [comment] 2023-07-24 19:36
Thanks for clarifying.

I have now managed to reproduce the `Incorrect syntax near 'CAST'.` issue. It seems like it's an issue with Hasura that is unrelated to the parentheses; even when I remove them, I get the same error. (Meanwhile, it _does_ solve the error when running it directly in Data Studio or `sqlcmd`, so at least that's one down.)

We're digging further into it.

**Comment by SamirTalwar** [comment] 2023-07-24 21:14
@lucasnad27, we are indeed generating `CAST(? AS nvarchar(max))`, but the underlying library is not rendering this for the error message, leading to our confusion.

This is generally a feature which remedies other issues, so I'm not sure what to do here. The issue seems to be that `FREETEXTTABLE` is special; it behaves more like a macro than a function. Its first two arguments are identifiers, and the third _must_ be a raw string. It cannot be a more complicated operation, including a `CAST` but also, for example, string concatenation.

As this issue is specific to `FREETEXTTABLE` I would encourage you to wrap it in your own function (coded to the table you're querying), which will behave more normally. You can then use this function in your native query. I apologize that we can't be more helpful.

**Comment by lucasnad27** [comment] 2023-07-26 20:53
When you say "underlying library," I assume you are talking about MS SQL Server internals?

Either way, thanks for looking into this and providing an alternative solution. While I'll be annoyed writing this custom function, I'll at least know it's the best I can do for now 🥹 I appreciate your help on this @SamirTalwar 

Feel free to close this issue if you like.

**Comment by SamirTalwar** [comment] 2023-07-27 09:02
I can totally understand not wanting to write that function; this is the point of Native Queries, after all. Sorry we couldn't figure out a better solution. I hope it works well enough for you.

**Closed by SamirTalwar** 2023-07-27 09:02 UTC
Labels: k/bug, a/data/mssql, t/native-dbs
