### ISSUE TITLE
Event triggers Webhook URLs can't be combination of evn var and hardcoded part

### ISSUE THREAD

**Issue by arashlayeghi** [hasura/graphql-engine#5738] opened 2020-09-07 13:48 UTC
In Hasura Actions we can simply use `{{ACTION_BASE_URL}}/job/create` for example. But for Event triggers webhook URLs, we can only use the env var and not the hardcoded part. 

Can you please make it possible for Webhook URLs, too? Thanks

**Comment by arjunyel** [comment] 2020-09-07 19:02
Duplicate of https://github.com/hasura/graphql-engine/issues/2483

**Comment by codingkarthik** [comment] 2020-09-10 09:35
Closed, dupe of https://github.com/hasura/graphql-engine/issues/2483

**Closed by codingkarthik** 2020-09-10 09:35 UTC
