### ISSUE TITLE
Actions openapi spec POST / PATCH / DELETE freeze

### ISSUE THREAD

**Issue by MichalNemec** [hasura/graphql-engine#9817] opened 2023-08-07 23:10 UTC
### Version Information

Server Version: v2.31.0
CLI Version (for CLI related issue): v2.31.0

### Environment

Self hosted linux

### What is the current behaviour?

Whenever i click create, the whole console freezes.
EDIT: some of endpoints say Maximum call stack size exceeded

### What is the expected behaviour?

to not freeze and add the endpoint correctly.

## Screenshots
![image](https://github.com/hasura/graphql-engine/assets/5663019/748cbfda-59bc-422d-a2c6-09f309f7c490)

### How to reproduce the issue?

1. Create json openapi with post/patch/delete
2. Click create
3. see freeze
```
"/api/alert/manager/set-record-state": {
      "post": {
        "tags": [
          "Alert"
        ],
        "summary": "Lock/unlock alert",
        "description": "Possible responses:\r\n - 200 OK: int\r\n - 401 Unauthorized\r\n - 403 Insufficient role\r\n - 500 Internal Server Error: An unexpected error occurred. (default response)",
        "parameters": [
          {
            "name": "alertId",
            "in": "query",
            "description": "",
            "required": true,
            "style": "form",
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          },
          {
            "name": "state",
            "in": "query",
            "description": "Lock, Unlock",
            "required": true,
            "style": "form",
            "schema": {
              "$ref": "#/components/schemas/RecordEditState"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "integer",
                  "format": "int32"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorDTO"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorDTO"
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "security": [
          {
            "oauth2": [
              "openid",
              "profile",
              "email",
              "phone",
              "address",
              "offline_access"
            ]
          }
        ]
      }
    },
```

### Please provide any traces or logs that could help here.

no log whatsoever, docker logs -f <CONT_ID> says only v1 metadata and healtz

### Any possible solutions/workarounds you're aware of?

not really.

### Keywords

actions freeze post delete patch

**Comment by Varun-Choudhary** [comment] 2023-09-04 12:52
Hello @MichalNemec 
We are currently facing an issue while trying to import the OpenAPI file. This problem appears to be related to a reference part in the file, specifically `"$ref": "#/components/schemas/ErrorDTO"`. To assist us in resolving this issue effectively, it would greatly benefit us if you could share the complete API specification with us.
If you are not comfortable sharing the full API specification on this public platform, please feel free to email it to me at my official email address: [varun@hasura.io](mailto:varun@hasura.io). Your cooperation in this matter is greatly appreciated.
Thank you!

**Comment by Varun-Choudhary** [comment] 2023-09-05 11:50
Hey @MichalNemec, still I'm facing issues with importing the OpenAPI spec, could also validate it [here ](https://apitools.dev/swagger-parser/online/). I'll be good if you can share the complete spec with me.

**Comment by soorajshankar** [comment] 2023-09-07 07:27
Hey @MichalNemec, 

> I Changed it to simple DTOs and it works properly.

Glad that you were able to find a solution here, looks like the issue was caused by an OpenAPI spec which had a cyclic dependency- though it is possible (from JSON schema PoV) to define cyclic dependency, it won't be able to generate any schema out of it and hence is considered invalid. 

If you are interested to know more, there is a related discussion [here in the OAS official repo](https://github.com/OAI/OpenAPI-Specification/issues/822#issuecomment-257527173) and I think from Hasura side, we can probably add an additional error check to identify the circular dependency and throw a better error for clarity- however the actual fix would still be needed to be done on the OpenAPI schema.

Closing this issue now - considering the issue is with the OAS file, feel free to re-open if you still face issue on the same.

**Closed by soorajshankar** 2023-09-07 07:27 UTC
Labels: k/bug, t/gql-services, actions/open-API
