### ISSUE TITLE
console : inconsistent UI on edit row page

### ISSUE THREAD

**Issue by soorajshankar** [hasura/graphql-engine#9190] opened 2022-11-08 08:37 UTC
### Version Information

Server Version: v2.14.0

### Environment

OSS

### What is the current behaviour?

https://user-images.githubusercontent.com/8408875/200514142-06d97079-aae7-40c2-9056-7a5fd2014441.mov

### What is the expected behaviour?

The UI should be consistent across the tabs on table view.

### How to reproduce the issue?

1. open console in a bigger resolution screen
2. open a table 
3. click on modify row

### Any possible solutions/workarounds you're aware of?

CSS fix

### Keywords

console data modify row

**Comment by nicoinch** [comment] 2023-05-09 12:11
@soorajshankar I tried to fix this bug but I am not able to reproduce it, both on `main` branch and on `hasura.cloud.io`. Can you confirm this bug does not exist anymore, so we can close this issue, please?

**Comment by nicoinch** [comment] 2023-05-24 14:22
Got a confirmation from @soorajshankar that this issue has been fixed.

**Closed by nicoinch** 2023-05-24 14:22 UTC
Labels: k/bug, c/console, estimate/S
