### ISSUE TITLE
Field description

### ISSUE THREAD

**Issue by venelin-mihaylov** [hasura/graphql-engine#1434] opened 2019-01-21 12:57 UTC
Is it possible to use the column description to populate the description field in the graphql schema? 
If not, can you please implement that feature?

**Comment by shahidhk** [comment] 2019-01-22 06:18
Hello @venelin-mihaylov, this is a duplicate of the issue https://github.com/hasura/graphql-engine/issues/446

We'll start working on the issue once certain code refactoring is complete, which could take a couple of weeks.

Thanks for creating the issue, but I will be closing this now in favour of the existing one.

**Closed by shahidhk** 2019-01-22 06:18 UTC

**Comment by venelin-mihaylov** [comment] 2019-01-23 13:22
Thank you
