### ISSUE TITLE
"Value for environment variables not found" when trying to apply metadata

### ISSUE THREAD

**Issue by Kangaroux** [hasura/graphql-engine#8254] opened 2022-02-25 20:21 UTC
Related to #4929

```
$ hasura version
INFO hasura cli                                    version=v1.3.3
INFO hasura graphql engine                         endpoint="http://graphql-engine:8080/" version=v1.3.3
```

When trying to apply the metadata to the database it gives an error saying the env `HASURA_ACTION_BASE_URL` is not set:

```
$ hasura metadata apply
FATA[0002] failed to apply metadata: cannot apply metadata on the database: [unexpected] cannot continue due to inconsistent metadata ($.args)

reason: in action "listUsers"; Value for environment variables not found: HASURA_ACTION_BASE_URL
type: action
definition:
{ ... }
```

However the value is clearly set:

```
$ echo $HASURA_ACTION_BASE_URL
http://web:8000/api
```

Dumping the value to a `.env` file and trying again still gives the same error:

```
$ echo "HASURA_ACTION_BASE_URL=http://web:8000/api" > .env
$ hasura metadata apply
FATA[0002] failed to apply metadata: cannot apply metadata on the database: [unexpected] cannot continue due to inconsistent metadata ($.args)
```

**Comment by Kangaroux** [comment] 2022-03-07 00:04
Updated CLI and engine to v2.3.0 (still using config v2). Error still continues

```
Inconsistent object: in cron trigger ...: Value for environment variables not found: HASURA_ACTION_BASE_URL
```

**Comment by rikinsk** [comment] 2022-03-09 12:00
@Kangaroux could you share the section of docs that you found confusing

**Comment by rikinsk** [comment] 2022-03-09 12:01
Closing this issue in any case as the problem is resolved

**Closed by rikinsk** 2022-03-09 12:01 UTC
Labels: k/question
