### ISSUE TITLE
Issue post upgrade to v2.8.3

### ISSUE THREAD

**Issue by nadendlaprasad** [hasura/graphql-engine#8668] opened 2022-07-05 14:23 UTC
Hi, can not delete a column from the table even after updating permissions. 

Here the steps to produce.

1. Create table and add some columns
2. Add permissions 
3. release all permissions on the column you want to delete
4. Now delete column and hasura throws dependent error message even though none of the permissions exists on the column

**Comment by nadendlaprasad** [comment] 2022-07-11 10:34
update- further troubleshooting the issue. This issue can be simulated on any table on which permissions are created irrespective of the column reference for the permissions

**Comment by BenoitRanque** [comment] 2022-07-11 14:13
Closing as a duplicate of #8415

@nadendlaprasad can you please let us know if this issue is _not_ a duplicate, and if it is different, how so?

Also please note that issue now has a fix, but the fix is not released yet (should be in next minor release).

**Closed by BenoitRanque** 2022-07-11 14:13 UTC
Labels: k/bug
