### ISSUE TITLE
Cannot untrack custom defined function from the console

### ISSUE THREAD

**Issue by lorenzo** [hasura/graphql-engine#7493] opened 2021-09-02 08:06 UTC
A function with the same characteristics as https://github.com/hasura/graphql-engine/issues/7492, that was tracked using the metadata API, cannot be untracked from the console.

If you try to click the `untrack` button, the page reloads, but nothing happens. No error message is provided

**Comment by julian-mayorga** [comment] 2023-06-22 18:22
@lorenzo thanks for reporting this issue and providing clear reproduction steps.

I could successfully untrack the function in Hasura v2.28.

https://github.com/hasura/graphql-engine/assets/118911427/9a84a2eb-315c-4513-9ac7-b0de4f03d8cc

Could you verify this is working for you as well on the latest version of Hasura? Thanks

**Comment by vijayprasanna13** [comment] 2023-06-27 10:57
@lorenzo I'm closing this issue for now since it's been fixed on the console for quite sometime. Please feel free to reopen this issue if you face this again!

**Closed by vijayprasanna13** 2023-06-27 10:57 UTC
Labels: k/bug, c/console, estimate/S
