### ISSUE TITLE
Feature request: cli-migrations also apply seeds

### ISSUE THREAD

**Issue by seanonthenet** [hasura/graphql-engine#8478] opened 2022-05-10 11:39 UTC
I would like to be able to deploy a Docker Hasura image to a container and have it apply seeds as easy as it works currently with metadata and migrations. 

This would be of benefit for apps which rely on enum values in db tables, or when staging and demo environments are spun up and they could automatically include verified testing users entries and testing data pre-populated. 

If `cli-migrations-v3` container finds a `seeds/` directory, assume that seeds should be applied and apply. 

I think this feature is logical, since the 3 "core" aspects of Hasura data are metadata, migrations, and seeds. 

The alternative is custom CI/CD pipelines and Dockerfiles. Which are fine but not an official Hasura supported option.

**Comment by rikinsk** [comment] 2022-05-12 08:18
Thanks for the request. Closing as a duplicate of #7914. Please give that a thumbs-up to help prioritize it

**Closed by rikinsk** 2022-05-12 08:18 UTC
Labels: k/enhancement
