### ISSUE TITLE
accept query params for preloading queries/mutations in console graphiql

### ISSUE THREAD

**Issue by praveenweb** [hasura/graphql-engine#1179] opened 2018-12-11 10:01 UTC
It would be nice to have the console accept query parameters to preload queries/mutations.

Right now `query_file` pointing to a github link works. But lets also accept `query` parameter directly with support for variables too.

So it would support the following:

1) `query` param for actual query
2) `headers` param for a list of headers to be templated

**Comment by CodHeK** [comment] 2018-12-18 02:55
@praveenweb could you please explain a little more what is the issue about?
 I don't quite get what preloading queries/mutations mean here

**Comment by manasag** [comment] 2023-12-27 14:09
This issue has not attracted significant attention for a long period of time, hence closing this.
Please feel free to reopen if the issue is still relevant for you.

**Closed by manasag** 2023-12-27 14:09 UTC
Labels: k/enhancement, c/console, s/wip, p/medium, e/easy, a/api/graphql
