### ISSUE TITLE
Hasura CLI error: version check: failed to get version from server

### ISSUE THREAD

**Issue by vonwao** [hasura/graphql-engine#2601] opened 2019-07-25 18:27 UTC
I get this anytime I try to run hasura cli, for example 

$ hasura migrate create "init" --from-server
time="2019-07-25T11:23:55-07:00" level=fatal msg="version check: failed to get version from server: failed making version api call: Get meshconnect-development.herokuapp.com/v1/version: unsupported protocol scheme \"\""

same error if I try to run hasura console

Thanks for any ideas, tips, etc.

**Comment by shahidhk** [comment] 2019-08-10 12:15
@vonwao In you `config.yaml`, can you add the `endpoint` with complete url? i.e. `endpoint: https://meshconnect-development.herokuapp.com` and see if the issue still happens?

**Comment by marionschleifer** [comment] 2019-08-17 09:52
@vonwao just wanted to check in if you were able to close this issue? 🙂

**Comment by marionschleifer** [comment] 2019-08-27 07:32
@vonwao I'm closing the issue. Feel free to re-open if you would like to add something 🙂

**Closed by marionschleifer** 2019-08-27 07:32 UTC
Labels: c/cli, k/question

**Comment by CkCreative** [comment] 2019-09-21 12:23
I have also encountered this problem

**Comment by shahidhk** [comment] 2019-09-22 02:17
@CkCreative Can you confirm if your URL is of the form `https://<your-app>`?

**Comment by CkCreative** [comment] 2019-09-22 08:25
@shahidhk thanks a lot, it worked.

**Comment by b3j0f** [comment] 2020-03-05 09:41
Hello.

I met the same problem on the docker image hasura/graphql-engine:v1.1.0.cli-engine while the docker image hasura/graphql-engine:v1.1.0 works perfectly.

Did I miss a flag ?

Here is my config.yaml:

```yaml
admin_secret: ***
endpoint: http://localhost:8011
```

**Comment by shahidhk** [comment] 2020-03-09 09:50
@b3j0f Can you check if your server is running?

**Comment by b3j0f** [comment] 2020-03-09 09:51
Hello. Things went back to normal. Sorry for inconvenience...

**Comment by mojobnichols** [comment] 2020-05-18 15:08
I Have this prolem I checked the config and url is correct.   The server is in hosted environment on a docker image

**Comment by sbussard** [comment] 2020-07-12 00:45
Also having this problem

**Comment by allpwrfulroot** [comment] 2020-07-13 20:39
I had the following error several times trying to connect to a Hasura Cloud project (Heroku Postgres):
```
FATA[0025] version check: failed to get version from server: failed making version api call: Get https://my-app-name.hasura.app/v1/version: dial tcp: lookup my-app-name.hasura.app on XXX.XXX.X.X:XX: server misbehaving
```

Eventually it did work, but in an unexpected manner: instead of several .yaml files under a `metadata` directory, I received a single .yaml under `migrations`

**Comment by arnaud-cortisse** [comment] 2020-07-31 16:00
I'm suddenly getting this error too. Don't know why yet.

**Comment by arnaud-cortisse** [comment] 2020-07-31 16:10
I was encountering this bug too (Hasura hosted on Heroku) but it's just been fixed on its own. 
Since I was getting it when deploying via Github Actions, I first I tried to reproduce it with the hasura CLI on my machine. 
It worked on my machine so I tried to start the deployment on Github Actions again and it worked.

**Comment by bkstorm** [comment] 2020-08-05 04:41
> FATA[0061] version check: failed to get version from server: failed making version api call: Get https://db_host/v1/version: dial tcp 10.0.1.33:443: i/o timeout
I encountered the same problem when running the following command:
> hasura migrate create "init" --from-server --schema "public"

**Comment by stijn-gravity** [comment] 2020-09-21 13:03
Hi, I am currently facing this issue on one of my servers, while all others (with the same setup) have no issues. 
I see that for most people here the issue resolves itself but I don't want to rely on this. 

I can confirm the server is running as it should, and that the secret and url are set correctly in the config.

Is there any update on what might cause this?

**Comment by arnaud-cortisse** [comment] 2020-09-21 13:49
> Hi, I am currently facing this issue on one of my servers, while all others (with the same setup) have no issues.
> I see that for most people here the issue resolves itself but I don't want to rely on this.
> 
> I can confirm the server is running as it should, and that the secret and url are set correctly in the config.
> 
> Is there any update on what might cause this?

Are all your servers using the same Hasura GraphQL Engine version ? 
My assumption is that this problem occurs when your Hasura CLI and your Hasura GraphQL Engine are the not same version...

For example, I got the problem when my CLI was 1.3.0 while one of my servers was 1.2.0.

**Comment by stijn-gravity** [comment] 2020-09-21 14:57
Hi @arnaud-cortisse, thank you for your reply.

The versions were in fact mismatching. However, after downgrading the cli the issue was still there.

What I forgot to mention is that before the weekend I was able to access the server that is now not connecting to ```hasura console```, and since then nothing changed. No work was done/released.

**Comment by williscool** [comment] 2020-10-24 00:26
So when I ran into this issue it was because I was setting some env var wrong

```
FROM hasura/graphql-engine:v1.3.2.cli-migrations-v2 as base
# https://hasura.io/docs/1.0/graphql/core/migrations/advanced/auto-apply-migrations.html#cli-migrations-image
 
# copy migrations and metadata in
COPY ./metadata /hasura-metadata
COPY ./migrations /hasura-migrations

# ENV HASURA_GRAPHQL_DATABASE_URL postgres://postgres:password@localhost:5432/dbname
# ENV HASURA_GRAPHQL_ADMIN_SECRET accessKey
# ENV HASURA_GRAPHQL_ENDPOINT http://hasura:80
# ENV HASURA_GRAPHQL_INSECURE_SKIP_TLS_VERIFY true

```

commenting all of the `ENV` out fixed it.

Not sure which one broke everything but it was likely the dburl or the insecure bit.

For the record im using a helm chart

https://github.com/williscool/hasura-k8s-stack/tree/master/hasura-chart

and was using the above docker file in it. 

Making sure to NOT set the env vars in the Dockerfile ...

and ONLY setting them in the helm values was what fixed for me. hope it helps someone else.

lost half a day to this

**Comment by stijn-gravity** [comment] 2020-11-18 10:05
This issue was fixed for me in the update to 1.3.3, thanks team.

**Comment by shankariyerr** [comment] 2020-11-19 07:46
I'm running version 1.3.3 and I just faced this issue.

FATA[0022] version check: failed to get version from server: failed making version api call: Get "https://my-app.hasura.app/v1/version": net/http: TLS handshake timeout

**Comment by b3j0f** [comment] 2020-11-19 07:55
In fact this error message comes from several possible issues...

Is it possible to get more specific message instead of a generic one ?

**Comment by ferry77** [comment] 2020-12-20 07:44
I am having same issue like @shankariyerr I am wondering if this related with Big Sur on Mac

**Comment by ferry77** [comment] 2020-12-20 07:45
Trying second attempt with `hasura console --insecure-skip-tls-verify` and it works

**Comment by austinrivas** [comment] 2021-02-18 15:41
I have noticed this issue on hasura cloud whenever I make changes to env vars, which results in the cloud instance resetting.

The confusing part is that awaiting a GET 200 response from /v1/version doesn't seem to be enough.

This is actually preventing me from using the hasura cli in our ci environment currently, which is more than a little troubling.

When I rerun our deploy command everything works, so it seems to me like v1/version has some inconsistent behavior between conventional GET polling and the hasura cli.

I've included logs below about this issue and will open a new ticket to reference this as well.

```sh
$ echo 'hasura:wait' && . ../../.env && echo $HASURA_CLOUD_PROJECT_NAME && wait-on https-get://api.dev.onework.services/v1/version -v
hasura:wait
onework-dev
waiting for 1 resources: https-get://api.dev.onework.services/v1/version
making HTTP(S) get request to  url:https://api.dev.onework.services/v1/version ...
making HTTP(S) get request to  url:https://api.dev.onework.services/v1/version ...
  HTTP(S) result for https://api.dev.onework.services/v1/version: {
  status: 200,
  statusText: 'OK',
  headers: {
    server: 'openresty/1.19.3.1',
    date: 'Thu, 18 Feb 2021 15:32:49 GMT',
    'content-type': 'application/json; charset=utf-8',
    'transfer-encoding': 'chunked',
    connection: 'close',
    'strict-transport-security': 'max-age=31536000; includeSubDomains'
  },
  data: { version: 'v1.3.3-cloud.3' }
}
wait-on(11710) complete
$ /home/austin/Workspace/Sophia/platform/node_modules/.bin/hasura migrate apply
FATA[0001] version check: failed to get version from server: GET https://api.dev.onework.services/v1/version failed - [502] 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

And the rerun immediately after

```sh
$ echo 'hasura:wait' && . ../../.env && echo $HASURA_CLOUD_PROJECT_NAME && wait-on https-get://api.dev.onework.services/v1/version -v
hasura:wait
onework-dev
waiting for 1 resources: https-get://api.dev.onework.services/v1/version
making HTTP(S) get request to  url:https://api.dev.onework.services/v1/version ...
making HTTP(S) get request to  url:https://api.dev.onework.services/v1/version ...
  HTTP(S) result for https://api.dev.onework.services/v1/version: {
  status: 200,
  statusText: 'OK',
  headers: {
    server: 'openresty/1.19.3.1',
    date: 'Thu, 18 Feb 2021 15:36:10 GMT',
    'content-type': 'application/json; charset=utf-8',
    'transfer-encoding': 'chunked',
    connection: 'close',
    'strict-transport-security': 'max-age=31536000; includeSubDomains'
  },
  data: { version: 'v1.3.3-cloud.3' }
}
wait-on(12893) complete
$ /home/austin/Workspace/Sophia/platform/node_modules/.bin/hasura migrate apply
INFO nothing to apply                             
$ /home/austin/Workspace/Sophia/platform/node_modules/.bin/hasura metadata apply
INFO Metadata applied                             
Done in 30.16s.
```

**Comment by enes-get-local** [comment] 2021-10-04 09:17
> Also having this problem on remote url

Hey @sbussard do you have still issue or how fixed it ? i have same problem on wsl2

**Comment by sbussard** [comment] 2021-10-04 17:39
No, the stack I was working with had a very unique configuration. What worked for me was to create a docker file with the hasura cli as the entrypoint and mount whatever folders I needed as well as a .env file.
