### ISSUE TITLE
Configurable Action Timeout

### ISSUE THREAD

**Issue by zolamk** [hasura/graphql-engine#5673] opened 2020-08-26 12:09 UTC
It would be helpful to be able to set a timeout for an action in case an action more time than expected, maybe make it configurable when creating the action

**Comment by tirumaraiselvan** [comment] 2020-08-31 12:06
Closing as dupe of: https://github.com/hasura/graphql-engine/issues/4966

**Closed by tirumaraiselvan** 2020-08-31 12:06 UTC

**Comment by zolamk** [comment] 2020-09-03 08:29
> Closing as dupe of: #4966

I think that issue is for async actions, i want to configure the timeout for synchronous actions

**Comment by tirumaraiselvan** [comment] 2020-09-15 05:14
> I think that issue is for async actions, i want to configure the timeout for synchronous actions

Right :) Maybe we should change that title for both async and sync actions. The action handler is the same in both cases and hence it would be expected that it should have the same timeout. In other words, there is no way for your action handler to distinguish between async and sync operations.
