### ISSUE TITLE
sort error: parsing Hasura.Backends.Postgres.SQL.DML.NullsOrder failed

### ISSUE THREAD

**Issue by hgiasac** [hasura/graphql-engine#8780] opened 2022-08-12 04:18 UTC
### Version Information

Server Version: v2.10.0
CLI Version (for CLI related issue):

### Environment

OSS 

### What is the current behaviour?

HGE returns error `parsing Hasura.Backends.Postgres.SQL.DML.NullsOrder failed, expected one of the tags ["ulls_first","ulls_last"], but found tag "last"` when sorting any table in the Data tab. 

### What is the expected behaviour?
Sorting table should work

### How to reproduce the issue?

1. Create any table
2. Browse Rows that table 
3. Choose any column to be sorted
4. Click `Run Query`

### Screenshots or Screencast
![Screenshot_20220812_110604](https://user-images.githubusercontent.com/1615675/184284130-8cdb28cb-eed5-4fe4-bf52-7297b49a951a.jpg)

### Please provide any traces or logs that could help here.

```json
{
  "detail": {
    "http_info": {
      "content_encoding": null,
      "http_version": "HTTP/1.1",
      "ip": "172.18.0.1",
      "method": "POST",
      "status": 400,
      "url": "/v2/query"
    },
    "operation": {
      "error": {
        "code": "parse-failed",
        "error": "parsing Hasura.Backends.Postgres.SQL.DML.NullsOrder failed, expected one of the tags [\"ulls_first\",\"ulls_last\"], but found tag \"last\"",
        "path": "$[0].order_by.nulls"
      },
      "raw_query": "{\"type\":\"bulk\",\"source\":\"default\",\"args\":[{\"type\":\"select\",\"args\":{\"source\":\"default\",\"table\":{\"schema\":\"public\",\"name\":\"status\"},\"columns\":[\"description\",\"id\"],\"offset\":0,\"limit\":20,\"order_by\":[{\"column\":\"id\",\"type\":\"desc\",\"nulls\":\"last\"}]}},{\"type\":\"run_sql\",\"args\":{\"source\":\"default\",\"sql\":\"SELECT\\n    reltuples::BIGINT\\n  FROM\\n    pg_class c\\n  JOIN\\n    pg_namespace n ON c.relnamespace = n.oid\\n  WHERE\\n    c.relname = quote_ident('status') AND n.nspname = quote_ident('public');\",\"cascade\":false,\"read_only\":true}}]}",
      "request_id": "f8a12c2f-ae5b-4689-ac7d-170eb06d2ace",
      "request_mode": "error",
      "response_size": 202,
      "user_vars": { "x-hasura-role": "admin" }
    },
    "request_id": "f8a12c2f-ae5b-4689-ac7d-170eb06d2ace"
  },
  "level": "error",
  "timestamp": "2022-08-12T04:10:02.222+0000",
  "type": "http-log"
}
```

### Any possible solutions?

Revert back to v2.9.0

### Can you identify the location in the source code where the problem exists?

No

### If the bug is confirmed, would you be willing to submit a PR?

No

### Keywords

sort order_by console

**Comment by efstathiosntonas** [comment] 2022-08-12 04:40
Same here on 2.10.0. I can’t order the tables at all.

**Comment by ajohnson1200** [comment] 2022-08-13 00:33
Thanks everyone for reporting this issue. We've identified the root cause and will be deploying a fix for this ASAP.

**Comment by ajohnson1200** [comment] 2022-08-18 23:20
This is fixed in 2.10.1: https://github.com/hasura/graphql-engine/releases/tag/v2.10.1

**Closed by ajohnson1200** 2022-08-18 23:20 UTC
Labels: k/bug

**Comment by efstathiosntonas** [comment] 2022-08-30 04:13
Is there any reason why this hasn’t dropped on 2.11.0?

**Comment by hitokiri82** [comment] 2022-09-01 16:24
I'm also running into this bug in v2.11.1-cloud.1

**Comment by bnol** [comment] 2022-09-03 15:43
+1 v2.11.1

**Comment by efstathiosntonas** [comment] 2022-09-03 15:49
This was “silently” fixed on 2.12.0-beta.1

**Comment by illepic** [comment] 2022-09-07 17:43
Verified fixed for me on `v2.12.0-beta.1`.

**Comment by ddevoss** [comment] 2022-09-09 16:44
Just started getting this error on our cloud instance.

v2.11.1-cloud.2

**Comment by ryparker** [comment] 2022-09-11 05:33
Can we reopen this or should we create a new issue?

**Comment by shahidhk** [comment] 2022-09-13 00:03
The fix is now available with https://github.com/hasura/graphql-engine/releases/tag/v2.11.2
