### ISSUE TITLE
Headers are not passed to an HASURA_GRAPHQL_UNAUTHORIZED_ROLE

### ISSUE THREAD

**Issue by rinfimate** [hasura/graphql-engine#1880] opened 2019-03-27 06:12 UTC
If i set a HASURA_GRAPHQL_UNAUTHORIZED_ROLE to a role, i am not able to access any custom http headers e.g (x-hasura-link-url) to use in permissions for this role. I have also noticed that headers not prefixed with x-hasura are not passed in any case for all type of roles.

**Comment by shahidhk** [comment] 2019-03-27 09:18
@rinfimate Headers not prefixed with `x-hasura-` will not be parsed by Hasura for enforcing permission rules. This is by design.

However, I am unable to reproduce you issue with `x-hasura-link-url`. Can you give me more details?

Here is what I did:

1. Setup server with admin secret and unauthorized role as `anonymous`
2. Setup a table with id and name columns, add some sample data.
3. Create a permission check for `anonymous` role on this table with the check as `{"id":{"_eq":"X-Hasura-User-Id"}}`
4. Make a request with headers `X-Hasura-Role: anonymous` and `X-Hasura-User-Id: 1`
5. As expected, I only get the response with `id: 1`

**Comment by marionschleifer** [comment] 2019-07-09 14:34
I'm closing this issue. @rinfimate feel free to re-open this if you would like to add anything 🙂

**Closed by marionschleifer** 2019-07-09 14:34 UTC
Labels: needs-more-info
