### ISSUE TITLE
Console: New relationship UI cannot load relationships on views

### ISSUE THREAD

**Issue by foxted** [hasura/graphql-engine#9091] opened 2022-10-09 22:11 UTC
### Version Information

Server Version: v2.12.0
CLI Version (for CLI related issue): v2.7.0

### Environment

- Docker (MacOS)
- Cloud

### What is the current behaviour?

When trying to load the relationships on a View, we are faced with this error message: 

![Screen Shot 2022-10-09 at 15 10 44](https://user-images.githubusercontent.com/1385160/194781825-5eeee120-b31c-42fd-b057-8027eaa09c25.png)

### What is the expected behaviour?

Relationships should be loaded correctly.

### How to reproduce the issue?

1. Turn-on the New relationship UI feature flag
2. Navigate on a View page
3. Click the Relationships tab
4. Wait until you see the error message

### Screenshots or Screencast

![Screen Shot 2022-10-09 at 15 05 51](https://user-images.githubusercontent.com/1385160/194781746-f1077063-f195-49c0-aa78-8ff2b77a8ee5.png)

### Keywords

- relationships
- relationships views
- relationships error

**Comment by meetzaveri** [comment] 2022-10-10 09:04
Hello @foxted 

Thanks for reporting the issue. I was able to replicate what you are facing in Hasura Cloud `v2.12.0-cloud.1`. I can replicate this issue for _materialized_ views as well as _non-materialized_ views too

### Short Synopsis
This issue is specifically focused on **VIEWS**(rather than tables). It works well in old(default) relationship UI (when you toggle off new relationship UI) and you can check that in views -> relationships

When I looked at network requests for `metadata`, it was containing the necessary/required data for relationship. From that, we can derive that there's no clear issue from the server side. This must be a console issue.

<img width="1439" alt="Screenshot 2022-10-10 at 2 13 06 PM" src="https://user-images.githubusercontent.com/21293048/194831899-aea550af-1cc8-4329-9765-eb1978663553.png">

**Comment by orcwarrior** [comment] 2023-02-02 15:28
I got the same issue with Hasura
```
Current server version: v2.16.0
Console asset version: a526fad3ff112
```
Old UI works as intended.

**Comment by vijayprasanna13** [comment] 2023-05-03 13:05
@foxted @meetzaveri This has been fixed in https://github.com/hasura/graphql-engine/commit/498d8fc9f4ad1e9cda8174d3b8afd7629f604713. Feel free to open this thread again if the issue persists.

**Closed by vijayprasanna13** 2023-05-03 13:05 UTC
Labels: k/bug, c/console, t/console, estimate/S
