### ISSUE TITLE
Function returns SETOF Materialized View doesn't track in Hasura

### ISSUE THREAD

**Issue by CoenNengerman** [hasura/graphql-engine#5379] opened 2020-07-14 14:05 UTC
I've created a search view (Materialized View) where i combine multiple tables. I want to be able to use a fuzzy search on multiple fields. 

When i try to track the function I get an error from Hasura:
**"reason": "in function "total_search": the function "total_search" cannot be tracked because the function does not return a SETOF table"**

SQL functions don't support variables, so I create a PLPQSQL function for that. I want to track the SQL function so I can use it in Graphql(Hasura). 

CREATE FUNCTION public.generate_total_search(search text, fields text, maxrecords integer, ioffset integer) RETURNS SETOF public.search_table_mv
    LANGUAGE plpgsql
    AS $$
	  DECLARE 
	  q1 public.search_table_mv;
	  BEGIN
	  FOR
      q1 in EXECUTE('SELECT id, src_id, sourcetable, title, description, transcription, permalink, status, source, annotations, bibliography, additional_notes, editor_description, name, "references", spellings, alternative_spellings, link, similarity(''' || search ||
      ''' , (' || fields || ')) as score FROM public.search_table_mv    WHERE      ''' || search
      || ''' <% (' || fields || ')    ORDER BY      similarity(''' || search ||
      ''' , (' || fields || ')) DESC    LIMIT ' || maxrecords || ' OFFSET ' || ioffset)
	  LOOP
	  RETURN
      next q1;
	  END LOOP;
	  END;
	  $$;

CREATE FUNCTION public.total_search(search text, fields text, maxrecords integer, ioffset integer) RETURNS SETOF public.search_table_mv
    LANGUAGE sql STABLE
    AS $$
    SELECT generate_total_search(search, fields, maxrecords, ioffset);
$$;

**Comment by tirumaraiselvan** [comment] 2020-09-24 08:15
Closing as dupe of https://github.com/hasura/graphql-engine/issues/5294

**Closed by tirumaraiselvan** 2020-09-24 08:15 UTC
Labels: c/server, k/enhancement
