### ISSUE TITLE
Custom Name for Enum table is ignored

### ISSUE THREAD

**Issue by lorenzo** [hasura/graphql-engine#8308] opened 2022-03-11 13:52 UTC
### Version Information

Server Version: 2.4.0

### Environment

ALL

### What is the expected behaviour?

It should be possible to customize the type name for enums like it is possible for regular tables.

### Keywords

enums

### What is the current behaviour?

In the same way that it is possible to alias a table to have a custom type name in GraphQL, it should be possible to change the name for an enum table.

Currently, the custom name for the type is ignored.

The generated name is always `[schema]_[table]_enun`

### How to reproduce the issue?

1. Create enum type following the instructions
2. Set the name for the GraphQL type
3. Be surprised that it does not work

### If the bug is confirmed, would you be willing to submit a PR?

Sure, with some guidance

**Comment by sordina** [comment] 2022-03-31 07:05
Hi @lorenzo,

We've tried replicating the issue you've described with

the following docker compose:

```docker-compose
> cat docker-compose.yml
version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.4.0
    ports:
    - "8888:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
volumes:
  db_data:
```

the following metadata:

```
{
  "resource_version": 6,
  "metadata": {
    "version": 3,
    "sources": [
      {
        "name": "mydb",
        "kind": "postgres",
        "tables": [
          {
            "table": {
              "schema": "public",
              "name": "baz"
            }
          },
          {
            "table": {
              "schema": "public",
              "name": "foo"
            },
            "is_enum": true,
            "configuration": {
              "custom_root_fields": {},
              "comment": null,
              "custom_name": "bar",
              "custom_column_names": {}
            }
          }
        ],
        "configuration": {
          "connection_info": {
            "use_prepared_statements": false,
            "database_url": "postgres://postgres:postgrespassword@postgres:5432/postgres",
            "isolation_level": "read-committed"
          }
        }
      }
    ]
  }
}
```

on both v2.4.0 and latest main branch, but we haven't been able to find any issue with the naming of the enum as of yet.

Would you be able to:

* Try pulling the tag again in case you were on a beta
* Try on a more recent tag
* If the problem is still persisting for you, include an attachment of your docker-compose, metadata export, and any db dump that is relevant.
* If the problem has been resolved, let us know so that we can close the issue!

Thanks!

**Comment by sordina** [comment] 2022-03-31 07:05
[dump.sql.zip](https://github.com/hasura/graphql-engine/files/8386747/dump.sql.zip)

**Comment by lorenzo** [comment] 2022-03-31 08:25
@sordina would you mind sharing the generated schema? I would like to make sure that we are talking about the same issue.

**Comment by lorenzo** [comment] 2022-03-31 08:29
@sordina I can also see that you added the tables to the public Postgres schema, and not to a custom schema as the issue describes. Would you mind adding the enum table to a custom Postgres schema and try again?

**Comment by sordina** [comment] 2022-04-11 03:50
Hi @lorenzo thanks for clarifying. We're working on a fix now.

**Comment by lorenzo** [comment] 2022-04-11 12:51
@sordina it would be ideal if setting a custom name also meant not having the `_enum` suffix

**Comment by paritosh-08** [comment] 2022-04-13 09:27
> @sordina it would be ideal if setting a custom name also meant not having the `_enum` suffix

This won't be possible as of now as the `select_by_pk` query on the enum table results in object with the same type name (i.e. custom name without any suffix, and that has a different type definition). For example, in @sordina's setup, we already have the type name `bar`, which represents the output type of `bar_by_pk` query which is:
```
bar_by_pk(name: String!): bar
```
And for the type of `baz.name` we have the `bar_enum`, which we cannot rename to `bar` as it will conflict with the above mentioned type definition.

**Comment by paritosh-08** [comment] 2022-04-13 10:31
@lorenzo, a fix for this issue has been merged in the `main` branch via https://github.com/hasura/graphql-engine/commit/4e0a0a5804a60b1d5fc0f7faba5f5b9b2060b7e1 (with custom name having the `_enum` suffix). I am closing this issue for now, but please feel free to reopen a separate issue if you still think that we should fix this behaviour of adding `_enum` suffix to the custom table name.

**Closed by paritosh-08** 2022-04-13 10:31 UTC
Labels: k/bug

**Comment by lorenzo** [comment] 2022-04-13 20:05
It definitely should not have the suffix. I’ll open a new issue
