### ISSUE TITLE
Why is Hasura erring on startup with “following root fields are duplicated” in beta8?

### ISSUE THREAD

**Issue by timtubescience** [hasura/graphql-engine#3220] opened 2019-10-23 20:17 UTC
This question is for a Hasura application running against a Postgres database. When running beta6, everything is working. However, after updating to beta8, Hasura does not start.

Here is the last log message when starting with beta6:

```
{
    "timestamp": "2019-10-23T19:07:55.521+0000",
    "level": "info",
    "type": "startup",
    "detail": {
        "kind": "server",
        "info": {
            "time_taken": 0.486567746,
            "message": "starting API server"
        }
    }
}
```

And here is the last log message starting with beta8:

```
{
    "path": "$.args[0].args",
    "error": "following root fields are duplicated: ******",
    "code": "unexpected"
}
```

We are carrying on with beta6 for now, if anyone has an open communications channel with Hasura, it might be good to let them know they introduced a breaking change with their latest release. It would be good to get on the upgrade pathway again, hopefully we are not stuck on beta6 for whatever reason.

Cross posted from: https://stackoverflow.com/questions/58529871/why-is-hasura-erring-on-startup-with-following-root-fields-are-duplicated-in-b

**Comment by ecthiender** [comment] 2019-10-24 05:54
Hi @timtubescience , we are unable to reproduce the issue on our end. It would be great if you can provide some details about your schema, or better even, the steps to reproduce (if you can reproduce consistently). That would help us to debug the issue.

**Comment by rakeshkky** [comment] 2019-10-24 07:18
Hi @timtubescience, I'm trying to solve this issue by looking at code. I have a custom docker image where the fix (possibly) is live. Can you please test it out. 
Image: `rakesh572/graphql-engine:issue-3220-root-fields-validation-718648097`

**Comment by timtubescience** [comment] 2019-10-24 16:38
Hi @rakeshkky , thanks so much for taking a look at this.  We are getting the same error message when starting with your debug docker image, as we do with the beta8 image.  Please find two screenshots attached, the first showing the correct docker image from your post above, and the second showing the error in the startup logs.

We are roughly following the CFN based deployment to AWS Fargate described here:

https://dev.to/lineup-ninja/deploying-hasura-on-aws-with-fargate-rds-and-terraform-4gk7

Would it be possible to add some debug logging to your debug docker image, which I could send to you privately?

![Screen Shot 2019-10-24 at 9 30 54 AM](https://user-images.githubusercontent.com/52723579/67506109-5754e780-f641-11e9-8b3c-c1ec5f223172.png)

![Screen Shot 2019-10-24 at 9 27 48 AM](https://user-images.githubusercontent.com/52723579/67506194-7f444b00-f641-11e9-8aff-4168465f1be6.png)

**Comment by rakeshkky** [comment] 2019-10-25 07:34
@timtubescience Thank you so much for trying the custom image. Now I'm able to narrow down the causes of the issue. 

Hasura generates the root fields for a table based on its name. For example `<table>`, `<table>_aggregate`, `<table>_by_pk` etc. Where `<table>` is `<table-name>` for `public` schema or `<schema-name>_<table-name>` for other schemas. 

Let's say, I have table with a name `test_user` in `public` schema and another table with a name `user` in `test` schema. Both tables are distinct but the root fields generated will conflict with each other. We didn't think about this edge case before but fortunately, this check is added with https://github.com/hasura/graphql-engine/pull/2509.

Please confirm if your database has something similar to above.

**Comment by timtubescience** [comment] 2019-10-25 18:15
@rakeshkky Thank you for your reply.  I understand you have identified a case where there could be a root name collision if a table in the public schema overlaps with `<schema>.<table-name>` for another table in another schema.  I do not believe this is what is happening for us, because we use a naming convention to prevent collisions in our database entity names.

For instance, the table names in our public schema all start with `ts_`, the views in our public schema all start with `view_`, and there are no schemas in the database that start with either `ts_` or `view_`.  I've double checked and confirmed the naming convention is being used for the table identified in the log message above.

Indeed, to test this issue, I renamed the table in question to `this_is_a_definitely_unique_table_name_100`.  Still getting a startup error related to the original table name, perhaps this error is due to something found in the metadata?

Here's the new startup error after renaming the offending table in the public schema.  The `******` below represents the exact same string as the redacted bits above, it's all the same table name.

```
{
    "internal": [
        {
            "definition": {
                "using": {
                    "manual_configuration": {
                        "remote_table": "******",
                        "column_mapping": {
                            "foo_id": "foo_id"
                        }
                    }
                },
                "name": "******",
                "comment": null,
                "table": "******"
            },
            "reason": "table \"******\" does not exist",
            "type": "object_relation"
        },
        {
            "definition": {
                "using": {
                    "manual_configuration": {
                        "remote_table": "******",
                        "column_mapping": {
                            "foo_id": "foo_id"
                        }
                    }
                },
                "name": "******",
                "comment": null,
                "table": "******"
            },
            "reason": "table \"******\" does not exist",
            "type": "object_relation"
        },
        {
            "definition": "******",
            "reason": "no such table/view exists in postgres: \"******\"",
            "type": "table"
        }
    ],
    "path": "$.args[0].args",
    "error": "cannot continue due to new inconsistent metadata",
    "code": "unexpected"
}
```

**Comment by marionschleifer** [comment] 2019-11-05 11:38
You have a table with name `<table-1>` in the metadata and this will conflict with  the aggregate root field of `<table-2>`.

Unfortunately you can't make an API request to customise the generated fields since the server refuses to start.
The possible solutions are:
1. While on `beta.6`, untrack any of `<table-1>` or `<table-2>` (warning: this also drops related relationships and permissions), migrate to `beta.8` and again track the table with custom configuration (use the API: https://docs.hasura.io/1.0/graphql/manual/api-reference/schema-metadata-api/table-view.html#track-table-v2)
2. Export and clean the metadata in `beta.6`. In the exported `metadata.json` file, manually add configuration for either of the tables. Upgrade to `beta.8` and import the metadata using edited `metadata.json` file.

As far as I'm aware, this problem has been resolved over Discord. I'm closing this issue for now. If you'd like to add anything, feel free to re-open 🙂

**Closed by marionschleifer** 2019-11-05 11:38 UTC
Labels: c/server, needs-more-info

**Comment by marionschleifer** [comment] 2019-11-06 12:27
@timtubescience thank you for elaborating 🙂
