### ISSUE TITLE
`user` role is not able to perform mutations

### ISSUE THREAD

**Issue by yogeshwar607** [hasura/graphql-engine#7304] opened 2021-07-27 18:11 UTC
### Discussed in https://github.com/hasura/graphql-engine/discussions/7301

<div type='discussions-op-text'>

<sup>Originally posted by **yogeshwar607** July 27, 2021</sup>
`user` role is not able to perform mutations even after giving proper permissions.
Previously it was working fine and there were no issues but now even in console its not showing mutations option all together even with proper headers.

Everything is working fine with `admin` role though

<img width="1440" alt="Screenshot 2021-07-27 at 7 03 02 PM" src="https://user-images.githubusercontent.com/10059011/127164148-7657ab07-0a1a-4faf-b099-d44017f36850.png">
<img width="1440" alt="Screenshot 2021-07-27 at 7 06 04 PM" src="https://user-images.githubusercontent.com/10059011/127164175-3268b4e4-f2bf-477e-9886-b0a6d6d140ff.png">
</div>

### PS : if we remove HASURA_GRAPHQL_EXPERIMENTAL_FEATURES  :  inherited_roles  then it  start working again

But `inherited_roles` is major feature and we have already designed our system surrounding it , so need a fix for this 

Version : 2.0.3-cloud.1 

Seems like there is issue in [release](https://github.com/hasura/graphql-engine/releases/tag/v2.0.3) which needs to be fixed

**Comment by mirzap** [comment] 2021-07-29 16:34
I can confirm this is still happening in latest release `v2.0.4` @coco98

**Comment by 0x777** [comment] 2021-08-03 05:23
Possibly related to: https://github.com/hasura/graphql-engine/issues/7334?

**Comment by mirzap** [comment] 2021-08-03 05:35
@0x777 Yes, I think #7334 is duplicate of this. @icodeforlove do you have `inherited_roles` enabled?

**Comment by icodeforlove** [comment] 2021-08-03 07:11
@mirzap Yes, I did have this enabled.

**Comment by alexandrim0** [comment] 2021-08-03 12:36
Have the same issue but inherited_roles is not enabled.

**Comment by yogeshwar607** [comment] 2021-08-09 17:00
fixed in v2.0.5

**Closed** 2021-08-09 17:00 UTC

**Comment by alexandrim0** [comment] 2021-08-10 20:28
Hello!

I am not sure about that!
I am using of JWT authentication.
If I create function it is not accessible for authenticated user even from Hasura console until anonymous user access granted.
This happen since 2.0.3 at least, my guess.
I have to duplicate all permissions of authenticated user also for anonymous user and check X-Hasura-User-Id to prevent access.
Is it same bug or I do something wrong? (I did read docs)
