### ISSUE TITLE
Enabling and disabling Event Triggers

### ISSUE THREAD

**Issue by tobiastornros** [hasura/graphql-engine#5288] opened 2020-07-03 12:19 UTC
### Enabling and disabling Event Triggers

Shouldn´t i be nice to be able to enable and disable event triggers from the UI or CLI?

**Comment by tirumaraiselvan** [comment] 2020-07-05 06:26
Closing this as dupe of https://github.com/hasura/graphql-engine/issues/3423

**Closed by tirumaraiselvan** 2020-07-05 06:26 UTC
