### ISSUE TITLE
Hasura Console - Error when relationship is based on >1 Foreign Key Column

### ISSUE THREAD

**Issue by rccoe** [hasura/graphql-engine#8130] opened 2022-02-03 15:12 UTC
### Version Information

Server Version: 2.0.3
CLI Version (for CLI related issue): 2.2.0

### Environment

GCP App engine, running console on M1 mac

### What is the expected behaviour?

http://localhost:9695/console/data/default/schema/public/tables/[table]/relationships should work

### Keywords

foreign key console error relationship 

### What is the current behaviour?

Getting a SWW error:

TypeError: Cannot read properties of null (reading 'length')
    at n (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.0/main.js.gz:1:2549063)
    at n (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.0/main.js.gz:1:3198091)
    at RelationshipEditor.n (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.0/main.js.gz:1:3200223)
    at ns (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.0/vendor.js.gz:1:4891619)
    at ts (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.0/vendor.js.gz:1:4891412)
    at Xl (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.0/vendor.js.gz:1:4927266)
    at jl (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.0/vendor.js.gz:1:4918915)
    at zl (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.0/vendor.js.gz:1:4918840)
    at Ol (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.0/vendor.js.gz:1:4915690)
    at https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.0/vendor.js.gz:1:4866662

### How to reproduce the issue?

1. Create 2 tables (table1, table2), one with a compound foreign key to the other (2 columns)
2. Add, via metadata yaml for table1, an object relationship to table2
```
object_relationships:
- name: table2
  using:
    foreign_key_constraint_on: 
    - id1
    - id2
  ```
  
3. Open the console and go to http://localhost:9695/console/data/default/schema/public/tables/table1/relationships

### Screenshots or Screencast

<img width="1386" alt="Screen Shot 2022-02-03 at 10 11 34 AM" src="https://user-images.githubusercontent.com/1855247/152370336-6c083ee4-5521-498a-b9fe-6790b7ac3d37.png">

### Any possible solutions?

Not sure

### Can you identify the location in the source code where the problem exists?

No

### If the bug is confirmed, would you be willing to submit a PR?

Maybe

**Comment by vijayprasanna13** [comment] 2023-06-23 08:12
@rccoe this seems to be fixed on `v2.28` and the relationships tab has had a redesign. Just to confirm if the issue still exists, I tried the following schema  - 
```sql
-- Create Table1
CREATE TABLE Table1 (
    id1 SERIAL,
    id2 SERIAL,
    PRIMARY KEY (id1, id2)
    -- Add other columns for Table1
);

-- Create Table2
CREATE TABLE Table2 (
    id SERIAL PRIMARY KEY,
    table1_id1 INT,
    table1_id2 INT,
    -- Add other columns for Table2
    FOREIGN KEY (table1_id1, table1_id2) REFERENCES Table1 (id1, id2)
);

```

Which would allow me to create an object relationship like you've mentioned and it works. The console does not crash anymore. Could you give it a try and let me know if the issue still persists on your end?

![Screenshot 2023-06-23 at 1 40 09 PM](https://github.com/hasura/graphql-engine/assets/11921040/8ffa125d-5541-4506-b1cc-2f89f958bd62)

**Comment by vijayprasanna13** [comment] 2023-07-04 07:32
@rccoe this issue is not reproducible in `v2.29.0`. I'm closing this issue for now, but feel free to reopen if it still persists after for you the update.

**Closed by vijayprasanna13** 2023-07-04 07:32 UTC
Labels: k/bug, c/console, support/needs-action, estimate/S

**Comment by sampbarrow** [comment] 2023-08-02 17:42
I am getting a similar error in v2.30.1 when trying to use a foreign key with >1 column for permissions.

https://github.com/hasura/graphql-engine/issues/9811
