### ISSUE TITLE
Add readonly mode to hasura core

### ISSUE THREAD

**Issue by abdullah2993** [hasura/graphql-engine#8109] opened 2022-01-31 09:38 UTC
### Is your proposal related to a problem?
No

### Describe the solution you'd like
It would be nice to have the ability to run a read-only hasura instance so we can run multiple instance to hasura against a single database.

**Comment by jflambert** [comment] 2022-04-06 15:53
Do you mean the Console itself?

Because then this is a duplicate of !5349

**Comment by tirumaraiselvan** [comment] 2022-04-07 03:41
Closing as dupe of #5349

**Closed by tirumaraiselvan** 2022-04-07 03:41 UTC
Labels: k/enhancement
