### ISSUE TITLE
healthz API returns OK not 200

### ISSUE THREAD

**Issue by chrishare08** [hasura/graphql-engine#3398] opened 2019-11-21 22:08 UTC
Documentation says the healthz API returns a 200 on success and a 500 on failure.  This is not what happens.  The API returns the text string "ok".

**Comment by lexi-lambda** [comment] 2019-11-21 22:10
The healthz endpoint returns an HTTP status code of 200 on success and a status code of 500 on failure—the actual response body is not especially meaningful. Are you seeing something else? And if so, what status code are you seeing?

**Comment by chrishare08** [comment] 2019-11-22 12:42
MacBook-Pro-2:.ssh robert.hare$ curl http://172.31.3.214:8080/healthz
OK
MacBook-Pro-2:.ssh robert.hare$ curl -v http://172.31.3.214:8080/healthz
*   Trying 172.31.3.214...
* TCP_NODELAY set
* Connected to 172.31.3.214 (172.31.3.214) port 8080 (#0)
> GET /healthz HTTP/1.1
> Host: 172.31.3.214:8080
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Date: Fri, 22 Nov 2019 03:52:43 GMT
< Server: Warp/3.2.27
< 
* Connection #0 to host 172.31.3.214 left intact
MacBook-Pro-2:.ssh robert.hare$ 

the health check for the AWS target group always fails, even though I can get an okay response from teh EC2 instance

**Comment by amrnt** [comment] 2019-11-22 19:03
> < HTTP/1.1 200 OK
> < Transfer-Encoding: chunked

It says `200 OK` whats the problem?

**Comment by lexi-lambda** [comment] 2019-12-02 17:53
I agree with @amrnt—I’m not totally sure what the issue is here/what you think should work differently. I’m going to close this, but feel free to reopen it if you think it’s still an issue and can provide a little more information.

**Closed by lexi-lambda** 2019-12-02 17:53 UTC
Labels: c/server, k/question, needs-more-info

**Comment by chrishare08** [comment] 2019-12-02 18:45
no worries.  I think we were grasping at straws when we couldn't get the health checks reporting correctly.
