### ISSUE TITLE
only '/v1/graphql', '/v1alpha1/graphql' and '/v1beta1/relay' are supported on websockets

### ISSUE THREAD

**Issue by Tyler-RCSD** [hasura/graphql-engine#9327] opened 2022-12-22 15:22 UTC
https://github.com/hasura/graphql-engine/blob/bcb46c863d6cbffd6dc8e9efa1d6679f339b8763/server/src-lib/Hasura/GraphQL/Transport/WebSocket.hs#L347-L354

I'm using Hasura 2.16.1 and Postgres 12.13 and I'm getting this error message when trying to use sockets in the console to subscribe to anything.  I've gotten this working in development on my local machine but when I move it to production it throws the error.  **My question is this:  does the above check fail if I'm proxying Hasura to a different path than root?**.  i.e. The Hasura endpoint is not https://mycoolwebsite.com/v1/graphql but instead at https://mycoolwebsite.com/gql/v1/graphql.  IF it does fail, is there a reason that it needs to?  If it doesn't fail.. does anything look obviously wrong with my apache config?  Suggestions?

Working apache config:
```
	ProxyPass / http://localhost:8080/
	ProxyPassReverse / http://localhost:8080/
	ProxyPass /v1/graphql ws://localhost:8080/v1/graphql
	ProxyPassReverse /v1/graphql ws://localhost:8080/v1/graphql

	RewriteEngine on
	RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
	RewriteCond %{HTTP:CONNECTION} ^Upgrade$ [NC]
	RewriteRule ^/?(.*) "ws://localhost.ca:8080/$1" [P,L]
```

Not working apache config:

```
	ProxyPass /gql http://localhost:8080/
	ProxyPassReverse /gql http://localhost:8080/
	ProxyPass /gql/v1/graphql ws://localhost:8080/v1/graphql
	ProxyPassReverse /gql/v1/graphql ws://localhost:8080/v1/graphql

	RewriteEngine on
	RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
	RewriteCond %{HTTP:CONNECTION} ^Upgrade$ [NC]
	RewriteRule ^/?(.*) "ws://localhost.ca:8080/$1" [P,L]
```

Thanks :)

**Comment by Tyler-RCSD** [comment] 2023-01-04 17:06
I've gotten this working by changing my RewriteRule to this:

`RewriteRule ^/?(.*) "ws://localhost:8080/v1/graphql" [P,L]`

I don't think this is the best solution to the problem, but it'll do for now.  I think a better solution would be to update the error check so that it allows for this use case.

**Comment by plcplc** [comment] 2024-01-04 09:55
I'm closing this issue since it appears to have a viable workaround and because it has not attracted significant attention over the several months that it has been open.
Feel free to reopen if the issue is still relevant for you.

**Closed by plcplc** 2024-01-04 09:55 UTC
