### ISSUE TITLE
https://localhost:8080/console : Hasura console not working for chrome browser

### ISSUE THREAD

**Issue by santoshpatro** [hasura/graphql-engine#6110] opened 2020-10-31 15:10 UTC
Hi Team,

Any help on this issue is much helpful: https://stackoverflow.com/questions/64623124/https-localhost8080-console-hasura-console-not-working-for-chrome-browser

Thanks,
Santosh

**Comment by beerose** [comment] 2020-11-20 12:54
Hi @santoshpatro, as someone mentioned in the comments on StackOverflow, the console can be accessed on `http://localhost:8080/console` (`http` instead of `https`). Could you confirm that the issue occurs also when you're using HTTP?

**Comment by beerose** [comment] 2021-03-10 17:56
As we can't reproduce this issue, I'm closing it. Please reopen if it happens again.

**Closed by beerose** 2021-03-10 17:56 UTC
Labels: c/console, support/needs-more-info, support/needs-triage
