### ISSUE TITLE
Feature request: Support comment as description for introspection query

### ISSUE THREAD

**Issue by revskill10** [hasura/graphql-engine#1474] opened 2019-01-25 12:14 UTC
Currently if we set value of `comment` in Console UI, it doesn't show as `description` in introspection query.

This feature allows us to use `comment` as `description` for fields/inputFields in introspection query.

**Comment by shahidhk** [comment] 2019-01-26 04:31
Hi @revskill10, thanks for the suggestion. This is already an open issue: https://github.com/hasura/graphql-engine/issues/446

The issue is supposed to propagate all SQL comments to GraphQL schema. The comments in console UI are saved as SQL comments on the objects for tables etc. and as Hasura metadata for relations. 

Closing this as a duplicate.

**Closed by shahidhk** 2019-01-26 04:31 UTC
Labels: duplicate
