### ISSUE TITLE
document usage of current_setting('hasura.user') in custom functions

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#1582] opened 2019-02-11 08:41 UTC
Currently it is documented only in auditing tables.

**Comment by howientc** [comment] 2019-03-08 19:18
Seconded. Thanks to browsing this issue, I poked around and found it's very convenient to access the x-hasura- session variables from within a view or function.

**Comment by tirumaraiselvan** [comment] 2019-11-15 03:22
Quoting from #2940 

> You have access to all sessions variables in your postgres functions using the `current_setting('hasura.user')` function.
> 
> ```
> ...
> DECLARE
>   session_variables json;
> BEGIN
>   session_variables := current_setting('hasura.user', 't');
>   ...
> END;
> ```

**Comment by tirumaraiselvan** [comment] 2019-11-15 20:00
Note that this works only for transactional queries like mutations, event triggers, metadata API.

**Comment by greatwitenorth** [comment] 2020-01-22 21:51
Could someone please provide a full example using `current_setting('hasura.user', 't')`. I'm trying to use the above example, but I keep getting are error when trying to create the function:

```
    "error": {
        "exec_status": "FatalError",
        "hint": null,
        "message": "syntax error at or near \"json\"",
        "status_code": "42601",
        "description": null
    },
```

and my function:

```sql
CREATE OR REPLACE FUNCTION public.test_function()
RETURNS SETOF users as $$
DECLARE 
    session_variables json;
BEGIN
    session_variables := current_setting('hasura.user', 't');

    SELECT
    	*
    FROM
    	users
    WHERE
    	id = session_variables.id
END;
$$ LANGUAGE sql STABLE

```

**Comment by tirumaraiselvan** [comment] 2020-01-29 12:00
@greatwitenorth I don't think `LANGUAGE sql` allows declaring variables: https://stackoverflow.com/questions/24755468/difference-between-language-sql-and-language-plpgsql-in-postgresql-functions

Try switching to `LANGUAGE plpgsql`.

**Comment by marionschleifer** [comment] 2020-05-04 13:16
Closing this issue because it's not possible to access session variables anymore using current_setting('hasura.user') in custom functions. However, it is possible to declare a parameter in custom functions where you want Hasura to send the session variables. This is documented [here](https://hasura.io/docs/1.0/graphql/manual/schema/custom-functions.html#accessing-hasura-session-variables-in-custom-functions).

**Closed by marionschleifer** 2020-05-04 13:16 UTC
Labels: c/docs, e/easy, p/high

**Comment by nilpunning** [comment] 2020-07-03 01:55
`current_setting('hasura.user')` works in 1.2.2 for trigger functions, in what version will it stop working?  Also since trigger functions are not permitted to have named parameters how are you supposed to use the `hasura_session` parameter like the documentation example: `CREATE FUNCTION get_session_role(hasura_session json)`?

**Comment by MichaelHadji-duplicate** [comment] 2020-07-28 11:44
This is very bizzare, and potentially a breaking change for many of us that are using instead of triggers that call hcurrent_setting('hasura.user').

**Comment by tirumaraiselvan** [comment] 2020-07-28 11:49
Hey folks, it is still possible and will continue to be possible to access `current_setting('hasura.user')` . This issue was for read only functions (which never supported this to begin with). A new issue for documenting this is here: https://github.com/hasura/graphql-engine/issues/4738

**Comment by MichaelHadji-duplicate** [comment] 2020-07-28 11:57
Thanks! Will support be provided to allow access to current_setting('hasura.user') when performing a query on a tracked view?

**Comment by tirumaraiselvan** [comment] 2020-07-28 12:00
@MichaelHadji-duplicate Should be. As `INSTEAD OF` triggers are defined for mutations (insert/update/delete), it should be available. Pls let us know if you face any issues.

**Comment by MichaelHadji-duplicate** [comment] 2020-07-28 12:02
INSTEAD OF triggers are used for mutations.. I am unable to use current_setting('hasura.user') when performing a QUERY (not mutation) on a view that uses the hasura.user within the query 'where' filter.

**Comment by tirumaraiselvan** [comment] 2020-07-28 12:06
@MichaelHadji-duplicate That's won't be possible as read only queries don't populate `current_setting('hasura.user')`

**Comment by MichaelHadji-duplicate** [comment] 2020-07-28 12:07
Fear so.. Any work-arounds or plans for such functionality?

**Comment by tirumaraiselvan** [comment] 2020-07-28 12:10
@MichaelHadji-duplicate You can create a custom function with the exact same view and track it. You get access to session variables in custom functions as explained here: https://hasura.io/docs/1.0/graphql/manual/schema/custom-functions.html#accessing-hasura-session-variables-in-custom-functions

**Comment by MichaelHadji-duplicate** [comment] 2020-07-28 12:11
Thanks a lot, will look into it :+1:

**Comment by MichaelHadji-duplicate** [comment] 2020-07-28 12:21
"You can create a custom function with the exact same view and track it." this doesn't make sense to me.. If I have a view that has a couple of columns how am I suppose to replace that with a custom function?? The documentation is not very good/clear.

Also the function must have a table to return to? How does this replace a query on a view.. Confusion.. 
![image](https://user-images.githubusercontent.com/724475/88664536-df42b300-d0e5-11ea-9e35-ece45a5d3671.png)

**Comment by tirumaraiselvan** [comment] 2020-07-29 09:50
@MichaelHadji-duplicate The return type can be `SETOF <view>` also. Here is an example:

```
CREATE OR REPLACE FUNCTION public.test_function(hasura_session json)
 RETURNS SETOF test_view
 LANGUAGE sql
 STABLE
AS $function$
    SELECT * FROM test_view where role = (hasura_session ->> 'x-hasura-role')
$function$
```

One thing to note is that after tracking this function, you will have to go to `Modify` and choose the session variable argument in your function (so that it is automatically populated):

![image](https://user-images.githubusercontent.com/8663570/88785625-13ce7180-d1af-11ea-97d0-eb3100f884a7.png)

Hope this makes sense.

**Comment by MichaelHadji-duplicate** [comment] 2020-07-29 10:06
Thanks, make sense, though for our case it's not an option to use custom functions.. Are there any plans to add the ability to obtain session details in a query on a view? if not, why not?

**Comment by tirumaraiselvan** [comment] 2020-07-29 11:26
@MichaelHadji-duplicate TBH, it is not mighty difficult to add this but it changes the runtime execution for `SELECT` queries a bit  (as we will need to wrap them in BEGIN .. COMMIT) and hence we will have to support this via a special flag (or a directive). See related issue here: https://github.com/hasura/graphql-engine/issues/4011 . Not many users have asked for this as they apply permissions via Hasura authz itself.

Just to be clear, the custom function workaround should give you an API just like your view (including `where` filters,etc). IMHO, It should also not affect the way you consume the API. Is there a reason it doesn't work for your use-case?

**Comment by MichaelHadji-duplicate** [comment] 2020-07-29 11:47
Will experiment for a while and let you know regarding 2nd paragraph.. Thanks for the assistance so far!
TBH if it's easy add it :)

**Comment by 0x777** [comment] 2020-07-29 15:35
@MichaelHadji-duplicate 
> Are there any plans to add the ability to obtain session details in a query on a view? if not, why not?

If we allowed using `hasura.user` in a view definition through `current_setting`, we cannot support subscriptions on the view. The subscription backend fetches the results needed for subscriptions on a view by multiple users in as few queries to Postgres as possible (to lower the load). This means that there is no one-to-one mapping from a subscription made by a user to the underlying query to Postgres that fetches the result, so we cannot set a transaction variable that can be accessed in a view's definition. Hence we ask users to use functions with an explicit `hasura_session` argument if there is such a requirement. 

> I want my view to be able to filter on current_setting('hasura.user') for our own custom purposes, and not have to rely on Hasura authorization

Can you explain how you are planning to use the session variables inside your view definition and how do you plan on exposing the view through Hasura's authz (unless the view is explicitly allowed through hasura's authz, it is not exposed in the GraphQL API)? It'll help us improve our authorization layer :)

**Comment by MichaelHadji-duplicate** [comment] 2020-07-30 05:14
@0x777 

Took a really quick look at custom function. (Just noticed I'm not the only one requesting this feature (https://github.com/hasura/graphql-engine/issues/4011))

The below works with postgres directly though fails through hasura if the query to the hasura.user variables is performed 
within the some_view view itself.

	create or replace function get_some_view(hasura_session json) 
	returns setof some_view language plpgsql stable as $function$
	BEGIN
		
		perform set_config('hasura.user', hasura_session::text, true);

		RETURN QUERY select * from some_view sv;

	END
	$function$;

some_view has an internal where clause that filters on "current_setting('hasura.user', true)::json->>'x-hasura-user-id'"..
Note that if the filter is performed within the function iteself against the view, everything works fine.. Though if performed within the view hasura returns:

 {
  "errors": [
    {
      "extensions": {
        "path": "$",
        "code": "access-denied"
      },
      "message": "Authentication hook unauthorized this request"
    }
  ]

**Comment by MichaelHadji-duplicate** [comment] 2020-07-30 06:11
Another potential issue with custom function is that the view it relates to has to be tracked and permissions set... so there is nothing stopping consumers performing a query on the view, even though they should be using custom function instead....

**Comment by MichaelHadji-duplicate** [comment] 2020-08-04 13:22
Any feedback relating to the last two posts?

**Comment by tirumaraiselvan** [comment] 2020-08-07 16:05
@MichaelHadji-duplicate Sorry for the delay.

> Note that if the filter is performed within the function iteself against the view, everything works fine

Yes, this is the recommended approach if you want to skip the native hasura permission layer. Again, we will be more than happy to hear about your filtering needs and include it natively via hasura perms.

Regarding the error thrown by this, I am not able to reproduce this. And the error "Authentication hook unauthorized this request" kind of suggests that this is thrown at the authentication layer (before hitting PG).

```
create or replace function get_some_view(hasura_session json) 
returns setof some_view language plpgsql stable as $function$
BEGIN
	
	perform set_config('hasura.user', hasura_session::text, true);

	RETURN QUERY select * from some_view sv;

END
$function$;
```

For example, I have set up a similar function in this app: https://get-some-view.herokuapp.com/ and I can query like so:

![image](https://user-images.githubusercontent.com/8663570/89663356-10e02900-d8f3-11ea-95ea-6f5f43caa782.png)

As discussed above, we do not really recommend the above approach (of using current_setting in view definition) and a detailed analysis will be posted in #4011 soon. In brief: it doesn't work for non-hasura connections, cannot use with subscriptions, and some more.

> Another potential issue with custom function is that the view it relates to has to be tracked and permissions set... so there is nothing stopping consumers performing a query on the view, even though they should be using custom function instead....

This is a valid concern and our upcoming schema customization work (for instance, this: https://github.com/hasura/graphql-engine/pull/4110 which is marked for v1.4 release) will allow you to hide the view generated field. We can also discuss other potential features/workarounds that will allow you to use the custom function but not the view.

**Comment by 0x777** [comment] 2020-08-10 10:25
>  I want my view to be able to filter on current_setting('hasura.user') for our own custom purposes, and not have to rely on Hasura authorization.

@MichaelHadji-duplicate Is it because the filter condition cannot be specified using permissions in graphql-engine? Because by using the `hasura.user` config variable you are already relying on Hasura's authorization.

**Comment by MichaelHadji-duplicate** [comment] 2020-08-10 18:54
Well we can abstract out hasura.user if needed on our end, so the reliance is minimised. Please do not try to convince all of us to rely on Hasura's authorization model, we may have many systems that integrate with our database's, not only Hasura!

This feature (query views / variables) missing from Hasura is very unfortunate, and forcing us to add custom functions (a hack) is an inconvenience at best....

**Comment by lsegal** [comment] 2025-03-15 22:07
This link is 404ing. Is there an updated link to the documentation?

**Comment by coffenbacher** [comment] 2025-04-02 15:07
> @MichaelHadji-duplicate Is it because the filter condition cannot be specified using permissions in graphql-engine? Because by using the hasura.user config variable you are already relying on Hasura's authorization

I know this is an old issue but our motivation for trying this is that the Hasura authz system results in huge queries for us and Postgres can't push down the predicates consistently enough. A simple hand-written view with predicates in-lined is way quicker in our testing.
