### ISSUE TITLE
[BUG] Hasura doesn't calculate correctly small numbers _inc

### ISSUE THREAD

**Issue by perrosnk** [hasura/graphql-engine#4733] opened 2020-05-11 11:01 UTC
If you use a number less than 0.000001 (6 decimals) which javascript converts it to 1E-7 hasura doesn't calculate correctly the _inc value.

This has caused a lot of trouble to us. Could we expect a fix?

**Comment by abooij** [comment] 2020-05-11 12:12
What postgres type are you using to store these values? And can you please also show which values you are adding up (including before, after, and expected values)?

Note that the `real` postgres type is mapped to a 4 byte IEEE 754 float, which doesn't have more than 6 decimals of precision: so for these types, `_inc`ing a small value such as 0.000001 can, by the very definition of IEEE 754, be forced to be the same as adding 0, and this should be calculated by graphql-engine correctly. So this would not be a mistake of graphql-engine, but rather a shortcoming of IEEE 754.

(Worse: if you are adding a `real` to another `real` with a large value may mean even `_inc`ing the value 1 may end up adding 0: for instance, `1E8+1=1E8` rather than `1.00000001E8`. See also [this](http://weitz.de/ieee/) IEEE 754 calculator - click "binary32" at the bottom of the page for a 4 byte precision float. Indeed, floats are problematic in all software, but graphql-engine should not introduce any additional problems.)

**Comment by perrosnk** [comment] 2020-05-11 12:31
@abooij I am using numeric

**Comment by abooij** [comment] 2020-05-11 12:35
@perrosnk Could you please show which values you are adding up (including before, after, and expected values)?

**Comment by perrosnk** [comment] 2020-05-11 12:42
@abooij I am actually trying to decrement a value using `_inc: {coins: ${-amount}}`.
This amount variable can be a floating point down to `1E-8`. Hasura mistakenly substacts `1` instead of `0.00000001`

**Comment by abooij** [comment] 2020-05-11 12:54
@perrosnk Sorry, I'm really going to need some more details in order to reproduce this issue. Can you please show a sequence of GraphQL queries and their corresponding outputs, indicating precisely where you believe Hasura to be mistaken?

**Comment by perrosnk** [comment] 2020-05-11 13:14
@abooij I have a model `User` and a column `balance` of type numeric.

I want to **decrement** the `balance` using an `update_user_by_pk` mutation.
The `amount` variable shown above is also a Float number, and can be greater or equal to `0.00000001` (8 decimal point). 

The amount is a variable sent by the user, and is `1E-8`.
When I use the code

```graphql
update_users_by_pk(pk_columns: {id: "${senderId}"}, _inc: {balance: ${-amount}}) {
    id
  }
```

hasura mistakenly decrements the balance by `1` and not `0.00000001`

By the way, the variable amount passed to the mutation is not a string, it's a number.

Was that information enough or do you need any further information? Please let me know

**Comment by tirumaraiselvan** [comment] 2020-05-11 13:30
Hi @perrosnk I guess it is getting clearer what the issue is. You are trying to send the literal `1E-8` as a value to the numeric field? 

Since this is not an actual valid graphql query:

```
update_users_by_pk(pk_columns: {id: "${senderId}"}, _inc: {balance: ${-amount}}) {
    id
  }
```

because the variable usage is not [graphql syntax](https://spec.graphql.org/June2018/#sec-Validation.Variables). Could you send the final query that is being sent to the server?

**Comment by perrosnk** [comment] 2020-05-11 13:48
Here is the actual graphql string:

```graphql
      mutation MyMutation {
        update_users_by_pk(pk_columns: {id: "aLongUUID"}, _inc: {coins: -1e-8}) {
          id
        }
      }

```

**Comment by abooij** [comment] 2020-05-11 14:03
Thanks for reporting this, @perrosnk. I have found the origin of this issue. I will send in a PR to fix this today or tomorrow.

**Comment by perrosnk** [comment] 2020-05-11 14:06
Could this be released to npm as a patch version (ex.1.2.2) or do we need to wait for the next release?

**Comment by abooij** [comment] 2020-05-11 15:49
@perrosnk As a workaround, you can either pass the value as a string, or convert it to non-scientific notation. In other words, the following queries should work:

```graphql
mutation MyMutation {
  update_users_by_pk(pk_columns: {id: "aLongUUID"}, _inc: {balance: "-1e-8"}) {
    id
  }
}
```
```graphql
mutation MyMutation {
  update_users_by_pk(pk_columns: {id: "aLongUUID"}, _inc: {balance: 0.00000001}) {
    id
  }
}
```

**Comment by perrosnk** [comment] 2020-05-11 17:25
@abooij I tested the option of `"-1e-8"` and it doesn't work. I am not sure if I can test the other option because javascript makes the number automatically 1E-8. I should use `number.toFixed(8)`, but this returns a string too.

**Comment by abooij** [comment] 2020-05-11 18:09
@perrosnk I'm sorry to hear the workaround doesn't work for you. Make sure you are using the quote symbols, so passing the value as `"-1E-8"` rather than `-1E-8` in the actual GraphQL string (the format you posted [here](https://github.com/hasura/graphql-engine/issues/4733#issuecomment-626713184)).

In any case, I have prepared a fix for this, so hopefully this will be part of graphql-engine soon.

**Comment by perrosnk** [comment] 2020-05-11 18:41
@abooij I passed `"-1E-8"` but it doesn't work. It doesn't work even if I pass `"0.00000001"` (as a string). I can't pass it as a decimal number `0.00000001` because javascript automatically converts it to `1E-8`

**Closed** 2020-05-13 10:10 UTC
Labels: k/bug

**Comment by perrosnk** [comment] 2020-05-15 14:13
@abooij When may we expect this to be released?

**Comment by abooij** [comment] 2020-05-18 16:14
@perrosnk Keep an eye out for the latest releases, hopefully it'll be out soon!
