### ISSUE TITLE
Link to  inconsistent state/metadata github issue in server logs whenever this happens

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#1721] opened 2019-03-08 06:20 UTC
Instead of just saying "X table not found" , the server logs can also point to
https://github.com/hasura/graphql-engine/issues/231

@shahidhk Also, please update the #231 with a link to the troubleshooting guide on docs.

**Comment by manasag** [comment] 2023-12-28 16:59
This issue has not attracted significant attention for a long period of time, hence closing this.
Please feel free to reopen if the issue is still relevant for you.

**Closed by manasag** 2023-12-28 16:59 UTC
Labels: k/enhancement, c/server, e/quickfix, p/medium, a/api/metadata
