### ISSUE TITLE
v1.3.0-beta.4 clone button click and bug

### ISSUE THREAD

**Issue by mkalayci35** [hasura/graphql-engine#5362] opened 2020-07-13 08:34 UTC
![Screen_Shot_2020-07-12_at_20 06 36](https://user-images.githubusercontent.com/38668796/87282336-d73b1e80-c4fc-11ea-9541-30c524a577b3.png)

**Comment by beerose** [comment] 2020-07-13 09:23
Closing as a duplicate of https://github.com/hasura/graphql-engine/issues/5336. Will be fixed in beta via https://github.com/hasura/graphql-engine/pull/5337.

**Closed by beerose** 2020-07-13 09:23 UTC
