### ISSUE TITLE
[console] Fields wrongly displayed as unique

### ISSUE THREAD

**Issue by deathemperor** [hasura/graphql-engine#7271] opened 2021-07-21 08:06 UTC
Hasura version 2.0.3

Field displayed:

![image](https://user-images.githubusercontent.com/4255482/126451905-33ff118f-2e24-467c-81da-ecfd904fe15c.png)

Data:

![image](https://user-images.githubusercontent.com/4255482/126451951-9a455883-5bc0-4a11-ac7e-dd3f3088559f.png)

Our intention isn't unique either. This is a one-to-many relationship between `user_role` table to `claim_requests` (one user role has many claim requests).

Don't know why all the unique keys are from as below while we only mark one field as unique: "claim_code"

![image](https://user-images.githubusercontent.com/4255482/126452796-898f889d-f520-481f-85a9-8cf5028b2fd9.png)

If I remove a field from the table, it will display correctly when finishes. Refreshing the page will make all the wrong info appears again.

![image](https://user-images.githubusercontent.com/4255482/126453155-1c6570d4-9089-4ae2-8ec0-4551e3455461.png)

This only appears on one of our table, I tried creating another table but couldn't reproduce it.

I tried everything but nothing fix it: Reloading database and schemas, restarting graphql-engine, restarting database, restarting console.

**Comment by ilyozzz** [comment] 2021-09-06 08:38
I have the same bug. console ver 2.0.7

**Comment by afmotta** [comment] 2022-02-21 09:55
Hey folks, thanks for reporting this issue. 
We're looking into it, will ping you when we've better understood the reasons behind this behaviour.
In the meantime, it would be really helpful if you could provide us with a minimal reproducible schema for the bug.
Thanks!

**Comment by afmotta** [comment] 2022-04-04 08:42
Hey folks, we're closing this as there was not enough informations to reproduce.
If you experience this issue again, feel free to reopen it.

**Closed by afmotta** 2022-04-04 08:42 UTC
Labels: k/bug, c/console, support/needs-more-info, c/console/data
