### ISSUE TITLE
Add ability to delete scheduled events via API

### ISSUE THREAD

**Issue by sondh0127** [hasura/graphql-engine#5025] opened 2020-06-09 07:09 UTC
There is no option to remove an event after `create_scheduled_event`

[Snipped orthogonal header issue from original post]

**Comment by codingkarthik** [comment] 2020-06-09 07:30
@sondh0127 the `headers` field expects an array of objects. 

The API documentation is here:

https://hasura.io/docs/1.0/graphql/manual/api-reference/schema-metadata-api/scheduled-triggers.html#create-scheduled-event-syntax

I see the example used is from the docs and it's not using an array, thanks for reporting this. We'll fix this.

**Comment by aaronhayes** [comment] 2020-06-22 07:23
@tirumaraiselvan is this expected to be in `v1.3.0`? 
It's a pretty big oversight leaving this feature out IMO.

The `create_scheduled_event` API also should return the scheduled event `id`.

**Comment by tirumaraiselvan** [comment] 2020-07-02 08:39
This facility has been added in console via https://github.com/hasura/graphql-engine/pull/5236

@aaronhayes It does seem idiomatic for `create_scheduled_event` to return the `id` but how might you use that value? Are you building something custom with the API?

**Comment by aaronhayes** [comment] 2020-07-02 08:59
@tirumaraiselvan assuming there is an API to cancel/delete a scheduled event; the ID would be used to call that API and cancel the event.

This and example how would like to be use the API.
- User schedules video to be created at XX
   - Our action handler creates the scheduled event
   - _We store the scheduled event `id` along with the time, metadata about the video to be created_
- User changes their minds or no longer wants the video to be created
   - _Our action handler would lookup the `id` and cancel the event_
 
Currently we have to use boolean flag in the DB that called `canceled_event`. Which our scheduled trigger handle looks up to proceed/stop when the event is triggered. IMO it would be much better to be able to simply cancel the event trigger.

**Comment by tirumaraiselvan** [comment] 2020-07-02 09:04
@aaronhayes Fair enough. I am changing the title to reflect this request.

**Comment by lakhansamani** [comment] 2020-09-28 06:38
It is very important to have control over schedule events.
Would love to have 
1. ability to update schedule event date/time
2. ability to delete the scheduled event.

Anyone working on this issue or any ETA?

If this issue is not in progress,  I can look more into the implementation of this.

**Comment by Johann-L-Pickard** [comment] 2020-12-21 22:53
Also really really want this feature, seems so strange to have a way to post a scheduled call only, but not read or update or delete it ? C  ... RUD

**Comment by Rykuno** [comment] 2021-02-09 21:54
@tirumaraiselvan or any member of Hasura, is there any support or roadmap for this feature as of today?

**Comment by kolharsam** [comment] 2021-09-14 03:49
Hello folks! This issue was resolved a while ago but we'd missed documenting it. The documentation for this API was resolved in bafefac. The API can be consumed via our metadata API, here's a gist of the same:

```json

POST /v1/metadata

{
  "type": "delete_scheduled_event",
  "args": {
     "type": "cron",
     "event_id": "<EVENT ID>"
   }
}

```

Here the `type` can be either `cron` or `one_off`. 

Apologies for any inconvenience caused. 🙏

**Closed by kolharsam** 2021-09-14 03:49 UTC
Labels: c/server, c/scheduled-triggers, a/api, a/eventing/scheduled-events

**Comment by DaleBeckles** [comment] 2021-09-14 13:49
Thanks for getting this done.

I just tested with "type" set to "one_off" and the returned status code was 200, however, the scheduled event was not deleted. With "type" set to "cron" it worked correctly and deleted the scheduled event.

**Comment by kolharsam** [comment] 2021-09-14 15:59
@DaleBeckles I tested this on a new cloud project, the API functions as intended. Could you provide more details about the scheduled event?
