### ISSUE TITLE
ra-hasura-data: The response to 'GET_LIST' must be like { data: ... }, but the received response does not have a 'data' key. The dataProvider is probably wrong for 'GET_LIST'.

### ISSUE THREAD

**Issue by mihazs** [hasura/graphql-engine#2619] opened 2019-07-29 03:31 UTC
Hello, i'm using react admin with hasura with the following code:

File for CRUD associado:
```javascript
import React from 'react';
import { List, Datagrid, TextField, Show, SimpleShowLayout, DateField } from 'react-admin';

export function AssociadoList(props) {
    return (
        <List {...props}>
            <Datagrid>
                <TextField source="nome" />
                <DateField source="data_aniversario" />
                {/*<ReferenceField label="Endereço" source="enderecoId" reference="enderecos">
                <TextField source="bairro" />
                <TextField source="bairro" />
            </ReferenceField>*/}
            </Datagrid>
        </List>
    )
};

export function AssociadoShow(props) {
    return (
        <Show {...props}>
            <SimpleShowLayout>
                <TextField source="nome" />
                <DateField source="data_aniversario" />
            </SimpleShowLayout>
        </Show>
    )
};
```
The auth provider:
```javascript
import { AUTH_LOGIN, AUTH_LOGOUT, AUTH_ERROR, AUTH_CHECK } from 'react-admin';
import graphql from './graphqlClient';
import Cookies from 'universal-cookie';
import { GraphQLClient } from 'graphql-request';

const cookies = new Cookies();

const LOGIN = `
    mutation($username:String!, $password:String!){
        login(username: $username, password: $password){
            token
        }
    }
`;
const ME = `
    query {
        me {
            username
        }
    }
`;

export default (type, params) => {

    if (type === AUTH_LOGIN) {
        const { username, password } = params;
        return graphql.request(LOGIN, { username, password }).then(data => {
            const token = data.login.token;
            cookies.set("authToken", token, { path: "/", sameSite: "strict" });
        });
    }
    if (type === AUTH_LOGOUT) {
        cookies.remove("authToken", { path: "/", sameSite: "strict" });
        return Promise.resolve();
    }
    if (type === AUTH_ERROR) {
        const graphqlauth = new GraphQLClient(process.env.REACT_APP_HASURA_ENDPOINT, {
            headers: {
                authorization: 'Bearer ' + cookies.get('authToken'),
            },
        })
        return graphqlauth.request(ME).then(data => { return (data.me.username) ? Promise.resolve() : Promise.reject(); }).catch(e => {
            cookies.remove("authToken", { path: "/", sameSite: "strict" });

        });

    }
    if (type === AUTH_CHECK) {
        return cookies.get('authToken') ? Promise.resolve() : Promise.reject();
    }
    return Promise.resolve();
};
```

and the App.js;
```javascript
import React from 'react';
import { Admin, Resource } from 'react-admin';
import Dashboard from './Dashboard';
import hasuraDataProvider from 'ra-data-hasura';
import authProvider from './authProvider';
import Cookies from 'universal-cookie';
import { AssociadoList, AssociadoShow } from "./Associado";
import portugueseMessages from 'ra-language-portuguese'


const dataProvider = function () {

  const cookies = new Cookies();
  const dataProvider = hasuraDataProvider(process.env.REACT_APP_HASURA_URL, { "content-type": "application/json", "Authorization": "Bearer " + cookies.get("AuthToken") });
  return dataProvider;
}
const messages = {
  'pt': portugueseMessages,
};
const i18nProvider = locale => messages[locale];
function App() {
  return (
    <Admin
      dataProvider={dataProvider}
      authProvider={authProvider}
      dashboard={Dashboard}
      locale="pt" i18nProvider={i18nProvider}
    >
      <Resource name="adear.associado" list={AssociadoList} options={{ label: 'Associado' }} show={AssociadoShow} />
    </Admin>
  );
}

export default App;

```

And i'm getting the error: The response to 'GET_LIST' must be like { data: ... }, but the received response does not have a 'data' key. The dataProvider is probably wrong for 'GET_LIST'.

I really don't know what i'm doing wrong.

Here is my package.json
```json
{
  "name": "dashboard",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "graphql-request": "^1.8.2",
    "ra-data-hasura": "^0.0.6",
    "ra-language-portuguese": "^1.5.1",
    "react": "^16.8.6",
    "react-admin": "2.9.5",
    "react-cookie": "^4.0.1",
    "react-dom": "^16.8.6",
    "react-scripts": "3.0.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```
The authentication is working fine, but i can't see any request for query the "associado" data.
What's wrong?

I'm getting:
```
The response to 'GET_LIST' must be like { data: ... }, but the received response does not have a 'data' key. The dataProvider is probably wrong for 'GET_LIST'.
```

**Comment by praveenweb** [comment] 2019-08-08 11:13
Hi @mihazs - I couldn't replicate your error. Also the dataProvider returns the response in the expected format for `GET_LIST`. Here's the [source](https://github.com/hasura/graphql-engine/blob/master/community/tools/ra-data-hasura/src/index.js#L201) for the same.

May be if you can give a repo with reproducible example, i can help debug further.

**Comment by mihazs** [comment] 2019-08-11 23:48
I've updated the code, and now, my problem is that the headers are not updated when login are done.
It's the same related problem:
the auth provider:

```javascript
import { AUTH_LOGIN, AUTH_LOGOUT, AUTH_ERROR, AUTH_CHECK } from 'react-admin';
import graphql from './graphqlClient';
import Cookies from 'universal-cookie';
import { GraphQLClient } from 'graphql-request';
const cookies = new Cookies();

const LOGIN = `
    mutation($username:String!, $password:String!){
        login(username: $username, password: $password){
            token
        }
    }
`;
const ME = `
    query {
        me {
            username
        }
    }
`;

export default (type, params) => {

    if (type === AUTH_LOGIN) {
        const { username, password } = params;
        return graphql.request(LOGIN, { username, password }).then(data => {
            const token = data.login.token;
            
            cookies.set("authToken", token, { path: "/", sameSite: "strict" });
            localStorage.setItem("loggedIn", true);
            //localStorage.setItem("reloaded", false);
            
        });
    }
    if (type === AUTH_LOGOUT) {
        cookies.set("authToken", "", { path: "/", sameSite: "strict" });
        localStorage.setItem("loggedIn", false);
        localStorage.removeItem("reloaded");
        return Promise.resolve();
    }
    if (type === AUTH_ERROR) {
        const graphqlauth = new GraphQLClient(process.env.REACT_APP_HASURA_ENDPOINT, {
            headers: {
                authorization: 'Bearer ' + cookies.get('authToken'),
            },
        })
        return graphqlauth.request(ME).then(data => { return (data.me.username) ? Promise.resolve() : Promise.reject(); }).catch(e => {
            cookies.set("authToken", "", { path: "/", sameSite: "strict" });
            localStorage.setItem("loggedIn", false);

        });

    }
    if (type === AUTH_CHECK) { 
        const graphqlauth = new GraphQLClient(process.env.REACT_APP_HASURA_ENDPOINT, {
            headers: {
                authorization: 'Bearer ' + cookies.get('authToken'),
            },
        })
        return graphqlauth.request(ME).then(data => { return (data.me.username) ? Promise.resolve() : Promise.reject(); });
        //return cookies.get('authToken') &&  cookies.get('authToken') !== "" ? Promise.resolve() : Promise.reject();
    }
    return Promise.resolve();
};
```
and the app.js:
``jsx
import React from 'react';

import { Admin, Resource,  } from 'react-admin';
import Dashboard from './Dashboard';
import hasuraDataProvider from 'ra-data-hasura';
import authProvider from './authProvider';
import {Cookies} from "react-cookie";
import { AssociadoList, AssociadoShow } from "./Associado";
import portugueseMessages from 'ra-language-portuguese';
import LoginPage from "./Login";
import "./App.scss";
const ucookies = new Cookies();

function dataProvider() {
  const dataProvider = hasuraDataProvider(process.env.REACT_APP_HASURA_URL, { "content-type": "application/json", "Authorization": "Bearer " +  ucookies.get("authToken")});
  return dataProvider;
}
const messages = {
  'pt': portugueseMessages,
};
const i18nProvider = locale => messages[locale];
function App() {

  return (
    <Admin
      dataProvider={dataProvider()}
      authProvider={authProvider}
      dashboard={Dashboard}
      loginPage={LoginPage}
      locale="pt" i18nProvider={i18nProvider}
    >
      <Resource name="adear.associado" list={AssociadoList} options={{ label: 'Associado' }} show={AssociadoShow} />
    </Admin>
  );
}

export default App;
```
And i got: 
```
{"path":"$","error":"Malformed Authorization header","code":"invalid-headers"}
``` 

If i reload the page, the admin component are reloaded and the dataProvider function are called again, than the header are refreshed, and everything works.


I've used the localStorage instead of cookies, but its has the same result.

The problem is that when i authenticate, i change the headers and they aren't updated in dataProvider. The current architeture make this impossible.

How can i make the headers of ra-hasura-data be updated?

**Comment by mihazs** [comment] 2019-08-26 09:43
I really don't know why to close the issue '-'.

I already have a bult-in auth system.
This isn't the problem of my auth system.

The hasura adapter for react-admin didn't support dynamic headers very well. There's a way to solve that?

**Comment by praveenweb** [comment] 2019-09-17 10:09
@mihazs - We will be adding `httpClient` argument instead of a static header object to solve this. 
Closing this as duplicate of #2771

**Closed by praveenweb** 2019-09-17 10:09 UTC
Labels: c/ra-data-hasura, k/question
