### ISSUE TITLE
Table's comment with ['s] causes sql error

### ISSUE THREAD

**Issue by deathemperor** [hasura/graphql-engine#6935] opened 2021-05-16 10:13 UTC
Table: user_sources
Add Comment to table: "A user's source"

Generated SQL:
```sql
CREATE TABLE "public"."user_sources" ("value" varchar NOT NULL, "comment" varchar, PRIMARY KEY ("value") );COMMENT ON TABLE "public"."user_sources" IS E'user\'s sources enum';
```

Insert value also cause the same issue

```sql
INSERT INTO "public"."company_roles"("value", "comment") VALUES ('user', 'can access a company's certain resources');
```

Happens on Hasura 2.0.0 alpha 10

**Comment by beaussan** [comment] 2021-05-19 10:18
I'm having trouble to reproduce this issue, could you provide more information ? Or even better a reproduction repo ?

**Comment by deathemperor** [comment] 2021-05-20 09:04
I've created a reproducible repo here: https://github.com/deathemperor/hasura-sql-escape-bug

Forgot to mention that it runs on `fedormelexin/graphql-engine-arm64:v2.0.0-alpha.10.cli-migrations-v3` image because I'm on Apple M1. I'm able to reproduce it with an official image.

Also, CLI version is 2.0.0 alpha 10.

**Comment by deathemperor** [comment] 2021-05-20 09:11
I confirm the issues do happen when running with official image of the same version

**Comment by beaussan** [comment] 2021-05-21 06:55
Thank you ! I will look into it

**Comment by abhi40308** [comment] 2021-06-30 12:17
Hi @deathemperor , I was trying to replicate this error but couldn't. 
Version: `hasura/graphql-engine:v2.0.0-alpha.10.cli-migrations-v3`
Steps:

1. I tried creating a table with name "user_sources".
2. Added comment "A user's source" and it's working for me.
<img width="362" alt="Screenshot 2021-06-30 at 5 46 35 PM" src="https://user-images.githubusercontent.com/26903230/123958807-20fd6d00-d9cb-11eb-80b0-57f2768dcf99.png">


I have created a repro [here](https://github.com/abhi40308/hasura-cli-comment-pg-repro).
I also looked into the [repro](https://github.com/hasura/graphql-engine/issues/6935#issuecomment-844888333) provided, but could not find any issue. Please let me know if I missed something.

**Comment by deathemperor** [comment] 2021-07-01 07:16
@abhi40308 I can confirm that using ' in table comment doesn't cause error as stated. Tested on 2.0.1

But inserting values with ' still generating wrong sql

`INSERT INTO "mp"."test"("id", "name") VALUES (1, 'a user's source');`

**Comment by abhi40308** [comment] 2021-07-07 19:24
Hey @deathemperor, seems like you have quotes in a text value field and you are not escaping the quotes.
```
INSERT INTO "mp"."test"("id", "name") VALUES (1, 'a user''s source');
```
This will be the correct SQL to insert values in this case. Please let us know if you still face problem.

**Comment by deathemperor** [comment] 2021-07-07 20:56
@abhi40308 I understand that. The problem is I'm inserting using the console and the SQL is generated when I marked the insert as "this is a migration".

**Comment by abhi40308** [comment] 2021-07-08 06:42
@deathemperor  thank you! I can reproduce this. Will look into it.

**Comment by abhi40308** [comment] 2021-07-27 19:33
This should be fixed now ref https://github.com/hasura/graphql-engine/commit/76d1430703f6643818d2e8e53436c7cc17682e69

**Closed by abhi40308** 2021-07-27 19:33 UTC
Labels: c/console

**Comment by deathemperor** [comment] 2021-07-28 06:35
@abhi40308 thanks. Just of out curiosity, why aren't the console project use absolute paths for module imports?

**Comment by abhi40308** [comment] 2021-07-28 09:29
@deathemperor Hey I think it's more of a preference thing, as we kept it that way since the beginning, but yeah changing to absolute from relative paths is surely something we can think about doing in the future.
