### ISSUE TITLE
Voyager feature in GraphiQL section

### ISSUE THREAD

**Issue by huss-jay** [hasura/graphql-engine#7160] opened 2021-07-01 03:13 UTC
I have upgraded to Hasura 2.0.0-beta and when i try to use the voyager feature in the GraphiQL section, it results in an error page with this error:

Error: abort(7). Build with -s ASSERTIONS=1 for more info.
    at Array.r.listeners.<computed> (https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v2.0/vendor.js.gz:1:6886012)
    at Worker.<anonymous> (https://graphql-engine-cdn.hasura.io/console/assets/channel/beta/v2.0/vendor.js.gz:1:6885841)

**Comment by rikinsk** [comment] 2021-07-01 08:16
Seems to be aduplicate of https://github.com/hasura/graphql-engine/issues/3023. Closing this.

**Closed by rikinsk** 2021-07-01 08:16 UTC
Labels: c/console
