### ISSUE TITLE
Relationship names should respect naming convention

### ISSUE THREAD

**Issue by kevinmichaelchen** [hasura/graphql-engine#9427] opened 2023-02-08 20:54 UTC
### Is your proposal related to a problem?

Hasura generates a relationship whenever foreign keys are tracked.

We use snake_case foreign key constraints in Postgres and have adopted the graphql-default [naming convention](https://hasura.io/docs/latest/schema/postgres/naming-convention/).

However, the relationship names that Hasura generates are still snake_cased.

### Describe the solution you'd like

The expectation, I think, is that they would be generated as camelCase.

### Describe alternatives you've considered

The solution is to manually change each relationship name's casing one by one.

**Comment by tirumaraiselvan** [comment] 2023-02-09 03:52
Dupe of https://github.com/hasura/graphql-engine/issues/8573

**Comment by tirumaraiselvan** [comment] 2023-02-16 12:17
Let's continue in the original issue: https://github.com/hasura/graphql-engine/issues/8573 

We have an update there as well.

**Closed by tirumaraiselvan** 2023-02-16 12:17 UTC
Labels: k/enhancement, t/native-dbs
