### ISSUE TITLE
Request Feature: Add ability to run specific hasura mutation in cron triggers

### ISSUE THREAD

**Issue by ghyath5** [hasura/graphql-engine#5199] opened 2020-06-24 13:20 UTC
Thank you for the great cron triggers feature.
Please add ability to run specific mutation in this cron-triggers, it could be super great feature

**Comment by tirumaraiselvan** [comment] 2020-07-02 15:44
Closing this as dupe of #5050

**Closed by tirumaraiselvan** 2020-07-02 15:44 UTC
