### ISSUE TITLE
maintain list of exceptions for relationship naming suggestions

### ISSUE THREAD

**Issue by benoitscherrer** [hasura/graphql-engine#2024] opened 2019-04-17 13:32 UTC
The new relationship names are definitely nicer when it works, but it might be quite challenging to get it to work well.
Example: One of my table is named `Series`. Because of the `s` it considers this is plural, and for a "back link" (one-to-one relationship) it creates the relation `Sery` ... which is not ideal (we say "one series", "two series")
Every language having exceptions, it would be great if you implement a dictionary of exceptions... (would probably be pretty easy)

More generally, how is this going to handle different languages? In other languages various words terminate by 's' without being a plural (e.g., 'fils', 'corps', 'temps' in french. In Latin.... almost every 2 words ;) , although not sure that many people use Latin to name their tables.)

**Comment by manasag** [comment] 2023-12-28 17:54
This issue has not attracted significant attention for a long period of time, hence closing this. Also in Hasura V3, users have the ability to customise all the types (which includes relationships).
Please feel free to reopen if the issue is still relevant for you.

**Closed by manasag** 2023-12-28 17:54 UTC
Labels: k/enhancement, c/console, p/longterm, e/easy
