### ISSUE TITLE
Server: Functions/views missing in CockroachDB

### ISSUE THREAD

**Issue by plcplc** [hasura/graphql-engine#8821] opened 2022-08-19 13:34 UTC
The GraphQL Engine relies on various Postgres SQL functions which have not been implemented in CockroachDB yet.

The lists below are incomplete and should be updated if more functions are found to be missing.

For each of these we either have to work around or engage with CockroachDB to provide implementations.

Console support:

- [x] `pg_is_other_temp_schema`
- [x] `pg_has_role`
- [x] `pg_get_functiondef` ([will be available in cockroach v22.2](https://github.com/cockroachdb/cockroach/pull/87439))
- [x] `pg_get_viewdef`
- [ ] `!~~` (alias for `NOT LIKE`)

Server support:

- [x] `jsonb_to_recordset` (will be available in `cockroach v22.2`)

**Comment by plcplc** [comment] 2022-08-22 15:53
c.f. https://github.com/cockroachdb/cockroach/pull/82435

**Comment by ZhouXing19** [comment] 2022-08-22 17:12
In [22.1](https://www.cockroachlabs.com/docs/stable/functions-and-operators.html) the CRDB side has already supported:

- [x] `pg_is_other_temp_schema`: Returns true if the given OID is the OID of another session’s temporary schema.
- [x] `pg_has_role`: Returns whether or not the user has privileges for role.
- [x]  `pg_get_viewdef`: Returns the CREATE statement for an existing view. (It's been implemented, but the doc missed it by mistake. We're [fixing the doc for it](https://github.com/cockroachdb/cockroach/pull/86579).)

We don't support `pg_get_functiondef`, `!~~` and `jsonv_to_recordset` yet.

**Comment by rafiss** [comment] 2022-09-08 21:16
`pg_get_functiondef` will be available in v22.2 as well

**Comment by sassela** [comment] 2022-09-15 08:30
thanks @rafiss ! @plcplc , looks like we only have `!~~` remaining. Is there any reason why we couldn't just swap the alias out for `NOT LIKE`? If not, please could you point me to exactly where you came across it?

**Comment by sassela** [comment] 2022-09-19 15:42
confirmed with Philip at the CockroachDB sync, we can simply replace the alias with the statement `NOT LIKE`, wherever it's blocking us for CockroachcDB. Closing this as done

**Closed by sassela** 2022-09-19 15:42 UTC
Labels: c/server, cockroachdb, t/native-dbs

**Comment by i-am-tom** [comment] 2022-09-26 14:01
A cursory grep suggests that `!~~` only exists in four places, three of which (1, 2, 4 below) are probably not important anyway!

```
console/src/dataSources/services/citus/sqlUtils.ts
269:pn.nspname::text !~~ 'pg_%'::text

console/src/dataSources/services/postgresql/sqlUtils.ts
894:pn.nspname::text !~~ 'pg_%'::text

frontend/libs/console/legacy-oss/src/lib/dataSources/services/citus/sqlUtils.ts
269:pn.nspname::text !~~ 'pg_%'::text

frontend/libs/console/legacy-oss/src/lib/dataSources/services/postgresql/sqlUtils.ts
887:pn.nspname::text !~~ 'pg_%'::text
```
