### ISSUE TITLE
Error while inserting 

### ISSUE THREAD

**Issue by MarcelloTheArcane** [hasura/graphql-engine#3704] opened 2020-01-14 15:38 UTC
I am unable to insert with a non-admin user role - permissions have been enabled (but I am having issues, see #3703)

This happens with I can insert with the `admin` role.

### Query:
```gql
mutation add_task (
  $sprintId: uuid!
  $goal: String!
  $pillar: String
) {
  insert_tasks (
    objects: {
      sprint_id: $sprintId
      goal: $goal
      pillar: $pillar
    }
  ) {
    affected_rows
  }
}
```
*Variables*: 
```json
{
  "sprintId": "c140f434-4125-4081-903e-4d06bdfab25d",
  "goal": "test",
  "pillar": "test"
}
```

### Response: 
```json
{
  "errors": [
    {
      "extensions": {
        "path": "$.selectionSet.insert_tasks.args.objects",
        "code":"unexpected"
      },
      "message": "postgres query error"
    }
  ]
}
```

**Hasura Version:** `v1.1.0-beta.1`

**Comment by blennopardim** [comment] 2020-01-14 17:09
I have the same problem :(

**Comment by MarcelloTheArcane** [comment] 2020-01-15 07:23
This is also happening on another project that is running `1.0.0`. 

I had upgraded it to `1.1.0-beta.1` but downgraded when this error happened.

**Comment by lexi-lambda** [comment] 2020-01-15 08:13
Duplicate of #3710

**Closed by lexi-lambda** 2020-01-15 08:13 UTC

**Comment by Julianojc** [comment] 2020-01-15 15:54
I have the same problem after update to 1.1.0-beta.1
