### ISSUE TITLE
passing custom headers into column presets on insert/update

### ISSUE THREAD

**Issue by ivan333m** [hasura/graphql-engine#3380] opened 2019-11-19 15:01 UTC
I'm getting following error on insert after "Permissions" -> "Column presets" setup with custom header (x-hasura-xxccvv)

`{"timestamp":"2019-11-18T16:15:16.701+0000","level":"error","type":"http-log","detail":{"operation":{"query_execution_time":null,"user_vars":{"x-hasura-role":"my-role","x-hasura-user-id":"zde-journey"},"error":{"path":"$","error":"\"x-hasura-xxccvv\" header is expected but not found","code":"not-found"},"request_id":"565c5a51-d0cf-427b-b58b-d0a23194356f","response_size":99,"query":{"query":"mutation {\n  insert_test(objects: {}) {\n    returning {\n      id\n      test\n    }\n    affected_rows\n  }\n}\n"}},"http_info":{"status":200,"http_version":"HTTP/1.1",...`

At the same time "X-Hasura-User-Id" works fine. 
I trigger the request by user with JWT token (without "x-hasura-admin-secret").

**Comment by rakeshkky** [comment] 2019-11-20 06:21
Hi @ivan333m, Please confirm the header `x-hasuraxxccvv` is present in your JWT claims.

**Comment by ivan333m** [comment] 2019-11-20 06:54
Hi @rakeshkky, `x-hasuraxxccvv` is not  present in my JWT token but I added it as header in console.
Is it possible to use headers for this functionality?

**Comment by marionschleifer** [comment] 2019-11-21 09:29
@ivan333m if you have JWT mode enabled, all the headers need to be passed in the JWT claims. You find more detailed information on this in our docs: https://docs.hasura.io/1.0/graphql/manual/auth/authentication/jwt.html 🙂

**Comment by ivan333m** [comment] 2019-11-21 09:41
Thanks @marionschleifer.
We would to have such functionality (passing arbitrary/custom headers into column presets on insert/updates) as it seems to be very useful feature; imagine a scenario when one wants to track incoming requests Ids into db tables whose are to be passed just as a http graphql headers.
What about to transform the issue into a change/feature request?
We ll appreciate your "yes"  answer :)
thanks in advance.

**Comment by tirumaraiselvan** [comment] 2019-11-21 09:47
Related to https://github.com/hasura/graphql-engine/issues/1601

**Comment by tirumaraiselvan** [comment] 2020-04-03 16:00
Closing this as a dupe of https://github.com/hasura/graphql-engine/issues/1601

**Closed by tirumaraiselvan** 2020-04-03 16:00 UTC
Labels: c/server
