### ISSUE TITLE
YAML parsing issue if the column is named "no"

### ISSUE THREAD

**Issue by abdullah2993** [hasura/graphql-engine#5537] opened 2020-08-05 18:57 UTC
If you have a column named `no` and you add premissions for it from hasura console and then apply metadata it fails. As `no` is interpreted as a boolean `false` (yaml treats `yes` as true and `no` as false)
Example of generated config:
```
insert_permissions:
  - role: somerole
    permission:
      check: {}
      columns:
      - id
      - no
      - somecol
```
The manual workaround is to quote the colums `"no"`
like so:
```
insert_permissions:
  - role: somerole
    permission:
      check: {}
      columns:
      - id
      - "no"
      - somecol
```

**Comment by Varun-Choudhary** [comment] 2020-09-08 07:26
Hey @abdullah2993! We weren't able to reproduce this issue on our end on either V1 config or v2 config. It would be helpful to know what was CLI config version you were using, your version of hasura and version of the CLI.

**Comment by beerose** [comment] 2020-10-05 11:55
Closing this issue, as the problem seems to be solved. Feel free to reopen if it happens again.

**Closed by beerose** 2020-10-05 11:55 UTC
Labels: c/console, e/quickfix, k/bug
