### ISSUE TITLE
Date breaks schema

### ISSUE THREAD

**Issue by santicomp2014** [hasura/graphql-engine#2331] opened 2019-06-04 21:49 UTC
Hi 
I found that when in use Date type in a column, the schema explorer breaks.

Is this a known bug?.

Thanks

**Comment by rikinsk** [comment] 2019-06-05 16:32
@santicomp2014 Thanks for reporting this. What exactly do you mean by the schema explorer breaks? Instructions to reproduce will be of help.

**Comment by santicomp2014** [comment] 2019-06-10 14:35
Thanks for the reply.

Here is a snapshot

![image](https://user-images.githubusercontent.com/9823189/59202627-3ea4d300-8b73-11e9-8b8d-39b8baed96ef.png)

![image](https://user-images.githubusercontent.com/9823189/59202699-6c8a1780-8b73-11e9-9bca-ba478b3d6ad9.png)

If I use a table that contains Date then the explorer is no longer visible.
When I remove such field then it goes back to normal.

I can still query, but the explorer disappears.

Thank you very much.

**Comment by wawhal** [comment] 2019-06-11 09:39
Hey @santicomp2014 
I tried reproducing this with the schema that you provided. Strangely, it seems to be working fine for me. If possible, could you give some more details i.e. your server version, your browser and if there is any error in the browser's developer console when this happens. It will be really helpful. Thanks.

**Comment by santicomp2014** [comment] 2019-06-21 02:03
Hey @wawhal 
Here are my specifics
Hasuira v1.0.0-beta.2 on Heroku
Google Chrome x64 Windows Version 75.0.3770.100 

The console only shows an error with the password not being in a form.
If I delete the Date field it works again.
It's really strange.

**Comment by wawhal** [comment] 2019-09-09 05:02
We couldn't reproduce this issue :(
So closing it for the time being.
If anybody faces a similar problem, please comment and we can reopen to  look into it :)

**Closed by wawhal** 2019-09-09 05:02 UTC
Labels: c/console
