### ISSUE TITLE
order_by don't use filter where 

### ISSUE THREAD

**Issue by kopitten** [hasura/graphql-engine#2279] opened 2019-05-27 06:55 UTC
Hello everyone,

I got an issue when apply where condition and order_by:

```
{
     
      product (
        order_by: {
          productQuantitysByproductId_aggregate:{
            sum: {
              quantity: desc_nulls_last
            }
            max: {
              quantity: desc_nulls_last
            }
          }
        }
        
        where: {
          productQuantitysByproductId: {
            store_id: {
              _eq: 1
            }
          }
        }
        ) {
          id
          name
          productQuantitysByproductId{
            quantity
          }
        }
    }
```

The order_by don't apply the where condition. it right? 

Thank you all.

**Comment by 0x777** [comment] 2019-05-27 13:18
@kopitten This is a duplicate of https://github.com/hasura/graphql-engine/issues/1357. The discussion there tells you why we don't have it yet.

**Closed by 0x777** 2019-05-27 13:18 UTC

**Comment by kopitten** [comment] 2019-05-28 02:20
@0x777 thanks for  your response
