### ISSUE TITLE
LIMIT on aggregate queries

### ISSUE THREAD

**Issue by dmoiseenko** [hasura/graphql-engine#1996] opened 2019-04-12 07:35 UTC
Hi!

Is there any way to disable `Limit number of rows` from Table Permission for aggregate queries?
Currently it is applied for any query(aggregate and non aggregate).
The following queries give same result because limit: 10 is set in Table Permission for table something:
`
{
  something_aggregate(limit: 10) {
    aggregate {
      count
    }
  }
}
`
`
{
  something_aggregate {
    aggregate {
      count
    }
  }
}
`

**Comment by coco98** [comment] 2019-04-12 09:47
Closing this as a duplicate of #1837 
@rakeshkky Please do take a look at this bug!

**Closed** 2019-04-12 09:47 UTC
Labels: k/bug
