### ISSUE TITLE
Recover from an inconsistent database state [manually]

### ISSUE THREAD

**Issue by karthikvt26** [hasura/graphql-engine#246] opened 2018-08-02 08:41 UTC
This issue is an extension of issue #231 which will help resolve any issue with `inconsistent database state` for the time being.

User can encounter an issue with the GraphQL engine because of the inconsistent database state in the following ways

- Console
  - Under data tabs (Browser rows, Relationship) whenever there is any issue we can provide them with instructions on what could have caused this issue and point them to docs ( link and content are WIP). 
    - For example: If the user creates a table and drops it from adminer. The data section of the console become inaccessible. Screenshot of the same is as below

- GraphQL
  - Can we include one more key in the error object called url, which can link to [docs.hasura.io](https://docs.hasura.io/1.0/graphql/manual/index.html?query=postgres-error) so that user knows what to next if he couldn't figure out from the error message.

Following are the issues if encountered can be solved via messaging on console and linking them to docs.

### CONSOLE
- Create a table on console. Delete it from adminer, console doesn't work. Right now I think there is a global catch which shows `something went wrong`. Can we show what we expected and what we got and point them to docs link?
- Create a table on console, add a column to the table via adminer and refresh the page. The `Browse rows` section doesn't load. 
- Create a foreign key to a table, add a relationship to that table, remove the foreign key. Everything works, but when visited relationship it shows `something went wrong`. 
- _Create a field with same name as relationship via adminer. Same error as in point 2 occurs._ 
- _Rename a column on adminer. Same error as in point 2 occurs_

### GraphQL Engine

- If GraphQL engine doesn't start, it should provide a link to docs which should have a solution.
  - For example if the error is as follows
    ```
    QErr {qePath = [], qeStatus = Status {statusCode = 500, statusMessage = "Internal Server Error"}, qeError = "table \"user_address\"; rel \"user\"; field already exists ", qeCode = unexpected, qeInternal = Nothing}
    ```
  It should link to the following [docs link] (https://docs.hasura.io/1.0/graphql/manual/index.html?query=error%20field%20already%20exists)

@praveenweb @rakeshkky when can we get started on this?

**Comment by rakeshkky** [comment] 2018-08-02 09:15
@karthikvt26 
If in case a tracked table is deleted from database without using graphql-engine APIs (using psql or adminer) use `untrack_table` query to remove table from metadata. 

```http
https://<graphql-endpoint>/v1/query

{
  "type": "untrack_table",
  "args": {
    "table": {
      "schema": "schema_name",
      "name": "table_name"
    },
    "cascade": true
  }
}
```

**Comment by coco98** [comment] 2018-08-22 18:55
@rakeshkky @karthikvt26 
Are these other 2 issues duplicates? can we close the right ones?
#231  #202

**Comment by shahidhk** [comment] 2018-08-28 06:15
Duplicate of https://github.com/hasura/graphql-engine/issues/231

**Closed by shahidhk** 2018-08-28 06:15 UTC
Labels: console, server
