### ISSUE TITLE
[CLI] "hasura migrate" shows an error BUT cli return code is 0

### ISSUE THREAD

**Issue by waterdrop01** [hasura/graphql-engine#7629] opened 2021-09-30 14:47 UTC
### Version Information

Server Version:
CLI Version: 2.0.6

### What is the expected behaviour?
cli return code should be set to 1 when there is an error message returned by postgresql.

### What is the current behaviour?
cli return code is 0

### How to reproduce the issue?

1. make a migration that is rejected by postgresql
2. run hasura migrate

### Screenshots or Screencast

![Screenshot from 2021-09-30 16-45-43](https://user-images.githubusercontent.com/47316824/135477855-7582d370-e2f6-4bac-ada4-fa3df2568b6f.png)
![Screenshot from 2021-09-30 16-46-09](https://user-images.githubusercontent.com/47316824/135477854-43e3c73b-e1a4-4691-85bb-556a0391c003.png)
![Screenshot from 2021-09-30 16-46-15](https://user-images.githubusercontent.com/47316824/135477850-9e49e710-5a7d-45fc-8e58-45f0a68b637e.png)

As you can see, migration failed, but the CI/CD step passed successfully (because it's based on the return code)

**Comment by scriptonist** [comment] 2021-09-30 15:39
duplicate of https://github.com/hasura/graphql-engine/issues/7499. Fixed via https://github.com/hasura/graphql-engine/commit/ffce0d266bc23a5142066f6b7fafc3105569bd32

**Closed by scriptonist** 2021-09-30 15:39 UTC
Labels: k/bug, duplicate

**Comment by waterdrop01** [comment] 2021-09-30 18:17
Ok, didn't see.

Not sure if a non zero exit code will be returned when specifying the database name though...with this command for instance `hasura-cli migrate apply --database-name default` (the PR only mentioned `--all-database` option. I added a comment)

**Comment by scriptonist** [comment] 2021-12-09 14:49
@waterdrop01 The fix should cover that too.
