### ISSUE TITLE
How To Register in Eureka to access from Zuul Proxy

### ISSUE THREAD

**Issue by udhayamgit** [hasura/graphql-engine#2873] opened 2019-09-12 17:51 UTC
Hi Team,

Currently, I have registered all my Java and Nodejs microservice in eureka, Now I would like to make a GraphQL call via my eureka registry to Hasura Engine. Is there is a way to register hasura service in Eureka?

**Comment by tirumaraiselvan** [comment] 2019-09-14 03:56
Hi @udhayamgit 

How do you normally register "external" services with Eureka? I am guessing there should be a proxy interface which registers with eureka and also proxies all endpoints to the underlying application.

**Comment by udhayamgit** [comment] 2019-09-14 07:31
> Hi @udhayamgit
> 
> How do you normally register "external" services with Eureka? I am guessing there should be a proxy interface which registers with eureka and also proxies all endpoints to the underlying application.

Generally, the service need to be registered in eureka before proxies all endpoint to the underlying application.

**Comment by udhayamgit** [comment] 2019-09-14 07:36
I Need to register the hasura instance in my eureka registry, In place of service-id, I need to put hasura server instance. What is the way to register the hasura in eureka?



zuul.routes.hasura.path=/graphql/**
zuul.routes.hasura.serviceId=Hasura-server
zuul.routes.hasura.filters=jwtVerify

**Comment by tirumaraiselvan** [comment] 2019-09-16 06:04
> Generally, the service need to be registered in eureka before proxies all endpoint to the underlying application.

Understood. My question is in your environment, is there an established pattern to register external/third-party services as Eureka clients? 

The solution to the problem is not hasura related, it is more specific to your deployment workflow. For e.g., if you are using some container orchestration platform (like Kubernetes), then you can deploy an init container/side-car container which registers hasura as a eureka client. Check the docs for that here: https://github.com/Netflix/eureka/wiki/Eureka-at-a-glance#non-java-services-and-clients

**Comment by dsandip** [comment] 2019-09-16 09:17
@udhayamgit Would love to discuss this over a call if you'd like. If this works for you, please pick a convenient slot using [this](https://calendly.com/team-hasura/graphql-helpline)

**Comment by marionschleifer** [comment] 2019-10-07 10:30
@udhayamgit just wanted to check in if your issue is resolved? 🙂 If yes, please close this issue. Otherwise, please feel free to set up a call.

**Comment by marionschleifer** [comment] 2019-11-20 16:31
@udhayamgit I'm closing this issue. Feel free to re-open if you would like to add something 🙂

**Closed by marionschleifer** 2019-11-20 16:31 UTC
Labels: k/question
