### ISSUE TITLE
api error code is confusing when we try to drop a permission that does not exist

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#1623] opened 2019-02-19 07:23 UTC
Error thrown when there I try to drop a permission that doesn't exist:

```
curl -d'{"type":"drop_update_permission", "args":{"table":{"name":"author", "schema":"public"}, "role":"user"}}' http://localhost:8080/v1/query

{"path":"$.args","error":"update permisison on \"author\" for role \"user\" does not exist","code":"permission-denied"}
```

Error message makes sense, but the code is kind of off - make it something like 404?

**Comment by manasag** [comment] 2023-12-28 16:34
This issue has not attracted significant attention for a long period of time, hence closing this.
Please feel free to reopen if the issue is still relevant for you.

**Closed by manasag** 2023-12-28 16:34 UTC
Labels: k/bug, c/server, e/quickfix, p/medium, a/authz
