### ISSUE TITLE
(cli): Error with MacOS big sur

### ISSUE THREAD

**Issue by CorentinWanteeed** [hasura/graphql-engine#6193] opened 2020-11-13 12:53 UTC
Hello,

This morning I updated my macbook to MacOS Big sur and now I can not start hasura cli

```bash
あ→ hasura
Killed: 9
```

I tried to reinstall it but the script also failed

```bash
あ→ curl -L https://github.com/hasura/graphql-engine/raw/master/cli/get.sh | sudo bash
Password:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   139  100   139    0     0   1130      0 --:--:-- --:--:-- --:--:--  1130
100  3577  100  3577    0     0  14966      0 --:--:-- --:--:-- --:--:--  105k
--> Getting latest version...
--> Latest version is v1.3.2
--> 
--> You already have the hasura cli at '/usr/local/bin/hasura'
--> Downloading again in 3 seconds... Press Ctrl+C to cancel.
--> 
--> Downloading hasura for darwin-amd64 to /tmp/cli-hasura-darwin-amd64
######################################################################## 100.0%##O#- #               ######################################################################## 100.0%
--> Download complete!
--> Moving cli from /tmp/cli-hasura-darwin-amd64 to /usr/local/bin
--> 
--> hasura cli installed to /usr/local/bin
--> 
bash: line 137: 48340 Killed: 9               hasura version
```

I think the only thing I did is to update the OS. 

![image](https://user-images.githubusercontent.com/47381529/99074210-a4428d80-25b7-11eb-98e2-a057bbe7ac9d.png)

Thank for your work!

**Comment by kolharsam** [comment] 2020-11-13 14:37
HI @CorentinWanteeed. I experienced a similar issue as well. You can build from source using `gox` or plain `go build` or you can use this [executable](https://github.com/hasura/graphql-engine/files/5537262/hasura_darwin_amd64.zip), which by no means is official. I'm sure this would be resolved in the upcoming release(s).

**Comment by kolharsam** [comment] 2020-11-13 15:11
This is also a dupe of #5462. My bad that I didn't check it earlier. So yeah, you could go there and see some other suggestions as well.

**Closed** 2020-11-13 15:12 UTC
Labels: c/cli
