### ISSUE TITLE
Support for conditional logic during the emission of event triggers 

### ISSUE THREAD

**Issue by pari-m** [hasura/graphql-engine#10203] opened 2024-04-15 12:00 UTC
### Component

c/v3-engine

### Is your proposal related to a problem?

N/A

### Describe the solution you'd like

Support for adding conditional logic before the event triggers are emitted from Hasura.

### Describe alternatives you've considered

A trigger can be created in the native database with the custom login whose action is to write to a new table. Hasura event triggers can be configured on this new table. This way the conditional logic occurs at the Database layer.

**Comment by tirumaraiselvan** [comment] 2024-09-24 15:12
Closing as dupe of https://github.com/hasura/graphql-engine/issues/1241

**Closed by tirumaraiselvan** 2024-09-24 15:12 UTC
Labels: k/enhancement, a/eventing/data-triggers, v2
