### ISSUE TITLE
 On adding a Relationship in console: Error; Cannot read property 'column_mapping' of undefined [v2.0.0-alpha.2.cloud.2]

### ISSUE THREAD

**Issue by oliviermills** [hasura/graphql-engine#6639] opened 2021-03-07 18:46 UTC
I receive this error every time I add a Relationship manually on cloud console v2.0.0-alpha.2.cloud.2

```
TypeError: Cannot read property 'column_mapping' of undefined
    at e (https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.0.0-alpha.2.cloud.2/vendor.js.gz:1:1950918)
    at https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.0.0-alpha.2.cloud.2/vendor.js.gz:1:3029841
    at Array.map (<anonymous>)
    at e (https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.0.0-alpha.2.cloud.2/vendor.js.gz:1:3029503)
    at pi (https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.0.0-alpha.2.cloud.2/vendor.js.gz:1:11090728)
    at Vi (https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.0.0-alpha.2.cloud.2/vendor.js.gz:1:11097684)
    at Xi (https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.0.0-alpha.2.cloud.2/vendor.js.gz:1:11104034)
    at ds (https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.0.0-alpha.2.cloud.2/vendor.js.gz:1:11126561)
    at fs (https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.0.0-alpha.2.cloud.2/vendor.js.gz:1:11126951)
    at Zs (https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.0.0-alpha.2.cloud.2/vendor.js.gz:1:11134129)
```

**Comment by beerose** [comment] 2021-03-09 07:07
Hi @oliviermills, I couldn't reproduce this issue with both array and object relationships. Could you provide more details, e.g. how the relationship looks like or about the schema?

**Comment by b9sk** [comment] 2021-03-12 20:25
Hello!

I faced with the same error in docker. Version of Hasura is `v2.0.0-alpha.3`.

The error is happening when manual One To One relation is created (despite a Array Relation suggestion). Finally `Object relationships` has been created and seems like the relation works properly.

Backtrace:
```
TypeError: Cannot read property 'column_mapping' of undefined
    at n (https://graphql-engine-cdn.hasura.io/console/assets/channel/alpha/v2.0/main.js.gz:1:2951810)
    at https://graphql-engine-cdn.hasura.io/console/assets/channel/alpha/v2.0/main.js.gz:1:3963613
    at Array.map (<anonymous>)
    at n (https://graphql-engine-cdn.hasura.io/console/assets/channel/alpha/v2.0/main.js.gz:1:3963249)
    at fo (https://graphql-engine-cdn.hasura.io/console/assets/channel/alpha/v2.0/vendor.js.gz:1:4829726)
    at es (https://graphql-engine-cdn.hasura.io/console/assets/channel/alpha/v2.0/vendor.js.gz:1:4838686)
    at Xl (https://graphql-engine-cdn.hasura.io/console/assets/channel/alpha/v2.0/vendor.js.gz:1:4877389)
    at jl (https://graphql-engine-cdn.hasura.io/console/assets/channel/alpha/v2.0/vendor.js.gz:1:4869122)
    at zl (https://graphql-engine-cdn.hasura.io/console/assets/channel/alpha/v2.0/vendor.js.gz:1:4869047)
    at Ol (https://graphql-engine-cdn.hasura.io/console/assets/channel/alpha/v2.0/vendor.js.gz:1:4865897)
```

**Comment by khan297** [comment] 2021-03-13 16:14
م

**Comment by iosifnicolae2** [comment] 2021-03-20 09:21
Same problem in `v2.0.0-alpha.5`
```
TypeError: Cannot read property 'column_mapping' of undefined
    at n (https://graphql-engine-cdn.hasura.io/console/assets/channel/alpha/v2.0/main.js.gz:1:2960809)
    at https://graphql-engine-cdn.hasura.io/console/assets/channel/alpha/v2.0/main.js.gz:1:3971593
    at Array.map (<anonymous>)
    at n (https://graphql-engine-cdn.hasura.io/console/assets/channel/alpha/v2.0/main.js.gz:1:3971229)
    at fo (https://graphql-engine-cdn.hasura.io/console/assets/channel/alpha/v2.0/vendor.js.gz:1:4835158)
    at es (https://graphql-engine-cdn.hasura.io/console/assets/channel/alpha/v2.0/vendor.js.gz:1:4844118)
    at Xl (https://graphql-engine-cdn.hasura.io/console/assets/channel/alpha/v2.0/vendor.js.gz:1:4882821)
    at jl (https://graphql-engine-cdn.hasura.io/console/assets/channel/alpha/v2.0/vendor.js.gz:1:4874554)
    at zl (https://graphql-engine-cdn.hasura.io/console/assets/channel/alpha/v2.0/vendor.js.gz:1:4874479)
    at Ol (https://graphql-engine-cdn.hasura.io/console/assets/channel/alpha/v2.0/vendor.js.gz:1:4871329)
```

**Comment by jacobaraujo7** [comment] 2021-04-02 02:40
Same problem hete! 2.0.0-alpha.6

**Comment by khan297** [comment] 2021-04-02 02:52
H

**Comment by lapidus** [comment] 2021-04-03 18:22
Bumped into the same issue when upgrading Cloud from `1.3` to `v2.0.0-cloud.2`.
Relationships for one of my tables (out of 100+) seems corrupted.


Would be great to get help tracking down the offending relationship.

![image](https://user-images.githubusercontent.com/66601/113487775-3e00cd80-94ba-11eb-9354-6e4983f0a24d.png)

**Comment by khan297** [comment] 2021-04-03 18:23
S

**Comment by beerose** [comment] 2021-04-08 12:59
Fixed in https://github.com/hasura/graphql-engine/commit/a93135d1b19f88bdd0377b721b818b2fb546e927

**Closed by beerose** 2021-04-08 12:59 UTC
Labels: c/console

**Comment by lapidus** [comment] 2021-04-08 13:39
Excellent, thank you! 
Sidenote: What's the release process for something like this to Hasura Cloud?
