### ISSUE TITLE
clarification on using aggregates with limit argument

### ISSUE THREAD

**Issue by zesterquinn** [hasura/graphql-engine#2141] opened 2019-05-08 02:14 UTC
```
subscription{
  suppliers_aggregate(limit:10){
    nodes{
      name
    }
    aggregate{
     count
    }
  }
} 
```

it still limit the aggregate query

```
SELECT
  json_build_object(
    'nodes',
    coalesce(json_agg("nodes"), '[]'),
    'aggregate',
    json_build_object('count', COUNT(*))
  ) AS "root"
FROM
  (
    SELECT
      1 AS "root__one",
      row_to_json(
        (
          SELECT
            "_1_e"
          FROM
            (
              SELECT
                "_0_root.base"."name" AS "name"
            ) AS "_1_e"
        )
      ) AS "nodes"
    FROM
      (
        SELECT
          *
        FROM
          "public"."suppliers"
        WHERE
          ('true')
      ) AS "_0_root.base"
    LIMIT
      10
  ) AS "_2_root"
```

heres the generated query. it doesnt define the only the node get to be limit

**Comment by shahidhk** [comment] 2019-05-08 05:29
@zesterquinn Since you're adding the limit argument, this is the expected behaviour.
If your intention is to get 10 items and also get the total count, you have to use two subscriptions:

```gql
# get 10 items
subscription {
  suppliers(limit:10) {
    name
  }
} 
```

```gql
# get the total count
subscription {
  suppliers_aggregate {
    aggregate{
     count
    }
  }
} 
```

**Comment by revskill10** [comment] 2019-05-08 17:29
@shahidhk I think the expected behaviour should be:

- Limit is used to fetch real data rows.
- Aggregate count is to calculate Total rows number of the table, independent of `limit`

So, 
```js
subscription {
  suppliers_aggregate(limit:10) {
    aggregate { count }    
  }
} 
```
should fetch 10 rows of data, but `aggregate.count` returns Total number of rows of that table based on permission.

**Comment by 0x777** [comment] 2019-05-09 05:28
@revskill10 limit is needed in aggregates too. How would you compute the avg population of top 10 cities by population?

**Comment by revskill10** [comment] 2019-05-09 06:36
@0x777 I think, in this case, the `avg` itself needs argument like `avg(limit: 10)` .

Those limits have different meanings. One for fetching data, one for calculating data.

**Comment by 0x777** [comment] 2019-05-09 09:03
@revskill10 Our convention is that the `limit` in `*_aggregate` fields' arguments applies to everything. You can always use multiple fields to get the behavior that you need

```graphql
query articles ($where: articles_bool_exp!) {
  articles_aggregate(where: $where) {
    aggregate {
      totalCount: count
    }
  }
  articles (where: $where limit: 10 order_by: {rating: desc}) {
    id
    title
  }
}
```
I understand that this is a problem with subscriptions but you can issue multiple subscriptions to work around this. We will try to improve the DX around this over time.

**Comment by shahidhk** [comment] 2019-05-09 09:20
@revskill10 To fetch data, you would use `tablename` node and to calculate aggregates, you would use `tablename_aggregate`. In `tablename_aggregate` context, the `limit` is for the aggregate.

**Comment by marionschleifer** [comment] 2019-07-09 10:11
@revskill10 I'm closing this issue. If you have any more questions or want to add something, feel free to re-open it 🙂

**Closed by marionschleifer** 2019-07-09 10:11 UTC
Labels: needs-more-info
