### ISSUE TITLE
Tweak Prettify GraphQL Setting in Console

### ISSUE THREAD

**Issue by MalikBagwala** [hasura/graphql-engine#10074] opened 2023-12-27 04:07 UTC
### Component

Console -> c/v3-console

-->

### Is your proposal related to a problem?

Current Implementation of Prettify
<img width="1694" alt="Screenshot 2023-12-27 at 9 32 48 AM" src="https://github.com/hasura/graphql-engine/assets/23068029/eb626970-c21e-4106-9bd7-10b47d8f29c5">

Current Hasura console prettifies everything into a single line and this is rarely useful since console is mostly used during the development and a more readable approach should be preferred instead of a compact one. I have to use tools like GraphQL Formatter very often, so I thought this links to a deep issue in the UX of the console.

### Describe the solution you'd like

I want the prettier to function like this instead.

<img width="1692" alt="Screenshot 2023-12-27 at 9 33 12 AM" src="https://github.com/hasura/graphql-engine/assets/23068029/b946fd01-8cad-4156-8e14-1ad1b5c91870">

### Describe alternatives you've considered

Manually formatting the code via online formatters

**Comment by MalikBagwala** [comment] 2023-12-27 09:25
@manasag I am happy to pick this up, let me know if this needs to be implemented.

**Comment by manasag** [comment] 2023-12-28 15:57
This feature is dependent on support by the [GraphiQL](https://github.com/graphql/graphiql) library. There is an open [issue](https://github.com/graphql/graphiql/issues/1517) with GraphiQL on the same. We have tested with GraphiQL 2, and its still not supported.
This is duplicate of #1571 , hence closing this one.

**Closed by manasag** 2023-12-28 15:57 UTC
Labels: k/enhancement, c/console, v2
