### ISSUE TITLE
Feature request: Link related documentation from Console UI.

### ISSUE THREAD

**Issue by revskill10** [hasura/graphql-engine#1110] opened 2018-11-25 10:31 UTC
We should put related links on documentation on Console UI for user to easily look up the documentation of functionalities on Console UI.

**Comment by CodHeK** [comment] 2018-12-12 10:44
@shahidhk @praveenweb  I'd like to work this out, I'll just make a list of where a link would be required and post it here.

**Comment by CodHeK** [comment] 2018-12-12 10:57
1. `Permissions`:  https://docs.hasura.io/1.0/graphql/manual/auth/basics.html 
2. `Event triggers`: https://docs.hasura.io/1.0/graphql/manual/event-triggers/index.html
@revskill10  if you could suggest a few more areas to link ?

**Comment by revskill10** [comment] 2018-12-14 16:47
@CodHeK Every tabs on ConsoleUI needs documentation.

**Comment by CodHeK** [comment] 2018-12-14 17:57
Every tab as in? Could you give me an example ? @revskill10

**Comment by revskill10** [comment] 2018-12-14 18:10
Actually, my expectation is to link all current markdown documentation files into its own react component with `mdx` , and in console ui, make a drawer so that people could view those documentations right from console ui. It's also a feasible approach. 
The benefit is when we update documentation, console ui documentation could automatically deployed with latest documentation, too.

**Comment by CodHeK** [comment] 2018-12-15 04:36
@revskill10 all the documentation is written in Sphinx right, I don't see any documentation written in markdown.

**Comment by revskill10** [comment] 2018-12-15 05:53
@CodHeK Is there any chance to rewrite documentation with markdown ? I don't see any reason not to use markdown for documentation though.

**Comment by manasag** [comment] 2023-12-27 12:59
This issue has not attracted significant attention for a long period of time, hence closing this.
Please feel free to reopen if the issue is still relevant for you.

**Closed by manasag** 2023-12-27 12:59 UTC
Labels: k/enhancement, c/console, p/high, e/easy
