### ISSUE TITLE
Misleading Computed Field Creation Failure

### ISSUE THREAD

**Issue by philipp-tailor** [hasura/graphql-engine#6687] opened 2021-03-20 15:30 UTC
I have table `a` and table `b`. Table `b` as no primary key. I create a function, which returns a matching row from table `b` when given a row from table `a`. I then attempt to add a computed field to table `b`, using the function returning a row from table `a`.

Actual outcome: Creation of computed field fails with message `Failed to create computed field. Table "b" not found.`.

Optimal outcome: Creation of computed field succeeds.

Better behavior: Creation of computed field fails with message `Failed to create computed field. Table "b" not found. Please ensure that the table exists and has a primary key.`.

**Comment by GreenRobot777** [comment] 2021-03-25 15:44
Can you show the function?

**Comment by philipp-tailor** [comment] 2021-03-30 06:36
@GreenRobot777 Sure, this is the function. `places` is what I abstracted as `a`, whereas `internet_availabilities` is table `b`.

```sql
CREATE OR REPLACE FUNCTION public.place_internet_availability(place_row places)
 RETURNS internet_availabilities
 LANGUAGE sql
 STABLE
AS $function$
    SELECT *
    FROM internet_availabilities
    WHERE search_term = CONCAT(place_row.postal_code, ' ', place_row.city)
    LIMIT 1
$function$
```

**Comment by tirumaraiselvan** [comment] 2021-04-28 08:24
Seems like dupe of https://github.com/hasura/graphql-engine/issues/5153

**Closed** 2021-04-28 08:24 UTC
