### ISSUE TITLE
How to know what permissions a user have for a table, through API

### ISSUE THREAD

**Issue by KrishnaPG** [hasura/graphql-engine#8528] opened 2022-05-26 01:56 UTC
While building the UI, certain parts of UI need to know if user is allowed access or not.

For example,
 - menu links enabled/disabled,
 - buttons enabled/disabled
based on whether user is allowed to perform an action or not.

This requires querying what permissions a user have for the underlying resource/table etc.

Any example that demonstrates how to achieve this functionality with Hasura backend permissions would be of great help.

For more background information on this: https://github.com/nhost/nhost/issues/575

**Comment by plcplc** [comment] 2024-01-04 09:48
The only way to know all the permissions active on a graphql-engine instance is the [export_metadata](https://hasura.io/docs/latest/api-reference/metadata-api/manage-metadata/#metadata-export-metadata) API call. There is no dedicated API to help reflecting on what permissions a role has.

Alternatively you can interrogate the GraphQL schema, which will be different for each role. The presence and absence of fields and objects of interest can provide some info on what is being restricted by the active permissions.

Because this issue is quite dated and doesn't really pertain to a shortcoming of the graphql-engine I'm going to close it.

Feel free to reopen if the issue is still relevant for you.

**Closed by plcplc** 2024-01-04 09:48 UTC
