### ISSUE TITLE
Remote schema customisation issue

### ISSUE THREAD

**Issue by ilidazilv** [hasura/graphql-engine#9757] opened 2023-07-07 09:56 UTC
### Version Information

Server Version:
CLI Version (for CLI related issue): v2.29.0

### Environment

Local Docker CLI

### What is the current behaviour?

Input type on remote schema is not working properly, when I'm using null value. I have this issue `"message": "Unknown type \"Graphqlapi_DateTime\"."` - `Graphqlapi_` is prefix for remote schema types

### What is the expected behaviour?

Get rid of this issue & accept null value in input types for remote schema

### How to reproduce the issue?

1. Add remote schema to your hasura env with prefix for types
2. Try to do mutation with null input type
3. Got Unknown type error

### Screenshots or Screencast

<img width="867" alt="image" src="https://github.com/hasura/graphql-engine/assets/46351425/4d11d54e-c25b-489f-9f40-a374a93dc0ea">

### Any possible solutions/workarounds you're aware of?

Dunno, sorry

### Keywords

remote schema, input types, null value

**Comment by abooij** [comment] 2023-07-10 07:51
@ilidazilv Could you share the GraphQL query that generated this error? If it's confidential you can share it by email as well.

**Comment by ilidazilv** [comment] 2023-07-12 19:32
Hey, @abooij! Sorry for a long response here you go (I made it a little smaller)

Mutation:
`mutation updateDraft($id: String!, $data: Graphqlapi_DraftUpdateInput!) {
  graphqlapi_ {
    updateDraft(data: {id: $id, data: $data}) {
      id
      __typename
    }
    __typename
  }
}`

Variables: 
`{
  "data": {
    "energyPerformanceCertificateName": null
  },
  "id": "5f22208f-28a8-45a1-a55a-10e3715f2011"
}`

Response:
<img width="1032" alt="image" src="https://github.com/hasura/graphql-engine/assets/46351425/e208116d-7bb5-4f99-aa37-ddb6c3579ea7">

EnergyPerformanceCertificateName is just enum, which can be nullable

**Comment by abooij** [comment] 2023-07-21 09:50
@ilidazilv We have a potential fix for this issue in the works. Could you try out docker image `hasura/graphql-engine-demo:mono-pr-9929-9757.ubuntu`?

**Comment by ilidazilv** [comment] 2023-07-26 13:08
Unfortunately, I'm using arm64 (m1). Is there an image for arm64? @abooij

**Comment by ilidazilv** [comment] 2023-07-26 13:18
Just tried version 2.30.0 and it's still broken for me
<img width="1004" alt="image" src="https://github.com/hasura/graphql-engine/assets/46351425/b9fe8fcd-9f8e-4e47-a57d-5321a2163d0a">

**Comment by abooij** [comment] 2023-07-27 13:09
@ilidazilv Sure, could you try `hasura/graphql-engine-demo:remote-schema-customisation.1`? It should work for both x64 and arm64.

**Comment by abooij** [comment] 2023-07-28 08:14
@ilidazilv Okay, thanks for the feedback. I'm not entirely sure how we'll fix it long-term - this build was really only a test to nail down the root cause.

I'll take this information back to my team and we'll let you know once a fix is ready for release.

**Comment by ilidazilv** [comment] 2023-07-28 08:52
Ah, I got it. Thank you so much for the information! I hope it'll be soon in some release. Have a nice day! @abooij

**Comment by abooij** [comment] 2023-08-28 07:52
@ilidazilv A fix for this issue is part of v2.33 which should be released either this week or the next.

**Closed by abooij** 2023-08-28 07:52 UTC
Labels: k/bug
