### ISSUE TITLE
Migrations generated when renaming a field are in the wrong order

### ISSUE THREAD

**Issue by majapersson** [hasura/graphql-engine#6084] opened 2020-10-28 13:00 UTC
After editing the field `last_modified` on one of my tables in the console, and renaming it to `updated_at`, the order of the generated `down` migration is incorrect. When trying to apply it, I get an error on the first query saying that the `last_modified` column doesn't exist, since renaming it back is the last of the queries.

`up.sql`:
```
ALTER TABLE "public"."audio" ALTER COLUMN "last_modified" TYPE timestamptz;
ALTER TABLE ONLY "public"."audio" ALTER COLUMN "last_modified" SET DEFAULT now();
alter table "public"."audio" rename column "last_modified" to "updated_at";
```
`down.sql`:
```
ALTER TABLE "public"."audio" ALTER COLUMN "last_modified" TYPE date;
ALTER TABLE ONLY "public"."audio" ALTER COLUMN "last_modified" DROP DEFAULT;
alter table "public"."audio" rename column "updated_at" to "last_modified";
```

**Comment by beerose** [comment] 2020-11-05 16:53
Closing as a duplicate of https://github.com/hasura/graphql-engine/issues/3503. It was fixed in https://github.com/hasura/graphql-engine/pull/4790 and will be included in the next release.

**Closed by beerose** 2020-11-05 16:53 UTC
Labels: c/console, duplicate, k/bug
