### ISSUE TITLE
pagination/count support

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#277] opened 2018-08-10 11:10 UTC
The least we can do till we workout the pagination spec is to have a `count_<table_name>` query type at the root.

**Comment by 0x777** [comment] 2018-10-30 13:55
`count` (part of aggregations from alpha27) can be used to do pagination as follows:

```graphql
query articles ($where: articles_bool_exp!) {
  articles_aggregate(where: $where) {
    aggregate {
      totalCount: count
    }
  }
  articles (where: $where limit: 10 order_by: {rating: desc}) {
    id
    title
  }
}
```

This is definitely not as clean as relay's support for pagination, but it is a start. We'll improve it further.

**Comment by nathanwaters** [comment] 2018-11-12 01:16
Shouldn't x-hasura-user-id be automatically applied as a where filter on aggregate queries?

**Comment by rafaelugolini** [comment] 2018-11-14 20:05
@0x777 is there a plan to add `order_by` on fields from aggregations? 

```gql
query articles (
  $where: articles_bool_exp!, 
  order_by: {
    articles_aggregate: {count: desc}      # order_by
  }
) {
  articles_aggregate(where: $where) {
    aggregate {
      totalCount: count
    }
  }
  articles (where: $where limit: 10 order_by: {rating: desc}) {
    id
    title
  }
}
```

**Comment by 0x777** [comment] 2018-11-15 06:30
@rafaelugolini I don't quite understand what ordering articles by their count mean? Maybe you meant something like this: order authors by their number of articles?

```graphql
author (order_by: {articles_aggregate: { count: desc }}) {
  id
  name
}
```

**Comment by rafaelugolini** [comment] 2018-11-15 06:59
@0x777 yeap, exactly... btw I'm on version `v1.0.0-alpha28`

**Comment by 0x777** [comment] 2018-11-15 07:06
@rafaelugolini I've opened a new issue to track this feature: https://github.com/hasura/graphql-engine/issues/1039. This might be slightly hard to implement.

**Comment by rafaelugolini** [comment] 2018-11-15 07:11
@0x777 thanks a lot.

**Comment by 0x777** [comment] 2018-11-15 08:00
@nathanwaters We'll need your help in reproducing this issue. Can you provide us the query and the necessary tables and permissions for the query?

**Comment by nathanwaters** [comment] 2018-11-16 03:49
> @nathanwaters We'll need your help in reproducing this issue. Can you provide us the query and the necessary tables and permissions for the query?

Tried to reproduce and couldn't lol. Disregard :)

**Comment by dsandip** [comment] 2019-07-25 06:11
This just needs to be documented properly

**Comment by pocketwalker** [comment] 2019-09-29 08:21
any update on this issue?

**Comment by marionschleifer** [comment] 2019-09-29 17:02
@pocketwalker the PR is in review: https://github.com/hasura/graphql-engine/pull/2874 and it should get merged soon 🙂

**Closed** 2019-11-21 08:42 UTC
Labels: c/docs, e/hard, p/high

**Comment by korengrip** [comment] 2021-03-16 08:15
What about totalCount in Relay's implementation? It's missing and it's really useful. (Right now we can't use Relay cursor pagination and show the total results because of the missing totalCount)
