### ISSUE TITLE
Hasura console is not able to reach your Hasura GraphQL engine instance. Please ensure that your instance is running and the endpoint is configured correctly. 

### ISSUE THREAD

**Issue by manishanaikmmn** [hasura/graphql-engine#2378] opened 2019-06-14 11:04 UTC
when i am trying to access hasura console with port 9695 am getting the message in my chrome browser. My configuration is,
hasura version :  hasura/graphql-engine:v1.0.0-beta.2.cli-migrations
hasura graphql-engine is running on 8080, and cli console is running on 9695.

Please help me to solve this asap

**Comment by dukedave** [comment] 2019-06-14 23:21
I am getting this too.

CLI `version=1.0.0-beta.2`, MacOS, with engine running via Docker Compose:
```
graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha42
```

**Comment by dukedave** [comment] 2019-06-14 23:41
I hacked [the install script](https://raw.githubusercontent.com/hasura/graphql-engine/master/cli/get.sh) to force it back to an older version by replacing:
```
version=$(curl -s -H 'Content-Type: text/plain' https://releases.hasura.io/graphql-engine?agent=cli-get.sh)
```

With:
```
version="v1.0.0-alpha42"
```

Then ran my modified `get.sh` and was able to install the older version and use `hasura console`:

```
$ hasura  version
INFO hasura cli                                    version=v1.0.0-alpha42
INFO hasura graphql engine                         endpoint="http://localhost:8080" version=v1.0.0-alpha42
```

**Comment by dukedave** [comment] 2019-06-14 23:42
I also tried updating my `graphql-engine` to `beta2`, but got the same `Hasura console is not able to reach your Hasura GraphQL engine instance`. error.

**Comment by hengsovandara** [comment] 2019-06-15 02:55
Same issue here, I have noticed that I have run the hasura console for couple hour, and then back to refresh page, it worked fine. The issue is about _http://0.0.0.0:9694/apis/migrate/settings_ cannot reachable.

**Comment by shahidhk** [comment] 2019-06-15 14:30
Hi folks, I am unable to reproduce this. Can you please provide repro instructions?

**Comment by hengsovandara** [comment] 2019-06-17 04:24
> Hi folks, I am unable to reproduce this. Can you please provide repro instructions?

For me, I have spawn hasura on the server, and I try to run hasura console cli on the same with port 9695, api-port 9693. but actually, the message from web when we are hitting the web of hasura console cli, it said  _Hasura console is not able to reach your Hasura GraphQL engine instance._. however, after I left the server running that for several hours, I came back to refresh it, it works fine.

**Comment by manishanaikmmn** [comment] 2019-06-17 04:29
I have installed hasura in a dcker container on linux machine.The console with port 8080 and migration to backend database was done successfully.But upon starting the cli console inside the container,it runs saying that it is running on port 9695.Still after hitting the browser it throws the above error.

To understand this,i tried installing hasura cli on linux host directly,still it says running but browser gives the popup of this error.

**Comment by shahidhk** [comment] 2019-06-17 04:41
@manishanaikmmn Running Hasura CLI in docker containers or remote servers is not supported at the moment. We will add this support soon, with https://github.com/hasura/graphql-engine/pull/1780

**Comment by dukedave** [comment] 2019-06-17 16:40
Some new clues:

The CLI has alway been working fine on my Mac laptop (Mojave 10.14.5) where the `version` output looks like this:

```
$ hasura version
INFO hasura cli                                    version=v1.0.0-beta.2
INFO hasura graphql engine                         endpoint="http://localhost:8080" version=v1.0.0-alpha42
```

**But** my colleague @jd-gray just repro'd it on his Mac laptop (also Mojave 10.14.5), and the output looks like this:

```
hasura CLI version: v0.4.43
GraphQL Engine CLI version:  v1.0.0-beta.2
GraphQL Engine Server [http://localhost:8080] version: v1.0.0-alpha42
```

I wonder why the outputs look different, even though they both claim to be CLI version `v1.0.0-beta.2`? 🤔

**Comment by dukedave** [comment] 2019-06-17 16:59
Aha! I can't speak to the reason for the different outputs show ⬆️, but I have identified what was causing the issue for me:

I had started setting `HASURA_GRAPHQL_CORS_DOMAIN: http://localhost:3000` in my `docker-compose.yaml`, and **that** was breaking `hasura console`.

Removing `HASURA_GRAPHQL_CORS_DOMAIN` makes it work again.

I think the versions were just red herrings (for me, at least).

**Comment by hengsovandara** [comment] 2019-06-18 02:39
> Aha! I can't speak to the reason for the different outputs show ⬆️, but I have identified what was causing the issue for me:
> 
> I had started setting `HASURA_GRAPHQL_CORS_DOMAIN: http://localhost:3000` in my `docker-compose.yaml`, and **that** was breaking `hasura console`.
> 
> Removing `HASURA_GRAPHQL_CORS_DOMAIN` makes it work again.
> 
> I think the versions were just red herrings (for me, at least).

Would you mind to give a copy oy docker-compose you use?

**Comment by manishanaikmmn** [comment] 2019-06-18 04:51
> @manishanaikmmn Running Hasura CLI in docker containers or remote servers is not supported at the moment. We will add this support soon, with #1780

@shahidhk Is it not supported for any of the Hasura CLI versions or any specific version? Is there any other workaround to export the data from the back end database using Hasura?

**Comment by shahidhk** [comment] 2019-06-18 05:58
@dukedave The difference in output is because we used to release CLI as part of the a different Hasura product. We recently changed it to a standalone CLI and all new installations will have that.

CORS can cause issues while using CLI. You should add `http://localhost:9695` as one of the CORS domain. 

@manishanaikmmn Running the CLI console elsewhere other than localhost is not supported in any version. You can export data using CLI running on your local machine, but connecting to a remote Hasura instance. See https://docs.hasura.io/1.0/graphql/manual/migrations/existing-database.html

Can you elaborate more on what you meant by "export data"?

**Comment by shahidhk** [comment] 2019-06-18 06:06
@hengsovandara Can you provide exact step-by-step instructions to reproduce this? Including your docker compose file etc.

**Comment by hengsovandara** [comment] 2019-06-20 07:46
@shahidhk  we can say, I have a server, running a docker contains 3 images, 2 of Hausra( dev and stage ) and 1 of postgres. and I want to run hasura console cli for _dev_ to migrate _stage_. the point is console cli cannot open from browser and produce the same error of name of Issue.

**Comment by shahidhk** [comment] 2019-06-21 07:06
Thanks @hengsovandara. But, with the information you've shared, I am unable to reproduce the issue.

Can you give me the docker compose file, and the list commands you executed leading upto the error?

**Comment by marionschleifer** [comment] 2019-07-08 15:39
I'm closing this. If you have any more questions or would like to add something, feel free to re-open this issue, @hengsovandara 🙂

**Closed by marionschleifer** 2019-07-08 15:39 UTC
Labels: needs-more-info, p/urgent

**Comment by tavakoli-ali** [comment] 2020-10-03 23:14
I hade up and run docker image but last week, all of the sudden, it had been down.
I got this error for 1 week and try all things and didn't work, I removed the docker file and image, container and install fresh but also didn't work, and got this message: DB schema loading failed
Failed to fetch.
docker : 

`version: '3.7'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DATABASE: postgres
  graphql-engine:
    image: hasura/graphql-engine:v1.3.2
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
                  #HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@host.docker.internal:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
volumes:
  db_data:
`

**Comment by abythachet** [comment] 2020-10-22 05:22
when I try running remort server in my local using 

`$ hasura console --admin-secret "XXXXXXX"`
getting error 
```
ERRO error listening on port 9695                  error="listen tcp: lookup localhost on 172.20.10.1:53: no such host"
ERRO error listening on port 9693                  error="listen tcp: lookup localhost on 172.20.10.1:53: no such host"
```

**Comment by ShanonJackson** [comment] 2021-02-20 00:38
I also had this; The solution for me personally was to go into localstorage/session storage/cookie storage on 8080 and 9695 and wipe everything then refresh

**Comment by nisharmultani** [comment] 2022-05-06 05:44
when your Hasura conflict with another project that means Hasura  all ready run in this port  error="listen tcp: lookup localhost on 172.20.10.1:53: no such host" 
step-1 
we will check is running or not
run this command
$sudo docker container ps

step-2 
the upper command gives you your Hasura runing details as well as one id also 
so close to all ports one by one 
$sudo docker stop {id}

and start again docker 
hope this solves your problem

**Comment by kochapas** [comment] 2024-08-21 07:19
I know this issue is closed and is 5 years old, but when I got the error, this issue was the first result I found on Google.
Here's my solution (or, rather, the source of the problem).

My Hasura instance is inside a docker and forwarding the port to my local machine.
I noticed a CORS error in my browser's console. Then, I realized that my PC had a proxy connection running in the background. 
After turning off the proxy connection, I can connect to my Hasura console again without a problem.

So you should check if you have a proxy or VPN running if you have this problem. I hope this helps.
