### ISSUE TITLE
console errors should link to docs whenever possible

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#1702] opened 2019-03-06 09:36 UTC
Few examples:

1. While adding remote schema, if the error is NotReachable then it could be possible that it is a docker networking issue in which case we should be able to point it to the correct place in docs.

2. If table doesn't have primary key, then we should point to the docs as to why this is the case.

3. If column can't be dropped because of some dependency, then we should point to the docs talking about direct and indirect dependencies.

**Comment by manasag** [comment] 2023-12-28 16:58
This issue has not attracted significant attention for a long period of time, hence closing this.
Please feel free to reopen if the issue is still relevant for you.

**Closed by manasag** 2023-12-28 16:58 UTC
Labels: c/console, p/medium, e/intermediate
