### ISSUE TITLE
suggest to create permissions on console when auth is configured

### ISSUE THREAD

**Issue by praveenweb** [hasura/graphql-engine#1737] opened 2019-03-12 09:07 UTC
When i enable JWT and use the auth token in my query, graphiql doesn't auto-complete my queries because permissions have not been enabled for the particular role. 

Console should be able to detect whether that table exists and suggest the user that permissions are missing for the role the user is trying to query as.

This can also be made clear in docs in JWT/webhook section.

**Comment by manasag** [comment] 2023-12-28 15:24
This issue has not attracted significant attention for a long period of time, hence closing this.
Please feel free to reopen if the issue is still relevant for you.

**Closed by manasag** 2023-12-28 15:24 UTC
Labels: k/enhancement, c/console, p/medium, e/intermediate, a/authz
