### ISSUE TITLE
'Deselect all' in "Listen columns for update"  

### ISSUE THREAD

**Issue by qqgg231** [hasura/graphql-engine#6040] opened 2020-10-19 11:18 UTC
"Listen columns for update"  In Events should have option "Deselect all"

If I have 50 columns and need only 1 I need to click 49 times to deselect....

**Comment by beerose** [comment] 2020-10-19 11:46
Closing as a duplicate of https://github.com/hasura/graphql-engine/issues/4972

**Closed by beerose** 2020-10-19 11:46 UTC
Labels: c/console, duplicate
