### ISSUE TITLE
Feature Request: Add WHEN clause for Events Trigger Operations

### ISSUE THREAD

**Issue by osseonews** [hasura/graphql-engine#5977] opened 2020-10-10 08:40 UTC
This is just a feature request for the Events features of Hasura. It would be great to add a "WHEN" possibility for the Trigger Operations in Events. Right now, if we set up an Event in Hasura and selection on a Trigger Operation for Update or Insert, the Event will fire our Webhook on every single Update/Insert for the table/field selected. This is a complete waste of resources and requires us to then add many lines of code in our Webhook to test for certain conditions. PostgresSQL has the possibility of adding a WHEN condition to any trigger so you can easily restrict the trigger operation to only certain cases, e.g. WHEN (OLD.balance IS DISTINCT FROM NEW.balance) (see examples on PostgresSQL docs).  So there should also be a possibility of adding a WHEN condition to Hasura Events based on the same principle. Thanks.

**Comment by tirumaraiselvan** [comment] 2020-10-22 13:05
Closing as dupe of https://github.com/hasura/graphql-engine/issues/1241

**Closed by tirumaraiselvan** 2020-10-22 13:05 UTC
