### ISSUE TITLE
disable filter / sort for object relationships in browse rows

### ISSUE THREAD

**Issue by rikinsk-zz** [hasura/graphql-engine#1722] opened 2019-03-08 08:12 UTC

**Comment by prajzwol7** [comment] 2022-07-07 07:44
@rikinsk-zz can you provide description for this issue

**Comment by manasag** [comment] 2023-12-28 17:00
This issue has not attracted significant attention for a long period of time, hence closing this.
Please feel free to reopen if the issue is still relevant for you.

**Closed by manasag** 2023-12-28 17:00 UTC
Labels: k/bug, c/console, e/quickfix, p/medium, a/api/graphql
