### ISSUE TITLE
Schema Issue on Release 33rd

### ISSUE THREAD

**Issue by rafaelugolini** [hasura/graphql-engine#1298] opened 2019-01-03 12:52 UTC
When you try to get the schema of hasura (let's say to do a schema stitching or something like that) there is an issue when you don't have a number in the table.

```bash
get-graphql-schema -h X-Hasura-Access-Key=yoursecret http://localhost:8080/v1alpha1/graphql > schema.graphql
```

Getting this will return something like this:
```gql
"""
order by avg() on columns of table "xxx"
"""
input xxx_avg_order_by {

}
```

This is not a valid graphql syntax, you will get an error `Syntax Error: Expected Name, found }`

It works fine on release 31rd

**Comment by ontofractal** [comment] 2019-01-03 16:30
Getting the same error during schema codegen.

@rafaelugolini my temporary workaround was to use codegen using public(anonymous) role authorization and do NOT allow aggregation queries for the problematic tables.

**Comment by rafaelugolini** [comment] 2019-01-03 19:04
@ontofractal to be honest not a solution for my use case right now. I will wait for a bugfix release.

**Comment by shahidhk** [comment] 2019-01-04 06:47
@rafaelugolini @ontofractal This is a bug, fixed on master, will make a release today.
Closing since duplicate of https://github.com/hasura/graphql-engine/issues/1243

**Closed by shahidhk** 2019-01-04 06:47 UTC
Labels: c/server, duplicate
