### ISSUE TITLE
Graphql delete_<table_name> mutation is deleting all rows when key is null.

### ISSUE THREAD

**Issue by subhrashisdas** [hasura/graphql-engine#4128] opened 2020-03-17 07:18 UTC
**Issue**
Graphql **delete_<table_name>** mutation is deleting all rows when key is null.

**Table**
```sql
                    Table "public.testing"
   Column   | Type | Collation | Nullable |      Default
------------+------+-----------+----------+-------------------
 testing_id | uuid |           | not null | gen_random_uuid()
Indexes:
    "testing_pkey" PRIMARY KEY, btree (testing_id)
```

**Mutation**
```graphql
mutation DeleteTesting {
  delete_testing(where: {testing_id: {_eq: null}}) {
    affected_rows
  }
}
```

**Response**
```json
{
  "data": {
    "delete_testing": {
      "affected_rows": 5
    }
  }
}
```
**Expected Behaviour**
As per the mutation, it should delete all rows whose testing_id is null.

**Current Behaviour**
Mutation is deleting all rows from the table.

**Postgres Version**
v11.6

**Hasura Version**
v1.1.0

**Comment by tirumaraiselvan** [comment] 2020-03-17 09:57
@subhrashisdas This is actually the expected behaviour currently. The reason for this and efforts to solve this are discussed here: https://github.com/hasura/graphql-engine/issues/704

I am closing this in favour of #704. Please feel free to re-open if you have any other comments.

**Comment by tirumaraiselvan** [comment] 2020-03-17 09:58
Forgot to mention, you can use the `is_null` operator to delete rows which have `null` value: https://hasura.io/docs/1.0/graphql/manual/queries/query-filters.html#filter-or-check-for-null-values-is-null

**Closed by tirumaraiselvan** 2020-03-17 09:57 UTC
