### ISSUE TITLE
"message": "A string is expected for type : _text"

### ISSUE THREAD

**Issue by MooreDevelopment** [hasura/graphql-engine#2138] opened 2019-05-07 14:49 UTC
```
mutation CreateDocument($category_id: uuid,$name: String, $desc: String, $facet_id: uuid){
  insert_documents(objects:
    [{
    	category_id: $category_id
      name: $name
      description: $desc
      documentValuessBydocumentId: {
        data: {
          category_id: $category_id
          facet_id: $facet_id
          value: "Unclassified"
        }
      }
    }]
  ){
    returning {
      id
      name
    }
  }
}
```

is the mutation i am using. In version 34 it worked great, but i can't actually install that anymore. So i upgraded to 45 and now i am getting:

```
{
  "errors": [
    {
      "extensions": {
        "path": "$.selectionSet.insert_documents.args.objects[0]",
        "code": "parse-failed"
      },
      "message": "A string is expected for type : _text"
    }
  ]
}
```

i haven't changed the query at at all and it just doesn't work now.  i have all the types correct. Any idea?

**Comment by ecthiender** [comment] 2019-05-07 15:22
@MooreDevelopment  This is because of a recent change, where we enforce type checking of variables. 

One of the variables used in your mutation is not `String` but `_text`. You can check this in the graphiql "docs" section. Just changing the type to the correct one should work.

**Comment by MooreDevelopment** [comment] 2019-05-07 15:29
@ecthiender I have checked the docs and i have a few fields that are _text but none of these fields. If i remove the "documentValuessBydocumentId" section it runs correctly. The only non uuid string is value and the docs say that it is a string.

**Comment by MooreDevelopment** [comment] 2019-05-07 15:52
@ecthiender So it was a random column in one of the tables that had a _text even though i wasn't inserting any data into that column. Shouldn't that be a bug?

**Comment by ecthiender** [comment] 2019-05-10 07:36
@MooreDevelopment are you sure that none of the columns you are using in the variables, have the type `_text` ?

Would it be possible for you to create a sample heroku app, and put up a minimal schema where this issue can reproduced?

**Comment by MooreDevelopment** [comment] 2019-05-10 13:22
@ecthiender  I am 100% sure. There was a column in the table that was _text but it wasn't part of the query in any way. I altered the table and change it to a String, which fixed the issue. I might be able to spin up a sample heroku app sometime next week, but won't be able to today or this weekend.

**Comment by ecthiender** [comment] 2019-09-11 07:00
@MooreDevelopment is your issue resolved? Closing this issue due to lack of info. Feel free to reopen if you have to add anything.

**Closed by ecthiender** 2019-09-11 07:00 UTC
Labels: needs-more-info

**Comment by guillaumeduhan** [comment] 2022-07-26 17:03
Hasura cannot process array but it can process array literals.

I've written a function to help you to transform your array into array literal before mutation:

`const toArrayLiteral = (arr) => (JSON.stringify(arr).replace('[', '{').replace(']', '}'))

myObject.array = toArrayLiteral(myObject.array) // will make ['friend'] to {'friend'}
`

Good luck
