### ISSUE TITLE
"_or" graphql condition generates "AND" postgres condition

### ISSUE THREAD

**Issue by gsturov** [hasura/graphql-engine#6360] opened 2020-12-16 20:54 UTC
My graphql query condition is something like:
_and ( _or (X1, X2), X3, X4)
But generated postgres query in the log looks like:
(X1 AND X2) AND X3 AND X4

Here is the log:
{"type":"query-log","timestamp":"2020-12-16T20:31:34.011+0000","level":"info","detail":{"request_id":"5831ed01-b8b7-452a-9d76-7027e2a1dc6f","generated_sql":{"asset":{"prepared_arguments":["{\"x-hasura-role\":\"admin\"}","%1001.q1labs%","%1001.q1labs%","2020-12-16T20:30:26.231Z","2020-12-16T20:30:26.231Z"],"query":"SELECT  coalesce(json_agg(\"root\" ), '[]' ) AS \"root\" FROM  (SELECT  row_to_json((SELECT  \"_1_e\"  FROM  (SELECT  \"_0_root.base\".\"id\" AS \"id\", \"_0_root.base\".\"name\" AS \"name\"       ) AS \"_1_e\"      ) ) AS \"root\" FROM  (SELECT  *  FROM \"public\".\"asset\"  WHERE ((((\"public\".\"asset\".\"name\") ILIKE (($2)::text)) AND ((\"public\".\"asset\".\"external_id\") ILIKE (($3)::text))) AND (((\"public\".\"asset\".\"_t1\") <= (($4)::timestamp)) AND ((\"public\".\"asset\".\"_t2\") >= (($5)::timestamp))))     ) AS \"_0_root.base\"      ) AS \"_2_root\"      "}},"query":{"operationName":"search","query":"\nquery search {\n  asset(where: {_and: {_or: {name: {_ilike: \"%1001.q1labs%\"}, external_id: {_ilike: \"%1001.q1labs%\"}}, _t1: {_lte: \"2020-12-16T20:30:26.231Z\"}, _t2: {_gte: \"2020-12-16T20:30:26.231Z\" }}}) {\n    id\n    name\n  }\n}"}}}

**Comment by wwwdepot** [comment] 2020-12-16 21:18
> The _or operator expects an array of expressions as input. Passing an object to it will result in the behaviour of the _and operator due to the way GraphQL list input coercion behaves. [Read the docs](https://hasura.io/docs/1.0/graphql/core/api-reference/graphql-api/query.html#orexp)

Rewrite your `_or` statement to 

```
{
  test(
    where: {
      _and: {
        _or: [
          { name: { _ilike: "FOOBAR" } }
          { external_id: { _ilike: "FOOBAR" } }
        ]
        _t1: { _lte: "FOORBAR" }
        _t2: { _gte: "FOORBAR" }
      }
    }
  ) {
    id
  }
}
```

**Comment by tirumaraiselvan** [comment] 2020-12-17 07:46
@wwwdepot is spot on. This is by design. OR (and AND) expect a list of singleton objects. We cannot enforce that an object have a single key and hence have to resolve multiple key objects and the engine chooses AND to resolve them.

The confusing DX is being tracked in this issue: https://github.com/hasura/graphql-engine/issues/4488

Closing this as dupe.

**Closed by tirumaraiselvan** 2020-12-17 07:46 UTC

**Comment by gsturov** [comment] 2020-12-18 15:45
@wwwdepot thanks!
