### ISSUE TITLE
Subscribing to __typename of a namespace errors

### ISSUE THREAD

**Issue by quody** [hasura/graphql-engine#8174] opened 2022-02-11 12:41 UTC
### Version Information

Server Version: 2.1.0 and 2.2.0

### Environment

OSS

### What is the expected behaviour?

Receiving the same __typename for namespaces both from subscriptions and queries.

### Keywords

subscription namespace introspection __typename

### What is the current behaviour?

When querying namespace __typename everything works fine. For example, in my database
`query {
  v2 {
		__typename
  }
}
`
Yields the response
`{
  "data": {
    "v2": {
      "__typename": "v2v2_query"
    }
  }
}`

However, if I use a subscription I receive the following error
`subscription {
  v2 {
		__typename
  }
}
`

`{
  "extensions": {
    "path": "$",
    "code": "not-supported"
  },
  "message": "Introspection not supported over subscriptions"
}`

This issue also essentially prevents using Apollo Client subscriptions on namespaces, because Apollo uses the __typename for caching and fragments.

### How to reproduce the issue?

1. Create a namespace in Hasura
2. In a subscription try to query the __typename field of a namespace

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/7430048/153591118-de660884-7fc0-41e0-b0a5-fef6cc64c707.png)

**Comment by EternalDeiwos** [comment] 2023-02-10 10:48
Any word on a fix for this?

**Comment by meetzaveri** [comment] 2023-03-22 06:22
Hey @quody can you explain what means by "creating a namespace in hasura" in this context ?

**Comment by EternalDeiwos** [comment] 2023-03-22 07:00
@meetzaveri he is referring to `v2` in the example he provides.

**Comment by meetzaveri** [comment] 2023-03-22 10:21
Thanks @EternalDeiwos , I tried repro'ing but couldn't reproduce the error. Can you help me with steps to reproduce if you faced similar problem ?

**Comment by jsmusgrave** [comment] 2023-03-23 22:01
This is blocking our work on a second product on the paid platform.

**Comment by tirumaraiselvan** [comment] 2023-04-04 13:09
We are looking into this. It's a bit weird that __typenames are being added for subscription operations which are not really intended for caching - so there are potential apollo-client fixes/enhancements which should allow to not add __typenames for subscriptions.

**Comment by jsmusgrave** [comment] 2023-04-04 17:03
@tirumaraiselvan Our issues with this is with flutter clients.  We've tried three different client sdks and they all have this problem.

**Comment by tirumaraiselvan** [comment] 2023-04-05 03:36
@jsmusgrave Got it. It may be worth looking into any client-side workarounds like mentioned here: https://github.com/zino-hofmann/graphql-flutter/issues/846#issuecomment-803939789 to unblock you while we are looking at the server-side fix for this.

**Comment by manasag** [comment] 2023-07-17 09:02
This is now supported in v2.30.0-beta.1. Here is the commit: https://github.com/hasura/graphql-engine/commit/249a3f4c77e0cd2a95ae3df71dda02965fc68796

**Closed** 2023-07-25 00:17 UTC
Labels: k/bug
