### ISSUE TITLE
Cannot use directive with variables inside `fragment`

### ISSUE THREAD

**Issue by xiaoyu-tamu** [hasura/graphql-engine#6397] opened 2020-12-28 16:45 UTC
Version: v1.3.4-beta.2

I'm not sure if this already fixed in this commit

https://github.com/hasura/graphql-engine/commit/4bbd2fd4dc0d903ca70252b5d204b2db2b9d49f6

### directive inside `fragment`
```
query products($withSKU: Boolean = false) {
  products {
    ...productRow
  }
}

fragment productRow on product {
  id
  sku @include(if: $withSKU)
}

// response
{
  "errors": [
    {
      "extensions": {
        "path": "$.query",
        "code": "validation-failed"
      },
      "message": "not a valid graphql query"
    }
  ]
}
```

### ### directive inside `query`
```
query products($withSKU: Boolean = false) {
  products {
    ...productRow
    sku @include(if: $withSKU)
  }
}

fragment productRow on product {
  id
}

// response
{
  "data": {
    "products": [
      {
        "id": 200080
      },
      ...
  }
}
```

**Comment by jberryman** [comment] 2021-01-04 22:57
Yes this is a dupe of https://github.com/hasura/graphql-engine/issues/6303 as far as I can tell

**Closed by jberryman** 2021-01-04 22:57 UTC
