### ISSUE TITLE
v1.4.0-alpha1 tracking sql volatile mutation issues

### ISSUE THREAD

**Issue by LydiaF** [hasura/graphql-engine#6538] opened 2021-02-10 14:47 UTC
Hi Hasura,

v1.4 is looking great, thank you!

I am having two issues:

### Issue 1

After I click Track -> Track as Mutation in hasura console in the section "Untracked custom functions" I get an error:

```
Adding existing function failed
{
    "path": "$[0]",
    "error": "When parsing Hasura.Server.API.Query.RQLQueryV2 expected an Object with a tag field where the value is one of [track_table, set_table_custom_fields, track_function], but got pg_track_function.",
    "code": "parse-failed"
}
```

### Issue 2

I was able to track a function through typescript metadata - it shows up in the side panel on the left of the schema. However, it is not showing up on the graphql api as either a query or mutation.

Thank you,

Lydia

**Comment by tirumaraiselvan** [comment] 2021-02-17 13:11
For `Issue 1`, we can't repro it. Could you confirm that you are on v1.4 because the API call is right but the server doesn't recognize it : `pg_track_function` 

>     "error": "When parsing Hasura.Server.API.Query.RQLQueryV2 expected an Object with a tag field where the value is one of [track_table, set_table_custom_fields, track_function], but got pg_track_function.",

**Comment by beerose** [comment] 2021-02-17 13:11
Hi @LydiaF,
I couldn't reproduce it. These issues could happen with an old version of a server. Are you sure you are using `v1.4.0-alpha.1`?

**Comment by tirumaraiselvan** [comment] 2021-02-18 11:03
Hi @LydiaF Going to close this for now for tracking. Please comment/reopen if you still hit this.

**Closed by tirumaraiselvan** 2021-02-18 11:03 UTC
Labels: c/console
