### ISSUE TITLE
All INSERT mutations fail, Hasura adds DEFAULT values into generated columns

### ISSUE THREAD

**Issue by nolandg** [hasura/graphql-engine#3681] opened 2020-01-10 22:39 UTC
When I have a Postgres generated column and attempt to make a Graphql insert mutation, it works perfectly when running as `admin` role with a Hasura admin secret set in the header.

It fails though for any other role, ie. whenever the admin secret is not set. When I make the insert mutation query without being admin, Hasura adds *all* fields into the `INSERT` statement and puts their values as `DEFAULT`. Postgres then complains that you can't insert into generated columns.

When my table name is `work_entry` and one of the generated columns is `startTime` (which casts the `start` timestamp to time of day) this is the query Hasura makes and Postgres fails on:

````sql
INSERT INTO "hdb_views"."manager__insert__public__work_entry" 
    ( "jobId", "createdAt", "startTime", "start", "userId", "end", "endTime", "id", "updatedAt", "duration" ) 
    VALUES ($2, DEFAULT, DEFAULT, DEFAULT, $3, DEFAULT, DEFAULT, $1, DEFAULT, DEFAULT)  RETURNING * )
````

````
acdcwelding_postgres | 2020-01-10 22:33:59.835 UTC [129] ERROR:  cannot insert into column "startTime"
acdcwelding_postgres | 2020-01-10 22:33:59.835 UTC [129] DETAIL:  Column "startTime" is a generated column.
````

There is no default set for all these columns. Why does Hasura stick them into the `INSERT` query? And why does this work perfectly when querying with a Hasura admin secret header but not without? 

I do not have any role presets and the permissions work perfectly for all other fields.

On discord it was pointed out that there is a separate code path for admin inserts vs. non-admin inserts:
https://github.com/hasura/graphql-engine/blob/master/server/src-lib/Hasura/RQL/DML/Insert.hs#L254

**Comment by GavinRay97** [comment] 2020-01-13 16:03
Upon further investigation, this is a duplicate of:

https://github.com/hasura/graphql-engine/issues/3572

And it seems will be fixed as a by-product of:

https://github.com/hasura/graphql-engine/pull/3598

See comment on issue thread:

https://github.com/hasura/graphql-engine/issues/3572#issuecomment-572665921

**Comment by paf31** [comment] 2020-01-14 02:42
Correct, thanks. I'll close this as a duplicate now.

**Closed by paf31** 2020-01-14 02:42 UTC
Labels: c/server, duplicate
