### ISSUE TITLE
update_many returns a single object rather than an array of objects if no updates provided; clashes with types

### ISSUE THREAD

**Issue by osdiab** [hasura/graphql-engine#10322] opened 2024-07-10 01:36 UTC
### Version Information

Server Version: 2.40.2
CLI Version (for CLI related issue): 2.40.2 (N/A)

### Environment

OSS locally

### What is the current behaviour?

for an `update_many` query on a table, the return types as generated by `graphql-codegen` were to return an array like `update_table_name_many: {returning: {...}[]}[]`; sometimes indeed this is what I got back, but if you provide an empty array of updates (`[]`), it returns a single object rather than an array. This is a problem because I use the `update_many` command for a variable number of updates as determined by what the user does, which often can be none at all (alongside other mutations like inserts and deletes to other related tables in the same GraphQL mutation document); and what my code ultimately does depends on the return value of the mutation.

The introspection query returned this for the relevant mutation:

```
  update_table_name_many(
    """updates to execute, in order"""
    updates: [table_name_updates!]!
  ): [table_name_mutation_response]
```

So my TypeScript types ended up being wrong and then it caused an `undefined` function invocation error when I tried to `.map()` across the results.

### What is the expected behaviour?

- My understanding is that the updates return type should be an array of the same size of the updates provided; so `graphql-engine` should just always return an array, and in the case of an empty `[]` updates, it should also return an empty array.

### How to reproduce the issue?

run a mutation like

```
update_table_name_many(updates: []) {
  returning {
    id
  }
}
```

see that it returns a single object like so:

```
{
  "data": {
    "update_table_name_many": {
      "returning": []
    }
  }
}
```

Instead of what I expected based on the types:

```
{
  "data": {
    "update_table_name_many": []
  }
}
```

### Screenshots or Screencast

--

### Please provide any traces or logs that could help here.

--

### Any possible solutions/workarounds you're aware of?

I am just special casing this scenario in my code like so:

```
    const updateResults =
      result.update_table_name_many &&
      !Array.isArray(result.update_table_name_many)
        ? [result.update_table_name_many]
        : result.update_table_name_many;
```

but that's gross.

### Keywords

update many object array return type schema graphql codegen typescript consistent consistency

**Comment by SamirTalwar** [comment] 2024-07-22 12:00
This looks like a duplicate of #10239. Is that correct, @osdiab?

**Comment by SamirTalwar** [comment] 2024-07-22 12:01
#10135 is also related.

**Comment by osdiab** [comment] 2024-07-22 14:05
Looks right, thanks.

**Comment by SamirTalwar** [comment] 2024-07-22 14:08
OK, thanks. We'll close this issue and bump up the priority of those issues instead. Thanks for adding your insights.

**Closed by SamirTalwar** 2024-07-22 14:08 UTC
Labels: k/bug, c/server, a/mutation
