### ISSUE TITLE
Can't mutate a field which has a default preset

### ISSUE THREAD

**Issue by mathieutu** [hasura/graphql-engine#3268] opened 2019-10-29 09:31 UTC
Hi,
I've set a default value to a user_id field using a session variable with preset:
<img width="967" alt="Screen Shot 2019-10-29 at 10 19 00" src="https://user-images.githubusercontent.com/11351322/67754022-00328680-fa36-11e9-8aab-d3a1a0ddb1aa.png">

As soon I've done that, the user_id field has disappeared from input type, so I've a type error when trying to execute my mutation : `field "user_id" not found in type: 'documents_insert_input'`

<img height="250" alt="Screen Shot 2019-10-29 at 10 19 14" src="https://user-images.githubusercontent.com/11351322/67754069-1dffeb80-fa36-11e9-82a0-b35393358e0b.png">

When I remove the preset, everything works again.
<img width="848" alt="Screen Shot 2019-10-29 at 10 19 39" src="https://user-images.githubusercontent.com/11351322/67754347-99619d00-fa36-11e9-9945-a5caec008191.png">
<img height="250" alt="Screen Shot 2019-10-29 at 10 19 51" src="https://user-images.githubusercontent.com/11351322/67754354-9bc3f700-fa36-11e9-854d-fc5cafae56fb.png">

Am I doing anything wrong?

Presets aren't supposed to be default value, that can be overwritten ?
<img width="372" alt="Screen Shot 2019-10-29 at 10 29 27" src="https://user-images.githubusercontent.com/11351322/67754621-11c85e00-fa37-11e9-84d1-3f583928689b.png">

Thanks.

**Comment by rikinsk** [comment] 2019-10-30 06:33
@mathieutu This is by design. Presets are currently not meant to be overriden.

You should take a look at https://docs.hasura.io/1.0/graphql/manual/schema/default-values/index.html for options on setting default values based on requirements. 

Do let us know if your use case doesn't fit into any of the options and we can discuss the use case and the current limitations in more detail.

**Comment by mathieutu** [comment] 2019-10-30 11:23
Ok, thanks for the answer.
Actually I would like to set the user_id from session variable if not present in the mutation input, or override it if present (like a real default value).

If its by design, I would change the help message, as it really specifies its a **default** value:
>Set static values or session variables as default values for columns while inserting

**Comment by marionschleifer** [comment] 2020-01-08 09:21
@mathieutu I'm closing this issue. Feel free to re-open if you would like to add something 🙂

**Closed by marionschleifer** 2020-01-08 09:21 UTC
Labels: k/question❓
