### ISSUE TITLE
Console error: [Minified React error] when metadata is in an inconsistent state

### ISSUE THREAD

**Issue by creatorrr** [hasura/graphql-engine#7328] opened 2021-08-01 04:13 UTC
Running into an error loading the console on opening _console/settings/metadata-status_ when metadata is in an inconsistent state.

Hasura server version: `2.0.3`

Stacktrace:
```js
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Braw_body%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ba (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.0/vendor.js.gz:1:4873555)
    at f (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.0/vendor.js.gz:1:4875244)
    at m (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.0/vendor.js.gz:1:4876357)
    at https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.0/vendor.js.gz:1:4878467
    at Ko (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.0/vendor.js.gz:1:4888040)
    at Xl (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.0/vendor.js.gz:1:4928519)
    at jl (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.0/vendor.js.gz:1:4919492)
    at zl (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.0/vendor.js.gz:1:4919417)
    at Ol (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.0/vendor.js.gz:1:4916267)
    at https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.0/vendor.js.gz:1:4867239
```

![Screenshot from 2021-08-01 09-39-42](https://user-images.githubusercontent.com/931887/127758911-c78adf2f-47ac-4697-a2e0-063971972b74.png)

**Comment by jadiaheno** [comment] 2021-08-02 20:57
We're having the exact same issue on 2.0.1-2.0.5

**Comment by jeffmath** [comment] 2021-08-03 05:07
Same for me.  This error prevents me from opening the console using any route.

**Comment by mirzap** [comment] 2021-08-03 15:11
I get the same now. It would be good anyway that app doesn't redirect to `console/settings/metadata-status` page. It should just display `error` notification or alert.

**Comment by purefun** [comment] 2021-08-14 05:39
try to run `hasura metadata inconsistency list` and `hasura metadata inconsistency drop` . it fixed for me.

**Comment by MatrixFrog** [comment] 2021-08-14 22:14
By staring at the minified code long enough, I've managed to determine that I _think_ the problem is here:

https://github.com/hasura/graphql-engine/blob/5d6211d3dcc823e38ee2dfacec5189942ad59307/console/src/components/Services/Settings/MetadataStatus/MetadataStatus.js#L152

`iconsistentObject.message` is supposed to be a string, but is instead an object (and not a React element) so the React tree is not valid. Hope this helps someone.

**Comment by HarunKilic** [comment] 2021-08-17 06:43
Clearing the localstorage and cookies fixed it for me.

**Comment by iykekings** [comment] 2021-08-17 08:41
@creatorrr @MatrixFrog Please I'm trying to reproduce this on my end. What led to your metadata inconsistent state?

**Comment by MatrixFrog** [comment] 2021-08-17 18:47
It seems like I may have gotten to this state in a few different ways, but one of them that I can repro consistently is that I have a remote schema that Hasura can't access because I haven't started that server yet. I made a minimal repro here: https://cloud.hasura.io/project/4f941bd6-c51c-4cc7-8595-268fe427c34a/console , let me know if I need to add you to that project so you can access it.

**Comment by MatrixFrog** [comment] 2021-08-17 19:01
Actually it might be easier to just list the steps.

1. Create a new project on Hasura Cloud
1. Create an environment variable `REMOTE_GQL_ENDPOINT` whose value is any valid graphql server (I used `https://api.spacex.land/graphql`)
1. Go into the Hasura Console and create a remote schema using the env var `REMOTE_GQL_ENDPOINT` as the URL.

1. Change the environment variable's value to `http://does.not.exist/graphql`
1. Go back to the Hasura Console and reload
1. Bam, React error `#31`

In the devtools Network tab, I see several requests to https://issue-7328-repro-2.hasura.app/v1/metadata , and for one of them the response looks like this:

![metadata-response](https://user-images.githubusercontent.com/244381/129784972-2aa07534-2fe7-451b-9e74-efa3fe5448ea.png)

As you can see the `message` property of the inconsistent object is an object, but it looks like the frontend code expects it to be a string. Hopefully this explanation makes sense, if not I can make a short video if that would help.

**Comment by iykekings** [comment] 2021-08-18 11:18
Thanks a @MatrixFrog. I was able to reproduce this.

**Comment by iykekings** [comment] 2021-08-23 08:42
Closing as resolved.

**Closed by iykekings** 2021-08-23 08:42 UTC
Labels: c/console/data, t/console/data

**Comment by MatrixFrog** [comment] 2021-08-23 16:27
It looks like the fix is https://github.com/hasura/graphql-engine/commit/4330798a71e9ec62924da4e7ae4e8b0b00523441 so it should be in v2.0.8

**Comment by bask-digital** [comment] 2021-10-18 23:13
You are right. We're unable to find any metadata in the network tab that is `is_inconsistent: false`.

We are seeing some metadata requests return with a 524 response (Gateway timeout).

**Comment by adhendo** [comment] 2022-03-24 14:53
@bask-digital any luck with a solution? I too am getting a minified react error on a single table and cant find any "is_consistent": false, hasura metadata inconsistency list also saying data is consistent

**Comment by adhendo** [comment] 2022-04-25 19:24
@bask-digital interesting, I'm actually using `_` in the table name that im having an issue with lol oh well!

**Comment by sarangnx** [comment] 2022-09-05 05:55
I encountered same issue a while ago,
It was due to enabling manual event trigger in that table. Disabling it cleared the issue.

```diff
event_triggers:
  - definition:
-      enable_manual: true
+      enable_manual: false
```
