### ISSUE TITLE
using Actions for type resolvers

### ISSUE THREAD

**Issue by andycmaj** [hasura/graphql-engine#5637] opened 2020-08-21 02:35 UTC
hey all! Anyone using Actions know if there's a way to re-use the hasura-generated schema types, eg. `activity_bool_exp`, etc. in action definitions? 

what i really want to do is to add an enricher (resolver) to an already generated type. but don't see an exact example for that case, so having to create a type query { enriched_activity(...) } but don't want to duplicate all the predicates/results/etc.

example:

### my hasura-generated schema

```graphql
"""query root"""
type query_root {
  """
  fetch data from the table: "activity"
  """
  activity(
    """distinct select on columns"""
    distinct_on: [activity_select_column!]

    """limit the number of rows returned"""
    limit: Int

    """skip the first n rows. Use only with order_by"""
    offset: Int

    """sort the rows by one or more columns"""
    order_by: [activity_order_by!]

    """filter the rows returned"""
    where: activity_bool_exp
  ): [activity!]!
}
```

### desired action

ideally, i could just write a resolver handler that actually just enriches the results returned by another query type without having to re-build all the generated hasura types.

```graphql
type query_root {
  versioned_activity {
    """distinct select on columns"""
    distinct_on: [activity_select_column!]

    """limit the number of rows returned"""
    limit: Int

    """skip the first n rows. Use only with order_by"""
    offset: Int

    """sort the rows by one or more columns"""
    order_by: [activity_order_by!]

    """filter the rows returned"""
    where: activity_bool_exp
  } [activity!]!
}
```

**Comment by tirumaraiselvan** [comment] 2020-08-31 11:53
Dupe of https://github.com/hasura/graphql-engine/issues/5001

**Closed by tirumaraiselvan** 2020-08-31 11:53 UTC
