### ISSUE TITLE
support passing session variables through "extensions" key

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#1587] opened 2019-02-12 05:38 UTC
We use http headers to pass session variables in these two scenarios:
1. admin/insecure mode
2. `x-hasura-role` in all other modes

This results in issues such as #213. We should start supporting sending these variables in the `extensions` key.

**Comment by 0x777** [comment] 2019-02-12 05:41
We should check if the popular client libraries allow customising `extensions` value.

**Comment by manasag** [comment] 2023-12-28 16:18
This issue has not attracted significant attention for a long period of time, hence closing this.
Please feel free to reopen if the issue is still relevant for you.

**Closed by manasag** 2023-12-28 16:18 UTC
Labels: c/console, c/server, p/longterm
