### ISSUE TITLE
[Hasura cli] [Error] Got error message when running `hasura scripts update-project-v3`

### ISSUE THREAD

**Issue by yumemi-omi** [hasura/graphql-engine#6973] opened 2021-05-23 10:21 UTC
- Prerequisite
``` config.yaml
version: 2
endpoint: <myapp domein>
admin_secret: <admin-secret>
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
```

```
INFO hasura cli      
version=v2.0.0-alpha.10
INFO hasura graphql engine
endpoint=<my endpoint>
version=v2.0.0-cloud.11
```

- Process
Run `hasura scripts update-project-v3`.
And I answered below
`The update process replaces project metadata with metadata on the server 
continue? (y/n): y`
`what database does the current migrations / seeds belong to?: my-db`
And then got error message.
```
FATA[0020] {
  "path": "$",
  "error": "source with name \"default\" does not exist",
  "code": "not-exists"
} 
```

- Question
We can't change the database name? I changed the database name.(`default` -> `my-db`)

**Comment by rikinsk** [comment] 2021-05-24 10:29
@yumemi-omi there seems to be a little confusion here. let me try to explain what's going on here

- While updating from v1 to v2, the database configured via `HASURA_GRAPHQL_DATABASE_URL` gets added to Hasura with the name `default` by default. 
- You can update this name to another name of your choice by [exporting the Hasura metadata](https://hasura.io/docs/latest/graphql/core/migrations/manage-metadata.html#exporting-hasura-metadata), changing the database name in it, and reimporting the metadata (_support for doing this via api/console is coming soon_).
- While updating the CLI project to config v3 using `update-project-v3`, the CLI prompts you to enter the database to which the migrations belong to. This just expects the name of a database that already exists in the metadata. It doesnt let you choose a new name for the database here. We will improve the UX of this command to not prompt for a database name as it can be derived from your metadata directly to avoid this confusion.

Hope this helps explain the cause of the error.

We can use this issue to track the UX improvement in the `update-project-v3` command mentioned above.

**Comment by scriptonist** [comment] 2021-06-07 03:36
Fixed in https://github.com/hasura/graphql-engine/commit/ea6a2c9a149df8b0d5dd911f8268c04d229ed125

**Closed by scriptonist** 2021-06-07 03:36 UTC
Labels: c/cli, k/enhancement

**Comment by yumemi-omi** [comment] 2021-06-07 04:43
@rikinsk 
Sorry for the delayed reply and thank you for elaborating on what's happened. I understood this situation and I'm working correctly now👍

@scriptnull 
Also thank you for fixing it！

**Comment by founderpad** [comment] 2022-01-07 18:42
What's this issue about? I changed the name of the db to something meaningful and now nothing will start. I can't export anything as Postgres won't start due to this error. What's the fix here????
