### ISSUE TITLE
create object/array relationship using foreign key constraint name

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#285] opened 2018-08-14 08:25 UTC
[ObjRelUsing](https://docs.platform.hasura.io/0.15/platform/manual/api-reference/data/query/relationship.html#objrelusing) should also support `foreign_key_constraint_name`

**Comment by dsandip** [comment] 2018-12-13 10:40
@shahidhk @0x777 @praveenweb This requires a change in the JSON API with type `create_object_relationship`, right? Does this have an impact on the console?

**Comment by shahidhk** [comment] 2018-12-14 10:01
@rakeshkky Can you confirm if the API changes are required?

**Comment by manasag** [comment] 2023-12-27 09:15
This issue has not attracted significant attention for a long period of time, hence closing this.
Please feel free to reopen if the issue is still relevant for you.

**Closed by manasag** 2023-12-27 09:15 UTC
Labels: k/enhancement, c/console, c/server, p/longterm
