### ISSUE TITLE
Issue with Remote Scheme request having a custom type argument after Hasura 2.0 upgrade

### ISSUE THREAD

**Issue by vamshi-tg** [hasura/graphql-engine#7397] opened 2021-08-16 08:21 UTC
**Description**:
If a Remote Schema mutation or query includes a **Custom Type argument** and if we do not pass a value to any of the argument's fields then the request is failing, even if the field is **nullable**.

**Example**:

Consider the below mutation where **metadata** is a Custom Type argument whose type is **`{ name: String!, label: String}`**.

```graphql
  mutation CreateEntity(
    $image_url: String!
    $name: String!
    $label: String
  ) {
    creatives_create_display_image(
      image: $image_url
      metadata: {
        name: $name
        label: $label
      }
    ) {
      creative {
        id
      }
    }
  }
```
On sending the mutation request with the below variables the request is failing.
```json
{
   "image_url": "test_url_string",
   "name": "Test Entity Name"
}
```
**Graphql Response**
```json
{
  "data": null,
  "errors": [
    {
      "message": "Syntax Error GraphQL request (1:28) Unexpected Name \"null\"\n\n1: mutation ($label: String = null,$name: String!,$hasura_json_var_1: String) { creatives_create_display_image(image: $hasura_json_var_1,metadata: {name: $name,label: $label}) { creative { id  } } }\n                              ^\n",
      "locations": [
        {
          "line": 1,
          "column": 28
        }
      ]
    }
  ]
}
```

**The same query worked fine before upgrading to Hasura 2.0.**

I'm using the below hasura versions
```shell
INFO hasura cli is up to date           version=2.0.4
INFO hasura cli                         version=v2.0.4
INFO hasura graphql engine              endpoint="http://localhost:9001/" version=v2.0.3
```

**Comment by sassela** [comment] 2021-09-06 09:29
@vamshi-tg thanks for raising this issue!

Hasura team, this issue involves:
1. reproducing with the above graphQL queries
2. confirming that this is indeed a bug (or whether it's a breaking change from 2.0, for example)
3. estimate effort/complexity & triage with @0x777

**Comment by nicuveo** [comment] 2021-09-15 12:26
Hi! Looking at the answer, it looks like the error was sent by the remote server. The message starts with "Syntax Error GraphQL request", which is not one we emit, and the error message mentions `hasura_json_var_1`, which is how we repack JSON values for remote server consumption.

Looking at the emitted query, included in the error message, this is what we sent:
```graphql
mutation ($label: String = null, $name: String!, $hasura_json_var_1: String) {
  creatives_create_display_image(image: $hasura_json_var_1, metadata: {name: $name, label: $label}) {
    creative {
      id
    }
  }
}
```

As far as I can tell, this is a valid query, syntax-wise: it is parsed without any problem by the graphql-engine. However, the remote server rejects it because of a "syntax error" on line 1, character 28, which is the `= null` of `label`.

I would therefore suspect that your remote server doesn't properly handle default values in mutation arguments, or perhaps doesn't handle the special case "null" properly.

**Comment by sassela** [comment] 2021-09-21 11:42
> I would therefore suspect that your remote server doesn't properly handle default values in mutation arguments, or perhaps doesn't handle the special case "null" properly.

I'm going to close this issue for now, in this case. @vamshi-tg please do reopen if you think the problem is on our end.

**Closed by sassela** 2021-09-21 11:42 UTC
Labels: t/server/data

**Comment by 1018715564** [comment] 2021-11-29 07:34
I had the same problem when I was building the query

```graphql
query getProducts($title: String, $desc: String, $minPrice: Int) {
  products(where: {title: {_like: $title}, desc: {_like: $desc}, price: {_gte: $minPrice}}) {
    id
    title
    desc
    price
    push_user {
      id
      phone
    }
  }
}

```

![image](https://user-images.githubusercontent.com/35763284/143826257-d8aeeb28-d9d1-408d-8484-37cd80016152.png)
