### ISSUE TITLE
[v2.0.0-alpha.3] Relationship is NON_NULL when the base field is nullable

### ISSUE THREAD

**Issue by esseswann** [hasura/graphql-engine#6633] opened 2021-03-04 19:24 UTC
Having this nullable field
![image](https://user-images.githubusercontent.com/6066417/110018304-383b8f00-7d38-11eb-8c97-1274ec10ce0c.png)
we create a relationship
![image](https://user-images.githubusercontent.com/6066417/110018387-48ec0500-7d38-11eb-86b8-af180858432b.png)
that leads to incorrect representation in `__schema`
![image](https://user-images.githubusercontent.com/6066417/110018491-6325e300-7d38-11eb-8087-3a981afcd5e3.png)
expected `viaStation` to be nullable

**Comment by tirumaraiselvan** [comment] 2021-03-08 08:12
Seems like a dupe of https://github.com/hasura/graphql-engine/issues/6555

**Comment by esseswann** [comment] 2021-03-08 10:22
Agree, should we close this one?

**Comment by tirumaraiselvan** [comment] 2021-03-09 09:01
@esseswann Let's use the current issue since more activity here

**Comment by tirumaraiselvan** [comment] 2021-03-10 09:28
Closed via https://github.com/hasura/graphql-engine/commit/d16bc4fe464b4958751d46a96ec8adff4606526a

**Closed by tirumaraiselvan** 2021-03-10 09:28 UTC
Labels: c/server, k/bug
