### ISSUE TITLE
How can hasura data types support integer arrays

### ISSUE THREAD

**Issue by messi2288** [hasura/graphql-engine#2802] opened 2019-08-30 07:22 UTC
Hi,How can hasura data types support integer arrays?
The tags field as shown below：
posts: [{ id: 1, title: 'title1',tags[1,2]}].

And how do I query tags using graphql (or other query ways)？

**Comment by messi2288** [comment] 2019-08-30 08:53
I found the solution:https://github.com/hasura/graphql-engine/pull/2243
I imported the test data using json2graphql, which you can see in the URL below:
https://hge-ci-pull-2243.herokuapp.com/console
It looks like the problem has been solved.
![image](https://user-images.githubusercontent.com/54701869/64006892-c502fc80-cb45-11e9-907a-10670358d700.png)
But there was a bug when I changed the tag field on the console
![image](https://user-images.githubusercontent.com/54701869/64007269-6ab66b80-cb46-11e9-808c-3d3a9fa2431e.png)
![image](https://user-images.githubusercontent.com/54701869/64007345-9a657380-cb46-11e9-9e1a-c5ef816efd9e.png)

**Comment by 0x777** [comment] 2019-09-02 12:05
Hi @messi2288 #2243 is still work in progress and hasn't been merged to master. In the current release, you can use Postgres literals for array input but we don't have any operators that work on array types. Duplicate of https://github.com/hasura/graphql-engine/issues/348.

**Closed by 0x777** 2019-09-02 12:05 UTC
Labels: c/server, k/question

**Comment by messi2288** [comment] 2019-09-04 04:49
Hi @0x777  Thank you very much
