### ISSUE TITLE
WebSocket is closed before the connection is established

### ISSUE THREAD

**Issue by rajinwonderland** [hasura/graphql-engine#5717] opened 2020-09-03 04:19 UTC
Hi there 👋 

Wanted to report a websocket issue I've been experiencing across all of my hasura instances (v1.3.1). 

Logs from chrome-dev on hasura's console

```
vendor.js.gz:1 WebSocket connection to 'wss://trufala-pipelines-hasura.fly.dev/v1/graphql' failed: WebSocket is closed before the connection is established.
```

```
vendor.js.gz:1 WebSocket connection to 'wss://fleeting-imac.fly.dev/v1/graphql' failed: WebSocket is closed before the connection is established.
```

The issue only appears to be happening on the self hosted instances and not on the cloud.

I'm using fly.io for deployments. Not having the same issue with v1.2.2

 Any help would be greatly appreciated! 👍

**Comment by rajinwonderland** [comment] 2020-09-03 05:35
I went ahead and ported over those two instances to hasura-cloud for now which seems to work well.

If anyone has any insight as to how I can fix this on my self hosted instances, I'd very much appreciate the help!

**Comment by tirumaraiselvan** [comment] 2020-09-07 07:08
Is it possible to give a small code-snippet with connection initialization and execution code which can be used to repro this on v1.3.x?

**Comment by beerose** [comment] 2020-09-12 18:01
I'm closing it as a duplicate of https://github.com/hasura/graphql-engine/issues/4509. If you have any insights on this issue, please leave a comment there.

**Closed by beerose** 2020-09-12 18:01 UTC
Labels: support/needs-more-info
