### ISSUE TITLE
Hasura Admin interface shows wrong mutation name defaults

### ISSUE THREAD

**Issue by larsblumberg** [hasura/graphql-engine#7516] opened 2021-09-07 08:41 UTC
### Version Information

Server Version: 2.0.6

### What is the expected behaviour?

The "Custom GraphQL Root Fields' sections shows correct mutation name defaults for deleting and updating rows by primary key.

### Keywords

wrong mutation names

### What is the current behaviour?

The default mutation name for delete/update by primary key shows as `update_by_pk_users` instead of `update_users_by_pk` - see screenshot below.

### How to reproduce the issue?

1. select a table
2. select tab "Modify"
3. click "Edit' in section "Custom GraphQL Root Fields"

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/5980316/132313884-88324477-e36b-46af-910e-c81c8ba58a63.png)

### Any possible solutions?

Change the placeholder text for the input fields to spell the proper mutation name defaults.

### Can you identify the location in the source code where the problem exists?

Did not look into the source code yet.

### If the bug is confirmed, would you be willing to submit a PR?

Yes.

**Comment by jflambert** [comment] 2022-02-09 17:33
Looks like I wrote exactly the same issue #8113 except I have additional suggestions.

I'll leave it to admins to decide which one should be closed (or not)

**Comment by julian-mayorga** [comment] 2023-06-22 17:09
Thanks for reporting this @larsblumberg and @jflambert 

Hasura v2.28 shows the correct mutation names, as you can see here:

<img width="761" alt="Screenshot 2023-06-22 at 14 05 33" src="https://github.com/hasura/graphql-engine/assets/118911427/981a5cad-cdc3-4fef-ad7b-3dfa9335aff1">

**Comment by jflambert** [comment] 2023-06-22 18:37
Confirmed fixed in 2.28.0

@larsblumberg @julian-mayorga @vijayprasanna13 please close the issue

**Closed** 2023-06-23 04:33 UTC
Labels: k/bug, c/console, e/easy, estimate/S
