### ISSUE TITLE
Cannot apply metadata; "key definition was not present" but doesn't say where

### ISSUE THREAD

**Issue by haf** [hasura/graphql-engine#8492] opened 2022-05-16 09:50 UTC
### Version Information

Server Version: 2.6.2
CLI Version (for CLI related issue): 2.6.2

### Environment

docker

### What is the expected behaviour?

To be able to apply metadata

### What is the current behaviour?

```
❯ hasura metadata apply --log-level trace
DEBU global config file exists, verifying contents
DEBU global config is pre-set to &cli.GlobalConfig{UUID:"95398f34-7c00-43f6-a950-60ceca8df3ec", EnableTelemetry:true, ShowUpdateNotification:true, CLIEnvironment:"default"}
DEBU global config: uuid: 95398f34-7c00-43f6-a950-60ceca8df3ec
DEBU global config: enableTelemetry: true
DEBU global config: showUpdateNotification: true
DEBU global config: cliEnvironment: default
DEBU versions: cli: [v2.6.2] server: [v2.6.2]
DEBU compatibility check: [true] compatible CLI and Server
DEBU cannot get config information from server, this might be because config API is not enabled: error unmarshalling fetching server config
DEBU graphql engine endpoint: http://localhost:8080
DEBU graphql engine admin_secret: ‹×›
DEBU server: uuid: 9f2063fa-e098-4529-bbe7-86715a2422ab
DEBU cli-ext: setting up using cli-ext embedded in cli binary
DEBU output: {"success":true,"output_file_path":"/var/folders/8w/cvcn82yj19v09j2tcj2t11vw0000gn/T/120300443.json"}  command="sdl from"
DEBU telemetry: beamed                             fields.time=220.398625ms isError=true
FATA[0003] error applying metadata
{
  "path": "$.args.metadata.query_collections[0]",
  "error": "the key 'definition' was not present",
  "code": "parse-failed"
}
```

### How to reproduce the issue?

No idea; I have hundreds of tables and I don't know where or how I should start to reproduce this. This comes incompatible changes to metadata when the CLI changed its yaml format, I think, but since the CLI doesn't say which bit of metadata it's currently appling, it's almost impossible to debug!

### Please provide any traces or logs that could help here.

```
analytics-api-1  | {"type":"http-log","timestamp":"2022-05-16T09:48:04.542+0000","level":"info","detail":{"operation":{"request_id":"5e5bcedc-cc83-4ea5-a71a-273b052ab967","response_size":15,"request_mode":"non-graphql"},"request_id":"5e5bcedc-cc83-4ea5-a71a-273b052ab967","http_info":{"status":200,"http_version":"HTTP/1.1","url":"/v1/version","ip":"172.19.0.1","method":"GET","content_encoding":null}}}
analytics-api-1  | {"type":"http-log","timestamp":"2022-05-16T09:48:04.542+0000","level":"info","detail":{"operation":{"query_execution_time":1.2311416e-2,"user_vars":{"x-hasura-role":"admin"},"request_id":"13050343-aa38-4a8b-a83d-e8611de3d03d","response_size":25349,"request_mode":"non-graphql","request_read_time":1.041e-6},"request_id":"13050343-aa38-4a8b-a83d-e8611de3d03d","http_info":{"status":200,"http_version":"HTTP/1.1","url":"/v1/query","ip":"172.19.0.1","method":"POST","content_encoding":"gzip"}}}
analytics-api-1  | {"type":"http-log","timestamp":"2022-05-16T09:48:04.542+0000","level":"info","detail":{"operation":{"request_id":"e4370d4e-49a4-49f4-a60a-5f8def900620","response_size":15,"request_mode":"non-graphql"},"request_id":"e4370d4e-49a4-49f4-a60a-5f8def900620","http_info":{"status":200,"http_version":"HTTP/1.1","url":"/v1/version","ip":"172.19.0.1","method":"GET","content_encoding":null}}}
analytics-api-1  | {"type":"http-log","timestamp":"2022-05-16T09:48:04.542+0000","level":"info","detail":{"operation":{"query_execution_time":1.7720584e-2,"user_vars":{"x-hasura-role":"admin"},"request_id":"99fdd4bf-4083-4648-bff0-31cd4195f454","response_size":1734,"request_mode":"non-graphql","request_read_time":2.583e-6},"request_id":"99fdd4bf-4083-4648-bff0-31cd4195f454","http_info":{"status":200,"http_version":"HTTP/1.1","url":"/v1/metadata","ip":"172.19.0.1","method":"POST","content_encoding":"gzip"}}}
analytics-api-1  | {"type":"http-log","timestamp":"2022-05-16T09:48:04.542+0000","level":"error","detail":{"operation":{"error":{"path":"$","error":"Missing 'Authorization' or 'Cookie' header in JWT authentication mode","code":"invalid-headers"},"request_id":"bb625713-8f6f-451c-b085-d12d0adfa2a2","response_size":117,"request_mode":"error","raw_query":""},"request_id":"bb625713-8f6f-451c-b085-d12d0adfa2a2","http_info":{"status":400,"http_version":"HTTP/1.1","url":"/v1alpha1/config","ip":"172.19.0.1","method":"GET","content_encoding":null}}}
analytics-api-1  | {"type":"http-log","timestamp":"2022-05-16T09:48:07.582+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"admin"},"error":{"path":"$.args.metadata.query_collections[0]","error":"the key 'definition' was not present","code":"parse-failed"},"request_id":"146b1e57-a78d-4d71-9b5e-158d3de6feb1","response_size":116,"request_mode":"error"},"request_id":"146b1e57-a78d-4d71-9b5e-158d3de6feb1","http_info":{"status":400,"http_version":"HTTP/1.1","url":"/v1/metadata","ip":"172.19.0.1","method":"POST","content_encoding":null}}}
```

It would seem that the CLI doesn't properly send Authorization?

### Can you identify the location in the source code where the problem exists?

No

### If the bug is confirmed, would you be willing to submit a PR?

No

**Comment by darronj** [comment] 2022-05-17 18:38
I was having this same issue, I did find that in my metadata/query_collections.yaml file contained the following:

<img width="962" alt="Screen Shot 2022-05-17 at 1 37 48 PM" src="https://user-images.githubusercontent.com/1216459/168886209-948ca2cd-85b8-4a55-80df-a7092dccf2f2.png">

I added the two lines that were omitted and the error went away.

**Comment by haf** [comment] 2022-05-18 07:30
This is automatically mishandled by the cli, without manual intervention.

**Comment by haf** [comment] 2022-05-24 11:23
Yes that would be great

**Comment by BenoitRanque** [comment] 2022-06-14 01:13
Confirmed this happens on 2.7.0, if you have an allow list but nothing in it.

**Comment by BenoitRanque** [comment] 2022-06-14 01:16
Closing as duplicate of #8503

**Closed by BenoitRanque** 2022-06-14 01:16 UTC
Labels: k/bug, c/cli
