### ISSUE TITLE
Trailing space when adding user role should be trimmed

### ISSUE THREAD

**Issue by jstansbe** [hasura/graphql-engine#4473] opened 2020-04-19 18:04 UTC
Issue:
When adding a role to the permissions table, trailing spaces are permitted.
This can be misleading as `'anonymous'  !==  'anonymous '` but the the Hasura cms doesn't show the space. In my case, I added 'anonymous ' to the permissions table but used 'anonymous' for the HASURA_GRAPHQL_UNAUTHORIZED_ROLE value. This resulted in preventing anonymous access.

Proposed solution:
This was user error on not a bug.
However, it would be beneficial to warn users of the trailing space or simply prevent trailing spaces. This should prevent lost time and frustration for future users that go down the same path.

![image](https://user-images.githubusercontent.com/1250522/79695229-8633cb00-822a-11ea-9fcf-8fec0eb0fbe8.png)

**Comment by GavinRay97** [comment] 2020-04-20 15:25
This is definitely something to look at, second time this issue has been filed:

Duplicate of https://github.com/hasura/graphql-engine/issues/3871

**Comment by rikinsk** [comment] 2020-04-21 13:30
Added the original issue #3871 to the backlog. Closing this as dup.

**Closed by rikinsk** 2020-04-21 13:30 UTC
Labels: c/console, duplicate, k/enhancement
