### ISSUE TITLE
beta failing for where condition on postgres enums

### ISSUE THREAD

**Issue by nayangoswami-liquidnet** [hasura/graphql-engine#4627] opened 2020-04-30 15:25 UTC
v1.2.0-beta(cli-migrations) is ending up throwing constraint error "field xxx not found" when applying where condition on postgres enum type column.

**Comment by rikinsk** [comment] 2020-05-02 09:10
Hi. It's not clear what the exact issue you are facing here. If you could share a small sample schema with the query you are attempting to run it would help us debug this better

**Comment by nayangoswami-liquidnet** [comment] 2020-05-02 10:22
@rikinsk , any postgres table with any one column of postgres ENUM type. Now when we query the table with where clause on ENUM column, we will face the given error.

**Comment by rikinsk** [comment] 2020-05-04 15:08
@nayangoswami-liquidnet Unfortunately I am not able to reproduce this issue on my end. 

I have a table defined as follows with a column `day` which is of a PG enum type and I am able to query it

![Screenshot from 2020-05-04 20-33-15](https://user-images.githubusercontent.com/54616969/80980950-e3dd2f80-8e46-11ea-9277-262326d8f61d.png)
![Screenshot from 2020-05-04 20-34-37](https://user-images.githubusercontent.com/54616969/80980957-e770b680-8e46-11ea-8279-32c1aca90646.png)

It would be great if you could share some more details to reproduce this. Your table schema (or a sample one) and the query you are attempting to run would help.

**Comment by nayangoswami-liquidnet** [comment] 2020-05-04 15:19
@rikinsk , the table you have is correct in terms of what I'm having,
my postgres engine is **PostgreSQL 11.4** and docker I'm using is **hasura/graphql-engine:latest.cli-migrations**.

please close the issue if you cannot reproduce after this.
Thank you for your time.

**Comment by GavinRay97** [comment] 2020-05-04 16:03
Hey @nayangoswami-liquidnet,

We'd really like to get to the bottom of this issue. Could you please reach out to me at gavin@hasura.io to coordinate a call to resolve this for you?

**Comment by rikinsk** [comment] 2020-05-05 07:31
@nayangoswami-liquidnet We have another similar issue #4630 reported. Can you confirm if your enum was defined in a non-public schema as well?

**Comment by nayangoswami-liquidnet** [comment] 2020-05-05 08:24
I confirm that the enum was defined in a non-public schema.

**Comment by rikinsk** [comment] 2020-05-05 08:25
Awesome! Closing this issue as a dup and tracking it at #4630

**Closed by rikinsk** 2020-05-05 08:25 UTC
Labels: support/needs-more-info
