### ISSUE TITLE
Support for namespacing queries based on schema instead of prefixing with '_'

### ISSUE THREAD

**Issue by prashantharaonv** [hasura/graphql-engine#355] opened 2018-09-05 08:32 UTC
Current behavior : 
query {
  schemaName_tableName { id name }
}

Requested Behavior : To have clear distinction between schema name and table name, also to avoid confusions with current implementation where tablename contains "_"

query {
  schemaName {
    tableName { id name }
  }
}
Aligned with @coco98  during call.

**Comment by coco98** [comment] 2018-09-05 08:35
@0x777 @rakeshkky 

Currently this is what we have:
```
query {
  schemaName_tableName { id name }
}
```

@prashantharaonv and Mounesh suggested that we do:
```
query {
  schemaName {
    tableName { id name }
  }
}
```

perhaps we can toggle this behaviour with a CLI flag/env var. I like the structure of the second query more too.

**Comment by manasag** [comment] 2023-12-27 09:47
We are closing this issue, as the new metadata structure in V3 is designed to be highly flexible and declarative, to support the perfect GraphQL schema you would like to achieve. In V3, we provide the control to override auto-generated names and use any value as you would like to define. Please follow the [guide](https://hasura.io/docs/3.0/getting-started/overview/) here for Alpha access to Hasura V3.
Please feel free to reopen if the issue is still relevant for you, or if you have further questions on the V3 metadata.

**Closed by manasag** 2023-12-27 09:47 UTC
Labels: k/enhancement, c/server, p/medium, a/api/graphql
