### ISSUE TITLE
standardise errors and logging on migrate lib

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#165] opened 2018-07-18 12:11 UTC
Errors thrown by migrate library though api and through cmd should follow a standard format, with a probable resolution path (if possible)

**Comment by manasag** [comment] 2023-12-27 08:40
This issue has not attracted significant attention for a long period of time, hence closing this.
Please feel free to reopen if the issue is still relevant for you.

**Closed by manasag** 2023-12-27 08:40 UTC
Labels: k/enhancement, c/cli, p/longterm, c/migrations
