### ISSUE TITLE
Allow metadata apply to retain web hooks and other stateful config if there is no change

### ISSUE THREAD

**Issue by danielcompton** [hasura/graphql-engine#1840] opened 2019-03-22 01:08 UTC
Currently `hasura metadata apply` will remove and replace the metadata inside graphql-engine with the metadata in the `metadata.yaml` file. For most features this is fine as there is no state to keep between resets. However the webhook execution history and retry state is useful information to be able to see over time.

As previously discussed, Hasura doesn't actually delete the old webhook history or retry state when apply. Instead it creates new webhooks with new ids and doesn't show the old webhooks in the UI.

**It would be great if there was a way for webhook configuration to be persisted across apply's if nothing has changed in the webhook configuration.** I can see a few ways this could be done:

* Setting the webhook ID in the metadata.yaml. The next time the metadata was applied, the webhook would be updated to the same configuration and keep the same ID. This would let you see previous webhook executions.
* Checking if all of the webhook configuration values are the same as the ones that exist. If so, leave the webhook configuration untouched, instead of deleting and recreating it.

This would only be possible if Hasura was able to booted up enough to read the existing metadata. Relates to #231 and #1839.

**Comment by coco98** [comment] 2019-03-22 01:09
@tirumaraiselvan 👆

**Comment by mike-thompson-day8** [comment] 2019-03-22 04:51
I would like to frame this feature request as having the ability to "assert" a yaml metadata file.  (I'm using "assert" in the prolog sense)

The assertion process would NOT make any changes if the existing metadata was found to match that being asserted.  But where changes were found, the old would be replaced. In effect, the minimal set of changes would be made to metadata so as to match the new metadata being asserted. (Not a brute force reset!) 

Specifically, anything stateful (like webhook history) would not be changed unless absolutely necessary. 

Just to be clear, this feature would be very useful (essential?) when ANOTHER system (like Django, Rails, etc) is being used to manage the database migrations, and all that's required of Hasura is provide a way to reliably establish metadata (without losing the stateful parts, like webhook history).

**Comment by tirumaraiselvan** [comment] 2019-03-22 07:09
The event_trigger_id is just an implementation detail and should not concern the metadata.yml. Unfortunately, we were joining some internal tables with event_trigger_id instead of event_trigger_name and hence this bug. 

Will send a patch ASAP.

**Comment by mike-thompson-day8** [comment] 2019-03-22 22:54
@tirumaraiselvan are you saying that in the future (after a bug is fixed) a `reset` won't drop web-hook state?

**Comment by tirumaraiselvan** [comment] 2019-03-23 02:24
@mike-thompson-day8 No, Hasura metadata will be completely stateless. Reset would drop everything and recreate everything from scratch.

**Comment by coco98** [comment] 2019-03-23 03:33
Well, actually if reset creates event triggers with the same name it might
be nice to maintain state. Esp. because reset might often be used to
recover from inconsistent state.

Tiru, thoughts?

**Comment by tirumaraiselvan** [comment] 2019-03-23 03:51
@coco98 What kind of state are you thinking? You mean something like the `event_trigger_id` which we just removed?

**Comment by coco98** [comment] 2019-03-23 03:52
Basically if I have events for a trigger I don’t want to miss them because
of a reset.

**Comment by tirumaraiselvan** [comment] 2019-03-23 03:56
Oh, so you mean don't purge. Just assert and apply. Well, there could be benefits to that but it is not really required in this case. @0x777 As per our discussion, events won't be missed because the dependant tables will be locked during a metadata reset, right?

**Comment by coco98** [comment] 2019-03-23 04:00
Yes, that’s what I thought would automatically happen and you wouldn’t miss
events even during a reset. We should add a test case.

I’m guessing this is what @mike-thompson-day8 wanted from the reset
behaviour too?

**Comment by mike-thompson-day8** [comment] 2019-03-23 05:48
I'm not too sure about the technical details on this, so I'm cautious about answering your questions, lest I confuse matters.  

As an alternative, in the interests of increased clarity, I'll just have a go at restating our feature request (bug fix?) ... 

I believe that Hasura users need two options:
   - a metadata reset which clears all (webhook) state. Starts with a completely clean state. As I understand it, this is close to the existing functionality.  

   - a metadata reset (use another name?) which keeps as much (webhook) state it can (although obviously if existing webhooks are not in the new metadata, their state has to be deleted).  We created this issue because, as we understand it, there is no way to get this outcome currently.

**Comment by 0x777** [comment] 2019-03-23 06:37
We have two metadata queries implemented on the server side, `apply_metadata` and `clear_metadata`. These are mapped to `apply` and `reset` on the cli respectively (the cli should have had the same terminology). Also, please do not worry about the internal implementation of these queries, they only surface when there is a bug. Let's speak in terms of expected behaviour. 

### apply_metadata
Applies the given metadata, i.e, the server's metadata becomes what is specified in this query. So, if the metadata that you are applying is the same as what the graphql-engine currently has, you should not see any difference, i.e, performing an `apply_metadata` with the same existing metadata is equivalent to not performing it. 

However there is a bug which disassociated existing events from an event trigger whenever `apply_metadata` query is issued with the same metadata that is present on the server. @tirumaraiselvan is fixing this issue.

### clear_metadata
This pretty much resets the server to its default state however it doesn't purge the state associated with some of the metadata.

### Now, about your requests

> (1) a metadata reset which clears all (webhook) state. The first thing it should do is to completely scrub existing metadata and associated state and only then put in the new metadata. As I understand it, this is close to the existing functionality.

This is `apply_metadata`'s current buggy behaviour but doesn't clear the underlying state of event triggers.

> (2) a metadata reset (use another name?) which keeps as much (webhook) state it can (although obviously if existing webhooks are not in the new metadata, their state has to be deleted). We created this issue because, as we understand it, there is no way to get this outcome currently.

This is `apply_metadata`'s post bug fix behaviour but it won't clear the state of dropped event triggers. 

### implementation ideas
1. I think `apply_metadata` should purge the state of dropped event triggers, i.e, event triggers which don't exist after the apply is successful. So, `apply_metadata` is what you want to get the behaviour as described in (2). 

2. I'm not sure where exactly the behaviour in (1) is needed. It should be trivial to add it though, with a flag like `clear_state_for_triggers` for `apply_metadata`.

3. `clear_metadata` should have a `clear_event_trigger_state` flag.

Thoughts @tirumaraiselvan @coco98

**Comment by tirumaraiselvan** [comment] 2019-03-24 13:40
I feel this issue has bloated more than required because of expected bug fix(s) and expected feature request(s).

Let's refocus back on ONE thing which is to get the behaviour that was expected in the first place i.e 

Quoting @danielcompton 

`
As previously discussed, Hasura doesn't actually delete the old webhook history or retry state when apply. Instead it creates new webhooks with new ids and doesn't show the old webhooks in the UI.
`
This was a bug and has been fixed in #1841 After this is merged you can expect:

1. If you apply metadata, you won't get new webhook IDs for pre-existing webhooks.
2. No events will be dropped during `metadata apply`

For anything else, let's create a new issue.

**Comment by danielcompton** [comment] 2019-03-25 00:17
@tirumaraiselvan thanks, that sounds good to me, and the fix in #1841 seems like it would do what we need.

Can you confirm that any pending webhook retries would also be preserved, along with the event history? I would assume so, as both would be related to the webhook.

**Comment by tirumaraiselvan** [comment] 2019-03-25 01:04
@danielcompton Yes, that's right. All pending events and the rest of the event history would also exist. Infact, after you upgrade with this patch, any pending events that were not delivered because webhook ID had changed will also get automatically retried.

**Closed** 2019-03-25 17:10 UTC
Labels: c/server, k/bug, p/urgent
