### ISSUE TITLE
[v2.0.0-alpha.10] Console error when accessing tables with inheritance

### ISSUE THREAD

**Issue by PedroBern** [hasura/graphql-engine#6941] opened 2021-05-18 00:07 UTC
Im facing the following error when opening a table with inheritance in the console on v2.0.0-cloud.10.

Everything works in the query explorer. The error happens only when clicking on table that has inheritance inside the DATA tab.

I think It's a pure console/web error, because everything works, I can update the permissions/metadata with the CLI, update the columns with migrations and my graphql schema is working as expected.

```
Error
    at n.e (https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.0.0-cloud.10/vendor.js.gz:1:3075238)
    at Wi (https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.0.0-cloud.10/vendor.js.gz:1:11471573)
    at Yi (https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.0.0-cloud.10/vendor.js.gz:1:11471366)
    at Xi (https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.0.0-cloud.10/vendor.js.gz:1:11474805)
    at ds (https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.0.0-cloud.10/vendor.js.gz:1:11497248)
    at fs (https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.0.0-cloud.10/vendor.js.gz:1:11497638)
    at Zs (https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.0.0-cloud.10/vendor.js.gz:1:11504816)
    at Xs (https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.0.0-cloud.10/vendor.js.gz:1:11504184)
    at Ys (https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.0.0-cloud.10/vendor.js.gz:1:11503191)
    at _s (https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/v2.0.0-cloud.10/vendor.js.gz:1:11501991)
```

![hasura-error](https://user-images.githubusercontent.com/39778068/118571181-d34adf00-b753-11eb-836b-de3338a4286f.png)

**Comment by 0x777** [comment] 2021-05-18 05:30
@PedroBern Thanks for reporting this. We will be fixing this shortly. Closing this as a duplicate of https://github.com/hasura/graphql-engine/issues/6926

**Closed by 0x777** 2021-05-18 05:30 UTC
