### ISSUE TITLE
v2.0.0-alpha.2 versioning and local assets issues

### ISSUE THREAD

**Issue by jflambert** [hasura/graphql-engine#6600] opened 2021-02-25 04:11 UTC
I'm pulling the `hasura/graphql-engine:v2.0.0-alpha.2.cli-migrations-v2` docker image.

FIRST ISSUE: the top left version still says v1.4.0-alpha.1. Same in settings/about
![image](https://user-images.githubusercontent.com/11539524/109101777-65af8980-76f5-11eb-83ab-2e2ae41a43f9.png)

![image](https://user-images.githubusercontent.com/11539524/109101903-a5767100-76f5-11eb-8a18-c5d66ab005d1.png)

SECOND ISSUE: the bottom bar says please upgrade to v2.0.0-alpha.2
![image](https://user-images.githubusercontent.com/11539524/109101821-7fe96780-76f5-11eb-9a6e-cdf8f1a7b935.png)

**Comment by scriptonist** [comment] 2021-02-25 10:36
@jflambert Thanks for reporting this. It happened because of a CI mishap, which has been fixed as of now, can you please verify?

**Comment by jflambert** [comment] 2021-02-25 13:13
@scriptonist now it's worse. The console won't load.

```
{"type":"http-log","timestamp":"2021-02-25T13:12:20.530+0000","level":"error","detail":{"operation":{"error":{"path":"$","error":"/srv/console-assets/versioned/vendor.js.gz: openBinaryFile: does not exist (No such file or directory)","code":"not-found"},"request_id":"160ecf62-a0a5-45a0-839a-456b3f7a0ed1","response_size":144,"raw_query":""},"request_id":"160ecf62-a0a5-45a0-839a-456b3f7a0ed1","http_info":{"status":404,"http_version":"HTTP/1.1","url":"/console/assets/versioned/vendor.js.gz","ip":"172.18.0.1","method":"GET","content_encoding":null}}}
```

**Comment by rikinsk** [comment] 2021-02-25 19:05
@jflambert this seems like a regression. this should be fixed in the next alpha release

**Comment by jflambert** [comment] 2021-02-25 19:10
I'll change the issue title

**Closed** 2021-02-26 16:32 UTC
