### ISSUE TITLE
sql query on table with event trigger timeout

### ISSUE THREAD

**Issue by jasine** [hasura/graphql-engine#3747] opened 2020-01-21 08:31 UTC
after upgrading to 1.0, sql query on table whit event trigger get timeout

I found when I use `pg_cancel_backend` cancel the process of function `CREATE OR REPLACE function hdb_views."notify_hasura_area_INSERT"() RETURNS trigger` works 

but after a while it get stuck again

**Comment by tirumaraiselvan** [comment] 2020-01-29 12:14
@jasine This is strange. Is it happening for all tables with event triggers?

Any more info would really help.

**Comment by jasine** [comment] 2020-02-12 06:01
> @jasine This is strange. Is it happening for all tables with event triggers?
> 
> Any more info would really help.

following log printed when timeout @tirumaraiselvan 

```
{"type":"event-trigger","timestamp":"2020-01-21T08:35:26.563+0000","level":"error","detail":{"path":"$","error":"table or event-trigger not found in schema cache","code":"unexpected"}}
WARNING:  unrecognized node type: 360
```

**Comment by jasine** [comment] 2020-02-12 06:19
> @jasine This is strange. Is it happening for all tables with event triggers?
> 
> Any more info would really help.

I found the sql executing when stuck : 

`DROP FUNCTION IF EXISTS hdb_views."notify_hasura_area_INSERT"() CASCADE
`
I have a trigger on table `area`， I tried to execute the sql on client, it do cause the problem

I also tried version 1.1.0-beta but not work

@tirumaraiselvan

**Comment by tirumaraiselvan** [comment] 2020-02-13 04:28
@jasine Are you doing DDLs from outside Hasura console or via migrations?

Can you try a `Reload metadata` from the console (look for the gear icon on the top right) ?

If you are using beta, then you may use the latest `v1.1.0-beta.3` .

**Comment by jasine** [comment] 2020-02-14 05:43
> @jasine Are you doing DDLs from outside Hasura console or via migrations? (Hard to think of a reason why `DROP FUNCTION IF EXISTS` would get stuck)
> 
> What version of postgres are you using?
> 
> Can you try a `Reload metadata` from the console (look for the gear icon on the top right) ?
> 
> If you are using beta, then you may use the latest `v1.1.0-beta.3` .

@tirumaraiselvan i am not doing  DDLs from outside, and my postgres version is 10.4,

I also tried reloading metadata and tried each version from v1.0.0 to v1.1.0-beta.3, but not working

**Comment by tirumaraiselvan** [comment] 2020-03-04 10:07
@jasine Sorry for the delay in getting back to this. I am not really sure what might be causing this behaviour. Do you want to email me at `tiru@hasura.io` so we can get on a screenshare and debug?

**Comment by njaremko** [comment] 2020-06-29 19:18
I'm also getting this on a particularly resource constrained (slow) postgres instance:
```
2020-06-29T19:17:35.528294163Z: [INFO]  {"type":"event-trigger","timestamp":"2020-06-29T19:17:35.412+0000","level":"error","detail":{"path":"$","error":"table or event-trigger not found in schema cache","code":"unexpected"}}
```

**Comment by njaremko** [comment] 2020-06-30 18:32
I tried updating from 1.2.2 -> 1.3.0-beta.3 and it has been working fine for a few hours now...might be related to the event being initially created in 1.3.0-beta.3 previously...

I'll try and find some time later tonight/tomorrow to look into this more.

**Comment by njaremko** [comment] 2020-07-03 15:12
Turns out, a scheduled event was causing a large number of row updates, so the event trigger was getting stuck waiting while other events were being processed. Making the update more specific eliminated the issue, not sure why it logs the above error in that case...

**Comment by tirumaraiselvan** [comment] 2020-12-24 14:50
Closing this for lack of reproduction steps. 

I think general advise is to check Postgres locks that are acquired on a table when it is taking a long time (when it shouldn't).

**Closed by tirumaraiselvan** 2020-12-24 14:50 UTC
Labels: k/question, support/needs-more-info
