### ISSUE TITLE
[1.3.0-beta.1] Remote Schemas  - Intersection of types

### ISSUE THREAD

**Issue by kuzmi4** [hasura/graphql-engine#5080] opened 2020-06-13 07:14 UTC
Steps to reproduce:

1. Auth on gitlab.com
2. Create token with api access
3. Try add remote scheme https://gitlab.com/api/graphql with headers "Authorization: bearer token"

Hasura console will show error: 
```
[
    {
        "definition": {
            "definition": {
                "timeout_seconds": 60,
                "url": "https://gitlab.com/api/graphql",
                "headers": [
                    {
                        "value": "bearer token",
                        "name": "Authorization"
                    }
                ],
                "forward_client_headers": false
            },
            "name": "gitlab",
            "comment": null
        },
        "reason": "types: [ PageInfo ] have mismatch with current graphql schema. HINT: Types must be same.",
        "type": "remote_schema"
    }
]
```

it's happened because both schemes ("hasura" and "gitlab") has same type PageInfo 

Update:
Will it be possible to add a prefix for a remote schema to be able to add any schema?

**Comment by tirumaraiselvan** [comment] 2020-06-13 11:19
This has been reported before and fixed in https://github.com/hasura/graphql-engine/pull/5013

For your request for prefixing remote schemas, an RFC has been published here: https://github.com/hasura/graphql-engine/pull/4821

**Comment by tirumaraiselvan** [comment] 2020-06-16 05:58
Closing as dupe of https://github.com/hasura/graphql-engine/issues/5046

**Closed by tirumaraiselvan** 2020-06-16 05:58 UTC
Labels: c/remote-schemas, c/server
