### ISSUE TITLE
Allow some JSON API operations to fail/ignore their errors

### ISSUE THREAD

**Issue by beepsoft** [hasura/graphql-engine#4029] opened 2020-03-05 09:23 UTC
I configure my Hasura instance via the JSON API. It would be great if there were options to let these operations fail in some cases.

I have a `"type": "bulk"` JSON with many other operations included in it. If any of these operations fails the whole JSON execution fails.

For example, if I try to add the a remote schema using `add_remote_schema` twice, it will result in a `remote schema with name "SOME_SCHEMA" already exists` error. This is not something that really hurts my installation, I'm fine with already having a schema set, so setting again could be ignored. I also tried adding a `remove_remote_schema` before every `add_remote_schema` however, if the schema has not yet been added then `remove_remote_schema` would fail.

I could imagine an extension to the current JSON operations by adding a `ignoreError` array with predefined error types by name, eg.:

```json
{
  "type": "add_remote_schema",
  "args": {
    "name": "REMOTE_SCHEMA",
    "definition": {
      "url_from_env": "REMOTE_SCHEMA_ENV_VAR"
    },
    "ignoreError": [
      "ALREADY_ADDED"
    ]
}
```

Would something like this be possible?

**Comment by tirumaraiselvan** [comment] 2020-03-09 07:43
@beepsoft I am closing this as a duplicate of https://github.com/hasura/graphql-engine/issues/3959

If you think otherwise feel free to comment and reopen this.

**Closed by tirumaraiselvan** 2020-03-09 07:43 UTC
Labels: c/server, support/needs-triage

**Comment by beepsoft** [comment] 2020-03-09 07:44
@tirumaraiselvan Great, thanks, I follow that issue then!
