### ISSUE TITLE
using Computed Field as a column in check for permission 

### ISSUE THREAD

**Issue by archywillhe** [hasura/graphql-engine#6055] opened 2020-10-21 15:19 UTC
Looks like right now only `PGColumn` is supported to be used as a column in check for permission. https://hasura.io/docs/1.0/graphql/core/auth/authorization/permission-rules.html

Will be nice if `Computed Field` is supported too. So say if a user is only allowed to insert at most N rows to a table we can restrict that using an insert check i.e.  by having a `Computed Field` like this to get the count: 

```
CREATE OR REPLACE FUNCTION public.get_app_count(user_row user)
 RETURNS integer
 LANGUAGE plpgsql
 STABLE
AS $function$
declare
   app_count integer;
begin
   select count(*) 
   into app_count
   from app_profile
   where app_profile.user.id = user.id;
   return app_count;
end;
$function$
```

related to - https://github.com/hasura/graphql-engine/issues/4356

**Comment by tirumaraiselvan** [comment] 2020-10-23 08:23
Closing this as a dupe of https://github.com/hasura/graphql-engine/issues/5646

Would be great if you could comment with your use-case over there!

**Closed by tirumaraiselvan** 2020-10-23 08:23 UTC
