### ISSUE TITLE
[v2.0.0-alpha.11] [console] _ceq permission operation is broken

### ISSUE THREAD

**Issue by jbek7** [hasura/graphql-engine#6977] opened 2021-05-25 23:34 UTC
I'm trying simple column comparison with `_exists` operation where it would compare a 

Let's say I'm in `foo_table`'s permission page and have a `foo_view` and the view's `foo_id_from_view` points to `same_foo_id_from_table`.    
```json
 {
  "_exists": {
    "_where": {
      "foo_id_from_view": {
        "_ceq": [
          "same_foo_id_from_table"
        ]
      }
    },
    "_table": {
      "schema": "public",
      "name": "foo_view"
    }
  }
}
```
and throws an incompatible data type error.

```json
"reason": "Inconsistent object: in table \"foo_table\": in permission for role \"reader\": incompatible column types : \"foo_id_from_view\", \"same_foo_id_from_table\"",
```
But both fields' data type are in `int`.

**Comment by jbek7** [comment] 2021-05-26 18:15
I see it was implemented in this PR #2606? Any suggestions for this issue, @rikinsk-zz ?

**Comment by tirumaraiselvan** [comment] 2021-05-27 08:17
@jbek7 Can you give the schema of `foo_view` ? Just to be clear, both `foo_id_from_view`  and `same_foo_id_from_table` are columns in the `foo_view` view? 

Also, perhaps related, you can also check for column comparisons across tables in v2.0. See release post here: https://hasura.io/blog/announcing-hasura-2-0-0-alpha-9

**Comment by jbek7** [comment] 2021-05-27 09:29
Hi @tirumaraiselvan , I've created a docker-compose with an SQL schema: https://github.com/jbek7/hasura-ceq-issue-demo. 

![image](https://user-images.githubusercontent.com/2989603/119801428-24e32e80-bef7-11eb-8a1b-dbad52a1bbc7.png)

**Comment by nicuveo** [comment] 2021-05-27 12:28
Hi @jbek7; I think something is off with your demo: the error you get there is `column "post_id" does not exist`, which suggests a configuration issue, while the error you originally got was `incompatible column types`. I'll see if I can find a way to fix the demo, and I'll investigate the bug.

**Comment by nicuveo** [comment] 2021-05-27 13:29
I tried the following, which I assume was what you intended to do in the demo, but I haven't been able to replicate your original bug: the following seems to be working?
![working_permissions](https://user-images.githubusercontent.com/1618949/119834441-de420400-bef7-11eb-92dc-b5b643dca9d3.png)

**Comment by nicuveo** [comment] 2021-05-27 16:58
In the meantime, I have merged a PR that improves the original error message; instead of saying `incompatible column types: "a" and "b"`, that error message will now read `incompatible column types: column "a" has type "foo", but column "b" has type "bar"`. This patch will be part of the next release.

**Comment by jbek7** [comment] 2021-05-27 17:01
@nicuveo I was trying to replicate my original database/hasura in my demo repo. But I got different error with the demo for some reason. And what's the difference of having `$` 
```json
"v_post_id": {
        "_ceq": [
          "post_id"
        ]
      }
```
vs 

```json
"v_post_id": {
        "_ceq": [
          "$", "post_id"
        ]
      }
```

**Comment by nicuveo** [comment] 2021-05-27 19:09
As per [our documentation](https://hasura.io/docs/latest/graphql/core/api-reference/syntax-defs.html#operator), "$" makes the column reference absolute. For instance, if you're defining the select permissions on a table "comments", then:

### Without dollar: relative
```json
{
  "_exists": {
    "_table": {
      "schema": "public",
      "name": "post_comment_permissions"
    },
    "_where": {
      "v_post_id": {
        "_ceq": [
          "post_id"
        ]
      }
    }
  }
}
```

In this context, in `_ceq`, "post_id" is interpreted as relative to the current table, as defined in the "exists" block, and therefore looks for column **"post_comment_permissions.post_id"**.

### With dollar: absolute
```json
{
  "_exists": {
    "_table": {
      "schema": "public",
      "name": "post_comment_permissions"
    },
    "_where": {
      "v_post_id": {
        "_ceq": [
          "$",
          "post_id"
        ]
      }
    }
  }
}
```

In this context, in `_ceq`, "post_id" is interpreted as absolute, regardless of the current table, and therefore looks for column "post_id" in table in which the permission is defined: **"comments.post_id"**.

**Comment by 0x777** [comment] 2021-06-01 13:47
@jbek7 I'm closing this issue but please feel free to reopen this in case the issue isn't resolved.

**Closed by 0x777** 2021-06-01 13:47 UTC
