### ISSUE TITLE
cloning permissions screwed up my UI

### ISSUE THREAD

**Issue by tehpsalmist** [hasura/graphql-engine#2354] opened 2019-06-09 02:20 UTC
<img width="852" alt="Screen Shot 2019-06-08 at 22 16 55" src="https://user-images.githubusercontent.com/26337310/59154212-5f6a0d00-8a3b-11e9-85b9-12a0ae5a4a41.png">
This is the result of trying to clone permissions across 6 tables and all 4 queries for each at one time. If I refresh, it's still like this, with those blank permissions, and I still can't clone anything. Nothing worked during cloning, either, just this UI wackiness. I was cloning the user permissions, and I might have tried to clone before hitting the initial save permissions in the upper portion of the edit permissions UI first. That may have been the cause, but at the very least, this is still a bug, because it kind of ruined my project (hopefully fixable??).

**Comment by evert-smit** [comment] 2019-06-09 12:53
Have you tried reloading the metadata?

**Comment by tehpsalmist** [comment] 2019-06-09 18:51
Reloaded the metadata... no dice.

**Comment by rikinsk** [comment] 2019-06-10 08:37
@tehpsalmist Could you share more information on what the rules were, which role were you applying to, etc. Exact reproduction instructions (with a dummy schema if you wish) would be of great help.

**Comment by tehpsalmist** [comment] 2019-06-20 14:37
yeah, it was full permissions (all fields, select/insert/update/delete, no checks) being applied to a "user" role. I think the issue came about because I did not save the initial rules, but instead configured them and went straight into cloning without hitting save on the initial rule first (select, no checks, I forget which table I started with). Is that enough information? I had also configured (successfully) auth0 jwt mode just prior to starting into that.

**Comment by rikinsk** [comment] 2019-07-23 13:07
@tehpsalmist Despite multiple attempts I couldn't reproduce this scenario. The issue is definitely related to the metadata getting corrupted but I cannot figure out how it could happen.

> I think the issue came about because I did not save the initial rules, but instead configured them and went straight into cloning without hitting save on the initial rule first

In this scenario the permissions get applied to the current table as well, so it shouldn't cause this.

Also realised we hadn't provided you an escape hatch for this. You can always delete messed up metadata by dropping the offending rows in the `hdb_catalog.hdb_permission` table.

With regard to this particular issue, it would have been nice if you could reproduce this and share the steps involved. If it's not repeatable, I guess we just close this issue as no other user seems to have faced this. If you still have this instance of hasura running, a snapshot of the metadata would also be of value. You can export the metadata by following [this](https://docs.hasura.io/1.0/graphql/manual/migrations/manage-metadata.html#exporting-hasura-metadata)

**Comment by rikinsk** [comment] 2019-08-23 07:49
@tehpsalmist Closing this for now. Please feel free to reopen if you have any more details.

**Closed by rikinsk** 2019-08-23 07:49 UTC
Labels: c/console, needs-more-info
