### ISSUE TITLE
[v2.0.1 bug] remote join failing when including remote join key in query

### ISSUE THREAD

**Issue by jacdx** [hasura/graphql-engine#7125] opened 2021-06-26 03:06 UTC
Just upgraded to v2.0.1 from v2.0.0-b1 and now I have a remote join query that is failing, when including the field that I use to going the remote schema. This previously worked back to 1.3.4-b3

My table is 2 columns: an int pkey (`id`) and a uuid (`sanityId`) that is used as my remote join key. `content` is the remote data.

`
post {
  id
  sanityId
  content {
      title
  }
}
`

Result: Query returns results, but `content` is `null` on every record.

Here's where it gets weirder, if I remove `sanityId` from the query, it works correctly, pulling the remote data. Scanning through the release notes, I thought maybe this could be related to the changes in the handling of `null` in queries. However, there are no `null` values in the table. Also, it worked on the 2.0 betas.

**Comment by 0x777** [comment] 2021-07-08 14:03
@jacdx I couldn't reproduce this without the join columns being aliased as described in #7180. I'm closing this in favour of #7180. Please feel free to reopen this issue if this bug can be reproduced even without the aliasing.

**Closed by 0x777** 2021-07-08 14:03 UTC
