### ISSUE TITLE
Support for arrays in custom JWT claims (subscriptions)

### ISSUE THREAD

**Issue by hellsan631** [hasura/graphql-engine#3171] opened 2019-10-17 15:32 UTC
It looks like this feature was implemented for queries (#1902), but when using *subscriptions* and custom arrays in the jwt claims, i've encountered these errors in the web socket payload when trying to connect:

```js
{
	payload: "x-hasura-* claims: expected Text, encountered Array"
	type: "connection_error"
}
{
	payload: {
		extensions: {path: "$", code: "start-failed"},
		message: "cannot start as connection_init failed with : x-hasura-* claims: expected Text, encountered Array",
		type: "error",
	}
}
```

Using version `1.0.0-beta.6` My JWT looks like this:
```json
{
	"x-hasura-default-role":"user",
	"x-hasura-allowed-org-ids":["org1"],
	"x-hasura-allowed-roles":["user"],
	"x-hasura-user-id":"auth0|0123456789"
}
```

Removal of the field `x-hasura-allowed-org-ids` results in a successful connection.

Using the following link as my websocket connection:
```js
const wsLink = new WebSocketLink({
  uri: `wss://${GRAPH_URL}`,
  options: {
    lazy: true,
    reconnect: true,
    connectionParams: () => {
	  return {
		headers: {
		  Authorization: `Bearer asd123token`,
		}
	  }
	},
  },
})
```

**Comment by emdagon** [comment] 2019-10-24 14:15
Hi @hellsan631 ! I just had the same problem last week, I solved it applying the postgres syntax on the header value, something like follows:

```javascript
const organizations = user.organizations.map(({ organization_id }) => organization_id)
// ...
return jwt.sign(
  {
    [JWT_NAMESPACE]: {
      'X-Hasura-Allowed-Roles': ["user", "anonymous"],
      'X-Hasura-Default-Role': "user",
      'X-Hasura-User-Id': user.id,
      'X-Hasura-Allowed-Org-Ids': `{"${organizations.join('", "')}"}`,
      // ...,
    }
  },
  // ...
```
As you can see, `X-Hasura-Allowed-Org-Ids` is actually a string shaped like this `{"id1", "id2", ...}`, if you use integers as id, you can (should?) skip the quotes (`{1,2,3}`), I use UUIDs so I had you wrap my ids.

I'm using subscriptions BTW!

Good luck!

**Comment by ecthiender** [comment] 2019-10-25 12:07
@hellsan631 #1902 was closed by mistake. We don't have support for arrays in JWT claims yet. I have added a comment there #1902 (comment)

**Comment by hellsan631** [comment] 2019-10-25 14:52
oh, it was mentioned briefly in the documentation: `https://docs.hasura.io/1.0/graphql/manual/auth/authorization/roles-variables.html`
> To convey this information, a session variable, say X-Hasura-Allowed-Organisations can be used by the configured authentication to relay this information.
```json
{
	"organization_id": {
		"_in": "X-Hasura-Allowed-Organisations"
	}
}
```

Thanks for pointing this out.

**Comment by tirumaraiselvan** [comment] 2020-12-24 14:30
Closing as dupe of: https://github.com/hasura/graphql-engine/issues/1902

**Closed by tirumaraiselvan** 2020-12-24 14:30 UTC
Labels: c/server, k/enhancement
