### ISSUE TITLE
FatalError: syntax error at or near "FUNCTION" 

### ISSUE THREAD

**Issue by imdwit** [hasura/graphql-engine#3821] opened 2020-02-02 22:44 UTC
I'm receiving this error when attempting to run a migration from my localhost instance to an instance running on digital ocean.

```
10380  hasura init --directory hasura-dev --endpoint http://localhost:8080 --admin-secret secret_key
10383  cd hasura-dev
10389  hasura migrate create "init" --from-server
10394  hasura migrate apply --version "1580682330078" --skip-execution
10395  hasura migrate apply --endpoint https://instanceondigitalocean.com --admin-secret  "the_real_secret"
```

I saw another issue that recommended changing the language from `sql` to `plpgsql` but I still get the error.

The same migration ran fine when the endpoint was heroku. I plan on using digital ocean for production and heroku as a staging server.

heres the generated migration

```
CREATE FUNCTION public.dup(integer, OUT f1 integer, OUT f2 text) RETURNS record
    LANGUAGE sql
    AS $_$ SELECT $1, CAST($1 AS text) || ' is text' $_$;
CREATE FUNCTION public.trigger_on_sign_up() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE user_id uuid;
BEGIN
  user_id := New.id;
  INSERT INTO categories (name, "order", owner) VALUES
  ('Engine', 0, user_id),
  ('Exterior', 1, user_id),
  ('Interior', 2, user_id),
  ('Chassis', 3, user_id),
  ('Wheels', 4, user_id),
  ('Accessories', 5, user_id),
  ('Misc', 6, user_id);
RETURN NEW;
END;
$$;
CREATE TABLE public.categories (
    name text NOT NULL,
    id uuid DEFAULT public.gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    "order" integer NOT NULL,
    owner uuid NOT NULL,
    soft_delete boolean DEFAULT false NOT NULL
);
CREATE TABLE public.links (
    "urlString" text NOT NULL,
    protocol text NOT NULL,
    host text NOT NULL,
    path text NOT NULL,
    query text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    fragment text,
    title text NOT NULL,
    active boolean DEFAULT true NOT NULL,
    description text,
    category_id uuid NOT NULL,
    soft_delete boolean DEFAULT false NOT NULL,
    id uuid DEFAULT public.gen_random_uuid() NOT NULL
);
CREATE TABLE public.link_clicks (
    link uuid NOT NULL,
    id uuid DEFAULT public.gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.role (
    name text NOT NULL,
    id uuid DEFAULT public.gen_random_uuid() NOT NULL
);
CREATE TABLE public.user_role (
    user_id uuid NOT NULL,
    role_id uuid NOT NULL,
    id uuid DEFAULT public.gen_random_uuid() NOT NULL
);
CREATE TABLE public.users (
    id uuid DEFAULT public.gen_random_uuid() NOT NULL,
    username text NOT NULL,
    created timestamp with time zone DEFAULT now() NOT NULL,
    instagram_id text,
    profile jsonb,
    views integer DEFAULT 0 NOT NULL
);
ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.link_clicks
    ADD CONSTRAINT link_clicks_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.links
    ADD CONSTRAINT links_id_key UNIQUE (id);
ALTER TABLE ONLY public.links
    ADD CONSTRAINT links_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_id_key UNIQUE (id);
ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_name_key UNIQUE (name);
ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT user_role_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_instagram_id_key UNIQUE (instagram_id);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey1 PRIMARY KEY (id);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key1 UNIQUE (username);
CREATE TRIGGER trigger_categories_creation AFTER INSERT ON public.users FOR EACH ROW EXECUTE FUNCTION public.trigger_on_sign_up();
ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_owner_fkey FOREIGN KEY (owner) REFERENCES public.users(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE ONLY public.link_clicks
    ADD CONSTRAINT link_clicks_link_fkey FOREIGN KEY (link) REFERENCES public.links(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE ONLY public.links
    ADD CONSTRAINT links_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT user_role_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.role(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT user_role_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
```

**Comment by marionschleifer** [comment] 2020-02-03 10:13
@imdwit could you please share the complete logs i.e. the server logs and the ones from the CLI? This will help us reproducing the issue.

**Comment by imdwit** [comment] 2020-02-03 22:20
```
{
   "type":"http-log",
   "timestamp":"2020-02-03T22:16:37.379+0000",
   "level":"error",
   "detail":{
      "operation":{
         "user_vars":{
            "x-hasura-role":"admin"
         },
         "error":{
            "internal":{
               "statement":"CREATE FUNCTION public.dup(integer, OUT f1 integer, OUT f2 text) RETURNS record\n    LANGUAGE plpgsql\n    AS $_$ SELECT $1, CAST($1 AS text) || ' is text' $_$;\nCREATE FUNCTION public.trigger_on_sign_up() RETURNS trigger\n    LANGUAGE plpgsql\n    AS $$\nDECLARE user_id uuid;\nBEGIN\n  user_id := New.id;\n  INSERT INTO categories (name, \"order\", owner) VALUES\n  ('Engine', 0, user_id),\n  ('Exterior', 1, user_id),\n  ('Interior', 2, user_id),\n  ('Chassis', 3, user_id),\n  ('Wheels', 4, user_id),\n  ('Accessories', 5, user_id),\n  ('Misc', 6, user_id);\nRETURN NEW;\nEND;\n$$;\nCREATE TABLE public.categories (\n    name text NOT NULL,\n    id uuid DEFAULT public.gen_random_uuid() NOT NULL,\n    created_at timestamp with time zone DEFAULT now() NOT NULL,\n    \"order\" integer NOT NULL,\n    owner uuid NOT NULL,\n    soft_delete boolean DEFAULT false NOT NULL\n);\nCREATE TABLE public.links (\n    \"urlString\" text NOT NULL,\n    protocol text NOT NULL,\n    host text NOT NULL,\n    path text NOT NULL,\n    query text,\n    created_at timestamp with time zone DEFAULT now() NOT NULL,\n    fragment text,\n    title text NOT NULL,\n    active boolean DEFAULT true NOT NULL,\n    description text,\n    category_id uuid NOT NULL,\n    soft_delete boolean DEFAULT false NOT NULL,\n    id uuid DEFAULT public.gen_random_uuid() NOT NULL\n);\nCREATE TABLE public.link_clicks (\n    link uuid NOT NULL,\n    id uuid DEFAULT public.gen_random_uuid() NOT NULL,\n    created_at timestamp with time zone DEFAULT now() NOT NULL\n);\nCREATE TABLE public.role (\n    name text NOT NULL,\n    id uuid DEFAULT public.gen_random_uuid() NOT NULL\n);\nCREATE TABLE public.user_role (\n    user_id uuid NOT NULL,\n    role_id uuid NOT NULL,\n    id uuid DEFAULT public.gen_random_uuid() NOT NULL\n);\nCREATE TABLE public.users (\n    id uuid DEFAULT public.gen_random_uuid() NOT NULL,\n    username text NOT NULL,\n    created timestamp with time zone DEFAULT now() NOT NULL,\n    instagram_id text,\n    profile jsonb,\n    views integer DEFAULT 0 NOT NULL\n);\nALTER TABLE ONLY public.categories\n    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);\nALTER TABLE ONLY public.link_clicks\n    ADD CONSTRAINT link_clicks_pkey PRIMARY KEY (id);\nALTER TABLE ONLY public.links\n    ADD CONSTRAINT links_id_key UNIQUE (id);\nALTER TABLE ONLY public.links\n    ADD CONSTRAINT links_pkey PRIMARY KEY (id);\nALTER TABLE ONLY public.role\n    ADD CONSTRAINT role_id_key UNIQUE (id);\nALTER TABLE ONLY public.role\n    ADD CONSTRAINT role_name_key UNIQUE (name);\nALTER TABLE ONLY public.role\n    ADD CONSTRAINT role_pkey PRIMARY KEY (id);\nALTER TABLE ONLY public.user_role\n    ADD CONSTRAINT user_role_pkey PRIMARY KEY (id);\nALTER TABLE ONLY public.users\n    ADD CONSTRAINT users_instagram_id_key UNIQUE (instagram_id);\nALTER TABLE ONLY public.users\n    ADD CONSTRAINT users_pkey1 PRIMARY KEY (id);\nALTER TABLE ONLY public.users\n    ADD CONSTRAINT users_username_key1 UNIQUE (username);\nCREATE TRIGGER trigger_categories_creation AFTER INSERT ON public.users FOR EACH ROW EXECUTE FUNCTION public.trigger_on_sign_up();\nALTER TABLE ONLY public.categories\n    ADD CONSTRAINT categories_owner_fkey FOREIGN KEY (owner) REFERENCES public.users(id) ON UPDATE RESTRICT ON DELETE RESTRICT;\nALTER TABLE ONLY public.link_clicks\n    ADD CONSTRAINT link_clicks_link_fkey FOREIGN KEY (link) REFERENCES public.links(id) ON UPDATE RESTRICT ON DELETE RESTRICT;\nALTER TABLE ONLY public.links\n    ADD CONSTRAINT links_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id) ON UPDATE RESTRICT ON DELETE RESTRICT;\nALTER TABLE ONLY public.user_role\n    ADD CONSTRAINT user_role_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.role(id) ON UPDATE RESTRICT ON DELETE RESTRICT;\nALTER TABLE ONLY public.user_role\n    ADD CONSTRAINT user_role_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE RESTRICT ON DELETE RESTRICT;\n",
               "prepared":false,
               "error":{
                  "exec_status":"FatalError",
                  "hint":null,
                  "message":"syntax error at or near \"FUNCTION\"",
                  "status_code":"42601",
                  "description":null
               },
               "arguments":[

               ]
            },
            "path":"$.args[0].args",
            "error":"query execution failed",
            "code":"postgres-error"
         },
         "request_id":"19516a48-839c-49af-b20c-c215bfc2a187",
         "response_size":4235,
         "query":{
            "args":[
               {
                  "args":{
                     "cascade":false,
                     "check_metadata_consistency":null,
                     "sql":"CREATE FUNCTION public.dup(integer, OUT f1 integer, OUT f2 text) RETURNS record\n    LANGUAGE plpgsql\n    AS $_$ SELECT $1, CAST($1 AS text) || ' is text' $_$;\nCREATE FUNCTION public.trigger_on_sign_up() RETURNS trigger\n    LANGUAGE plpgsql\n    AS $$\nDECLARE user_id uuid;\nBEGIN\n  user_id := New.id;\n  INSERT INTO categories (name, \"order\", owner) VALUES\n  ('Engine', 0, user_id),\n  ('Exterior', 1, user_id),\n  ('Interior', 2, user_id),\n  ('Chassis', 3, user_id),\n  ('Wheels', 4, user_id),\n  ('Accessories', 5, user_id),\n  ('Misc', 6, user_id);\nRETURN NEW;\nEND;\n$$;\nCREATE TABLE public.categories (\n    name text NOT NULL,\n    id uuid DEFAULT public.gen_random_uuid() NOT NULL,\n    created_at timestamp with time zone DEFAULT now() NOT NULL,\n    \"order\" integer NOT NULL,\n    owner uuid NOT NULL,\n    soft_delete boolean DEFAULT false NOT NULL\n);\nCREATE TABLE public.links (\n    \"urlString\" text NOT NULL,\n    protocol text NOT NULL,\n    host text NOT NULL,\n    path text NOT NULL,\n    query text,\n    created_at timestamp with time zone DEFAULT now() NOT NULL,\n    fragment text,\n    title text NOT NULL,\n    active boolean DEFAULT true NOT NULL,\n    description text,\n    category_id uuid NOT NULL,\n    soft_delete boolean DEFAULT false NOT NULL,\n    id uuid DEFAULT public.gen_random_uuid() NOT NULL\n);\nCREATE TABLE public.link_clicks (\n    link uuid NOT NULL,\n    id uuid DEFAULT public.gen_random_uuid() NOT NULL,\n    created_at timestamp with time zone DEFAULT now() NOT NULL\n);\nCREATE TABLE public.role (\n    name text NOT NULL,\n    id uuid DEFAULT public.gen_random_uuid() NOT NULL\n);\nCREATE TABLE public.user_role (\n    user_id uuid NOT NULL,\n    role_id uuid NOT NULL,\n    id uuid DEFAULT public.gen_random_uuid() NOT NULL\n);\nCREATE TABLE public.users (\n    id uuid DEFAULT public.gen_random_uuid() NOT NULL,\n    username text NOT NULL,\n    created timestamp with time zone DEFAULT now() NOT NULL,\n    instagram_id text,\n    profile jsonb,\n    views integer DEFAULT 0 NOT NULL\n);\nALTER TABLE ONLY public.categories\n    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);\nALTER TABLE ONLY public.link_clicks\n    ADD CONSTRAINT link_clicks_pkey PRIMARY KEY (id);\nALTER TABLE ONLY public.links\n    ADD CONSTRAINT links_id_key UNIQUE (id);\nALTER TABLE ONLY public.links\n    ADD CONSTRAINT links_pkey PRIMARY KEY (id);\nALTER TABLE ONLY public.role\n    ADD CONSTRAINT role_id_key UNIQUE (id);\nALTER TABLE ONLY public.role\n    ADD CONSTRAINT role_name_key UNIQUE (name);\nALTER TABLE ONLY public.role\n    ADD CONSTRAINT role_pkey PRIMARY KEY (id);\nALTER TABLE ONLY public.user_role\n    ADD CONSTRAINT user_role_pkey PRIMARY KEY (id);\nALTER TABLE ONLY public.users\n    ADD CONSTRAINT users_instagram_id_key UNIQUE (instagram_id);\nALTER TABLE ONLY public.users\n    ADD CONSTRAINT users_pkey1 PRIMARY KEY (id);\nALTER TABLE ONLY public.users\n    ADD CONSTRAINT users_username_key1 UNIQUE (username);\nCREATE TRIGGER trigger_categories_creation AFTER INSERT ON public.users FOR EACH ROW EXECUTE FUNCTION public.trigger_on_sign_up();\nALTER TABLE ONLY public.categories\n    ADD CONSTRAINT categories_owner_fkey FOREIGN KEY (owner) REFERENCES public.users(id) ON UPDATE RESTRICT ON DELETE RESTRICT;\nALTER TABLE ONLY public.link_clicks\n    ADD CONSTRAINT link_clicks_link_fkey FOREIGN KEY (link) REFERENCES public.links(id) ON UPDATE RESTRICT ON DELETE RESTRICT;\nALTER TABLE ONLY public.links\n    ADD CONSTRAINT links_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id) ON UPDATE RESTRICT ON DELETE RESTRICT;\nALTER TABLE ONLY public.user_role\n    ADD CONSTRAINT user_role_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.role(id) ON UPDATE RESTRICT ON DELETE RESTRICT;\nALTER TABLE ONLY public.user_role\n    ADD CONSTRAINT user_role_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE RESTRICT ON DELETE RESTRICT;\n",
                     "read_only":false
                  },
                  "version":1,
                  "type":"run_sql"
               },
               {
                  "args":{
                     "cascade":false,
                     "check_metadata_consistency":null,
                     "sql":"INSERT INTO hdb_catalog.schema_migrations (version, dirty) VALUES (1580682330078, false)",
                     "read_only":false
                  },
                  "version":1,
                  "type":"run_sql"
               },
               {
                  "args":{
                     "remote_schemas":[

                     ],
                     "version":2,
                     "tables":[
                        {
                           "select_permissions":[
                              {
                                 "role":"driver",
                                 "comment":null,
                                 "permission":{
                                    "allow_aggregations":false,
                                    "computed_fields":[

                                    ],
                                    "columns":[
                                       "soft_delete",
                                       "order",
                                       "name",
                                       "created_at",
                                       "id",
                                       "owner"
                                    ],
                                    "filter":{
                                       "owner":{
                                          "_eq":"X-Hasura-User-Id"
                                       }
                                    }
                                 }
                              },
                              {
                                 "role":"public",
                                 "comment":null,
                                 "permission":{
                                    "allow_aggregations":false,
                                    "computed_fields":[

                                    ],
                                    "columns":[
                                       "name",
                                       "id",
                                       "created_at",
                                       "order",
                                       "owner",
                                       "soft_delete"
                                    ],
                                    "filter":{

                                    }
                                 }
                              }
                           ],
                           "object_relationships":[
                              {
                                 "using":{
                                    "foreign_key_constraint_on":"owner"
                                 },
                                 "name":"user",
                                 "comment":null
                              }
                           ],
                           "is_enum":false,
                           "computed_fields":[

                           ],
                           "event_triggers":[

                           ],
                           "insert_permissions":[
                              {
                                 "role":"driver",
                                 "comment":null,
                                 "permission":{
                                    "set":{

                                    },
                                    "check":{
                                       "owner":{
                                          "_eq":"X-Hasura-User-Id"
                                       }
                                    },
                                    "columns":[
                                       "name",
                                       "order",
                                       "owner"
                                    ]
                                 }
                              }
                           ],
                           "configuration":{
                              "custom_root_fields":{
                                 "insert":null,
                                 "select_aggregate":null,
                                 "select_by_pk":null,
                                 "select":null,
                                 "delete":null,
                                 "update":null
                              },
                              "custom_column_names":{

                              }
                           },
                           "table":"categories",
                           "update_permissions":[
                              {
                                 "role":"driver",
                                 "comment":null,
                                 "permission":{
                                    "set":{

                                    },
                                    "columns":[
                                       "name",
                                       "order",
                                       "soft_delete"
                                    ],
                                    "filter":{
                                       "owner":{
                                          "_eq":"X-Hasura-User-Id"
                                       }
                                    }
                                 }
                              }
                           ],
                           "delete_permissions":[

                           ],
                           "array_relationships":[
                              {
                                 "using":{
                                    "foreign_key_constraint_on":{
                                       "column":"category_id",
                                       "table":"links"
                                    }
                                 },
                                 "name":"links",
                                 "comment":null
                              }
                           ]
                        },
                        {
                           "select_permissions":[
                              {
                                 "role":"driver",
                                 "comment":null,
                                 "permission":{
                                    "allow_aggregations":false,
                                    "computed_fields":[

                                    ],
                                    "columns":[
                                       "created_at",
                                       "id",
                                       "link"
                                    ],
                                    "filter":{
                                       "linkByLink":{
                                          "category":{
                                             "owner":{
                                                "_eq":"X-Hasura-User-Id"
                                             }
                                          }
                                       }
                                    }
                                 }
                              }
                           ],
                           "object_relationships":[
                              {
                                 "using":{
                                    "foreign_key_constraint_on":"link"
                                 },
                                 "name":"linkByLink",
                                 "comment":null
                              }
                           ],
                           "is_enum":false,
                           "computed_fields":[

                           ],
                           "event_triggers":[

                           ],
                           "insert_permissions":[
                              {
                                 "role":"public",
                                 "comment":null,
                                 "permission":{
                                    "set":{

                                    },
                                    "check":{

                                    },
                                    "columns":[
                                       "link"
                                    ]
                                 }
                              }
                           ],
                           "configuration":{
                              "custom_root_fields":{
                                 "insert":null,
                                 "select_aggregate":null,
                                 "select_by_pk":null,
                                 "select":null,
                                 "delete":null,
                                 "update":null
                              },
                              "custom_column_names":{

                              }
                           },
                           "table":"link_clicks",
                           "update_permissions":[

                           ],
                           "delete_permissions":[

                           ],
                           "array_relationships":[

                           ]
                        },
                        {
                           "select_permissions":[
                              {
                                 "role":"driver",
                                 "comment":null,
                                 "permission":{
                                    "allow_aggregations":false,
                                    "computed_fields":[

                                    ],
                                    "columns":[
                                       "active",
                                       "soft_delete",
                                       "description",
                                       "fragment",
                                       "host",
                                       "path",
                                       "protocol",
                                       "query",
                                       "title",
                                       "urlString",
                                       "created_at",
                                       "category_id",
                                       "id"
                                    ],
                                    "filter":{
                                       "category":{
                                          "owner":{
                                             "_eq":"X-Hasura-User-Id"
                                          }
                                       }
                                    }
                                 }
                              },
                              {
                                 "role":"public",
                                 "comment":null,
                                 "permission":{
                                    "allow_aggregations":false,
                                    "computed_fields":[

                                    ],
                                    "columns":[
                                       "active",
                                       "category_id",
                                       "description",
                                       "id",
                                       "soft_delete",
                                       "title",
                                       "urlString"
                                    ],
                                    "filter":{

                                    }
                                 }
                              }
                           ],
                           "object_relationships":[
                              {
                                 "using":{
                                    "foreign_key_constraint_on":"category_id"
                                 },
                                 "name":"category",
                                 "comment":null
                              }
                           ],
                           "is_enum":false,
                           "computed_fields":[

                           ],
                           "event_triggers":[

                           ],
                           "insert_permissions":[
                              {
                                 "role":"driver",
                                 "comment":null,
                                 "permission":{
                                    "set":{

                                    },
                                    "check":{
                                       "category":{
                                          "owner":{
                                             "_eq":"X-Hasura-User-Id"
                                          }
                                       }
                                    },
                                    "columns":[
                                       "active",
                                       "category_id",
                                       "description",
                                       "fragment",
                                       "host",
                                       "path",
                                       "protocol",
                                       "query",
                                       "soft_delete",
                                       "title",
                                       "urlString"
                                    ]
                                 }
                              }
                           ],
                           "configuration":{
                              "custom_root_fields":{
                                 "insert":null,
                                 "select_aggregate":null,
                                 "select_by_pk":null,
                                 "select":null,
                                 "delete":null,
                                 "update":null
                              },
                              "custom_column_names":{

                              }
                           },
                           "table":"links",
                           "update_permissions":[
                              {
                                 "role":"driver",
                                 "comment":null,
                                 "permission":{
                                    "set":{

                                    },
                                    "columns":[
                                       "active",
                                       "soft_delete"
                                    ],
                                    "filter":{
                                       "category":{
                                          "owner":{
                                             "_eq":"X-Hasura-User-Id"
                                          }
                                       }
                                    }
                                 }
                              }
                           ],
                           "delete_permissions":[

                           ],
                           "array_relationships":[
                              {
                                 "using":{
                                    "foreign_key_constraint_on":{
                                       "column":"link",
                                       "table":"link_clicks"
                                    }
                                 },
                                 "name":"link_clicks",
                                 "comment":null
                              }
                           ]
                        },
                        {
                           "select_permissions":[

                           ],
                           "object_relationships":[

                           ],
                           "is_enum":false,
                           "computed_fields":[

                           ],
                           "event_triggers":[

                           ],
                           "insert_permissions":[

                           ],
                           "configuration":{
                              "custom_root_fields":{
                                 "insert":null,
                                 "select_aggregate":null,
                                 "select_by_pk":null,
                                 "select":null,
                                 "delete":null,
                                 "update":null
                              },
                              "custom_column_names":{

                              }
                           },
                           "table":"role",
                           "update_permissions":[

                           ],
                           "delete_permissions":[

                           ],
                           "array_relationships":[
                              {
                                 "using":{
                                    "foreign_key_constraint_on":{
                                       "column":"role_id",
                                       "table":"user_role"
                                    }
                                 },
                                 "name":"roles",
                                 "comment":null
                              }
                           ]
                        },
                        {
                           "select_permissions":[

                           ],
                           "object_relationships":[
                              {
                                 "using":{
                                    "foreign_key_constraint_on":"role_id"
                                 },
                                 "name":"role",
                                 "comment":null
                              },
                              {
                                 "using":{
                                    "foreign_key_constraint_on":"user_id"
                                 },
                                 "name":"user",
                                 "comment":null
                              }
                           ],
                           "is_enum":false,
                           "computed_fields":[

                           ],
                           "event_triggers":[

                           ],
                           "insert_permissions":[

                           ],
                           "configuration":{
                              "custom_root_fields":{
                                 "insert":null,
                                 "select_aggregate":null,
                                 "select_by_pk":null,
                                 "select":null,
                                 "delete":null,
                                 "update":null
                              },
                              "custom_column_names":{

                              }
                           },
                           "table":"user_role",
                           "update_permissions":[

                           ],
                           "delete_permissions":[

                           ],
                           "array_relationships":[

                           ]
                        },
                        {
                           "select_permissions":[
                              {
                                 "role":"driver",
                                 "comment":null,
                                 "permission":{
                                    "allow_aggregations":false,
                                    "computed_fields":[

                                    ],
                                    "columns":[
                                       "created",
                                       "id",
                                       "instagram_id",
                                       "profile",
                                       "username",
                                       "views"
                                    ],
                                    "filter":{
                                       "id":{
                                          "_eq":"X-Hasura-User-Id"
                                       }
                                    }
                                 }
                              },
                              {
                                 "role":"public",
                                 "comment":null,
                                 "permission":{
                                    "allow_aggregations":false,
                                    "computed_fields":[

                                    ],
                                    "columns":[
                                       "id",
                                       "profile",
                                       "username"
                                    ],
                                    "filter":{

                                    }
                                 }
                              }
                           ],
                           "object_relationships":[

                           ],
                           "is_enum":false,
                           "computed_fields":[

                           ],
                           "event_triggers":[

                           ],
                           "insert_permissions":[

                           ],
                           "configuration":{
                              "custom_root_fields":{
                                 "insert":null,
                                 "select_aggregate":null,
                                 "select_by_pk":null,
                                 "select":null,
                                 "delete":null,
                                 "update":null
                              },
                              "custom_column_names":{

                              }
                           },
                           "table":"users",
                           "update_permissions":[
                              {
                                 "role":"driver",
                                 "comment":null,
                                 "permission":{
                                    "set":{

                                    },
                                    "columns":[
                                       "profile"
                                    ],
                                    "filter":{
                                       "id":{
                                          "_eq":"X-Hasura-User-Id"
                                       }
                                    }
                                 }
                              }
                           ],
                           "delete_permissions":[

                           ],
                           "array_relationships":[
                              {
                                 "using":{
                                    "foreign_key_constraint_on":{
                                       "column":"owner",
                                       "table":"categories"
                                    }
                                 },
                                 "name":"categories",
                                 "comment":null
                              },
                              {
                                 "using":{
                                    "foreign_key_constraint_on":{
                                       "column":"user_id",
                                       "table":"user_role"
                                    }
                                 },
                                 "name":"roles",
                                 "comment":null
                              }
                           ]
                        }
                     ],
                     "query_collections":[

                     ],
                     "functions":[

                     ]
                  },
                  "version":1,
                  "type":"replace_metadata"
               }
            ],
            "version":1,
            "type":"bulk"
         }
      },
      "http_info":{
         "status":400,
         "http_version":"HTTP/1.1",
         "url":"/v1/query",
         "ip":"205.185.202.10",
         "method":"POST",
         "content_encoding":null
      }
   }
}
```

here's the full error pulled from the log.

**Comment by tirumaraiselvan** [comment] 2020-02-05 07:01
@imdwit What is the configuration in DO, Hasura and Postgres versions?

**Comment by imdwit** [comment] 2020-02-05 21:55
I started from the Droplet at https://marketplace.digitalocean.com/apps/hasura-graphql

Digital Ocean docker yaml
```
version: '3.6'
services:
  postgres:
    image: postgres:10.5
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0
    depends_on:
    - "postgres"
    restart: always
    environment:
      # database url to connect
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      # enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set "false" to disable console
      ## uncomment next line to set an admin secret key
      HASURA_GRAPHQL_ADMIN_SECRET: shhhh
      HASURA_GRAPHQL_JWT_SECRET: shhhhh
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: shhhh
    command:
    - graphql-engine
    - serve
  caddy:
    image: abiosoft/caddy:0.11.0
    depends_on:
    - "graphql-engine"
    restart: always
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./Caddyfile:/etc/Caddyfile
    - caddy_certs:/root/.caddy
volumes:
  db_data:
  caddy_certs:
```


localhost:3000 - where the migration was created 
```
version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: shhh
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: shh
      HASURA_GRAPHQL_JWT_SECRET: shhh
volumes:
  db_data:

```

**Comment by imdwit** [comment] 2020-02-06 22:28
`1 GB Memory / 25 GB Disk / SFO2 - Hasura GraphQL on Ubuntu 18.04`
droplet info

**Comment by imdwit** [comment] 2020-02-08 00:28
fwiw I just ran through setting up a new droplet from the starter.
ssh'ed in, added a secret, turned off the console. Restarted the server.

then I ran the migration again, and still the same error.
Should I just host somewhere else?

**Comment by tirumaraiselvan** [comment] 2020-02-08 01:54
@imdwit Sorry for taking some time on this. I will take a look at this today.

**Comment by tirumaraiselvan** [comment] 2020-02-08 07:55
@imdwit The issue is with the syntax for `CREATE TRIGGER`

If you look at the Postgres docs for [10.5](https://www.postgresql.org/docs/10/sql-createtrigger.html), it says 

```
    EXECUTE PROCEDURE function_name ( arguments )
```

and if you look at the docs for [11](https://www.postgresql.org/docs/11/sql-createtrigger.html), it says

```
    EXECUTE { FUNCTION | PROCEDURE } function_name ( arguments )

```

So, you can change your migration to use the keyword `PROCEDURE` instead of `FUNCTION` in like this:

```
CREATE TRIGGER trigger_categories_creation AFTER INSERT ON public.users FOR EACH ROW EXECUTE PROCEDURE public.trigger_on_sign_up();
```

**Comment by imdwit** [comment] 2020-02-08 16:49
Thanks I’ll find that a shot.

**Comment by imdwit** [comment] 2020-02-08 20:09
`INFO migrations applied`
That did it. Thank you so much.

**Comment by marionschleifer** [comment] 2020-02-09 10:33
@imdwit glad to see that your problem is solved. I'm closing this issue. Feel free to re-open if you'd like to add something 🙂

**Closed by marionschleifer** 2020-02-09 10:33 UTC
Labels: k/question❓, support/action-needed
