### ISSUE TITLE
Has-one-through and has-many-through

### ISSUE THREAD

**Issue by Youhan** [hasura/graphql-engine#2407] opened 2019-06-20 03:23 UTC
So
```
Article 
   - id
   - title
   - author_id

Author
  - id
  - name
  - country_id

Country
  - id
  - name
```

An `Article` has one `Author`
An `Author` has many `Articles`
An `Author` is from one `country`
A `Country` belongs to many `Authors`

Now you want to query all Articles from a Country. 
So `Article` is related to `country` **through** `author`

How do you implement that with Hasura?

**Comment by leoalves** [comment] 2019-06-21 01:49
```javascript
query {
   articles (where:{authors: {country:{name:{_eq: "Brazil"}}}}) {
      id
      title
    }
}
```
Considering you have the following relationships configured in Hasura:
Table: Article
Relationship:
  name: authors
  type: array
  reference: article.author_id -> author.id
Table: Author
Relationship
  name: country
  type: Object
  reference: author.country_id -> country.id

**Comment by marionschleifer** [comment] 2019-07-08 09:23
@Youhan it seems like the issue is resolved. Closing it 🙂feel free to re-open in case you have more questions.

**Closed by marionschleifer** 2019-07-08 09:23 UTC
Labels: k/question
